### ISSUE TITLE
Problems with Sendmail_Relay

### ISSUE THREAD

**Issue by huloza** [mailwatch/1.2.0#1005]
Hi guys, can you give me a hand with this. im trying to use the Sendmail_relay tool, but im unable to make it work(im not seeing mta info on mail details page), im using

- Debian 8.7 
- exim4
- MailScanner: 5.0.6
- MailWatch 1.2.6

 all the mailwatch system is configured, i did all the steps: 

 cp tools/Sendmail_relay/mailwatch_sendmail_relay.php /usr/local/bin/.
 cp tools/Sendmail_relay/mailwatch-sendmail-relay /etc/init.d/.
 chmod +x /usr/local/bin/mailwatch_sendmail_relay.php
 chmod +x /etc/init.d/mailwatch-sendmail-relay
 /etc/init.d/mailwatch-sendmail-relay start
 update-rc.d mailwatch-sendmail-relay defaults

in Mailwatch conf.php i have :

define('MS_LOG', '/var/log/mail.log'); // Where is MailScanner logging to?
define('MAIL_LOG', '/var/log/exim4/mainlog'); // MTA log file, it's diferent between distributions and sometimes MTA

Im using exim4 and is logging all to /var/log/exim4/mainlog

status of mailwatch-sendmail-relay is:

***@***:/usr/local/bin# /etc/init.d/mailwatch-sendmail-relay status
● mailwatch-sendmail-relay.service - LSB: mailwatch_relay to watch relay log
   Loaded: loaded (/etc/init.d/mailwatch-sendmail-relay)
   Active: active (running) since Thu 2017-11-30 00:22:59 -04; 4 days ago
  Process: 243 ExecStart=/etc/init.d/mailwatch-sendmail-relay start (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/mailwatch-sendmail-relay.service
           ├─ 282 /usr/bin/php -q /usr/local/bin/mailwatch_sendmail_relay.php
           ├─1552 sh -c tail -F -n0 /var/log/exim4/mainlog
           └─1554 tail -F -n0 /var/log/exim4/mainlog

when i manually execute the script using "php -q /usr/local/bin/mailwatch_sendmail_relay.php" nothing happens, just hang the terminal.

any ideas to make it work please ???

thanks!!!

**Comment by Skywalker-11** [comment]
It is normal that the script doesn't have any output. It does the work in the background.

If you want to test if it is logging the relay information send a mail over the server while the service/script is running and execute the following query in mysql:
`select count(*) from mtalog` 
If this shows something different to `0` it is working correctly and you should be able to see the additional infos in MW or by running `select * from mtalog` in mysql. 

If nothing is logged check your syslog file for errors

**Comment by huloza** [comment]
The tables are empty, so there is nothing logged, the mailwatch-sendmail-relay is running and i dont find any errors on logs dir:

grep -rnw '/var/log/' -e 'mailwatch-sendmail-relay'

i double checked the status and /var/log/exim4/mainlog is the correct path for exim4 log.

any other suggestion? 

thanks for your help.

**Comment by Skywalker-11** [comment]
@stefaweb can you take a look at this?

**Comment by stefaweb** [comment]
Hello!

First, you don't need "/etc/init.d/mailwatch-sendmail-relay" in init.d and others files in tools/Sendmail_relay/

The right files are in https://github.com/mailwatch/MailWatch/blob/master/tools/Sendmail-Exim_queue/.

Read INSTALL.

mailwatch_sendmail_queue.php need to be run with a cron under root.

`0-59 * * * * /usr/local/bin/mailwatch_sendmail_queue.php >/dev/null`

mailwatch_sendmail_relay.php only output something if you have an error somewhere.

EDIT:

Don't need to change:

```
define('MS_LOG', '/var/log/mail.log'); // Where is MailScanner logging to?
define('MAIL_LOG', '/var/log/exim4/mainlog'); // MTA log file, it's diferent between distributions and sometimes MTA
```

Stay with:

```
// Log file location
define('MS_LOG', '/var/log/mail.log');
define('MAIL_LOG', '/var/log/mail.log');
```

If possible, update to MailWatch 1.2.7 to be sure to have the last version.

Please give us your database engine and version.

**Comment by huloza** [comment]
Thanks for your response:

I added to /etc/crontab:

**10 *    * * *   root    /usr/local/bin/mailwatch_sendmail_relay.php > /dev/null**

and changed mailwatch configuration :

**define('MAIL_LOG', '/var/log/exim4/mainlog');**
to
**define('MAIL_LOG', '/var/log/mail.log');**

(even mail.log only receive MailScanner Log, the MTA log is all in /var/log/exim4/mainlog the MTA debug information for any message is stored there.)

I tested with some outgoing and inbound messages, but "mtalog" and "mtalog_ids" **tables still empty.** also for testing i manually triggered /usr/local/bin/mailwatch_sendmail_relay.php after the changes.

from INSTALL: 

> You can get MailWatch to watch your Sendmail MTA logs and store all message relay information which is then displayed on the 'Message Detail' page which helps debugging and makes it easy for a Helpdesk to actually see where a message was delivered to by the MTA and what the response back was (e.g. the remote queue id etc.).

So this means that for every server message has to be an entry in mtalog right ?

**Database Version**
MySQL 5.5.58-0+deb8u1 - (Debian)
mailscanner Database Engine : InnoDB 5.5.58

**Comment by stefaweb** [comment]
> MailWatch to watch your **Sendmail** MTA logs

Euh! If I don't do an error, `mailwatch_sendmail_relay.php` is for Sendmail not Exim.

With Exim, all is done in mailwatch_sendmail_queue.php.

As you say you use Exim, you don't need relay script.

**Comment by huloza** [comment]
Lol, i misunderstand, but hey, Sendmail-Exim_queue does not do the same work as Sendmail Relay right? i mean with Sendmail-Exim_queue i will not have MTA Details from every message in Details page right?

Thanks.

**Comment by stefaweb** [comment]
Yes, you don't need Relay script. You will have all info from message header stored in the database.

Like this. If this is you're looking for?
![sc](https://user-images.githubusercontent.com/12907102/33673581-73ff51c4-daad-11e7-82bf-f015b46b5d3b.png)

**Comment by ghost** [comment]
Wait, does Sendmail_Relay even work for exim?

**Comment by jmcgranahan** [comment]
Sorry to hijack this, but I do have this issue with RedHat 7.5 server with MailScanner 5.07, MailWatch 1.2.9, connecting to an external MySQL database running version 5.6.39. When I try to start it, it fails:

```
[root@libvm15 bin]# /etc/init.d/mailwatch-sendmail-relay start
Starting mailwatch-sendmail-relay (via systemctl):  Warning: mailwatch-sendmail-relay.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Job for mailwatch-sendmail-relay.service failed because a fatal signal was delivered causing the control process to dump core. See "systemctl status mailwatch-sendmail-relay.service" and "journalctl -xe" for details.
                                                           [FAILED]
```

And then further details of the error:

```
● mailwatch-sendmail-relay.service - LSB: mailwatch_relay to watch relay log
   Loaded: loaded (/etc/rc.d/init.d/mailwatch-sendmail-relay; bad; vendor preset: disabled)
   Active: failed (Result: core-dump) since Mon 2018-07-02 15:29:09 CDT; 1min 24s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 11427 ExecStart=/etc/rc.d/init.d/mailwatch-sendmail-relay start (code=dumped, signal=SEGV)

Jul 02 15:27:22 libvm15.library.vanderbilt.edu systemd[1]: Starting LSB: mailwatch_relay to watch relay log...
Jul 02 15:29:09 libvm15.library.vanderbilt.edu systemd[1]: mailwatch-sendmail-relay.service: control process exited, code=dumped status=11
Jul 02 15:29:09 libvm15.library.vanderbilt.edu systemd[1]: Failed to start LSB: mailwatch_relay to watch relay log.
Jul 02 15:29:09 libvm15.library.vanderbilt.edu systemd[1]: Unit mailwatch-sendmail-relay.service entered failed state.
Jul 02 15:29:09 libvm15.library.vanderbilt.edu systemd[1]: mailwatch-sendmail-relay.service failed.
```

I did install LSB (originally was not installed on the server): 
```
Installed Packages
redhat-lsb.x86_64                                                      4.1-27.el7                                                 @vuit-rhel7-base
redhat-lsb-core.x86_64                                                 4.1-27.el7                                                 @vuit-rhel7-base
redhat-lsb-cxx.x86_64                                                  4.1-27.el7                                                 @vuit-rhel7-base
redhat-lsb-desktop.x86_64                                              4.1-27.el7                                                 @vuit-rhel7-base
redhat-lsb-languages.x86_64                                            4.1-27.el7                                                 @vuit-rhel7-base
redhat-lsb-printing.x86_64                                             4.1-27.el7                                                 @vuit-rhel7-base
redhat-lsb-submod-multimedia.x86_64                                    4.1-27.el7                                                 @vuit-rhel7-base
redhat-lsb-submod-security.x86_64                                      4.1-27.el7                                                 @vuit-rhel7-base

```

But there has been no change. It keeps failing. Ideas? Suggestions?
