### ISSUE TITLE
Unable so see details with Chrome browser

### ISSUE THREAD

**Issue by Aponton** [mailwatch/1.2.0#1009]
### Issue summary
Write a short summary of the issue, trying to pinpoint it as much as possible.
Mention the URL where this bug occurs, if applicable.
Please include *full error messages* and *screenshots* if possible.

### Steps to reproduce
1. visit mailwatch page on configured internal site with Firefox Quantum 57.0.2 (64-bit) 
2. visit mailwatch page on configured internal site with Google Chrome
3. 

### Expected result
get the same page and access to the same features

### Actual result
Logged with the same user (admin) on both browsers
on Google Chrome, unable to see or access details of messages
![chrome_not_show_nor_lets_access_details](https://user-images.githubusercontent.com/4056792/34411474-1c78e34e-ebd7-11e7-902d-f3d0d21ee9e8.png)
Results in Firefox... this one works :
![firefox_show_and_lets_access_details](https://user-images.githubusercontent.com/4056792/34411488-31aa7462-ebd7-11e7-9335-b25bf1efc00c.png)

 

### Version and method
 - MailWatch Version: [ stable 1.2.7 |- master ]
 - Install type: [ GitHub checkout ] 
 - Updated from an older MailWatch or fresh install:  Fresh install 

### Server configuration
 - Operation System: [ openSUSE ]  version [Leap 42.3]
 - PHP version: [ 5.5.14 ]
 - Database: [ MariaDB ] version [ 10.0.31 ]
 - Mail Server: [ Sendmail ] version [8.15.2]
 - Used web server: [ Apache ] version [ 2.4.23 ]

### Client configuration 
 - Operation System: [ MSWindows ] version [7-64bits ]
 - Browser1: [ Firefox Quantum 57.0.2 ]
 - Browser2: [ Google Chrome Version 63.0.3239.108 (Build officiel) (64 bits) ]

**Comment by asuweb** [comment]
Are there any errors in the Chrome Console?  (right click and select "Inspect")?  Also, can you try it in an incognito tab on chrome to see if the issue persists?

**Comment by Aponton** [comment]
Hello,
open the page on a "incognito tab" (Private Mode) tab solves the issue ...
![chrome_private_mode_lets_access_details](https://user-images.githubusercontent.com/4056792/34414237-69bc6c82-ebe8-11e7-8164-19752f9900b3.png)

**Comment by Aponton** [comment]
Oops, forgot 2 things:
1) there are no errors on the console
2) Thank-you !
Tony Ponton

**Comment by asuweb** [comment]
If it's working in Incognito mode, that points to a browser cache issue.  Can you try and clear the chrome browser cache, and that should resolve the issue.

Thanks,

**Comment by Aponton** [comment]
Clearing the cache did the job !
Thanks a lot again !
Regards,
Tony Ponton
