### ISSUE TITLE
ldap(s) against samba 4 AD.

### ISSUE THREAD

**Issue by thctlo** [mailwatch/1.2.0#1013]
Hai,
I've just setup a new mailscanner+mailwatch on debian stretch. 
Now i want to use the user authentication with ldaps against a samba 4 AD DC. 
postfix samba ldap ssl etc, is already running. 

running :  
ldapsearch -W -b ou=Some,DC=Base,DC=test -h $(hostname -f) -D 'cn=mybinduser,ou=ServiceUsers,ou=SomeOU,DC=Base,DC=test 
or 
ldapsearch -W -b ou=Some,DC=Base,DC=test -H ldaps://$(hostname -f) -D 'cn=mybinduser,ou=ServiceUsers,ou=Some,DC=Base,DC=test 
works, as it shows my output. 
so my bind works fine. 

sAMAccountName  is what i want for the logins on the interface. 
mail is the users primary mail adres. 
userPrincipalName contains my internal mail adres, ( not used ).

The same bind DN is used for my postfix setup with ssl and this works for some time already. 
/etc/ldap/ldap.conf  contains my BASE and URI and TLS_REQCERT allow

Installation
i followed : 
http://docs.mailwatch.org/install/optional-setup.html 
i did read all other issues found for mailwatch with ldap, but i did not get it working. 
ldapsearch -W -b ou=Some,DC=Base,DC=test -H ldaps://$(hostname -f) -D 'cn=mybinduser,ou=ServiceUsers,ou=Some,DC=Base,DC=test 'sAMAccountName=someuser' 
search result
search: 2
result: 0 Success

numResponses: 2
numEntries: 1

changing 'sAMAccountName to uid 
same result as above.

changing 'sAMAccountName to UserPrincipalName
( and change user@login.domain.tld )  
same result. 

My main problem im unable to login with ldap accounts. 
What did i miss.  php-ldap, php7.0-ldap and libnet-ldap-perl is installed 

The LDAP part from conf.php
// LDAP settings for authentication
define('USE_LDAP', true);
define('LDAP_HOST', 'ldaps://samba4dc1.internal.domain.tld');
define('LDAP_PORT', '636');
define('LDAP_PROTOCOL_VERSION', 3);
define('LDAP_USER', 'cn=mybinduser,ou=ServiceUsers,ou=SomeOU,DC=Base,DC=test'); 
define('LDAP_PASS', 'yesThisIsReallyMyPassword!Not!!)');
define('LDAP_DN', 'ou=SomeOU,DC=Base,DC=test');
define('LDAP_FILTER', 'sAMAccountName=%s'); 
define('LDAP_EMAIL_FIELD', 'mail');
define('LDAP_USERNAME_FIELD', 'userPrincipalName');
//define('LDAP_BIND_PREFIX', 'cn=');
//define('LDAP_BIND_SUFFIX', ',' . LDAP_DN);
define('LDAP_MS_AD_COMPATIBILITY', true);

as suggested in https://github.com/mailwatch/MailWatch/issues/955#issuecomment-336276935 
i've added : error_log($user); just above the line in question. 

Now i notice the following in my apache logs.
PHP Warning:  ldap_connect() expects parameter 2 to be integer, string given in /opt/mailwatch/mailscanner/functions.php on line 2870, referer: https://samba4dc1..internal.domain.tld/mailscanner/login.php?error=baduser
Any suggestions ??  

( p.s. sidenote ) 
When i click on "Software Versions" 
ERROR: Can't parse command line options
mkdir: cannot create directory '/var/spool/MailScanner/incoming': Permission denied
mktemp: failed to create directory via template '/var/spool/MailScanner/incoming/clamav-tmp/tmp.XXXXXXXXXX': Permission denied
ERROR: Option --tempdir requires a non-empty string argument
ERROR: Can't parse command line options

chmod 777 /var/spool/MailScanner/incoming 
and suddenly it also showed :  ClamAV Version: 0.99.2 
before it was missing the version number and clamav-status now also correct. 
maybe a hint for #1010 and #610 
I'm wondering why a tempfile is needed here to get the output of clamd -V 
Sorry, i'm not a php coder, maybe its needed. 

### Version and method
 - MailWatch Version: [ stable 1.2.7  ] git clone.
 - Fresh install 
I checked this fix. ( from #955 ) 
https://github.com/mailwatch/MailWatch/pull/958/commits/e4549925b0ec414dd6dc4cad581d5b5adca81a70 and that is already applied. 

### Server configuration
 - Operation System: [ Debian 9.3 ]
 - PHP version: [  7.0.19-1  ]
 - Database: [ MariaDB ] version [ 10.1.26-0+deb9u1 ]
 - Mail Server: [ Postfix  ] 3.1.6-0+deb9u1
 - Used web server: [ Apache 2.4.25-3+deb9u3

### Client configuration 
 - Operation System: Win7/10 x64
 - Browser: IE Edge chrome Firefox

**Comment by thctlo** [comment]
ok, extra info. 
this : PHP Warning: ldap_connect() expects parameter 2 to be integer, string given in /opt/mailwatch/mailscanner/functions.php on line 2870, referer:  
is also gone after the chmod 777 /var/spool/MailScanner/incoming

**Comment by asuweb** [comment]
@Skywalker-11 - any thoughts?

**Comment by Skywalker-11** [comment]
@thctlo I created a pr with a script to debug ldap problems:
https://github.com/mailwatch/MailWatch/pull/1016/files

Please fill in valid username and password in the beginning and run it with
`php ldaptest.php` and post the output

**Comment by thctlo** [comment]
Hai, thanks for the responce. 
Here is the output. 

Test connection to server
enable AD compatibility
Try authenticating as cn=mybinduser,ou=ServiceUsers,ou=SomeOU,DC=Base,DC=test
authentication for searching the account was successful
search for mailwatch in LDAP directory
search done
no results searching for accounts

ow and this is done with the rights correction to 777 /var/spool/MailScanner/incoming 
i'll do quick test again with the default rights. 

Done... same result. 

Ok, i did a re-check of my complete setup.
Its a new install but, i used my "old" 4.85 settings config file, use the upgraded program for that and i did manualy check it. 

I noticed the changes of the use of groups, so i reconfigure this now to mtagroup as set by the install.sh script, but i dont think that impacts the AD login.

**Comment by Skywalker-11** [comment]
The output says that you tried to search for an account with samaccountname "mailwatch" wich is not present in the LDAP or the mybinduser does not have the LDAP permissions to access the attribute.

**Comment by Skywalker-11** [comment]
The following command should print the ldap object of the ldap object with samaccountname "mailwatch":
`ldapsearch -W -b ou=Some,DC=Base,DC=test -H ldaps://$(hostname -f) -D 'cn=mybinduser,ou=ServiceUsers,ou=Some,DC=Base,DC=test '(samaccountname=mailwatch)'`

Output should be like:
```
# extended LDIF
#
# LDAPv3
# base < ou=Some,DC=Base,DC=test> with scope subtree
# filter: (samaccountname=mailwatch)
# requesting: ALL
#

dn: ...
objectClass: top
objectClass: person
....
mail: ...
....
samaccountname: mailwatch
...
# search result
search: 2
result: 0 Success

# numResponses: ...
# numEntries: 1
# numReferences: ...
```

**Comment by thctlo** [comment]
Hai, thanks for the responce. 
the ldap bind user does have the needed rights, i use this one also on my printers and other mail servers to lookup my email adresses. 

That shows my user as it should. 
I see things like : 
userPrincipalName: username@internal.base.test
mail: username@base.test 

So this looks good but still unable to login,..

**Comment by Skywalker-11** [comment]
So is there `samaccountname: mailwatch` in the output?

**Comment by Skywalker-11** [comment]
Just to clarify the username you enter in the script should be a user from the ldap, not the MW admin user defined in the sql db.

**Comment by thctlo** [comment]
which the bind user? yes he is, see my config in the top of the thread. 
that user is fine. my printers use these also and about 12 postfix servers with ldap. 
and yes sAMAccountName is shown.

what is the "expected" line with the test, can you show and example of a good result so i can compair.

**Comment by Skywalker-11** [comment]
If the test script is run successful it will print:
```
# php tools/LDAP/ldaptest.php
Test connection to server
enable AD compatibility
Try authenticating as cn=ldap,dc=example,dc=org
authentication for searching the account was successful
search for foo_test in LDAP directory
search done
found 1 accounts matching the filter
Trying to authenticate as user: testu@example.org
authentication success
db data for account: Mail: testumailadd@example.org; Internal account idTest User1
login success
```
Here the user has the following attributes in ldap:
samaccountname: foo_test
userprincipalname: testu@example.org
mail: testumailadd@example.org
cn: cn=Test User1,<....>

**Comment by thctlo** [comment]
ah, ok. thats better, i changed the user/pass in the test script.  ( sorry misunderstoot that. ) 

search for myuser in LDAP directory
search done
found 1 accounts matching the filter
found ldap account object does not contain the username field: userPrincipalName

now if i do the ldapsearch  ( see command line in top of thread ) 
That shows my UPN normal, as it should, i use that also for my windows pc login.
The only thing is ... my UPN has @internal.domain.tld  and my email had @domain.tld.
but this is used on lots of servers.

**Comment by Skywalker-11** [comment]
Ok. Next step is to verify that you should are able to login with the value of that UPN on your ldap server:
`ldapsearch -D <UPN> ...`

If that is not compatible with your setup you can use `define('LDAP_BIND_PREFIX', '<prefix>');` and `define('LDAP_BIND_SUFFIX', '<suffix>');` to generate the username that will be used to check the credentials: eg. 
LDAP_USERNAME_FIELD: `samaccountname`
LDAP_BIND_PREFIX: `cn=`
LDAP_BIND_SUFFIX: `,dc=internal,dc=domain,dc=tld` 

Which will result to `cn=<samaccountname>,dc=internal,dc=domain,dc=tld` beeing used with the provided password to check the credential of the user who wants to login (<samaccountname> is the attribute found by the first ldap search)

**Comment by thctlo** [comment]
ok, that works fine, 
ldapsearch -W -b ou=Some,DC=Base,DC=test -H ldaps://$(hostname -f) -D username@internal.domain.tld 
shows same as my binduser.  and same result about 70x userPrincipalName exits and thats correct. 
I'll the try your suggestion now and report back quickly.

**Comment by thctlo** [comment]
Ok, latest info.  
found 1 accounts matching the filter
found ldap account object does not contain the username field: sAMAccountName
resume. 
LDAP_USER', 'cn=mybinduser,ou=ServiceUsers,ou=SomeOU,DC=internal,DC=domain,DC=tld' and LDAP_USER', 'mybinduser@internal.domain.tld are both working for the ldapsearch. 
both find with ldapsearch sAMAccountName and userPrincipalName

If i change the ldapsearch to the user i want to login with in mailwatch, that works also, same tests, CN= and user@.. tested both work and show sAMAccountName and userPrincipalName
The mail field in ldapsearch shows the correct email adres. 
The userPrincipalName in ldapsearch shows the correct UPN.
This was tested with sAMAccountName and userPrincipalName in the LDAP_USERNAME_FIELD and i tested without the settings LDAP_BIND_PREFIX and LDAP_BIND_SUFFIX.

if i understand correctly. if i use the cn= 

'LDAP_BIND_PREFIX','LDAP_USERNAME_FIELD',''LDAP_BIND_SUFFIX', ',' . LDAP_DN
cn=username,ou=SomeOU,DC=internal,DC=domain,DC=tld' 
which is incorrect because my user is in : 
ou=SUB1,ou=SomeOU,DC=internal,DC=domain,DC=tld' 
but other users are also in : 
ou=SUB2,ou=SomeOU,DC=internal,DC=domain,DC=tld' 
ou=SUB3,ou=SomeOU,DC=internal,DC=domain,DC=tld' 

i dont know.. :-/

**Comment by Skywalker-11** [comment]
Can you use `var_dump($result);` in line 86 of the test script and validate that the output realy contains the samaccountname. 
Not sure about the samba ldap but maybe its not working because of case sensitivity.

It would help to post that output or send it to me per mail (address is in my profile)

**Comment by thctlo** [comment]
Thanx, thats a cool var :-).  Mail send.

**Comment by Skywalker-11** [comment]
@thctlo I tried to reply per mail but somehow multiple mail systems where blocked ```550 5.7.1
    Service unavailable; client [<serverip>] blocked using multiple
    DNS-based blocklists.```

for your problem:
try
`define('LDAP_USERNAME_FIELD', 'userprincipalname');`
(all small letters)

**Comment by thctlo** [comment]
Just tested this and YES!!!! now it works. 

Maybe its good to mention that in the conf.php, that you must use lowercase . 
even what the ldap output show userPrincipalName 

but im happy, i did try that also, dont know why that did not worked first time. 
I noticed some updates where done also on my debian and it had a reboot this last night. 

But thank you for all the support.
