### ISSUE TITLE
wishlist : (debian) detect /var/lib/geoip-database-contrib/ 

### ISSUE THREAD

**Issue by thctlo** [mailwatch/1.2.0#1015]
Hi, 

On the wishlist, update geoip is not needed if geoip-database-contrib is installed. 
the following can be used : 
/var/lib/geoip-database-contrib/GeoIP.dat
/var/lib/geoip-database-contrib/GeoIPASNum.dat
/var/lib/geoip-database-contrib/GeoIPASNumv6.dat
/var/lib/geoip-database-contrib/GeoIPv6.dat
/var/lib/geoip-database-contrib/GeoLiteCity.dat
/var/lib/geoip-database-contrib/GeoLiteCityv6.dat

**Comment by endelwar** [comment]
We migrated to GeoLite2 on March 2018 (https://github.com/mailwatch/MailWatch/commit/1e97b3a1673a9bf7db5dca96eab7de376195e069), and the new code needs to find the GeoLite2 file in a prefixed path
