### ISSUE TITLE
Error message from mailwatch-postfix-relay

### ISSUE THREAD

**Issue by philrandal** [mailwatch/1.2.0#1021]
### Issue summary

Every hour, I'm getting an email from cron:

/etc/cron.hourly/mailwatch-postfix-relay:

Notice: Undefined offset: 1 in /opt/mailwatch/public/mtalogprocessor.inc.php on line 194

This may be a result of me enabling very verbose logging in postfix.  However, mailwatch should handle unparseable input a bit more cleverly than it does.

### Steps to reproduce
1.  
2. 
3. 

### Expected result
No spam from cron

### Actual result
The hourly email as above

### Version and method
 - MailWatch Version: 1.2.7
 - Install type: Installer (beta)
 - Fresh install

### Server configuration
 - Operation System: CentOS 7.4
 - PHP version: 5.4 
 - Database: MariaDB
 - Mail Server: Postfix
 - Used web server: Apache

**Comment by Skywalker-11** [comment]
@philrandal can you post a mail log line as example that causes this?

**Comment by philrandal** [comment]
I wish I knew. It would take me some time to figure out which lines cause this. I'll see if I can figure out what is triggering it.

**Comment by Skywalker-11** [comment]
You can change the [mtalogprocessor.php line 191-195](https://github.com/mailwatch/MailWatch/blob/1.2/mailscanner/mtalogprocessor.inc.php#L191)  to 
```
                if (isset($entry[2])) {
                    $entries[$entry[0]] = $entry[1] . '=' . $entry[2];
                } elseif (!isset($entry[1])) {
                    echo "!!!!!error line!!!!!";
                    var_dump($this->raw);
                } else {
                    $entries[$entry[0]] = $entry[1];
                }
```
And manually run `php mailwatch_postfix_relay.php` again. This should print the erroneous log line.

**Comment by philrandal** [comment]
OK, this was when testing mandatory TLS

!!!!!error line!!!!!string(90) "send attr reason = TLS is required, but was not offered by host 10.x.y.z[10.x.y.z]"
