### ISSUE TITLE
Meltdown / Spectre

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#1022]
WARNING

I tried this morning to update some servers with new kernel patched for these critical security flaws. Some server crash at boot, some other not. Depend of the server brand or model (they have the same linux).

**Comment by philrandal** [comment]
Which processors (Manufacturer and model) and which linux, exactly?

And you may need BIOS updates for your servers too.

**Comment by stefaweb** [comment]
With Proxmox VE.

https://forum.proxmox.com/threads/meltdown-and-spectre-linux-kernel-fixes.39110/

I tried with an HP DL120-G7 and it was crashing at boot.

For me, it's solved with last kernel rev published this afternoon. 

But others have the same problem. I don't know if it's solved for them yet.

It seems that the mitigation code for Meltdown in kernel is not stabilized and I'm sure that side effect will arrive fast.

**Comment by stefaweb** [comment]
Hi!

A nice script to test meltdown/spectre status on your server.

https://github.com/speed47/spectre-meltdown-checker

![68747470733a2f2f6672616d617069632e6f72672f364f3476344141774d656e762f4d364a34434657777342337a2e706e67](https://user-images.githubusercontent.com/12907102/34834069-42d31ad0-f6f1-11e7-9d73-7110e97dc004.png)

Personally, I stopped to upgrade servers. Too many "side effect" and instabilities. Same for servers's BIOS (problem with buggy Intel microcodes).

Cheers,

**Comment by stefaweb** [comment]
Compatibility and stability problems with mitigation codes continue and rise.

Spectre and Meltdown patches causing trouble as realistic attacks get closer
https://arstechnica.com/gadgets/2018/01/spectre-and-meltdown-patches-causing-trouble-as-realistic-attacks-get-closer/

Meltdown/Spectre fixes made AWS CPUs cry, says SolarWinds
https://www.theregister.co.uk/2018/01/15/solarwinds_aws_meltdown_fix_analysis/

Meltdown-Spectre: More businesses warned off patching over stability issues
http://www.zdnet.com/article/meltdown-spectre-more-businesses-warned-off-patching-over-stability-issues/

**Comment by Skywalker-11** [comment]
@stefaweb links are not working

**Comment by stefaweb** [comment]
Oops, wrong cp. Corrected.

**Comment by stefaweb** [comment]
A new piece of shit is coming soon...

Skyfall and Solace
https://skyfallattack.com

**Comment by ghost** [comment]
Grrrrreat...

**Comment by stefaweb** [comment]
Intel continu to smoked us out.

Intel admits Spectre patch problems also affect newer Core chips
https://www.engadget.com/2018/01/18/intel-spectre-reboot-problem-affects-newer-cpu/

**Comment by Skywalker-11** [comment]
Skyfall and Solace may are just hoax pages:
https://translate.google.de/translate?sl=de&tl=en&js=y&prev=_t&hl=de&ie=UTF-8&u=https%3A%2F%2Fwww.heise.de%2Fnewsticker%2Fmeldung%2FMeltdown-und-Spectre-Vermutlich-Scherze-mit-spekulativen-Angriffen-Skyfall-und-Solace-3946313.html&edit-text=&act=url&act=url

**Comment by stefaweb** [comment]
Linus Torvalds is not happy at all and that's an understatement.

https://lkml.org/lkml/2018/1/21/192
