### ISSUE TITLE
Postfix Version: postconf not found

### ISSUE THREAD

**Issue by pztop** [mailwatch/1.2.0#1026]
I upgraded v1.2.7 from v1.2.6. It works OK but I found a small issue: MailWatch cannot find postconf command.

Here I copied from MailWatch "Software Version" page:

> Software Versions
MailWatch Version: 1.2.7
Operating System Version: CentOS Linux 7 (Core)
Postfix Version: postconf not found
MailScanner Version: 5.0.7
ClamAV Version: 0.99.2 
SpamAssassin Version: 3.4.0 
PHP Version: 7.1.13
MySQL Version: 10.2.12-MariaDB-log
GeoIP Database Version: Fri, 12 Jan 2018 14:00:04 -0800 (download date)
GeoIPv6 Database Version: Fri, 12 Jan 2018 14:00:04 -0800 (download date)
> 

I see there are some changes in sf_version.php but I don't know how to fix it. I tried run the postconf command in terminal and it works fine:
`# postconf -d | grep 'mail_version ='
mail_version = 3.2.4
`

**Comment by ghost** [comment]
What do you get when you run "which postconf" ?

**Comment by pztop** [comment]
[root@mail ~]# which postconf
/usr/sbin/postconf

**Comment by ghost** [comment]
What about "ls -l /usr/sbin/postconf" ?

**Comment by pztop** [comment]
[root@mail ~]# ls -l /usr/sbin/postconf
-rwxr-xr-x 1 root root 1485728 Nov 27 12:08 /usr/sbin/postconf

**Comment by ghost** [comment]
selinux enabled?

**Comment by pztop** [comment]
[root@mail ~]# sestatus 
SELinux status:                 disabled

**Comment by Skywalker-11** [comment]
What does `sudo -u apache which postconf` return?
You could also insert this`var_dump` line there to see what the which command generates.
```
        exec("which postconf", $postconf);
        var_dump($postconf);
        if (isset($postconf[0])) {
```

**Comment by pztop** [comment]
```
root@mail ~]# sudo -u nginx which postconf
/sbin/postconf
[root@mail ~]# which postconf
/usr/sbin/postconf

[root@mail ~]# ll /sbin/postconf
-rwxr-xr-x 1 root root 1485728 Nov 27 12:08 /sbin/postconf
[root@mail ~]# ll /usr/sbin/postconf
-rwxr-xr-x 1 root root 1485728 Nov 27 12:08 /usr/sbin/postconf
[root@mail ~]#
```
It seems I have two identical postconf in two locations. The Postfix I am using on this server is compiled and installed from source code with default path configuration.  It there any problem?

**Comment by pztop** [comment]
after add the var_dump line in sf_version.php, the MailWatch shows:

> Postfix Version: array(0) { } postconf not found

**Comment by asuweb** [comment]
I'm assuming you are running mailwatch through Nginx?

If so can you run `sudo -u nginx postconf -d` and see what is output?

**Comment by pztop** [comment]
sudo -u nginx postconf -d
output my postfix configuration, see here:
[https://pastebin.com/tx1RWpG6](https://pastebin.com/tx1RWpG6)

**Comment by asuweb** [comment]
I'm assuming the web server / php is running processes with the default user i,e nginx for Nginx (or apache if using apache).  You're not using any kind of privacy separation and running php scripts under a different user?

**Comment by pztop** [comment]
I am using Nginx and php-fpm by user nginx:
```
[root@mail ~]# ps aux | grep nginx
root      1255  0.0  0.0  48440  1632 ?        Ss   Jan14   0:00 nginx: master process /usr/sbin/nginx -c /etc/nginx/nginx.conf
nginx     1256  0.0  0.0  48708  4428 ?        S    Jan14   0:01 nginx: worker process
nginx     1257  0.0  0.0  48728  4668 ?        S    Jan14   0:00 nginx: worker process
nginx     1490  0.0  0.2 673984 12724 ?        S    Jan14   0:00 php-fpm: pool www
nginx     1491  0.0  0.2 673984 12724 ?        S    Jan14   0:00 php-fpm: pool www
nginx     1492  0.0  0.2 673984 12724 ?        S    Jan14   0:00 php-fpm: pool www
nginx     1493  0.0  0.2 673984 12724 ?        S    Jan14   0:00 php-fpm: pool www
nginx     1494  0.0  0.2 673984 12728 ?        S    Jan14   0:00 php-fpm: pool www
root      9012  0.0  0.0 112660   976 pts/0    S+   09:38   0:00 grep --color=auto nginx
```

**Comment by asuweb** [comment]
Strange.  What does `grep 'MTA' /etc/MailScanner/MailScanner.conf` output?

**Comment by pztop** [comment]
```
[root@mail ~]# grep 'MTA' /etc/MailScanner/MailScanner.conf
MTA = postfix
# Set how to invoke MTA when sending messages MailScanner has created
#		your MTA and virus scanners. the installer creates mtagroup		
# queue for the MTA to deliver when it wants to?
#      queue -- just place them in the queue and let the MTA find them.
```

**Comment by Skywalker-11** [comment]
Can you also try changing the exec to to the following
`exec("whoami", $postconf);`  (show the actual user the command is executed as)
`exec('echo $PATH', $postconf);` (show the PATH that will be used for which to find the command)

**Comment by pztop** [comment]
Changed to:
```
...
        echo '<br>' . "\n";
        echo 'Postfix ' . __('version11') . ' ';
//        exec("which postconf", $postconf);
        exec("whoami", $postconf);  
        exec('echo $PATH', $postconf);  
...
```
Now the it gave blank oupput:
> Postfix Version: 

I checked php-fpm.log and it logged as:
```
[15-Jan-2018 11:07:48] WARNING: [pool www] child 1493 said into stderr: "sh: nginx: command not found"
```
Here is my www pool config file /etc/php-fpm.d/www.conf:
```[www]
user = nginx
group = nginx
listen = /var/run/php-fpm/php-fpm.sock
listen.owner = nginx
listen.group = nginx
listen.allowed_clients = 127.0.0.1
pm = dynamic
pm.max_children = 50
pm.start_servers = 5
pm.min_spare_servers = 5
pm.max_spare_servers = 35
slowlog = /var/log/php-fpm/www-slow.log
catch_workers_output = yes
php_admin_flag[log_errors] = on
php_value[session.save_handler] = files
php_value[session.save_path]    = /var/lib/php/session
php_value[soap.wsdl_cache_dir]  = /var/lib/php/wsdlcache
```

**Comment by ghost** [comment]
I'm about to play with php-fpm, I wonder if it has something to do with it.....

**Comment by Skywalker-11** [comment]
Do you have safe_mode and safe_mode_exec_dir enabled in php? http://php.net/manual/en/function.exec.php

**Comment by pztop** [comment]
I made a test.php file in the webroot dir like the example in the link:
[root@mail mailscanner]# cat test.php 
```
<?php
echo exec('whoami');
?>
```

Then in browser I see the output with one word:
nginx

So my server does execute "whoami" through php and returened "nginx".

**Comment by ghost** [comment]
Confirmed, php-fpm is the culprit.  I reproduced this on apache:

Postfix Version: postconf not found

**Comment by ghost** [comment]
Looks like php-fpm runs in a chroot jail.  Seeing if I can work around it...

**Comment by ghost** [comment]
Ok, in my case, that was not it, it is actually an environment variable problem

'which' depends on the PATH environment variable.

I added this to my php-fpm configuration:

```
env[PATH] = /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
```

Restarted php-fpm and it is now working for me.

**Comment by endelwar** [comment]
It's a security configuration in php-fpm; from http://php.net/manual/en/install.fpm.configuration.php#clear-env

>  clear_env boolean
> Clear environment in FPM workers. Prevents arbitrary environment variables from reaching FPM worker processes by clearing the environment in workers before env vars specified in this pool configuration are added. Since PHP 5.4.27, 5.5.11, and 5.6.0. Default value: Yes.

passing `PATH` in `/etc/php/fpm/pool.d/www.conf` as @shawniverson suggested is a good workaround, disabling `clear_env` it's not

**Comment by pztop** [comment]
Yes it works! Thank you for the great work. :+1:

**Comment by hifihedgehog** [comment]
This is an issue also in OpenLitespeed. @endelwar, @shawniverson, @asuweb, do you have any ideas on how to approach this?

**Comment by hifihedgehog** [comment]
See also:

https://forum.openlitespeed.org/threads/env-path.4341/

@hennaboy, who actively contributes to the CyberPanel web panel project, had recently added MailWatch as an optional feature but this minor issue persists. He had contacted the OpenLitespeed team to try to resolve it but they appear to have not yet provided a solution.

**Comment by Skywalker-11** [comment]
If you have access to the MailWatch source files on the web server you could also try to modify the conf.php to change the include path for MailWatch with `set_include_path`. This way the change should also not be overwritten when updating MailWatch to a new release.
See [https://www.php.net/manual/de/function.set-include-path.php](https://www.php.net/manual/de/function.set-include-path.php) for an example

**Comment by hifihedgehog** [comment]
This is a fantastic solution and what I will use until OLS is updated. That said, I believe the issue (which I am discovering) is OpenLitespeed (unlike commercial Litespeed) does not properly support editing the PATH environment variable. It should, in theory, but, in practice, it doesn't.

**Comment by hifihedgehog** [comment]
@Skywalker-11, I just added this line at the end of conf.php:

> set_include_path('/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin');

I restarted my server and attempted to access it. It still shows "Postfix Version: postconf not found." :(

**Comment by hifihedgehog** [comment]
@Skywalker-11, I did some digging and this worked for LiteSpeed and CyberPanel. I added this at the end of my /usr/local/CyberCP/public/mailwatch/mailscanner/conf.php file.

putenv('PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin');

**Comment by master3395** [comment]
> @Skywalker-11, I did some digging and this worked for LiteSpeed and CyberPanel. I added this at the end of my /usr/local/CyberCP/public/mailwatch/mailscanner/conf.php file.
> 
> putenv('PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin');

This worked for me also on OLS.

**Comment by surfroot** [comment]
putenv('PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin');  it is work and my situation, i can see ClamAV version and  see postconf info but I lost my state Mailscanner NO, before that, I only had an inactive postfiх NO, by the way how fix this trouble ?
