### ISSUE TITLE
"Go To Message" needs partial match logic

### ISSUE THREAD

**Issue by philrandal** [mailwatch/1.2.0#1030]
### Issue summary
In the status screen there's a handy "Go to message" box which works great when pasting message IDs from sendmail's received headers but fails when your mta is postfix as only the partial message ID is available in the email's message header

### Steps to reproduce
1.  Message headers say

"Received: from test.com [w.x.y.z])
     by mymailserver (Postfix) with ESMTP id E2A6680B83B3"

2. The detail screen in Mailwatch says "ID:  E2A6680B83B3.A4FCB"

3.  Entering the ID from (1) results in email not being found

### Expected result
Partial matching should be used so we can easily retrieve the email details in Mailwatch

### Actual result
Not found

### Version and method
 - MailWatch Version:  stable 1.2.x
 - Install type: Installer (beta)
 - Updated from an older MailWatch or fresh install:  Fresh install

### Server configuration
 - Operation System:  CentOS
 - PHP version: 5.4
 - Database: MariaDB
 - Mail Server: Postfix 
 - Used web server: Apache

**Comment by xpufx** [comment]
While this would be useful, the info you need is available in the log file  a few lines below the postfix queue stuff. When mailscanner reques it. It's also there in the MailWatch log message. (I am using Postfix too)

It would look like this:

MailWatch: Logging message E2A6680B83B3.A4FCB to SQL
