### ISSUE TITLE
minor feature request: add "rowhover" style to remaining report tables

### ISSUE THREAD

**Issue by pdwalker** [mailwatch/1.2.0#1033]
that elegant new style "table.rowhover" should be applied to the remaining report tables:

suggested files to modify (in no particular order)
- rep_sa_rule_hits.php
- rep_total_mail_by_date.php
- graphgenerator.inc.php
- rep_viruses.php
- rep_mcp_rule_hits.php
- sa_lint.php
- sa_rules_update.php
- ms_lint.php

(ok, maybe those last three maybe a bit silly, but I work on a large screen and this really helps a lot visually)

**Comment by Skywalker-11** [comment]
Active development of 1.2 is halted. No new features will be implemented. 

You could do it locally in the style.css file.
