### ISSUE TITLE
mailwatch_update_sarules.php errors

### ISSUE THREAD

**Issue by atftb** [mailwatch/1.2.0#1035]
### Issue summary
Testing the new mailwatch_update_sarules.php script reported errors:
    root@mxl:~# ./mailwatch_update_sarules.php 
    Error: Cannot find functions.php file in "/media/sf_1.2.0/mailscanner/functions.php": edit 
    /root/mailwatch_update_sarules.php and set the right path on line 27

I set the path to /var/www/html/mailscanner/functions.php then reran the script which produced this error:
    Fatal error: Call to undefined function __() in /root/mailwatch_update_sarules.php on line 48
    uniq: write error: Broken pipe

Please include *full error messages* and *screenshots* if possible.

### Steps to reproduce
1.  Download https://github.com/mailwatch/MailWatch/blob/1.2/tools/Cron_jobs/mailwatch_update_sarules.php
2. chmod to make it executable
3. run ./mailwatch_update_sarules.php

### Expected result
the SA rule descriptions should be updated 

### Actual result
The errors noted above occur.

### Version and method
 - MailWatch Version: 1.2.0 - RC1 DEV
 - Install type: Zip/tarball install
 - Updated from an older MailWatch or fresh install: Upgrade ] (from version Don't recall, sorry.  Been to long)

### Server configuration
 - Operation System: Debian Jessie
 - PHP version: 5.6.33+dfsg-0+deb8u1
 - Database: MySQL 5.5.59-0+deb8u1
 - Mail Server: Postfix
 - Used web server: Apache 2.4.10-10+deb8u11

### Client configuration 
 - Operation System: n/a (running the script on the server
 - Browser: n/a

**Comment by Skywalker-11** [comment]
@atftb can you try instead?
```
if (!@is_file($pathToFunctions)) {
    die('Error: Cannot find functions.php file in "' . $pathToFunctions . '": edit ' . __FILE__ . ' and set the right path on line ' . (__LINE__ - 3) . PHP_EOL);
}
require $pathToFunctions;
function dbg($text)
{
    if (DEBUG) {
        echo $text . "\n";
    }
}
ini_set('error_log', 'syslog');
ini_set('html_errors', 'off');
ini_set('display_errors', 'on');
ini_set('implicit_flush', 'false');
$result = shell_exec("grep -hr '^\s*describe' " . SA_RULES_DIR . ' /usr/share/spamassassin /usr/local/share/spamassassin ' . SA_PREFS . ' /etc/MailScanner/spam.assassin.prefs.conf /opt/MailScanner/etc/spam.assassin.prefs.conf /usr/local/etc/mail/spamassassin /etc/mail/spamassassin /var/lib/spamassassin 2>/dev/null | sort | uniq');
audit_log(__('auditlog13', true), __FILE__);
foreach(preg_split("/((\r?\n)|(\r\n?))/", $result) as $line){
    // debug("line: ".$line."\n");
    preg_match("/^(?:\s*)describe\s+(\S+)\s+(.+)$/", $line, $regs);
    if (isset($regs[1], $regs[2])) {
        $regs[1] = trim($regs[1]);
        $regs[2] = trim($regs[2]);
        $regs[1] = safe_value($regs[1]);
        $regs[2] = safe_value($regs[2]);
        dbquery("REPLACE INTO sa_rules VALUES ('$regs[1]','$regs[2]')");
        dbg("\t\tinsert: ".$regs[1]. ', ' .$regs[2]);
    } else {
        dbg("$line - did not match regexp, not inserting into database");
    }
}
```

**Comment by atftb** [comment]
Same error:
root@mxl:~# ./mailwatch_update_sarules.php
Fatal error: Call to undefined function __() in /root/mailwatch_update_sarules.php on line 47

Seems to be this line: 
    audit_log(__('auditlog13', true), __FILE__); 

grepping in the mailwatch web directory, there are no references to auditlog13.  Or auditlog without the 13 on the end for that matter.

**Comment by Skywalker-11** [comment]
Can you try updating your mailwatch to 1.2.7?

**Comment by endelwar** [comment]
> Version and method
> 
>     MailWatch Version: 1.2.0 - RC1 DEV

The script won't work on 1.2.0 - RC1, and you should update asap, did you miss the security alert (http://mailwatch.org/news/2017/03/20/mailwatch-1-2-0-final-released/)?

**Comment by atftb** [comment]
Thanks.  I'll get that on the todo list.
