### ISSUE TITLE
Release from quarantine: Helo still with not FQDN

### ISSUE THREAD

**Issue by Stephanowicz** [mailwatch/1.2.0#1038]
Hi,

we're running MailWatch für MailScanner v1.2.7 - today I wanted to release a file from quarantine.
It didn't work as the **Helo** sent was just 'localhost' and our postfix only allows fqdns.

I searched a bit and found that this was a problem before but should have been fixed...?
This has been discussed quite a while ago (~12 years) [https://sourceforge.net/p/mailwatch/mailman/message/7563108/](https://sourceforge.net/p/mailwatch/mailman/message/7563108/
)
and
[http://lists.mailscanner.info/pipermail/mailscanner/2005-March/047360.html](http://lists.mailscanner.info/pipermail/mailscanner/2005-March/047360.html)

On another site I found a discussion saying that the problem is the pear smtp.php file where $localhost is hardcoded to 'localhost'.
After changing THIS to a fqdn I could release the quaratined files...
...only running into the next problem, that the released mail has been quarantined again?! (But thats another topic)

Cheers, Stephan

**Comment by asuweb** [comment]
Can you try the following:

Change this line `functions.php:3509` 
`$mail_param = array('host' => MAILWATCH_MAIL_HOST);`

to 

`$mail_param = array('host' => MAILWATCH_MAIL_HOST, 'localhost' => 'your.fq.dn');`

and see if that fixes it

**Comment by endelwar** [comment]
We should use MAILWATCH_SMTP_HOSTNAME conf.php parameter on functions.php:3509 like it is done on line 4310

**Comment by endelwar** [comment]
Should be ok on 1.2 branch, can you test it @Stephanowicz ?

**Comment by Stephanowicz** [comment]
Ok,

so I replaced line 3517 in functions.php
`$mail_param = array('host' => MAILWATCH_MAIL_HOST);`
with
```
if (defined('MAILWATCH_SMTP_HOSTNAME')) {
	$mail_param = array('localhost' => MAILWATCH_SMTP_HOSTNAME, 'host' => MAILWATCH_MAIL_HOST, 'port' => MAILWATCH_MAIL_PORT);
 } else {
	$mail_param = array('host' => MAILWATCH_MAIL_HOST, 'port' => MAILWATCH_MAIL_PORT);
 }
```

and restored the hardcoded value in /lib/pear/Mail/smtp.php in line 142:
  `  var $localhost = 'localhost';`

I then successfully restored a quarantined mail - so far this seemed to work - will give feedback in case we get another blocked atachment.

Thank You & cheers, Stephan
