### ISSUE TITLE
messages details link missing after upgrade.

### ISSUE THREAD

**Issue by SWoodyUK** [mailwatch/1.2.0#1041]
### Issue summary
Write a short summary of the issue, trying to pinpoint it as much as possible.
Mention the URL where this bug occurs, if applicable.
Please include *full error messages* and *screenshots* if possible.

### Steps to reproduce
1. git cloned 1.2.7
2. backed up the database
3. added the additional options needed since 1.2.0rc4
4. swapped out the contents of /var/www/html/mailscanner
5. replaced symlinks for .pm's etc
6. run php upgrade.php

I do have VMWare snapshots of these if needed.

### Expected result
Tell us what should happen:
The message details links should be there.

### Actual result
Tell us what happens instead:
Messages details links are missing 

### Version and method
 - MailWatch Version: [ stable 1.2.x | RC-x | master | develop ]
1.2.7
 - Install type: [ GitHub checkout | Zip/tarball install | Installer (beta) ]
git
 - Updated from an older MailWatch or fresh install: [ Fresh install | Upgrade ] (from version [ version ]Upgraded from 1.2.0rc4)

### Server configuration
 - Operation System: [ Debian 8 Jessie ]
 - PHP version: [ 7.0.27-1~dotdeb+8.1 ]
 - Database: [ MySQL 5.7.21 ]
 - Mail Server: [ Postfix ]
 - Used web server: [ Apache 2.4.10-10+deb8u11 ]

### Client configuration 
 - Operation System: [ Mac OSx 10.13.3 (17D47) ]
 - Browser: [ Version 64.0.3282.140 (Official Build) (64-bit) ]

**Comment by Skywalker-11** [comment]
@SWoodyUK can you post a screenshot of the page?
Also check if you also copied the images folder especially `mailscanner/images/info-circle.png` should be there. 
There were also changes in the style.css. So make sure you also have copied the newer css file. Custom css can be defined in a separate skin.css file in the mailscanner directory

**Comment by SWoodyUK** [comment]
This was in fact css, and caching issues on both browser and loud balancer. Thanks for the help.
