### ISSUE TITLE
' (apostrophe) in MailWatch username

### ISSUE THREAD

**Issue by SelcomSys** [mailwatch/1.2.0#1042]
We are using Mailwatch and have a user with an email address that contains an apostrophe ('). I am unable to create the account and get the error: For all users other than Administrator you must use an e-mail address for the username. 

Is there something I am missing?

**Comment by Skywalker-11** [comment]
Can you provide your system setup as described here: https://github.com/mailwatch/MailWatch/blob/1.2/.github/ISSUE_TEMPLATE.md

**Comment by endelwar** [comment]
I think that the actual code that validate and clean the username is too much aggressive, and need to be recalibrated to conform to RFC 5322 and 5321. Valid email address can be 

> #!$%&'*+-/=?^_`{}|~@example.org

 or 

> "()<>[]:,;@\\\"!#$%&'-/=?^_`{}| ~.a"@example.org

On 1.2 we can use a validator like PHP filter_var with FILTER_VALIDATE_EMAIL and for 2.0 a more complex validator like [Zend\Validator](https://docs.zendframework.com/zend-validator/validators/email-address/)

**Comment by SelcomSys** [comment]
Hi Skywalker, I have just heard back from the guy who built the server and he used the VMWare build from the EFA project: https://efa-project.org/download/. I am not sure what version of MailWatch this has bundled in.

Endelwar, I agree that the code is too aggressive. We are going to look at the code here. We are not sure how easy it will be to access considering we have installed a prebuilt image.

**Comment by shawniverson** [comment]
@SelcomSys In your case the fix is simple.  See PR #1043 and edit functions.php accordingly on the appliance.

**Comment by ghost** [comment]
@SelcomSys PR #1043 is WIP at the moment.  Stand by.

**Comment by SelcomSys** [comment]
Thanks for all your help with this everyone! Excellent response.

**Comment by ghost** [comment]
@SelcomSys The code changes appear to be in the 1.2 branch now.
