### ISSUE TITLE
Quarantine report cronjob is sending multiple emails and also showing messages that have been delivered to the user

### ISSUE THREAD

**Issue by kenneth-vkd** [mailwatch/1.2.0#1046]
### Issue summary
After upgrading from a very old 1.2.0-beta5 release to 1.2.7, following the upgrade guide on the website, we are recieving 1-4 quaratine report emails instead of just 1 email.
We have checked that the cronjob only exists once

### Expected result
It would be expected that we only get 1 email showing only the messages that have actually not been delivered to the recipient

### Actual result
We recieve 1-4 emails and a lot of messages state the reason `UNKNOWN`. Checking a few of these messages indicate that they have actually been delivered and are not quarantined as spam

### Version and method
 - MailWatch Version: stable 1.2.7
 - Install type: ZIP downloaded from the "Releases" page on Github
 - Updated from an older MailWatch or fresh install: Upgrade from 1.2.0 beta 5

### Server configuration
 - Operation System: CentOS version 6.9
 - PHP version: 5.3.3 (Will be upgraded to 5.6 in the coming weekend)
 - Database: MySQL 5.1.73
 - Mail Server: Sendmail
 - Used web server: Apache 2.2

**Comment by Skywalker-11** [comment]
@kenneth-vkd are the 4 mails going to the same recipient address or are they different?

**Comment by kenneth-vkd** [comment]
I just checked over a few days. The message are for the same recipient. Looking closely at the contents, the report is for different domains.
For some reason the emails listed with reason `UNKNOWN` were emails that had actually been delivered and could be filtered out in `return_quarantine_list_array` function in `mailscanner/quarantine_report.inc.php`

I modified it to skip the ones with reason `UNKNOWN` and it now looks like this:

```
/**
     * @param string $to_address
     * @param string $to_domain
     * @return array
     */
    private static function return_quarantine_list_array($to_address, $to_domain)
    {
        $result = dbquery(sprintf(self::get_report_sql(), quote_smart($to_address), quote_smart($to_domain)));
        $rows = $result->num_rows;
        $array = array();
        //if ($rows > 0) {
        if ($rows > 0) {
            while ($row = $result->fetch_object()) {
                if ($row->reason != 'UNKNOWN') {
                $array[] = array(
                    'id' => trim($row->id),
                    'datetime' => trim($row->datetime),
                    'to' => trim_output($row->to_address, FROMTO_MAXLEN),
                    'from' => trim_output($row->from_address, FROMTO_MAXLEN),
                    'subject' => trim_output($row->subject, SUBJECT_MAXLEN),
                    'reason' => trim($row->reason),
                    'timestamp' => trim($row->timestamp),
                    'token' => trim($row->token)
                );
                }
            }
        }
```

**Comment by Skywalker-11** [comment]
Have you tried setting QUARANTINE_FILTERS_COMBINED to `true`? That should only send one mail per user.

**Comment by Skywalker-11** [comment]
Closing as no feedback. If it still present please respond to the question and reopen
