### ISSUE TITLE
Quarantine report not working

### ISSUE THREAD

**Issue by sjaak327** [mailwatch/1.2.0#1047]
Manually running /usr/local/bin/mailwatch_quarantine_report.php 

with  QUARANTINE_FILTERS_COMBINED in conf.php does not pick up the right number of Q. emails for the users. Setting the above bool to true (which would be my desired outcome anyway), produces the following:

PHP Warning:  array_merge() expects at least 1 parameter, 0 given in /opt/mailwa                                                                                                                                                             tch/mailscanner/quarantine_report.inc.php on line 392
and:

then nothing, to date I have not been able to get even a single report.

Ubuntu 16, PHP7, MW 1.27 Exim 4.9_1 Mailscanner 5.07.

### Issue summary
Write a short summary of the issue, trying to pinpoint it as much as possible.
Mention the URL where this bug occurs, if applicable.
Please include *full error messages* and *screenshots* if possible.

### Steps to reproduce
1. 
2. 
3. 

### Expected result
Tell us what should happen

### Actual result
Tell us what happens instead

### Version and method
 - MailWatch Version: [ stable 1.2.x | RC-x | master | develop ]
 - Install type: [ GitHub checkout | Zip/tarball install | Installer (beta) ]
 - Updated from an older MailWatch or fresh install: [ Fresh install | Upgrade ] (from version [ version ])

### Server configuration
 - Operation System: [ Debian | Ubuntu | CentOS | Other ] version [ version ]
 - PHP version: [ 5.3 | 5.4 | 5.5 | 5.6 | 7.0 | 7.1 ]
 - Database: [ MySQL | MariaDB ] version [ version ]
 - Mail Server: [ Postfix | Exim | Sendmail ]
 - Used web server: [ Apache | Nginx ] version [ version ]

### Client configuration 
 - Operation System: [ operation system ] version [ version ]
 - Browser: [ browser name and version ]

**Comment by sjaak327** [comment]
Added a few filters, and now it does work, still the users originally tried did have spam emails, so the question is why were these not picked up ? what is the date range used ?

**Comment by asuweb** [comment]
The number of days to include in a quarantine report is defined in `conf.php`

`define('QUARANTINE_REPORT_DAYS', 7);`

**Comment by sjaak327** [comment]
Yes, thank you, still don't understand exactly why it did return 0, as number of days was 1 and I send myself spam to test. Now that I added filters, and added all other users, I at least get all the spam on a single day. But initially even though I specifically sent spam to the same user as the report recipient, it never got sent, and the number of spam email Always displayed as zero. Oh well :)

**Comment by sjaak327** [comment]
Ok, figured it out, I had to specifically create another filter with my regular email address (which was entered already as the user/recipient address) for emails addressed to my main user to appear on the report. That is confusing, the spam emails addressed to the recipient of the report should be included automatically.

**Comment by Skywalker-11** [comment]
@sjaak327 if you use a mail address as username for your domain admin it will only receive quarantine reports for addresses in that domain.

**Comment by Skywalker-11** [comment]
You can also check /usr/local/bin/mailwatch_quarantine_report.php to see which domains are included for which report

**Comment by sjaak327** [comment]
I used a normal user name without email, then set my normal email address as "recipient address" yet, even though that address had spam, the report remained empty.
