### ISSUE TITLE
Mail not logging in SQL database

### ISSUE THREAD

**Issue by markrochester** [mailwatch/1.2.0#1049]
Hi,

After two fresh installations I have decided to ask for some help.

Everything works well with the MailScanner, mail flow etc etc. But the data never gets logged to the SQL database. There is an active listener on port 11553 for MailWatch SQL sitting on 127.0.0.1:11553, although the log files only show this when starting up, nothing about the connection to the database.

Mar  6 14:05:41 vps172450 MailScanner[4024]: Read 1500 hostnames from the phishing whitelist
Mar  6 14:05:41 vps172450 MailScanner[4024]: Read 16118 hostnames from the phishing blacklists
Mar  6 14:05:41 vps172450 MailScanner[4024]: Config: calling custom init function MailWatchLogging
Mar  6 14:05:41 vps172450 MailScanner[4024]: MailWatch: Started MailWatch SQL Logging child
Mar  6 14:05:41 vps172450 MailScanner[4024]: Using SpamAssassin results cache
Mar  6 14:05:41 vps172450 MailScanner[4024]: Connected to SpamAssassin cache database
Mar  6 14:05:41 vps172450 MailScanner[4024]: Enabling SpamAssassin auto-whitelist functionality...
Mar  6 14:05:43 vps172450 MailScanner[4024]: Connected to Processing Attempts Database

I have checked and rechecked the DB connection properties and logged in with the mailwatch user directly. The front end comes up fine, just has no data in it.

Going mad here, any help is appreciated.

PS. Centos 7 64 bit, MariaDB 5.5.63. Mailwatch 1.2.7 installed.

Mark

**Comment by atftb** [comment]
You don’t say what version of MailScanner you’re using, but when I upgraded mine from 4.85  to 5.0.7-2 I had copy the MailWatch.pm to the new custom function directory which changed between 4.x and 5.x.  To wit:
  cp /root/1.2.0-master/MailScanner_perl_scripts/MailWatch.pm /usr/share/MailScanner/perl/custom/

May or may not be your issue, but until I did so mail flow was normal but nothing appeared in the MailWatch web interface...

...Kevin
--
Kevin Miller
Network/email Administrator, CBJ MIS Dept.
155 South Seward Street
Juneau, Alaska 99801
Phone: (907) 586-0242, Fax: (907) 586-4588 Registered Linux User No: 307357

**Comment by Skywalker-11** [comment]
@markrochester additionally to the MailWatch.pm you also have to copy MailWatchConf.pm from /MailScanner_perl_scripts/ to that directory and configure the database connection in it.

After that run `MailScanner --lint` and post the output here.

**Comment by markrochester** [comment]
Hi,

Thank you very much for those responses. I am going to check those two things out, make adjustments as necessary. If it doesn’t work then I will post the –lint up and see where we go from there.

Kind Regards,

Mark

**Comment by Skywalker-11** [comment]
@markrochester any news on this?

**Comment by markrochester** [comment]
Hi Guys,

Thanks for the follow up.

After playing with the configuration and multiple rebuilds, I came across the install script that was put together. Using that, and modifying it as it didn't work correctly during the MySQL installation, I managed to get it to work. Now I have a 'virtually' zero touch installation method for multiple instances of MailWatch, that all work beautifully. I wrapped some code around it that pulls preset config files for Postfix etc from another webserver, then places them in the right location. Saves editing files as part of the build process, it just drops them in.

As a note, in your install script, the MySQL service needs to be started before you call the mysql_secure_installation line in the mailwatch-mysql.inc file. Then I commented out the $sqlpassw component and replaced with just mysql -u root -p which prompted for the password and runs fine. This is the 'virtually' zero touch I was referring to.

Anyway, as is well. Thanks for your time.

Mark

**Comment by Skywalker-11** [comment]
Closing as problem is solved

**Comment by atftb** [comment]
I tried updating MailWatch on Debian Jessie and ran into issue, so decided to do a fresh install on Stretch.  I've installed MailScanner 5.0.7, and began to install Mailwatch.  Going to the web site and starting at the "Getting Started" web page.  That's about as far as I got.  The first step seems to be to upgrade DBD::mysql.  Here's the result of that effort:
========================================================= 
root@mxt:~# perl -MDBD::mysql -e 'print $DBD::mysql::VERSION'
4.041
root@mxt:~# 
root@mxt:~# apt-get install libmysqlclient-dev
Reading package lists... Done                                                                                                                                               
Building dependency tree                                                                                                                                                    
Reading state information... Done                                                                                                                                           
Package libmysqlclient-dev is not available, but is referred to by another package.                                                                                         
This may mean that the package is missing, has been obsoleted, or                                                                                                           
is only available from another source                                                                                                                                       
                                                                                                                                                                            
E: Package 'libmysqlclient-dev' has no installation candidate                                                                                                               
=========================================================

Is anyone running MailScanner/MailWatch on Stretch?  What's the secret?

Here's my apt sources - do I need to add a different one?
=========================================================
root@mxt:/etc/apt# cat sources.list
deb http://ftp.us.debian.org/debian/ stretch main
deb-src http://ftp.us.debian.org/debian/ stretch main

deb http://security.debian.org/debian-security stretch/updates main
deb-src http://security.debian.org/debian-security stretch/updates main

# stretch-updates, previously known as 'volatile'
deb http://ftp.us.debian.org/debian/ stretch-updates main
deb-src http://ftp.us.debian.org/debian/ stretch-updates main
=========================================================

Thanks...

...Kevin
--
Kevin Miller
Network/email Administrator, CBJ MIS Dept.
155 South Seward Street
Juneau, Alaska 99801
Phone: (907) 586-0242, Fax: (907) 586-4588 Registered Linux User No: 307357

**Comment by Skywalker-11** [comment]
The correct package is libdbd-mysql-perl
https://packages.debian.org/search?searchon=names&suite=stable&section=all&keywords=libdbd-mysql-perl

You can also try the develop branch of the installer script https://github.com/mailwatch/mailwatch-install-script/tree/develop/. It should install all the necessary packages and does a basic config (MariaDB-MySql, Apache, Postfix/Exim, MailScanner, MailWatch). It is still not finished but should work fine for Debian 8/9.
