### ISSUE TITLE
Pear error with quarantine report link

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#1053]
### Issue summary
Got error in MailWatch when I click on "View link" in Quarantine report mail.

### Steps to reproduce
1. click on "View link" on Quarantine report

https://host/viewmail.php?token=2a23148620b5501fb82e4a95566860797599fd02&id=1f3q0D-0002pb-Rl

Seems to have loop.

### Actual result

![sc-bug](https://user-images.githubusercontent.com/12907102/38351711-01a34a1a-38b1-11e8-9f26-664c48f8f07b.png)

### Version and method
 - MailWatch Version: 2.2.8

### Server configuration
 - Operation System: Debian Jessie uptodate
 - PHP version: 5.6.33
 - Database: MariaDB 10.1
 - Mail Server: Exim
 - Used web server: Apache

### Client configuration 
 - Operation System: OSX 10.13
 - Browser: Safari 11.1 or others

**Comment by Skywalker-11** [comment]
Can you provide that mail?

**Comment by stefaweb** [comment]
Hi @Skywalker-11!

It does not seem to be dependent on the message. The 2 mails in the quarantine report do the same when I click on them.

**Comment by stefaweb** [comment]
Hello @Skywalker-11!

I tried login with administrator, admin-domain or user. Same problem.

But I tried with others reports and it works. Seems related to these specific mails.

I will send you the mail.

At the end, I got this:
 
```
<b>Warning</b>:  Creating default object from empty value in <b>/var/www/html/mailscanner/lib/pear/Mail/mimeDecode.php</b> on line <b>424</b><br />
<br />
<b>Fatal error</b>:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 72 bytes) in <b>/var/www/html/mailscanner/lib/pear/Mail/mimeDecode.php</b> on line <b>424</b><br />

```
