### ISSUE TITLE
Error during "Send Daily Report" if no email address 

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#1054]
### Issue summary
Got error we click on "Send Daily Report" without email address in "Quarantine Report Recipient".

### Steps to reproduce
1. click on "Send Now"

![sc](https://user-images.githubusercontent.com/12907102/38407305-35bfa460-3979-11e8-88fe-9e706d94daf1.png)

### Actual result

> Warning: array_merge() expects at least 1 parameter, 0 given in /var/www/html/mailscanner/quarantine_report.inc.php on line 392
> The quarantine report was successfully sent.

If "Quarantine Report Recipient" is empty, we should have an alert message as "Please enter an email address in Quarantine Report Recipient first".

### Version and method
 - MailWatch Version: 2.2.8

### Server configuration
 - Operation System: Debian Jessie uptodate
 - PHP version: 5.6.33
 - Database: MariaDB 10.1
 - Mail Server: Exim
 - Used web server: Apache

### Client configuration 
 - Operation System: OSX 10.13
 - Browser: Safari 11.1 or others

**Comment by Skywalker-11** [comment]
If there is no quarantine recipient it defaults to send the report to the username (their mail address). 
https://github.com/mailwatch/MailWatch/blob/1.2/mailscanner/quarantine_report.inc.php#L304-L308

**Comment by Skywalker-11** [comment]
Problem that causes the error is not having a quarantined mail 😁
