### ISSUE TITLE
Maillog file empty

### ISSUE THREAD

**Issue by gregh3269** [mailwatch/1.2.0#1057]
Hello,

I have been trying to get the maillog to populate on various versions 1.2.6 and now 1.2.8 on centos 7. There seems some mismatch with the latest MailWatch.pm, because if I revert to a previous version which as the credentials in the MailWatch.pm file it works OK.  The credentials are correct in MailWatchConf.pm.  

Maybe I have missed something in the setup?  Any ideas?

Cheers Greg

Here is a dump for sending an email using the DBI->trace statement

    DBI 1.627-ithread default trace level set to 0x0/2 (pid 19049 pi 1d7f010) at MailWatch.pm line 51 via Config.pm line 752
    -- DBI::END ($@: , $!: )
    -- DBI::END ($@: , $!: )
    -> DBI->connect(dbi:SQLite:/var/spool/MailScanner/incoming/SpamAssassin.cache.db, , ****, HASH(0x3f5b2c8))
    -> DBI->install_driver(SQLite) for linux perl=5.016003 pid=19049 ruid=89 euid=89
       install_driver: DBD::SQLite version 1.39 loaded from /usr/lib64/perl5/vendor_perl/DBD/SQLite.pm
    <- install_driver= DBI::dr=HASH(0x4ba2c48)
    !! warn: 0 CLEARED by call to connect method
    -> connect for DBD::SQLite::dr (DBI::dr=HASH(0x4ba2c48)~0x4ba2cc0 '/var/spool/MailScanner/incoming/SpamAssassin.cache.db' '' **** HASH(0x21b06d8)) thr#1d7f010
    <- connect= ( DBI::db=HASH(0x4ba34e8) ) [1 items] at DBI.pm line 670
    -> STORE for DBD::SQLite::db (DBI::db=HASH(0x4ba3440)~INNER 'PrintError' 0) thr#1d7f010
    <- STORE= ( 1 ) [1 items] at DBI.pm line 722
    -> STORE for DBD::SQLite::db (DBI::db=HASH(0x4ba3440)~INNER 'AutoCommit' 1) thr#1d7f010
    <- STORE= ( 1 ) [1 items] at DBI.pm line 722
    -> STORE for DBD::SQLite::db (DBI::db=HASH(0x4ba3440)~INNER 'InactiveDestroy' 1) thr#1d7f010
    <- STORE= ( 1 ) [1 items] at DBI.pm line 725
    -> STORE for DBD::SQLite::db (DBI::db=HASH(0x4ba3440)~INNER 'Username' '') thr#1d7f010
    <- STORE= ( 1 ) [1 items] at DBI.pm line 725
    -> connected in DBD::_::db for DBD::SQLite::db (DBI::db=HASH(0x4ba34e8)~0x4ba3440 'dbi:SQLite:/var/spool/MailScanner/incoming/SpamAssassin.cache.db' '' **** HASH(0x3f5b2c8)) thr#1d7f010
    <- connected= ( undef ) [1 items] at DBI.pm line 732
    <- connect= DBI::db=HASH(0x4ba34e8)
    -> STORE for DBD::SQLite::db (DBI::db=HASH(0x4ba3440)~INNER 'dbi_connect_closure' CODE(0x4ba2c18)) thr#1d7f010
    <- STORE= ( 1 ) [1 items] at DBI.pm line 741
    -> do for DBD::SQLite::db (DBI::db=HASH(0x4ba34e8)~0x4ba3440 'PRAGMA default_synchronous = OFF') thr#1d7f010
    -> DESTROY for DBD::SQLite::st (DBI::st=HASH(0x4bde8c0)~INNER) thr#1d7f010
    <- DESTROY= ( undef ) [1 items] at SQLite.pm line 206
    <- do= ( '0E0' ) [1 items] at SA.pm line 214
    -> do for DBD::SQLite::db (DBI::db=HASH(0x4ba34e8)~0x4ba3440 'CREATE TABLE cache (md5 TEXT, count INTEGER, last TIMESTAMP, first TIMESTAMP, sasaysspam INT, sahighscoring INT, sascore FLOAT, saheader BLOB, salongreport BLOB, virusinfected INT)') thr#1d7f010
    -> DESTROY for DBD::SQLite::st (DBI::st=HASH(0x4bde908)~INNER) thr#1d7f010
         DESTROY for DBI::st=HASH(0x4bde908) ignored - handle not initialised
       ERROR: 1 'table cache already exists' (err#1)
    <- DESTROY= ( undef ) [1 items] at SQLite.pm line 207
    !! ERROR: 1 'table cache already exists' (err#0)
    <- do= ( undef ) [1 items] at SA.pm line 215
    !! ERROR: 1 CLEARED by call to do method
    -> do for DBD::SQLite::db (DBI::db=HASH(0x4ba34e8)~0x4ba3440 'CREATE UNIQUE INDEX md5_uniq ON cache(md5)') thr#1d7f010
    -> DESTROY for DBD::SQLite::st (DBI::st=HASH(0x4bde8c0)~INNER) thr#1d7f010
         DESTROY for DBI::st=HASH(0x4bde8c0) ignored - handle not initialised
       ERROR: 1 'index md5_uniq already exists' (err#1)
    <- DESTROY= ( undef ) [1 items] at SQLite.pm line 207
    !! ERROR: 1 'index md5_uniq already exists' (err#0)
    <- do= ( undef ) [1 items] at SA.pm line 216
    !! ERROR: 1 CLEARED by call to do method
    -> do for DBD::SQLite::db (DBI::db=HASH(0x4ba34e8)~0x4ba3440 'CREATE INDEX last_seen_idx ON cache(last)') thr#1d7f010
    -> DESTROY for DBD::SQLite::st (DBI::st=HASH(0x4bdea70)~INNER) thr#1d7f010
         DESTROY for DBI::st=HASH(0x4bdea70) ignored - handle not initialised
       ERROR: 1 'index last_seen_idx already exists' (err#1)
    <- DESTROY= ( undef ) [1 items] at SQLite.pm line 207
    !! ERROR: 1 'index last_seen_idx already exists' (err#0)
    <- do= ( undef ) [1 items] at SA.pm line 217
    !! ERROR: 1 CLEARED by call to do method
    -> do for DBD::SQLite::db (DBI::db=HASH(0x4ba34e8)~0x4ba3440 'CREATE INDEX first_seen_idx ON cache(first)') thr#1d7f010
    -> DESTROY for DBD::SQLite::st (DBI::st=HASH(0x4bde920)~INNER) thr#1d7f010
         DESTROY for DBI::st=HASH(0x4bde920) ignored - handle not initialised
       ERROR: 1 'index first_seen_idx already exists' (err#1)
    <- DESTROY= ( undef ) [1 items] at SQLite.pm line 207
    !! ERROR: 1 'index first_seen_idx already exists' (err#0)
    <- do= ( undef ) [1 items] at SA.pm line 218
    !! ERROR: 1 CLEARED by call to prepare method
    -> prepare for DBD::SQLite::db (DBI::db=HASH(0x4ba34e8)~0x4ba3440 '
   DELETE FROM cache WHERE (
   (sasaysspam=0 AND virusinfected<1 AND first<=(strftime('%s','now')-?)) OR
   (sasaysspam>0 AND sahighscoring=0 AND virusinfected<1 AND first<=(strftime('%s','now')-?)) OR
   (sasaysspam>0 AND sahighscoring>0 AND virusinfected<1 AND last<=(strftime('%s','now')-?)) OR
   (virusinfected>=1 AND last<=(strftime('%s','now')-?))
  )') thr#1d7f010
    <- prepare= ( DBI::st=HASH(0x22121d8) ) [1 items] at SA.pm line 799
    -> execute for DBD::SQLite::st (DBI::st=HASH(0x22121d8)~0x4bde920 '1800' '300' '10800' '172800') thr#1d7f010
    <- execute= ( '0E0' ) [1 items] at SA.pm line 807
    -> finish for DBD::SQLite::st (DBI::st=HASH(0x22121d8)~0x4bde920) thr#1d7f010
    <- finish= ( 1 ) [1 items] at SA.pm line 808
    -> DESTROY for DBD::SQLite::st (DBI::st=HASH(0x4bde920)~INNER) thr#1d7f010
    <- DESTROY= ( undef ) [1 items] at SA.pm line 224
    -> DBI->connect(dbi:SQLite:/var/spool/MailScanner/incoming/Processing.db, , ****, HASH(0x57c50b8))
    -> connect for DBD::SQLite::dr (DBI::dr=HASH(0x4ba2c48)~0x4ba2cc0 '/var/spool/MailScanner/incoming/Processing.db' '' **** HASH(0x4ba36f8)) thr#1d7f010
    <- connect= ( DBI::db=HASH(0x57a0aa0) ) [1 items] at DBI.pm line 670
    -> STORE for DBD::SQLite::db (DBI::db=HASH(0x5686150)~INNER 'PrintError' 0) thr#1d7f010
    <- STORE= ( 1 ) [1 items] at DBI.pm line 722
    -> STORE for DBD::SQLite::db (DBI::db=HASH(0x5686150)~INNER 'AutoCommit' 1) thr#1d7f010
    <- STORE= ( 1 ) [1 items] at DBI.pm line 722
    -> STORE for DBD::SQLite::db (DBI::db=HASH(0x5686150)~INNER 'InactiveDestroy' 1) thr#1d7f010
    <- STORE= ( 1 ) [1 items] at DBI.pm line 725
    -> STORE for DBD::SQLite::db (DBI::db=HASH(0x5686150)~INNER 'Username' '') thr#1d7f010
    <- STORE= ( 1 ) [1 items] at DBI.pm line 725
    -> connected in DBD::_::db for DBD::SQLite::db (DBI::db=HASH(0x57a0aa0)~0x5686150 'dbi:SQLite:/var/spool/MailScanner/incoming/Processing.db' '' **** HASH(0x57c50b8)) thr#1d7f010
    <- connected= ( undef ) [1 items] at DBI.pm line 732
    <- connect= DBI::db=HASH(0x57a0aa0)
    -> STORE for DBD::SQLite::db (DBI::db=HASH(0x5686150)~INNER 'dbi_connect_closure' CODE(0x58b9390)) thr#1d7f010
    <- STORE= ( 1 ) [1 items] at DBI.pm line 741
    -> do for DBD::SQLite::db (DBI::db=HASH(0x57a0aa0)~0x5686150 'PRAGMA default_synchronous = OFF') thr#1d7f010
    -> DESTROY for DBD::SQLite::st (DBI::st=HASH(0x6d9ddc8)~INNER) thr#1d7f010
    <- DESTROY= ( undef ) [1 items] at SQLite.pm line 206
    <- do= ( '0E0' ) [1 items] at MailScanner line 1770
    -> do for DBD::SQLite::db (DBI::db=HASH(0x57a0aa0)~0x5686150 'CREATE TABLE processing (id TEXT, count INT, nexttime INT)') thr#1d7f010
    -> DESTROY for DBD::SQLite::st (DBI::st=HASH(0x6d91288)~INNER) thr#1d7f010
         DESTROY for DBI::st=HASH(0x6d91288) ignored - handle not initialised
       ERROR: 1 'table processing already exists' (err#1)
    <- DESTROY= ( undef ) [1 items] at SQLite.pm line 207
    !! ERROR: 1 'table processing already exists' (err#0)
    <- do= ( undef ) [1 items] at MailScanner line 1771
    !! ERROR: 1 CLEARED by call to do method
    -> do for DBD::SQLite::db (DBI::db=HASH(0x57a0aa0)~0x5686150 'CREATE UNIQUE INDEX id_uniq ON processing(id)') thr#1d7f010
    -> DESTROY for DBD::SQLite::st (DBI::st=HASH(0x6d9ddc8)~INNER) thr#1d7f010
         DESTROY for DBI::st=HASH(0x6d9ddc8) ignored - handle not initialised
       ERROR: 1 'index id_uniq already exists' (err#1)
    <- DESTROY= ( undef ) [1 items] at SQLite.pm line 207
    !! ERROR: 1 'index id_uniq already exists' (err#0)
    <- do= ( undef ) [1 items] at MailScanner line 1772
    !! ERROR: 1 CLEARED by call to do method
    -> do for DBD::SQLite::db (DBI::db=HASH(0x57a0aa0)~0x5686150 'CREATE TABLE archive (id TEXT, count INT, nexttime INT)') thr#1d7f010
    -> DESTROY for DBD::SQLite::st (DBI::st=HASH(0x6ddd0f0)~INNER) thr#1d7f010
         DESTROY for DBI::st=HASH(0x6ddd0f0) ignored - handle not initialised
       ERROR: 1 'table archive already exists' (err#1)
    <- DESTROY= ( undef ) [1 items] at SQLite.pm line 207
    !! ERROR: 1 'table archive already exists' (err#0)
    <- do= ( undef ) [1 items] at MailScanner line 1773
    !! ERROR: 1 CLEARED by call to selectrow_array method
    -> selectrow_array for DBD::SQLite::db (DBI::db=HASH(0x57a0aa0)~0x5686150 'SELECT COUNT(*) FROM processing') thr#1d7f010
    <- selectrow_array= ( 0 ) [1 items] at MailScanner line 1776
    -> DESTROY for DBD::SQLite::st (DBI::st=HASH(0x5bb8298)~INNER) thr#1d7f010
    <- DESTROY= ( undef ) [1 items] at MailScanner line 1777
    -> prepare for DBD::SQLite::db (DBI::db=HASH(0x57a0aa0)~0x5686150 'SELECT id,count,nexttime FROM processing WHERE (id=?)') thr#1d7f010
    <- prepare= ( DBI::st=HASH(0x6ddcad8) ) [1 items] at MailScanner line 1781
    -> prepare for DBD::SQLite::db (DBI::db=HASH(0x57a0aa0)~0x5686150 'DELETE FROM processing WHERE (id=?)') thr#1d7f010
    <- prepare= ( DBI::st=HASH(0x4bdeb60) ) [1 items] at MailScanner line 1783
    -> prepare for DBD::SQLite::db (DBI::db=HASH(0x57a0aa0)~0x5686150 'INSERT INTO archive (id,count,nexttime) VALUES (?,?,?)') thr#1d7f010
    <- prepare= ( DBI::st=HASH(0x5bd3f88) ) [1 items] at MailScanner line 1785
    -> prepare for DBD::SQLite::db (DBI::db=HASH(0x57a0aa0)~0x5686150 'UPDATE processing SET count=count+1, nexttime=? WHERE (id=?)') thr#1d7f010
    <- prepare= ( DBI::st=HASH(0x5a29c80) ) [1 items] at MailScanner line 1787
    -> prepare for DBD::SQLite::db (DBI::db=HASH(0x57a0aa0)~0x5686150 'INSERT INTO processing (id,count,nexttime) VALUES (?,?,?)') thr#1d7f010
    <- prepare= ( DBI::st=HASH(0x57de420) ) [1 items] at MailScanner line 1789
    -> prepare for DBD::SQLite::db (DBI::db=HASH(0x57a0aa0)~0x5686150 'SELECT id,count,nexttime FROM processing WHERE (id=?)') thr#1d7f010
    <- prepare= ( DBI::st=HASH(0x6e6ac20) ) [1 items] at MailScanner line 1791
    -> prepare for DBD::SQLite::db (DBI::db=HASH(0x57a0aa0)~0x5686150 'SELECT count FROM processing WHERE (id=?)') thr#1d7f010
    <- prepare= ( DBI::st=HASH(0x6cfa488) ) [1 items] at MailScanner line 1793
    -> prepare for DBD::SQLite::db (DBI::db=HASH(0x57a0aa0)~0x5686150 'UPDATE processing SET count=count-1 WHERE (id=?)') thr#1d7f010
    <- prepare= ( DBI::st=HASH(0x57df7f8) ) [1 items] at MailScanner line 1795

**Comment by gregh3269** [comment]
Comparing the working old debug with the not working new :

Old MailWatch.pm
> execute for DBD::SQLite::st (DBI::st=HASH(0x4b804c8)~0x6d99c60 'A3D2133B198.AB453') thr#1d40010
    <- execute= ( 1 ) [1 items] at MessageBatch.pm line 1306
    -> ping for DBD::mysql::db (DBI::db=HASH(0x431faf8)~0x431fc90) thr#23b8010
    <- ping= ( 1 ) [1 items] at MailWatch.pm line 130

New MailWatch.pm

-> execute for DBD::SQLite::st (DBI::st=HASH(0x505d908)~0x52ac188 '91B5733B1B3.ABA18' 1 1523610019) thr#1656010
    <- execute= ( 1 ) [1 items] at Postfix.pm line 1951
    -- DBI::END ($@: , $!: )
    -> disconnect_all for DBD::SQLite::dr (DBI::dr=HASH(0x449cfd8)~0x449d050) thr#1656010

seems to be using different .pm files, where the new version does not use the MailWatch.pm routine.

**Comment by Skywalker-11** [comment]
Which mailscanner version do you use? One of the older versions had a bug which caused mailwatch not beeing restartet when using `systemctl restart mailscanner`. 

Also please post the output of `MailScanner --lint`

**Comment by Skywalker-11** [comment]
Also make sure that you have run upgrade.php after updating MailWatch. There have been changes in the sql table structure that requires an update.

**Comment by gregh3269** [comment]
I have already run the upgrade.php.  Everything is working except the sql.

MailScanner --lint
Trying to setlogsock(unix)
Reading configuration file /etc/MailScanner/MailScanner.conf
Reading configuration file /etc/MailScanner/conf.d/README
Read 1501 hostnames from the phishing whitelist
Read 15849 hostnames from the phishing blacklists
Config: calling custom init function MailWatchLogging
MailWatch: Started MailWatch SQL Logging child

Checking version numbers...
Version number in MailScanner.conf (5.0.6) is correct.

Your envelope_sender_header in spamassassin.conf is correct.
MailScanner setting GID to  (89)
MailScanner setting UID to  (89)

Checking for SpamAssassin errors (if you use it)...
Using SpamAssassin results cache
Connected to SpamAssassin cache database
SpamAssassin reported no errors.
Connected to Processing Attempts Database
Created Processing Attempts Database successfully
There are 0 messages in the Processing Attempts Database
Using locktype = posix
MailScanner.conf says "Virus Scanners = clamav"
Found these virus scanners installed: clamav
===========================================================================
Filename Checks: Windows/DOS Executable (1 eicar.com)
Other Checks: Found 1 problems
Virus and Content Scanning: Starting
1.message: Eicar-Test-Signature FOUND

./1/eicar.com: Eicar-Test-Signature FOUND

Virus Scanning: ClamAV found 2 infections
Infected message 1 came from 10.1.1.1
Virus Scanning: Found 2 viruses
===========================================================================
Virus Scanner test reports:
ClamAV said "eicar.com contains Eicar-Test-Signature"

If any of your virus scanners (clamav)
are not listed there, you should check that they are installed correctly
and that MailScanner is finding them correctly via its virus.scanners.conf.
Config: calling custom end function MailWatchLogging

**Comment by gregh3269** [comment]
systemctl status mailscanner
● mailscanner.service - LSB: MailScanner daemon
   Loaded: loaded (/usr/lib/MailScanner/init/ms-init; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/mailscanner.service.d
           └─override.conf
   Active: active (running) since Fri 2018-04-13 13:44:09 BST; 10s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 20578 ExecStop=/usr/lib/MailScanner/init/ms-init stop (code=exited, status=0/SUCCESS)
  Process: 21037 ExecStart=/usr/lib/MailScanner/init/ms-init start (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/mailscanner.service
           ├─21559 MailWatch SQL
           ├─21564 MailScanner: starting children
           ├─21565 MailScanner: scanning for filenames and filetypes
           ├─21580 MailScanner: starting children
           ├─21593 /bin/sh /usr/lib/MailScanner/wrapper/clamav-wrapper /usr -r --infected --stdout .
           ├─21602 /usr/bin/clamscan --tempdir=/var/spool/MailScanner/incoming/clamav-tmp/tmp.keapSXAMSW -r --infected --stdout .
           └─21607 MailScanner: starting children

Apr 13 13:44:19 dev.uk MailScanner[21607]: Reading configuration file /etc/MailScanner/MailScanner.conf
Apr 13 13:44:19 dev.uk MailScanner[21607]: Reading configuration file /etc/MailScanner/conf.d/README
Apr 13 13:44:19 dev.uk MailScanner[21607]: Read 1501 hostnames from the phishing whitelist
Apr 13 13:44:19 dev.uk MailScanner[21607]: Read 15849 hostnames from the phishing blacklists
Apr 13 13:44:19 dev.uk MailScanner[21607]: Config: calling custom init function MailWatchLogging
Apr 13 13:44:19 dev.uk MailScanner[21607]: MailWatch: Started MailWatch SQL Logging child
Apr 13 13:44:19 dev.uk MailScanner[21607]: Using SpamAssassin results cache
Apr 13 13:44:19 dev.uk MailScanner[21607]: Connected to SpamAssassin cache database
Apr 13 13:44:19 dev.uk MailScanner[21607]: Enabling SpamAssassin auto-whitelist functionality...

**Comment by Skywalker-11** [comment]
Can you try adding `MailScanner::Log::InfoLog("Loaded MailWatch Config");` in the MailWatchConf.pm:
``` 
sub mailwatch_get_SS_refresh_time { return $ss_refresh_time };
MailScanner::Log::InfoLog("Loaded MailWatch Config");
1;
```
And run `MailScanner --lint` again. If the config file is loaded correctly in MailScanner it will show "Loaded MailWatch Config" in the output. 
Also consider updating MailScanner to the current version (v5.0.7-2) which contains fixes for usage with systemd.

**Comment by gregh3269** [comment]
Logs correctly:
MailScanner --lint
Trying to setlogsock(unix)
Loaded MailWatch Config

Reading configuration file /etc/MailScanner/MailScanner.conf
Reading configuration file /etc/MailScanner/conf.d/README
...

I use the default centos repo  so would not really like to switch packages
Installed Packages
Name        : MailScanner
Arch        : noarch
Version     : 5.0.6
Release     : 4
Repo        : installed
..

It seems there is a script/config issue in MailWatch.pm somewhere, otherwise the old version would not work?  ...it also does not work on any of my other centos7 distros. 

Cheers Greg

**Comment by gregh3269** [comment]
From the debug traces, this is the output where it seems to go wrong, any idea what it means?

imp_dbh->pmysql: 2fe1b60

not working output
!   <- DESTROY= ( undef ) [1 items] during global destruction
    -> disconnect for DBD::mysql::db (DBI::db=HASH(0x2c760f0)~0x2c761b0) thr#c8b010
imp_dbh->pmysql: 2fe1b60
    <- disconnect= ( 1 ) [1 items] at MailWatch.pm line 145

working debug
-> ping for DBD::mysql::db (DBI::db=HASH(0x431faf8)~0x431fc90) thr#23b8010
    <- ping= ( 1 ) [1 items] at MailWatch.pm line 130
    -> execute for DBD::mysql::st (DBI::st=HASH(0x431f7c8)~0x431fae0 '2018-04-13 09:29:21' 'A3D2133B198.AB453' 796 'dev@dev.uk' 'dev.uk'

**Comment by Skywalker-11** [comment]
Are you sure you installed it via default centos repository? I can only find the install method via rhel.tar.gz that installs the rpm file. https://www.mailscanner.info/downloads/

**Comment by Skywalker-11** [comment]
An other thing could be outdated dbd version `cpan -D DBD::mysql` shows this or missing perl module `MailScanner -v | grep missing`.

**Comment by gregh3269** [comment]
I did a yum info which replied, ..Repo        : installed,  so may be its from mailscanner.info. I will upgrade it to see if it fixes it.

**Comment by gregh3269** [comment]
Still not working. :-(
 
MailScanner --lint
Trying to setlogsock(unix)
Reading configuration file /etc/MailScanner/MailScanner.conf
Reading configuration file /etc/MailScanner/conf.d/README
Read 868 hostnames from the phishing whitelist
Read 5807 hostnames from the phishing blacklists
Config: calling custom init function MailWatchLogging
MailWatch: Started MailWatch SQL Logging child

Checking version numbers...
Version number in MailScanner.conf (5.0.7) is correct.

Your envelope_sender_header in spamassassin.conf is correct.
MailScanner setting GID to  (89)
MailScanner setting UID to  (89)

Checking for SpamAssassin errors (if you use it)...
Using SpamAssassin results cache
Connected to SpamAssassin cache database
SpamAssassin reported no errors.
Connected to Processing Attempts Database
Created Processing Attempts Database successfully
There are 0 messages in the Processing Attempts Database
Using locktype = posix
MailScanner.conf says "Virus Scanners = clamav"
Found these virus scanners installed: clamav
===========================================================================
Filename Checks: Windows/DOS Executable (1 eicar.com)
Other Checks: Found 1 problems
Virus and Content Scanning: Starting
1.message: Eicar-Test-Signature FOUND

./1/eicar.com: Eicar-Test-Signature FOUND

Virus Scanning: ClamAV found 2 infections
Infected message 1 came from 10.1.1.1
Virus Scanning: Found 2 viruses
===========================================================================
Virus Scanner test reports:
ClamAV said "eicar.com contains Eicar-Test-Signature"

If any of your virus scanners (clamav)
are not listed there, you should check that they are installed correctly
and that MailScanner is finding them correctly via its virus.scanners.conf.
Config: calling custom end function MailWatchLogging

**Comment by gregh3269** [comment]
From the command I get: 

MailScanner -v | grep missing
missing	Mail::ClamAV
missing	SAVI

**Comment by Skywalker-11** [comment]
What does `cpan -D DBD::mysql` return?

**Comment by gregh3269** [comment]
cpan -D DBD::mysql
Reading '/root/.cpan/Metadata'
  Database was generated on Fri, 13 Apr 2018 13:54:27 GMT
DBD::mysql
-------------------------------------------------------------------------
	(no description)
	C/CA/CAPTTOFU/DBD-mysql-4.046.tar.gz
	/usr/lib64/perl5/vendor_perl/DBD/mysql.pm
	Installed: 4.023
	CPAN:      4.046  Not up to date
	Patrick Galbraith (CAPTTOFU)
	patg@patg.net

**Comment by Skywalker-11** [comment]
I just did a fresh install of CentOS 7 with the install script here https://github.com/Skywalker-11/mailwatch-install-script/tree/fixnosqluser (PR https://github.com/mailwatch/mailwatch-install-script/pull/34)
Using MS 5.0.7-2, MW 1.2.8, apache, postfix for setup logging to the db is working. In some cases it requires a reboot after install

**Comment by gregh3269** [comment]
Can you share the mailscanner.conf, postfix main.cf, (any others?) maybe I can check for differences.
Cheers Greg

**Comment by Skywalker-11** [comment]
Postfix config doesn't matter as long as MailScanner starts the scan (only needs the header_checks).
MailScanner is the default config with https://github.com/Skywalker-11/mailwatch-install-script/blob/fixnosqluser/setup.scripts/postfix/etc/MailScanner/conf.d/00_mailwatch.conf in the /etc/MailScanner/conf.d/ folder.
An other thing to check is if MailScanner actually starts the sql thread:
```
# ps aux | grep "MailWatch SQL"
postfix   17089  0.0  0.6 140420 50860 ?        S    14:17   0:00 MailWatch SQL
```
And if it actually listens on port 11553:
```
# netstat -tulpen | grep "MailWatch SQL"
tcp        0      0 127.0.0.1:11553         0.0.0.0:*               LISTEN      108        95823      17089/MailWatch SQL
```

Or simply a reboot 😁 
If that doesn't work you can try the install script from here https://github.com/Skywalker-11/mailwatch-install-script/archive/fixnosqluser.zip on a fresh CentOS (tested with minimal iso) to get a basic working setup and then customize it

**Comment by Skywalker-11** [comment]
One more thing: use the current MariaDB server repo provided here: https://github.com/Skywalker-11/mailwatch-install-script/blob/fixnosqluser/yum.repo/CentOS-7-MariaDB.64.repo

**Comment by gregh3269** [comment]
I checked 00_mailwatch.conf and the only differences are the groups : mtagroup

Run As Group = postfix
Incoming Work Group = clamscan
Quarantine User = root
Quarantine Group = apache

ps aux | grep "MailWatch SQL"
root     32743  0.0  0.0 112660   976 pts/0    S+   13:44   0:00 grep --color=auto MailWatch SQL

I do not get anything for the netstat on 11553 ?
netstat -tulpen | grep "MailWatch SQL"

**Comment by Skywalker-11** [comment]
The group shouldn't be a problem for logging to sql.

The ps command and netstat command show that the sql logging process has not been started or has been stopped. 
Have you already done a reboot?

**Comment by gregh3269** [comment]
I checked/adjusted the firewall and now I get :

ps aux | grep "MailWatch SQL"
postfix   3055  0.0  0.5 334996 39536 ?        S    14:12   0:00 MailWatch SQL
root      5546  0.0  0.0 112664   980 pts/0    S+   14:18   0:00 grep --color=auto MailWatch SQL

netstat -tulpen | grep "MailWatch SQL"
tcp        0      0 127.0.0.1:11553         0.0.0.0:*               LISTEN      89         32135      3055/MailWatch SQL 

but, still no logging to maillog.

I will try and put some debug statements in the Mailwatch.pm.

Cheers Greg

**Comment by gregh3269** [comment]
use Encoding::FixLatin qw(fix_latin);

(Error: Can't locate Encoding/FixLatin.pm in @INC (@INC contains: /usr/sbin /usr/sbin/MailScanner

Where should Encoding/FixLatin.pm be?

**Comment by Skywalker-11** [comment]
`cpan install Encoding::FixLatin`

**Comment by gregh3269** [comment]
I have to admit defeat now on this,  still not working and now not working on the old config file.  Maybe on a next server this will be useful again.

Cheers for your help.

**Comment by gregh3269** [comment]
Rechecking this today it is now is now working :-).  On my other box, I ran the cpan install Encoding::FixLatin command, dropped the files on the db (encoding was different??), recreated the files and ran the upgrade.php.  Rebooted.

So it seemed to be the missing: cpan install Encoding::FixLatin 
Maybe add a check for this somewhere?

Cheers Greg
