### ISSUE TITLE
ClamAV version not displayed on MW-1.2.9

### ISSUE THREAD

**Issue by falsagoff** [mailwatch/1.2.0#1062]
### Issue summary
On the "Software Versions" tab, ClamAV Version is not displayed.

I know this has been reported before. This is just an update to that considering that I am running latest version of MailScanner(5.0.7) and latest version of MW(1.2.9) 

Running "/usr/lib/MailScanner/wrapper/clamav-wrapper . -V" on the commandline works perfectly though. It returns:
ClamAV 0.99.4/24505/Mon Apr 23 12:24:23 2018

### Version and method
 - MailWatch Version: [ stable 1.2.9 ]
 - Install type: [ GitHub checkout | tarball install ]
 - Updated from a fresh install: [ Fresh install ]

### Server configuration
 - Operation System: [ CentOS ] version [ 7.4.1708 ]
 - PHP version: [ 5.4.16 ]
 - Database: [ MariaDB ] version [ 10.1 ]
 - Mail Server: [ Postfix ]
 - Used web server: [ Apache ] version [ 2.4.6 ]
- ClamAV version 0.99.4

### Client configuration 
 - Operation System: [ Fedora Linux ] version [ 27 ]
 - Browser: [ Chrome ]

**Comment by stefaweb** [comment]
Hello!

Works here with Debian Jessie / php 5.6.

**Comment by falsagoff** [comment]
FYI. I applied philrandal's patch as in "Simplify ClamAV version detection #1060" post. It works good for me.
I know its not official but I will just stick with it for now.
