### ISSUE TITLE
MYSQL Syntax Errors thrown if there's no filter defined by default

### ISSUE THREAD

**Issue by RT4U** [mailwatch/1.2.0#1065]
On a fresh installation of MailWatch, after a successful login, status.php spews out SQL Syntax errors.

After digging deep into the codes, I found that $SESSION['global_filter'] is blank and that's causing the issue. 

For example
When `printTodayStatistics` function is called, the sql query throws an error.

> "PHP message: PHP Fatal error:  Uncaught mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')'

Upon examining the code, there's indeed an SQL syntax error caused by the blank `$SESSION['global_filter']`, which is in-turn injected to the end of the sql code like `"...AND ". $SESSION['global_filter']."";` in functions.php - function `printTodayStatistics`.

It also affects every part of the code which uses global_filter in the SQL code.

Affected version - 1.2.9 maybe also lower versions.

I've made an easy fix for this.

Patched the function address_filter_sql in functions.php by adding the following two lines of code before return statement

```
#Patch if no filters found
    if($sqladdr == '')
       $sqladdr = "1=1";
```

**Comment by Skywalker-11** [comment]
#1067
