### ISSUE TITLE
MYSQL Syntax Error - When listing Total Messages by Date

### ISSUE THREAD

**Issue by RT4U** [mailwatch/1.2.0#1066]
Error message thrown

`PHP message: PHP Fatal error:  Uncaught mysqli_sql_exception: Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'mailscanner.maillog.date' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by`

Fresh installation - version 1.2.9

Fix, that worked for me

Execute the below query as admin or root to reset the sql_mode

`SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''))`

**Comment by Skywalker-11** [comment]
@RT4U which mysql server and version are you using?

**Comment by Skywalker-11** [comment]
#1067
