### ISSUE TITLE
MYSQL Syntax Error - When listing whitelist/blacklist

### ISSUE THREAD

**Issue by RT4U** [mailwatch/1.2.0#1067]
Fresh installation of MailWatch 1.2.9

Blank whitelist/blanklist.

PHP Error thrown

`"PHP message: PHP Fatal error:  Uncaught mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ORDER BY from_address'` in lists.php at line 416

Query in php

```
'SELECT id, from_address, to_address FROM whitelist WHERE ' . $_SESSION['global_list'] . ' ORDE$
    'w'
```

NOTE - It also affects every part of the code where `$_SESSION['global_list']` is used.

Cause of the problem, $_SESSION['global_list'] is set to blank in checklogin.php line 165

` $_SESSION['global_list'] = (isset($global_list) ? $global_list : '');`

My fix/patch,

` $_SESSION['global_list'] = (isset($global_list) ? $global_list : '1=1');`

**Comment by Skywalker-11** [comment]
The variable $global_list should never be empty as it will be set by https://github.com/mailwatch/MailWatch/blob/1.2/mailscanner/checklogin.php#L127-L154

Is this happening for all users?

**Comment by RT4U** [comment]
Feel free to close my last 3 issues. I didn't set the user type to A at the time of user creation. That resolved the problem.

The code spews out errors if the user type is not set, so the usertype field should be a non null in create.sql
