### ISSUE TITLE
Description of database tables

### ISSUE THREAD

**Issue by KHIT93** [mailwatch/1.2.0#1068]
I am working on a task to pull some data using an external application and for that task I need to know what is located in each table. Is there a description available somewhere on what is stored in each table?

**Comment by Skywalker-11** [comment]
* audit_log: If enabled contains security related changes and changes of system setting like changes of password, black/whitelist
* blacklist/whitelist: used to filter by mails by their recipient/sender 
* maillog: log all mails that are beeing processed by mailscanner with their meta data (headers, quarantined, file path in quarantine, spamassassin rating ...)
* inq/outq: mailq (inbound/outbound) of exim
* mcp_rules:  for MailScanner MCP 
* mtalog: additional logs when using postfix_relay (independend from mailscanner)
* mtalog_ids: mapping from mtalog to maillog
* saved_filters: store filters for "search and reports" page
* sa_rules: spamassassin rules descriptions to show for mails on detail page
* users: users with their settings
* user_filters: filter for mail addresses on per user basis

**Comment by Skywalker-11** [comment]
@KHIT93 do you need more info or can we close this issue?
