### ISSUE TITLE
Spamassassin bayes not present

### ISSUE THREAD

**Issue by mickaelmonsieur** [mailwatch/1.2.0#1070]
Hi,
I followed the installation instructions (http://docs.mailwatch.org/install/installing.html) 
My system is a debian 9.
I installed spamassassin (apt-get install spamassassin)
mailwatch sees spamassassin (SpamAssassin Version: 3.4.1)
I am stuck at the next step:

>$ cp /root/.spamassassin/bayes_* /etc/MailScanner/bayes
>$ chown root:www-data /etc/MailScanner/bayes/bayes_*
>$ chmod g+rw /etc/MailScanner/bayes/bayes_*

because /root/.spamassassin/ is empty. 

>root@in-mx:~/.spamassassin# ls -al
>total 8
>drwx------ 2 root root 4096 mai 13 09:25 .
>drwx------ 5 root root 4096 mai 13 11:26 ..

Why ?
Thanks.

**Comment by Skywalker-11** [comment]
If you don't have a bayes database yet you can create a new one with `sa-learn --sync`. For more debug output use `sa-learn -D --sync`.
It should show something like the following at the end
```
...
May 13 17:28:19.681 [30424] dbg: bayes: bayes journal sync starting
May 13 17:28:19.682 [30424] dbg: bayes: bayes journal sync completed
May 13 17:28:19.683 [30424] dbg: plugin: Mail::SpamAssassin::Plugin::Bayes=HASH(0x185b510) implements 'learner_expire_old_training', priority 0
May 13 17:28:19.683 [30424] dbg: bayes: expiry starting
May 13 17:28:19.684 [30424] dbg: locker: mode is 384
May 13 17:28:19.685 [30424] dbg: locker: safe_lock: created /etc/MailScanner/bayes.mutex
May 13 17:28:19.686 [30424] dbg: locker: safe_lock: trying to get lock on /etc/MailScanner/bayes with 300 timeout
May 13 17:28:19.687 [30424] dbg: locker: safe_lock: link to /etc/MailScanner/bayes.mutex: link ok
May 13 17:28:19.688 [30424] dbg: bayes: tie-ing to DB file R/W /etc/MailScanner/bayes_toks
May 13 17:28:19.703 [30424] dbg: bayes: tie-ing to DB file R/W /etc/MailScanner/bayes_seen
...
```
Then continue with the chown
