### ISSUE TITLE
Please verify read permissions on /var/spool/postfix/hold and /var/spool/postfix/incoming

### ISSUE THREAD

**Issue by mickaelmonsieur** [mailwatch/1.2.0#1071]
Hi,
I followed the installation instructions (http://docs.mailwatch.org/install/installing.html)
My system is a debian 9.
I have the error: "Please verify read permissions on /var/spool/postfix/hold and /var/spool/postfix/incoming"

My config of MailScanner.conf is:

>Run As User = postfix
>Run As Group = postfix
>Incoming Work User = postfix
>Incoming Work Group = mtagroup
>Incoming Work Permissions = 0660
>Quarantine User = postfix
>Quarantine Group = mtagroup
>Quarantine Permissions = 0644

the group "mtagroup" exists with users "clamav,postfix,mail"

my postfix spool is:

```
root@in-mx:/var/spool/postfix# ls -al
total 80
drwxr-xr-x 20 root    root     4096 mai 13 09:21 .
drwxr-xr-x  6 root    root     4096 mai 13 09:33 ..
drwx------  2 postfix root     4096 mai 13 09:21 active
drwx------  2 postfix root     4096 mai 13 09:21 bounce
drwx------  2 postfix root     4096 mai 13 09:21 corrupt
drwx------  2 postfix root     4096 mai 13 09:21 defer
drwx------  2 postfix root     4096 mai 13 09:21 deferred
drwxr-xr-x  2 root    root     4096 mai 13 09:21 dev
drwxr-xr-x  3 root    root     4096 mai 13 09:21 etc
drwx------  2 postfix root     4096 mai 13 09:21 flush
drwx------  2 postfix root     4096 mai 13 09:21 hold
drwx------  2 postfix root     4096 mai 13 09:21 incoming
drwxr-xr-x  3 root    root     4096 mai 13 09:21 lib
drwx-wx--T  2 postfix postdrop 4096 mai 13 09:21 maildrop
drwxr-xr-x  2 root    root     4096 mai 13 17:30 pid
drwx------  2 postfix root     4096 mai 13 09:21 private
drwx--s---  2 postfix postdrop 4096 mai 13 09:21 public
drwx------  2 postfix root     4096 mai 13 09:21 saved
drwx------  2 postfix root     4096 mai 13 09:21 trace
drwxr-xr-x  3 root    root     4096 mai 13 09:20 usr
```

obviously, if I put chmod 777 on incoming and hold, the error disappears.
but it is not recommended.

if I modify the users / rights on incoming and hold, postfix will probably be impacted.

what should I do ?

**Comment by asuweb** [comment]
Add apache user to `mtagroup` - presumably `www-data` for debian

```
chgrp mtagroup /var/spool/postfix/incoming
chgrp mtagroup /var/spool/postfix/hold
chmod g+rx /var/spool/postfix/incoming
chmod g+rx /var/spool/postfix/hold
```

**Comment by Skywalker-11** [comment]
It is also mtagroup for debian

**Comment by asuweb** [comment]
@Skywalker-11 - correct, what I meant was the apache user is `www-data` on debian and `apache` on CentOS/RH etc

**Comment by mickaelmonsieur** [comment]
The error is always present:
"Please verify read permissions on /var/spool/postfix/hold and /var/spool/postfix/incoming"
Commands entered:

```
usermod -a -G mtagroup www-data
chgrp mtagroup /var/spool/postfix/incoming
chgrp mtagroup /var/spool/postfix/hold
chmod g+rx /var/spool/postfix/incoming
chmod g+rx /var/spool/postfix/hold
```

**Comment by asuweb** [comment]
What's the output of `ls -al /var/spool`

**Comment by mickaelmonsieur** [comment]
I run mailwatch with nginx and php7.0-fpm:

phpinfo():

$_SERVER['USER'] | www-data
$_SERVER['HOME'] | /var/www

**Comment by mickaelmonsieur** [comment]
@asuweb 

```
root@in-mx:/opt/mailwatch# ls -al /var/spool
total 24
drwxr-xr-x  6 root root 4096 mai 13 09:33 .
drwxr-xr-x 12 root root 4096 mai 13 10:13 ..
drwxr-xr-x  3 root root 4096 mai 12 21:03 cron
lrwxrwxrwx  1 root root    7 mai 12 21:01 mail -> ../mail
drwxr-xr-x  6 root root 4096 mai 13 09:57 MailScanner
drwxr-xr-x 20 root root 4096 mai 14 09:33 postfix
drwx------  2 root root 4096 jan 18  2017 rsyslog
```

I specify that it is the packet postfix 3.1.8-0+deb9u1 which created the tree structure and that I did not touch it.

**Comment by Skywalker-11** [comment]
Can you try running `sudo -u www-data -g mtagroup ls /var/spool/postfix/hold`

**Comment by mickaelmonsieur** [comment]
@Skywalker-11 no output!

**Comment by mickaelmonsieur** [comment]
because /var/spool/postfix/hold is empty...

```
sudo -u www-data -g mtagroup ls -al /var/spool/postfix/hold
total 8
drwxr-x---  2 postfix mtagroup 4096 mai 14 09:34 .
drwxr-xr-x 20 root    root     4096 mai 14 09:33 ..
```

**Comment by Skywalker-11** [comment]
Try restarting the webserver

**Comment by mickaelmonsieur** [comment]
Exactly!!
If i restart php-fpm  `/etc/init.d/php7.0-fpm restart` it works!

But it's completely stupid! php-fpm!
Thanks to you, I had arrived at the same result a few minutes after you, I had not yet seen your answer.

**Comment by mickaelmonsieur** [comment]
It looks like php-fpm copy /etc/group in memory, because if i remove www-data from mtagroup (`gpasswd -d www-data mtagroup`) it still works, if i restart php-fpm, there i have a 'denied'.

a snippet for debug:

```
root@in-mx:/opt/mailwatch/mailscanner# cat test.php 
<?php
$dir    = '/var/spool/postfix/hold';
$files1 = scandir($dir) or die("error on hold folder!");
print_r($files1);
```
