### ISSUE TITLE
Cannot release mail from Quarantine

### ISSUE THREAD

**Issue by Salted-Fries** [mailwatch/1.2.0#1072]
### Hello MailWatchers,

i managed to setup  MailWatch v1.2.8 with postfix and apache2. 
Today i did the update to v1.2.9 successfully.
Now i have two problems i cant resolve by my self.

### 1. When i click on a Quarantined Mail to release it, or to Learn it as Ham/Spam the displayed details stop at Spam Report. Very similar to this https://github.com/mailwatch/MailWatch/issues/392 .
I checked the OS access rights  and MailScanners Spam Actions:

grep "Spam Actions =" /etc/MailScanner/MailScanner.conf
Spam Actions = deliver header "X-Spam-Status: Yes" store
High Scoring Spam Actions = deliver header "X-Spam-Status: Yes" store
Non Spam Actions = deliver header "X-Spam-Status: No"

ps axu|grep apache2
root     12182  0.0  1.0 450044 21736 ?        Ss   10:44   0:00 /usr/sbin/apache2 -k start
www-data 12422  0.0  1.2 452984 24996 ?        S    10:45   0:00 /usr/sbin/apache2 -k start

groups www-data
www-data : www-data

ls -la /var/spool/MailScanner/
insgesamt 20
drwxr-xr-x  5 root    root     4096 Nov 30  2016 .
drwxr-xr-x  7 root    root     4096 Apr 10 09:49 ..
drwxr-xr-x 38 postfix postfix  4096 Mai 17 11:30 incoming
drwxrwx---  4 postfix www-data 4096 Mai 16 09:55 quarantine

ls -la /var/spool/MailScanner/quarantine/
insgesamt 16
drwxrwx--- 4 postfix www-data 4096 Mai 16 09:55 .
drwxr-xr-x 5 root    root     4096 Nov 30  2016 ..
drwxrwx--- 4 postfix www-data 4096 Mai 15 16:14 20180515
drwxrwx--- 4 postfix www-data 4096 Mai 16 20:30 20180516

tail -f /var/log/apache2/error.log:
[Thu May 17 11:40:06.660823 2018] [php7:warn] [pid 13593] [client 10.10.20.88:45370] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /var/www/html/mailscanner/lib/xmlrpc/xmlrpc.inc on line 2635, referer: https://mailscanner/mailscanner/quarantine.php?token=960cdf7fe96440df1b70fe64fd00f293395af001e02ff70b23ebae9a8e23fac7&dir=20180516
[Thu May 17 11:40:15.439863 2018] [php7:warn] [pid 14477] [client 10.10.20.7:55314] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /var/www/html/mailscanner/lib/xmlrpc/xmlrpc.inc on line 2635
....
[Thu May 17 11:40:15.606402 2018] [php7:warn] [pid 13593] [client 10.10.20.88:45370] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /var/www/html/mailscanner/lib/xmlrpc/xmlrpc.inc on line 2635, referer: https://mailscanner/mailscanner/quarantine.php?token=960cdf7fe96440df1b70fe64fd00f293395af001e02ff70b23ebae9a8e23fac7&dir=20180516

### 2. Software Versions won't display GeoIP Database Versions

MailWatch Version: 1.2.9

Operating System Version: Ubuntu 16.04.4 LTS (Xenial Xerus)

Postfix Version: 3.1.0

MailScanner Version: 5.0.7

ClamAV Version: 0.101.0

SpamAssassin Version: 3.4.1

PHP Version: 7.2.5-1+ubuntu16.04.1+deb.sury.org+1

MySQL Version: 5.7.22-0ubuntu0.16.04.1

GeoIP Database Version: No database downloaded

GeoIPv6 Database Version: No database downloaded

If i click on Tools and Links -> Update GeoIP Database i get: 

Downloading file, please wait...
GeoIP data file successfully downloaded
Download complete, unpacking files...

GeoIP data file successfully unpacked
Process completed! 

Any ideas ?

**Comment by Salted-Fries** [comment]
I turned on debugging in conf.php and maybe this helps to ind the issue:

HEADER: date: Thu, 17 May 2018 12:19:05 GMT HEADER: server: Apache/2.4.18 (Ubuntu) HEADER: set-cookie: MW_LANG=de; path=/, PHPSESSID=pnqttanmjgbq23mcm16o9nr427; path=/; HttpOnly HEADER: x-xss-protection: 1; mode=block HEADER: x-frame-options: SAMEORIGIN HEADER: x-content-type-options: nosniff HEADER: expires: Thu, 19 Nov 1981 08:52:00 GMT HEADER: cache-control: no-store, no-cache, must-revalidate HEADER: pragma: no-cache HEADER: vary: Accept-Encoding HEADER: content-encoding: gzip HEADER: content-length: 799 HEADER: connection: close HEADER: content-type: text/xml;charset=UTF-8 COOKIE: MW_LANG=de COOKIE: PHPSESSID=pnqttanmjgbq23mcm16o9nr427  

### XML-RPC Error: Received from server invalid compressed HTTP

**Comment by Skywalker-11** [comment]
It looks like you have a setup where you have the webinterface running on a different server than where mailscanner is running at. Is that correct? 
* If yes: try too open the page on the server where the mail was quarantined. Validate that it is working and then setup rpc between the servers
* If not: then the server is having a problem resolving its own hostname and so tries to contact itself over the rpc (wich isn't enabled by default). In take a look at this issue https://github.com/mailwatch/MailWatch/issues/960#issuecomment-331712965 and validate with the test file I described there

**Comment by Salted-Fries** [comment]
It turn out, you're right :-)
The Webinterface is on the same host. This host is a clone of a "master" VM (mailscanner2016) and i did the hostnamechange to late on the clone, so the first spams were logged with the hostname of the "master" VM. 

mysql> select hostname from maillog where id="5D4AC100008.A28E4";
+-------------+
| hostname    |
+-------------+
| mailscanner |
+-------------+
1 row in set (0,00 sec)

mysql> select hostname from maillog where id="9F17D100AFE.AD50C";
+-----------------+
| hostname        |
+-----------------+
| mailscanner2016 |
+-----------------+
1 row in set (0,00 sec)

The clones hostname is mailscanner, so 5D4AC100008.A28E4 is working fine and this one 5D4AC100008.A28E4 not :-)
I can live with that, as it is working fine with the newly quarantined Spams.

Thank You, greate help!

**Comment by Salted-Fries** [comment]
Did a: "UPDATE maillog SET hostname="mailscanner" WHERE hostname="mailscanner2016";" Now everythings fine :-)
Thanks again!
