### ISSUE TITLE
Facture spam (invoice)

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#1076]
Hello!

No directly related to mail watch but dit you receive this kind of scam?

<img width="1095" alt="sc" src="https://user-images.githubusercontent.com/12907102/41029322-adde5018-697b-11e8-9dbb-307ebab717ca.png">

I receive plenty of them. I tried to filter them but no way. The mail is clean and spamassassin score is low and no test are successful.

**Comment by asuweb** [comment]
@stefaweb - any chance you can get the original mail and send it to me, so I can see what it produces?

Thanks

**Comment by stefaweb** [comment]
Hi @asuweb!

I've this one. Not exactly the same but seems to be the same "engine".

Some have a DKIM signature too depending where they come from.

[mail.txt](https://github.com/mailwatch/MailWatch/files/2075876/mail.txt)

**Comment by Skywalker-11** [comment]
Currently b.barracudacentral.org and spam.dnsbl.sorbs.net are blacklisting them but of course this probably won't be the case for very recent mails.

Also in this case the sender domain has an spf record that doesn't match the sending server:
`cyhab.com.              14318   IN      TXT     "v=spf1 +a +mx +ip4:74.220.207.143 ip4:5.188.231.97 ?all"`

Sadly it doesn't enforce them (`?all`)

**Comment by stefaweb** [comment]
Most of them are not referenced in RBL. They comes in small quantity and each time from a different server and domain. The "invoice number" change too.

We have this since March 2018 (but not all the day).

Difficult to catch them as you can see.

![sc2](https://user-images.githubusercontent.com/12907102/41046002-d6f04e10-69a9-11e8-9f88-3259c7c18bbd.png)

**Comment by Skywalker-11** [comment]
If the subject always has the same structure like `Fracture [0-9]{6} de [A-Z]+.*` you could filter for that in the headers. But kind of unreliable as there are endless possible variations and a chance to match valid mails.

**Comment by Skywalker-11** [comment]
Maybe there is some sort of pattern in the mail content, HTML body or style? But again kind of easy to circumvent and can require quite some cpu power especially when also dealing with larger mails or a large quantity.

**Comment by stefaweb** [comment]
I agree. ;)

An sometime, we got some in English langage.

And if I have false positive on regular invoice, customers will burn me. ;)
