### ISSUE TITLE
Not recording to MySQL database

### ISSUE THREAD

**Issue by jmcgranahan** [mailwatch/1.2.0#1081]
### Issue summary
Data is not being stored in the MySQL database. 

### Steps to reproduce
1. On the server itself, issue this command to send an email directly to me: "mailx -s 'Test email' jamen.mcgranahan@v.e < log"; check the /var/log/maillog file and see that it was sent; check MailWatch and it's empty; check the MySQL database, and the maillog table is still empty.
2. checked conf.php and verified database settings:
```
// Database settings
//
// As this file might be publically readable. It might be very userful to
// have a completely separate username/password for this database.
//
// (IE) Do not use your main-global-admin accounts.
//
define('DB_TYPE', 'mysql');
define('DB_USER', 'mailwatch');
define('DB_PASS', '1234567890');
define('DB_HOST', 'mysql.xxx.xxx');
define('DB_NAME', 'mailscanner');
define('DB_DSN', DB_TYPE . '://' . DB_USER . ':' . DB_PASS . '@' . DB_HOST . '/' . DB_NAME);
```

### Expected result
"Recent Messages" tab should be displaying the messages recorded in /var/log/maillog, with the data being stored on the MySQL database, in the maillog table.

### Actual result
However, no data is being stored in the maillog table - remains empty. As a result, the "Recent Messages" tab is empty. I can connect to our MySQL server without a problem from our mail server. I can update the data (SpamAssassin rules), and I can view the database within MailWatch via Tools -> MySQL Database Status.

### Version and method
- MailWatch Version: 1.2.9
- Install type: Zip install
- Fresh install

### Server configuration
- Operating system: RedHat 7.5
- PHP version: 5.4.16
- Database: MySQL 5.6.39
- Mail Server: Sendmail 8.14.7

Please assist. Thank you!

**Comment by Skywalker-11** [comment]
@jmcgranahan Can you post the part of the maillog file for a mail?

Also run `MailScanner --lint` and post the output

**Comment by jmcgranahan** [comment]
Sure. Here is a snippet from maillog:

```
Jul  3 03:37:06 libvm15 sendmail[14586]: w638b4g2014586: from=root, size=24898, class=-60, nrcpts=1, msgid=<201807030837.w638b4g2014586@libvm15.library.vanderbilt.edu>, relay=root@localhost
Jul  3 03:37:06 libvm15 sendmail[14875]: w638b65W014875: from=<root@libvm15.library.vanderbilt.edu>, size=25211, class=-60, nrcpts=1, msgid=<201807030837.w638b4g2014586@libvm15.library.vanderbilt.edu>, proto=ESMTP, daemon=MTA, relay=localhost [127.0.0.1]
Jul  3 03:37:06 libvm15 sendmail[14586]: w638b4g2014586: to=root, ctladdr=root (0/0), delay=00:00:02, xdelay=00:00:00, mailer=relay, pri=162898, relay=[127.0.0.1] [127.0.0.1], dsn=2.0.0, stat=Sent (w638b65W014875 Message accepted for delivery)
Jul  3 03:37:06 libvm15 sendmail[14876]: STARTTLS=client, relay=vanderbilt-edu.mail.protection.outlook.com., version=TLSv1/SSLv3, verify=FAIL, cipher=ECDHE-RSA-AES256-SHA384, bits=256/256
Jul  3 03:37:09 libvm15 sendmail[14876]: w638b65W014875: to=libsys@vanderbilt.edu\t, ctladdr=<root@libvm15.library.vanderbilt.edu> (0/0), delay=00:00:03, xdelay=00:00:03, mailer=esmtp, pri=163457, relay=vanderbilt-edu.mai...ction.outlook.com. [207.46.163.170], dsn=2.0.0, stat=Sent (<201807030837.w638b4g2014586@libvm15.library.vanderbilt.edu> [InternalId=154764851545249, Host...R0801MB0788.namprd08.prod.outlook.com] 33436 bytes in 0.331, 98.377 KB/sec Queued mail for delivery)

```
And then here is the output from "`MailScanner --lint`":

```
[root@libvm15 log]# MailScanner --lint
Trying to setlogsock(unix)
Subroutine mailwatch_get_db_name redefined at /etc/MailScanner/custom/MailWatchConf.pm line 27.
Subroutine mailwatch_get_db_host redefined at /etc/MailScanner/custom/MailWatchConf.pm line 28.
Subroutine mailwatch_get_db_user redefined at /etc/MailScanner/custom/MailWatchConf.pm line 29.
Subroutine mailwatch_get_db_password redefined at /etc/MailScanner/custom/MailWatchConf.pm line 30.
Subroutine mailwatch_get_BWL_refresh_time redefined at /etc/MailScanner/custom/MailWatchConf.pm line 31.
Subroutine mailwatch_get_SS_refresh_time redefined at /etc/MailScanner/custom/MailWatchConf.pm line 32.

Reading configuration file /etc/MailScanner/MailScanner.conf
Reading configuration file /etc/MailScanner/conf.d/README
Read 1500 hostnames from the phishing whitelist
Read 16893 hostnames from the phishing blacklists
Config: calling custom init function SQLBlacklist
MailWatch: Starting up MailWatch SQL Blacklist
MailWatch: Read 421 blacklist entries
Config: calling custom init function MailWatchLogging
MailWatch: Started MailWatch SQL Logging child
Config: calling custom init function SQLWhitelist
MailWatch: Starting up MailWatch SQL Whitelist
MailWatch: Read 43 whitelist entries

Checking version numbers...
Version number in MailScanner.conf (5.0.7) is correct.

Your envelope_sender_header in spamassassin.conf is correct.

Checking for SpamAssassin errors (if you use it)...
Using SpamAssassin results cache
Connected to SpamAssassin cache database
SpamAssassin reported no errors.
Auto: Found virus scanners: clamavmodule
Connected to Processing Attempts Database
Created Processing Attempts Database successfully
There are 0 messages in the Processing Attempts Database
Using locktype = posix
MailScanner.conf says "Virus Scanners = auto"
Found these virus scanners installed: clamavmodule
===========================================================================
Filename Checks: Windows/DOS Executable (1 eicar.com)
Other Checks: Found 1 problems
Virus and Content Scanning: Starting
ClamAVModule::INFECTED:: Eicar-Test-Signature:: ./1/
ClamAVModule::INFECTED:: Eicar-Test-Signature:: ./1/eicar.com
Virus Scanning: ClamAVModule found 2 infections
Infected message 1 came from 10.1.1.1
Virus Scanning: Found 2 viruses
===========================================================================
Virus Scanner test reports:
ClamAVModule said "eicar.com was infected: Eicar-Test-Signature"

If any of your virus scanners (clamavmodule)
are not listed there, you should check that they are installed correctly
and that MailScanner is finding them correctly via its virus.scanners.conf.
Config: calling custom end function SQLBlacklist
MailWatch: Closing down MailWatch SQL Blacklist
Config: calling custom end function MailWatchLogging
Config: calling custom end function SQLWhitelist
MailWatch: Closing down MailWatch SQL Whitelist

```

**Comment by Skywalker-11** [comment]
This shouldn't be there.
```
Subroutine mailwatch_get_db_name redefined at /etc/MailScanner/custom/MailWatchConf.pm line 27. Subroutine mailwatch_get_db_host redefined at /etc/MailScanner/custom/MailWatchConf.pm line 28. Subroutine mailwatch_get_db_user redefined at /etc/MailScanner/custom/MailWatchConf.pm line 29. Subroutine mailwatch_get_db_password redefined at /etc/MailScanner/custom/MailWatchConf.pm line 30. Subroutine mailwatch_get_BWL_refresh_time redefined at /etc/MailScanner/custom/MailWatchConf.pm line 31. Subroutine mailwatch_get_SS_refresh_time redefined at /etc/MailScanner/custom/MailWatchConf.pm line 32. 
```
Please check if you have duplicates of the MailWatch .pm files in any other directory of your MailScanner installation

**Comment by jmcgranahan** [comment]
I have MailWatchConf.pm in /usr/share/MailScanner/perl/custom/ directory as well as the location of the unzipped file (/apps/MalWatch/MailScanner_perl_scripts). The same for MailWatch.pm (actually the one in /usr/share/MailScanner/perl/custom/ points to /apps/MailWatch/MailScanner_perl_scripts).

**Comment by jmcgranahan** [comment]
Is there a way to debug these scripts? No errors are being recorded (that I can tell at least).

**Comment by stefaweb** [comment]
Hello @jmcgranahan!

Try to place the files *.pm directly in /etc/MailScanner/custom not to link them from  /apps/MailWatch/MailScanner_perl_scripts directory.

**Comment by jmcgranahan** [comment]
@stefaweb 
Just did, but still no change. Funny thing is, I can add a user, which writes to the database just fine. So I know my MySQL database credentials are right. Other suggestions?

**Comment by Skywalker-11** [comment]
Can you do a global search for MailWatchConf.pm or mailwatch_get_db_name`  on your system. Maybe there is a duplicate somewhere else which perl has in its include path. You may also have a file 00MailWatchConf.pm which has been replaced by MailWatchConf.pm

The web interface and the logging of mail are independent parts. Thats why everything in the gui might work but not the logging itself.

**Comment by jmcgranahan** [comment]
I actually did do a search globally on the system for those files and there are no duplicates. I also can see within the MySQL database where the entry for the new user I added is stored. It seems as if the system is not seeing or processing the /var/log/maillog file like it supposed to do. I made sure the structure is there for the table. And I verified my settings are pointing to maillog. I just don’t get it. I have an older system running an older version of MailWatch/MailScanner that is recording just fine. I’ve compared the two and there’s not a whole lot different so I’m not sure where to look. Any other suggestions?

Jamen McGranahan
* Sent from my iPhone

On Jul 4, 2018, at 2:43 AM, Michael Pietsch <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you do a global search for MailWatchConf.pm or mailwatch_get_db_name` on your system. Maybe there is a duplicate somewhere else which perl has in its include path. You may also have a file 00MailWatchConf.pm which has been replaced by MailWatchConf.pm

The web interface and the logging of mail are independent parts. Thats why everything in the gui might work but not the logging itself.

**Comment by Skywalker-11** [comment]
Have you tried the suggestion from stefaweb and then run `MailScanner --lint` again? 

> Try to place the files *.pm directly in /etc/MailScanner/custom not to link them from /apps/MailWatch/MailScanner_perl_scripts directory.

**Comment by stefaweb** [comment]
He did. But not sure if he ran `MailScanner --lint` again.

**Comment by jmcgranahan** [comment]
Yes and get the same results

Jamen McGranahan
* Sent from my iPhone

On Jul 4, 2018, at 6:59 AM, Stéphane <notifications@github.com<mailto:notifications@github.com>> wrote:


He did. But not sure if he ran MailScanner --lint again.

**Comment by ghost** [comment]
I'm not busy at the moment, so I can spin up a RH instance to try to reproduce...

**Comment by jmcgranahan** [comment]
Any luck with this?

**Comment by jmcgranahan** [comment]
I am uninstalling both MailScanner and MailWatch and will start from scratch

**Comment by ghost** [comment]
Took me a while to get my hands on a copy of RH 7.5.  I have a copy now and will do an install.

**Comment by ghost** [comment]
Bump....I don't have a RH subscription, so I have not update repos :(  

I can confirm, however, this issue is not present on CentOS 7.5, but I am unable to test RH 7.5 at the moment...
