### ISSUE TITLE
DNS down for many RBLs ?

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#1082]
Starting one hour ago, many RBLs no longer answer to nslookup.

As well, I tried with many dns server (1.1.1.1, 8.8.8.8, 9.9.9.9) and with online nslookup page as this one.

https://network-tools.com/nslook/Default.asp?domain=b.barracudacentral.org&type=255&server=9.9.9.9&class=1&port=53&timeout=5000&go.x=17&go.y=5

Do you have the same problem on your side?

82 RBLS on 97 on my list are gone.

The RBL server aspews.ext.sorbs.net is down.
The RBL server b.barracudacentral.org is down.
The RBL server bad.psky.me is down.
The RBL server bl.deadbeef.com is down.
The RBL server bl.emailbasura.org is down.
The RBL server bl.mailspike.net is down.
The RBL server bl.spameatingmonkey.net is down.
The RBL server blackholes.five-ten-sg.com is down.
The RBL server bogons.cymru.com is down.
The RBL server cbl.abuseat.org is down.
The RBL server cbl.anti-spam.org.cn is down.
The RBL server cdl.anti-spam.org.cn is down.
The RBL server combined.abuse.ch is down.
The RBL server combined.rbl.msrbl.net is down.
The RBL server db.wpbl.info is down.
The RBL server dnsbl-1.uceprotect.net is down.
The RBL server dnsbl-2.uceprotect.net is down.
The RBL server dnsbl-3.uceprotect.net is down.
The RBL server dnsbl.dronebl.org is down.
The RBL server dnsbl.justspam.org is down.
The RBL server dnsbl.sorbs.net is down.
The RBL server drone.abuse.ch is down.
The RBL server dsn.rfc-ignorant.org is down.
The RBL server duinv.aupads.org is down.
The RBL server dul.dnsbl.sorbs.net is down.
The RBL server dul.rukorea.services.net is down.
The RBL server dyna.spamrats.com is down.
The RBL server dynip.rothen.com is down.
The RBL server http.dnsbl.sorbs.net is down.
The RBL server httpbl.abuse.ch is down.
The RBL server images.rbl.msrbl.net is down.
The RBL server ips.backscatterer.org is down.
The RBL server ix.dnsbl.manitu.net is down.
The RBL server misc.dnsbl.sorbs.net is down.
The RBL server multi.surbl.org is down.
The RBL server netblock.pedantic.org is down.
The RBL server noptr.spamrats.com is down.
The RBL server ohps.dnsbl.net.au is down.
The RBL server omrs.dnsbl.net.au is down.
The RBL server orvedb.aupads.org is down.
The RBL server osps.dnsbl.net.au is down.
The RBL server osrs.dnsbl.net.au is down.
The RBL server owfs.dnsbl.net.au is down.
The RBL server owps.dnsbl.net.au is down.
The RBL server pbl.spamhaus.org is down.
The RBL server phishing.rbl.msrbl.net is down.
The RBL server probes.dnsbl.net.au is down.
The RBL server proxy.bl.gweep.ca is down.
The RBL server proxy.block.transip.nl is down.
The RBL server query.senderbase.org is down.
The RBL server rbl.suresupport.com is down.
The RBL server rdts.dnsbl.net.au is down.
The RBL server relays.bl.gweep.ca is down.
The RBL server relays.bl.kundenserver.de is down.
The RBL server relays.nether.net is down.
The RBL server residential.block.transip.nl is down.
The RBL server ricn.dnsbl.net.au is down.
The RBL server rmst.dnsbl.net.au is down.
The RBL server sbl.spamhaus.org is down.
The RBL server short.rbl.jp is down.
The RBL server short.rbl.jpvirus.rbl.jp is down.
The RBL server smtp.dnsbl.sorbs.net is down.
The RBL server socks.dnsbl.sorbs.net is down.
The RBL server spam.abuse.ch is down.
The RBL server spam.dnsbl.sorbs.net is down.
The RBL server spam.rbl.msrbl.net is down.
The RBL server spam.spamrats.com is down.
The RBL server spamguard.leadmon.net is down.
The RBL server spamlist.or.kr is down.
The RBL server t3direct.dnsbl.net.au is down.
The RBL server tor.dan.me.uk is down.
The RBL server tor.dnsbl.sectoor.de is down.
The RBL server truncate.gbudb.net is down.
The RBL server ubl.lashback.com is down.
The RBL server ubl.unsubscore.com is down.
The RBL server virus.rbl.jp is down.
The RBL server virus.rbl.msrbl.net is down.
The RBL server web.dnsbl.sorbs.net is down.
The RBL server xbl.spamhaus.org is down.
The RBL server zen.spamhaus.org is down.
The RBL server zombie.dnsbl.sorbs.net is down.

```
; <<>> DiG 9.10.3-P4-Debian <<>> @1.1.1.1 httpbl.abuse.ch
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 6439
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1452
;; QUESTION SECTION:
;httpbl.abuse.ch.		IN	A

;; AUTHORITY SECTION:
abuse.ch.		1582	IN	SOA	ns1.p04.dynect.net. dnsadmin.abuse.ch. 2018070200 3600 600 604800 1800

;; Query time: 11 msec
;; SERVER: 1.1.1.1#53(1.1.1.1)
;; WHEN: Wed Jul 04 19:01:24 CEST 2018
;; MSG SIZE  rcvd: 115
```

**Comment by ghost** [comment]
Wow, is there a massive outage on global DNS?

My DNS is lagging really bad, and I'm seeing the same thing.

**Comment by stefaweb** [comment]
Glad I'm not the only one. I was starting to panic for my infrastructure.

**Comment by Skywalker-11** [comment]
I didn't saw outtake and manually testing some of them it seems that they are working with my local and google/cloudflare dns.

Remember that the dns domain used for the blacklist does not have to be resolvable to A/AAAA. Eg. `b.barracudacentral.org` does not have an A/AAAA entry but querying the actual test `2.0.0.127..barracudacentral.org` returns the response.

**Comment by stefaweb** [comment]
My fault. I inverted 2 variables.

I close. Sorry.
