### ISSUE TITLE
Sendmail Relay Log issues.

### ISSUE THREAD

**Issue by karl-dessol** [mailwatch/1.2.0#1083]
Hey guys.

First off, hats off to the work you have done with this. This is really just a heads-up as much as anything else.

I encountered a couple of issues/bugs setting up the Sendmail Relay Log watcher.

Expected:
Follow the documentation for the Sendmail Relay watcher [here](https://docs.mailwatch.org/install/optional-setup.html) and it loads without having to change filenames/core code.

Actual:
The filename mailwatch_sendmail_relay.php is not what the executable 'mailwatch-sendmail-relay' is looking for and throws an error, as it is expecting sendmail_relay.php. There's also a missing require in mailwatch_sendmail_relay.php for the mtalogprocessor at line 57 (where you try and use the class that does not exist because it was not required).

Installation:
MailWatch: 1.2.9
[Via tarball](https://github.com/mailwatch/MailWatch/releases)
Fresh

Server Config:
Ubuntu 16.04
PHP 7
MySQL
Sendmail
Apache

Client: N/A (it was an installation thing)

This might just be a weird quirk with my version or how it was downloaded, but just in case it is not thought I'd give you a heads up.

**Comment by endelwar** [comment]
Hi @karl-dessol,
I've checked both files and it seems to me that the code is right:
- [tools/Sendmail_relay/mailwatch-sendmail-relay](https://github.com/mailwatch/MailWatch/blob/89745f352b97c2cdc0d0edfb126c031c9e76c639/tools/Sendmail_relay/mailwatch-sendmail-relay#L26) on line 26 defines `DAEMON="/usr/local/bin/mailwatch_sendmail_relay.php"` (so no need to rename files)
- [tools/Sendmail_relay/mailwatch_sendmail_relay.php](https://github.com/mailwatch/MailWatch/blob/89745f352b97c2cdc0d0edfb126c031c9e76c639/tools/Sendmail_relay/mailwatch_sendmail_relay.php#L44) on line 44 requires the `mtalogprocessor` class file.

Could you double check the tarball contents? The one that I can download from GitHub has the right version of files in it

**Comment by karl-dessol** [comment]
Ah, nevermind. My bad, I seem to have installed an older version. Not sure why I did that, I would have thought I would have just used the latest version. Checking your changelog I can see that the issue I mentioned was fixed here: https://github.com/mailwatch/MailWatch/pull/881.

Sorry to waste your time!
