### ISSUE TITLE
Postfix, dovecot, rimap and SSL (off topic)

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#1086]
Hello!

Sorry, this is a question unrelated to mailwatch.

I'm starting to switch from Exim to Postfix. As I'm not a power user with Postfix, I've a "basic" problem trying to use a remote postfix auth/smtp server to connect to an remote imap server for authentification.

saslauthd on the remote auth server is using rimap to connect to the imap server but I do not find the right setup. saslauthd/rimap don't want to talk using startssl by default (needed by the imap server). 

```
Jul 12 10:04:30 smtp-auth saslauthd[6467]: auth_rimap: unexpected response to auth request: * BAD [ALERT] Plaintext authentication not allowed without SSL/TLS, but your client did it anyway. If anyone was listening, the password was exposed.
Jul 12 10:04:30 smtp-auth saslauthd[6467]:                 : auth failure: [user=uers@domain.tld] [service=imap] [realm=] [mech=rimap] [reason=[ALERT] Unexpected response from remote authentication server]
```
If someone have the solution. Thanks.

**Comment by Skywalker-11** [comment]
Here it is suggested to use stunnel:
https://listi.jpberlin.de/pipermail/postfixbuch-users/2005-August/019112.html

Or maybe using pam with pam_imap.

But I have no experience with this.

**Comment by stefaweb** [comment]
I've just discovered the info on stunnel too. I've to look at this page:

http://www.postfix.org/TLS_README.html

I didn't found any answer on google as rimap do not support SSL !

> "rimap" is not able to start a SSL-Session, so you need it without issuing "STARTTLS".

As well, transmit password  in clear is not an option.

With Exim I was using a direct database connexion. Now with dovecot/postfix, it seems more complicated to get "remote auth from the imap server" for a "smtp-auth" server. 

Cheers,

**Comment by Skywalker-11** [comment]
I think pam also supports authentications with mysql.

If you are using dovecot as imap backend you can also use sockets to directly authenticate against it. Eg. see https://workaround.org/ispmail/stretch/relaying-smtp-authentication
Not sure though if that can send it to remote servers encrypted. I only used it locally.

**Comment by stefaweb** [comment]
I'm testing a new platform https://github.com/modoboa/modoboa

One vhost for pop/imap (do not send email to ovoid blacklisting)
One server for smtp-auth
One server for webmail (roundcube + modoboa api)
One server for mailwatch

Seems, I only have the rimap daemon or the modoboa API to access the imap server remotely. I don't want to use a direct database access.

**Comment by stefaweb** [comment]
Yo, it works with stunnel4. ;)

postfix/saslauthd call localhost 143 and stunnel map it to the imap server on 993.

```
root@smtp-auth:/home/user# testsaslauthd -u  user@domain.tld -p 123456789
0: OK "Success."
```

Will post the config files later.

**Comment by stefaweb** [comment]
**EDITED 5/12/2018**

How to for Debian Stretch:

Stop services:
```
systemctl stop postfix
systemctl stop postfwd
```

Install sasl2-bin:
`apt-get install sasl2-bin`

Configure saslauthd for Postfix:
```
adduser postfix sasl
mkdir -p /var/spool/postfix/var/run/saslauthd
chgrp sasl /var/spool/postfix/var/run/saslauthd
dpkg-statoverride --add root sasl 770 /var/spool/postfix/var/run/saslauthd
```

In /etc/fstab
```
# Mount for saslauthd
/var/run/saslauthd /var/spool/postfix/var/run/saslauthd bind defaults,nodev,noauto,bind 0 0
```

In /etc/postfix/sasl/smtpd.conf
```
pwcheck_method: saslauthd
mech_list: PLAIN LOGIN
allow_plaintext: true
saslauthd_path: /var/run/saslauthd/mux
```

In /etc/default/saslauthd
```
START=yes
MECHANISMS="rimap"
MECH_OPTIONS="localhost"
OPTIONS="-c -m /var/run/saslauthd -r"
```

In /etc/postfix/main.cf
```
smtpd_tls_auth_only = yes
smtpd_sasl_local_domain = $myhostname
smtpd_sasl_authenticated_header = yes
broken_sasl_auth_clients = yes
smtpd_recipient_restrictions = permit_sasl_authenticated,permit_mynetworks,reject_unauth_destination
smtpd_sasl_security_options = noplaintext,noanonymous
smtpd_sasl_tls_security_options = noanonymous
```

In /etc/systemd/system/var-spool-postfix-var-run-saslauthd.mount
```
# Systemd mount saslauthd from fstab

[Unit]
Description=Mount saslauthd /var/spool/postfix/var/run/saslauthd

[Mount]
What=/var/run/saslauthd
Where=/var/spool/postfix/var/run/saslauthd
Type=bind
Options=defaults,nodev,noauto,bind

[Install]
WantedBy=multi-user.target
```

Enable new systemd mount service:
```
systemctl daemon-reload
systemctl enable var-spool-postfix-var-run-saslauthd.mount
systemctl start var-spool-postfix-var-run-saslauthd.mount
```

To check:
`systemctl list-units --type=mount`

In /etc/stunnel/mail.domain.tld.conf
```
# Config for mail.domain.tld imap server

setuid = stunnel4
setgid = stunnel4

; PID file
pid = /var/run/stunnel4/stunnel4.pid

; Debugging stuff
debug = info
output = /var/log/stunnel4/stunnel.log

[imaps]
client = yes
accept = 127.0.0.1:143
connect = mail.domain.tl:993
CApath = /etc/ssl/certs
CAfile = /etc/stunnel/smtp-auth.domain.tld.cer
cert = /etc/stunnel/smtp-auth.domain.tld.cer
verifyChain = yes
checkHost = mail.domain.tld
```

In /etc/default/stunnel4:

`ENABLED=1`

In /etc/default/postfwd:

`STARTUP=1`

Restart services:
```
systemctl start stunnel4
systemctl start postfwd
systemctl start saslauthd
systemctl start postfix
```

Check if saslauthd is working:

`testsaslauthd -u  user@domain.tld -p 123456789`

Check if saslauthd is working using smtp-auth server:

`swaks -tls --to user@domain.tld --from=user2@domain.tld --auth --auth-user=user@domain.tld --auth-password=123456789 --server smtp-auth.domain.tld:587 --header-X-Test "Test email"`

**Comment by stefaweb** [comment]
Hi again!

I've found a small problem. When I send a wrong password, the message is not good.

In the smtp-auth server log, "Password verification failed" is well printed.
`Jul 13 12:44:31 smtp-auth postfix/submission/smtpd[2014]: warning: SASL authentication failure: Password verification failed`

But in the smtp session with swaks, I lost the real error reason:
```
<~* 535 5.7.8 Error: authentication failed: authentication failure
 ~> AUTH PLAIN AHNsZWNsZXJjQGFjdGlvbndlYi5ldQA5NkttbjdiVjM=
<~* 535 5.7.8 Error: authentication failed: authentication failure
*** No authentication type succeeded
```

With testsaslauthd , I got the right message:
`0: NO "authentication failed"`

No idea how to correct this.

**Comment by Skywalker-11** [comment]
The part with mounting and the systemd unit can be skipped if you change 
`OPTIONS="-c -m /var/run/saslauthd -r"`
to
`OPTIONS="-c -m /var/spool/postfix/var/run/saslauthd -r"`
The saslauthd service will then use it there

**Comment by stefaweb** [comment]
@Skywalker-11 

It doesn't work if the mount is not done.

But your true for the OPTIONS. In fact, it work with both OPTIONS versions BUT ONLY if we mount:

`/var/run/saslauthd /var/spool/postfix/var/run/saslauthd bind defaults,nodev,noauto,bind 0 0
`

Some people do a "ln -s /var/spool/postfix/var/run/saslauthd  /run/saslauthd" to have the system working but this solution is lost after a reboot.

**Comment by Skywalker-11** [comment]
I have saslauthd running with only the OPTIONS path but using ldap as backend. I don't need any additional mount.
I think I followed this example https://wiki.debian.org/PostfixAndSASL to install saslauthd

**Comment by stefaweb** [comment]
This is needed by the "rimap" mechanism. Seems that "/var/run/saslauthd" is hard coded somewhere.

**Comment by Skywalker-11** [comment]
Is it postfix that doesn't work without it or testsaslauthd (path to saslauthd mux file has to be passed with `-f` parameter)?

**Comment by stefaweb** [comment]
Hi @Skywalker-11!

Not found many information on this problem between postfix and saslauthd in chroot mode but it seems old and still seems relevant today. Look at this post.

`The problem arises because postfix insists on looking up saslauthd lock files in /var/run/saslauthd, yet these have moved to /var/spool/postfix/var/run/saslauthd.`

https://github.com/webmin/webmin/issues/58

Still not found a solution for the "authentication failed" problem.

**Comment by stefaweb** [comment]
Hello Postfix power user!

I've a question. Not found the doc for this.

I've see that some people add a `*number` at the end of blacklist server.

```
b.barracudacentral.org*2
bl.mailspike.net*3
zen.spamhaus.org*3
cbl.anti-spam.org.cn
```

I've not found what it mean and the rule for that.

**Comment by Skywalker-11** [comment]
I guess its a weight http://www.postfix.org/postconf.5.html#postscreen_dnsbl_sites

I'm not using the postfix rbl though

**Comment by stefaweb** [comment]
Hi @Skywalker-11 

Normally, I don't use RBL direct in MTA or in Mailscanner. Only in Spamassassin, but I'm doing some test using a combinaison of white listing (IPs) and RBL.

I've setup this:

I wrote scripts to generate smtp-out MTA IPs from the most important ISPs. The `postscreen_spf_whitelist.cidr` is generated with postwhite. Others use dedicated scripts.

In /etc/postfix/
```
-rw-r--r-- 1 root root    72 juil. 20 00:00 postscreen_bouygues_whitelist.cidr
-rw-r--r-- 1 root root    72 juil. 20 00:00 postscreen_free_whitelist.cidr
-rw-r--r-- 1 root root    96 juil. 20 00:00 postscreen_orange_whitelist.cidr
-rw-r--r-- 1 root root 43769 juil. 20 00:00 postscreen_ovh_whitelist.cidr
-rw-r--r-- 1 root root   736 juil. 20 00:00 postscreen_sfr_whitelist.cidr
-rw-r--r-- 1 root root 42806 juil. 20 00:27 postscreen_spf_whitelist.cidr
```

In main.cf
```
# Postcreen settings
postscreen_access_list =
       permit_mynetworks
       cidr:/etc/postfix/postscreen_bouygues_whitelist.cidr
       cidr:/etc/postfix/postscreen_free_whitelist.cidr
       cidr:/etc/postfix/postscreen_orange_whitelist.cidr
       cidr:/etc/postfix/postscreen_ovh_whitelist.cidr
       cidr:/etc/postfix/postscreen_sfr_whitelist.cidr
       cidr:/etc/postfix/postscreen_spf_whitelist.cidr
postscreen_blacklist_action = enforce

# Use some DNSBL
postscreen_dnsbl_sites =
       b.barracudacentral.org
       zen.spamhaus.org
       bl.spameatingmonkey.net
       bl.spamcop.net
       dnsbl.sorbs.net
       spam.dnsbl.sorbs.net
       cbl.anti-spam.org.cn
postscreen_dnsbl_threshold = 3
postscreen_dnsbl_action = enforce
```

The combinaison of both seems interesting but need a long testing to check for the % of false postive.

**Comment by Skywalker-11** [comment]
I haven't used it so I can't help with that

**Comment by thctlo** [comment]
I can, i'll show you my postscreen setup.  

About the config below, 
- postscreen_access_list = i permit mynetwork and i use the postscreen_access_list-....  files to override things for special customers. 
- postscreen_dnsbl_reply_map  contains 
```
!/^fakename\.spamhaus\.org$/         multiple DNS-based blocklists, see http://multirbl.valli.org/
```
If one is listed, based on the counting system of postscreen (see below), then give the above message back. 

postscreen_dnsbl_threshold=4  , if you hit this number, block them. 
its adding and substracting for its result. 
i give high weight to spamhouse barracurra central and badspyme. 
And i subtract if they are in whitelists. 

Things like this. adding and substracting within one DNSBL server. 
rep.mailspike.net=127.0.0.[13;14]*1   
rep.mailspike.net=127.0.0.[17;18]*-1
reference : http://mailspike.org/usage.html 

Please note, i dont advice the complete list as shown, this is optimized for the company im working.
If been optimizing this for more than a year, im pretty happing with it. 
If offloads you spamassasin a lot since listed servers wont be scanned. 

Any other questions, just ask. 

CONFIG : 
```
### Before-220 tests (postscreen / DNSBL)
postscreen_greet_banner =
    $myhostname, checking blacklists, please wait.
# Drop connections if other server is sending too quickly
postscreen_greet_action = drop
postscreen_greet_wait = 3s
postscreen_greet_ttl = 2d
postscreen_access_list =
    permit_mynetworks,
    cidr:/etc/postfix/personal/postscreen_access_list.cidr,
    pcre:/etc/postfix/personal/postscreen_access_list-reject.fqrdns.pcre
    cidr:/etc/postfix/personal/postscreen_access_list-drop.spamhaus-lasso.cidr
postscreen_whitelist_interfaces = $mynetworks, static:all
postscreen_blacklist_action     = drop
postscreen_dnsbl_reply_map      = pcre:/etc/postfix/personal/postscreen_dnsbl_reply_map.pcre
postscreen_dnsbl_action         = enforce
postscreen_dnsbl_ttl            = 2h
postscreen_dnsbl_threshold      = 4
postscreen_dnsbl_sites =
        zen.spamhaus.org*4
        b.barracudacentral.org*4
        bad.psky.me*4
        dnsbl.cobion.com*2
        bl.spameatingmonkey.net*2
        fresh.spameatingmonkey.net*2
        cblless.anti-spam.org.cn*1
        dnsbl.kempt.net*1
        dnsbl.inps.de*2
        bl.spamcop.net*2
        srn.surgate.net=127.0.0.2*1
        spam.dnsbl.sorbs.net*1
        rbl.rbldns.ru*2
        psbl.surriel.com*2
        bl.mailspike.net*2
        rep.mailspike.net=127.0.0.[13;14]*1
        bl.suomispam.net*1
        bl.blocklist.de*2
        ix.dnsbl.manitu.net*2
        dnsbl-2.uceprotect.net*1
        dnsbl.justspam.org=127.0.0.2*2
        all.s5h.net=127.0.0.2*2
        hostkarma.junkemailfilter.com=127.0.0.[2;4]*2
        rbl.abuse.ro=127.0.0.[2;4]*2
        dnsbl.spfbl.net=127.0.0.[2;4]*2
        # No RDNS
        dnsbl.spfbl.net=127.0.0.3*1
        hostkarma.junkemailfilter.com=127.0.0.3*1
        # whitelists
        swl.spamhaus.org*-6
        dnswl.spfbl.net=127.0.0.[2;3;4]*-3
        list.dnswl.org=127.0.[0..255].[2;3]*-4
        rep.mailspike.net=127.0.0.[17;18]*-1
        rep.mailspike.net=127.0.0.[19;20]*-2
        hostkarma.junkemailfilter.com=127.0.0.1*-4
        nobl.junkemailfilter.com=127.0.0.5*-4
#
### End of before-220 tests
### After-220 tests
### WARNING -- See "Tests after the 220 SMTP server greeting" in the
### Postscreen Howto and *UNDERSTAND* it *BEFORE* you enable the
### following tests! This basically enables some kind of greylisting!
#postscreen_bare_newline_action = enforce
#postscreen_bare_newline_enable = yes
#postscreen_non_smtp_command_enable = yes
#postscreen_pipelining_enable = yes
### ADDENDUM: Any one of the foregoing three *_enable settings may cause
### significant and annoying mail delays.
```

**Comment by thctlo** [comment]
ps on topic, 
if you make rimap auth agains localhost, 

then you need : 
```
OPTIONS="-r -c -m /var/spool/postfix/var/run/saslauthd"
```
now you dont need to mount anymore. 

/etc/postfix/sasl/smtpd.conf
```
pwcheck_method: saslauthd
mech_list: plain login
```

```
smtpd      pass  -       -       y       -       -       smtpd
    -o smtpd_sasl_auth_enable=no
    -o content_filter=spamassassin
```
disable sending mail over port 25.

and allow it over submission/port 587
```
submission inet  n       -       y       -       -       smtpd
    -o syslog_name=postfix/submission
    -o smtpd_etrn_restrictions=reject
    -o smtpd_enforce_tls=yes
    -o smtpd_tls_security_level=encrypt
    -o smtpd_sasl_auth_enable=yes
    -o smtpd_sasl_authenticated_header=yes
    -o smtpd_client_restrictions=permit_sasl_authenticated,reject
    -o smtpd_recipient_restrictions=permit_sasl_authenticated,reject
    -o smtpd_relay_restrictions=permit_sasl_authenticated,reject
    -o milter_macro_daemon_name=ORIGINATING
```

and smtps/port 465
```
smtps      inet  n       -       y       -       -       smtpd
    -o syslog_name=postfix/smtps
    -o smtpd_tls_wrappermode=yes
    -o smtpd_tls_security_level=encrypt
    -o smtpd_sasl_auth_enable=yes
    -o smtpd_sasl_authenticated_header=yes
    -o smtpd_client_restrictions=permit_sasl_authenticated,reject
    -o smtpd_recipient_restrictions=permit_sasl_authenticated,reject
    -o smtpd_relay_restrictions=permit_sasl_authenticated,reject
    -o milter_macro_daemon_name=ORIGINATING
```
that should do it.

**Comment by thctlo** [comment]
The order of restrictions.  
Note the disabled part, becarefull before you enable these. 
```
### restrictions
smtpd_helo_required = yes
smtpd_delay_reject = yes
smtpd_helo_restrictions =
    permit_mynetworks,
    permit_sasl_authenticated,
    check_helo_access hash:/etc/postfix/overrule/allow_helo_access.map,
#    reject_non_fqdn_helo_hostname,
#    reject_invalid_helo_hostname,
#    reject_unknown_helo_hostname,
    reject_invalid_hostname,
    reject_non_fqdn_hostname,
    check_helo_access pcre:/etc/postfix/pcre/helo.pcre

strict_rfc821_envelopes = yes

smtpd_client_restrictions =
    permit_mynetworks,
    permit_auth_destination,
    permit_sasl_authenticated,
    reject_unknown_reverse_client_hostname

##  "unknown" is also the name in the case of a temporary dns lookup failure. so using 5xx for all "unknown" is not a good idea.
# reject_unknown_client_hostname: requires that the address->name and name->address mappings exist, but also that the two mappings reproduce the client IP address
#,reject_unknown_client_hostname
# reject_unknown_reverse_client_hostname: Reject the request when the client IP address has no address->name mapping. This is a weaker restriction than the reject_unknown_client_hostname
#,reject_unknown_reverse_client_hostname

smtpd_sender_restrictions =
    permit_mynetworks,
    permit_sasl_authenticated,
    reject_non_fqdn_sender,
    reject_unknown_sender_domain,
    check_sender_mx_access cidr:/etc/postfix/cidr/check_sender_mx_access.cidr,
    check_sender_access cidr:/etc/postfix/cidr/deny_sender_access.cidr,
    check_sender_access hash:/etc/postfix/map/deny_sender_access.map,
    reject_unauth_pipelining

smtpd_recipient_restrictions =
    permit_mynetworks,
    permit_sasl_authenticated,
    reject_unknown_recipient_domain,
    reject_non_fqdn_recipient,
    reject_non_fqdn_hostname,
    reject_non_fqdn_sender,
    reject_unauth_destination,
    reject_unauth_pipelining,
    reject_invalid_hostname

smtpd_relay_restrictions =
    permit_mynetworks,
    permit_sasl_authenticated,
    reject_unauth_destination,
    reject_unknown_recipient_domain,
    check_policy_service unix:private/policy-spf
#, check_policy_service inet:127.0.0.1:12525
#, check_policy_service inet:127.0.0.1:10023

smtpd_data_restrictions = reject_unauth_pipelining
```

**Comment by thctlo** [comment]
```
# /etc/postfix/cidr/check_sender_mx_access.cidr
#
# We wijzen email af als het domein van de afzender
# een MX record heeft dat naar een pertitent onjuist adres
# verwijst.

0.0.0.0/8       REJECT Domain MX in broadcast network
10.0.0.0/8      REJECT Domain MX in RFC 1918 private network
127.0.0.0/8     REJECT Domain MX in loopback network
169.254.0.0/16  REJECT Domain MX in link local network
172.16.0.0/12   REJECT Domain MX in RFC 1918 private network
192.0.2.0/24    REJECT Domain MX in TEST-NET network
192.168.0.0/16  REJECT Domain MX in RFC 1918 private network
224.0.0.0/4     REJECT Domain MX in class D multicast network
240.0.0.0/5     REJECT Domain MX in class E reserved network
248.0.0.0/5     REJECT Domain MX in reserved network

::1/128         REJECT Domain MX is Loopback address
::/128          REJECT Domain MX is Unspecified address
::/96           REJECT Domain MX in IPv4-Compatible IPv6
::ffff:0:0/96   REJECT Domain MX in IPv4-Mapped IPv6
ff00::/8        REJECT Domain MX in Multicast network
fe80::/10       REJECT Domain MX in Link-local unicast network
fec0::/10       REJECT Domain MX in Site-local unicast network
```
