### ISSUE TITLE
Empty To address

### ISSUE THREAD

**Issue by dobrildobrilov** [mailwatch/1.2.0#1087]
Hello,

I'm using postfix+mailscanner+mailwatch. To remove mail duplicates the posfix was configured with option enable_original_recipient=no , then in Mailwatch interface , To (Mail to) column is empty.  Release from Quarantine not working by the same reason, probably cannot get the address of recipient.
When postfix is configured with enable_original_recipient=yes , all working correctly but there are too many duplicated emails because usually emails are sent to few group emails where are listed same users.
Please advice how to solve this issue.

### Version and method
 - MailWatch Version: 1.2.9
 - Install type:  Zip/tarball install 
 -Fresh install
### Server configuration
 - Operation System: [ Debian | Ubuntu | CentOS | Other ] version [ version ]
 - PHP version: [ 5.3 | 5.4 | 5.5 | 5.6 | 7.0 | 7.1 ]
 - Database: [ MySQL | MariaDB ] version [ version ]
 - Mail Server: [ Postfix ]
 - Used web server: [ Apache 2.4

**Comment by ghost** [comment]
Can you provide a sanitized postfix message header for each condition?  This may give some insight into why the MailWatch Logger is having trouble...

**Comment by Skywalker-11** [comment]
Could reproduce it. Just add the mentioned option to the postfix conf. No `to` addresses are shown in GUI.
Problem is that the perl `$message` object in MailWatch.pm `sub MailWatchLogging` does have an empty `to` field. Dump by Dumper with `yes`:
```
Jul 12 18:07:21 mailtest MailScanner[64104]:                  'to' => [
Jul 12 18:07:21 mailtest MailScanner[64104]:                            'test1@example.com',
Jul 12 18:07:21 mailtest MailScanner[64104]:                            'test2@example.com',
Jul 12 18:07:21 mailtest MailScanner[64104]:                          ],
```
With `no`:
```
Jul 12 18:03:38 mailtest MailScanner[64093]:                  'to' => [
Jul 12 18:03:38 mailtest MailScanner[64093]:                            ''
Jul 12 18:03:39 mailtest MailScanner[64093]:                          ],
```
Headers field still contains the correct addresses.
`Jul 12 18:03:39 mailtest MailScanner[64093]:                                                                                                      'To: test1@example.com, test2@example.com',`

Same with `postfixrecips` field:
```
Jul 12 18:03:38 mailtest MailScanner[64093]:                  'postfixrecips' => {
Jul 12 18:03:38 mailtest MailScanner[64093]:                                       'test1@example.com' => 1,
Jul 12 18:03:38 mailtest MailScanner[64093]:                                       'test2@example.com' => 1,
Jul 12 18:03:38 mailtest MailScanner[64093]:                                     },
``` 
... and with metadata field:
```
Jul 12 18:03:39 mailtest MailScanner[64093]:                                  'Adsn_orig_rcpt=rfc822;test1@example.com',
Jul 12 18:03:39 mailtest MailScanner[64093]:                                  'O',
Jul 12 18:03:39 mailtest MailScanner[64093]:                                  'Rtest1@example.com',
Jul 12 18:03:39 mailtest MailScanner[64093]:                                  'Adsn_orig_rcpt=rfc822;test2@example.com',
Jul 12 18:03:39 mailtest MailScanner[64093]:                                  'O',
Jul 12 18:03:39 mailtest MailScanner[64093]:                                  'Rtest2@example.com', 
```
With `yes` the `'O'` line would also contain the recipients

**Comment by ghost** [comment]
Interesting, looks like it could be a MailScanner bug.  I will need to run some tests.

**Comment by Skywalker-11** [comment]
Probably has to be fixed around this code https://github.com/MailScanner/v5/blob/master/common/usr/share/MailScanner/perl/MailScanner/Message.pm#L1454-L1458

EDIT: Code snippets exists multiple times for each message type (spam, ham, etc.)

**Comment by ghost** [comment]
It is deeper than that...it is occurring during the initial reading of the queue file...

https://github.com/MailScanner/v5/blob/master/common/usr/share/MailScanner/perl/MailScanner/Postfix.pm#L483-L505

**Comment by Skywalker-11** [comment]
Your right. First matches the `O` and sets `$ORIGFound` and after that matches `R` but doesn't add the `$recdata` because `$ORIGFound` is already set.

This seems to fix that:
If the data for `'O'` is empty (no real recipient found) only log the metadata and then continue with next entry.
```
      } elsif ($rectype eq 'O') {
        # Recipient address
        $recdata =~ s/^\<//;
        $recdata =~ s/\<$//;
        # If recipient is empty only add metadata
        push @{$message->{metadata}}, "$rectype$recdata";
        next unless $recdata ne '';
        push @{$message->{to}}, lc($recdata);
        $TOFound = 1;
        $ORIGFound = 1;
        #print STDERR "Pre R Recip $recdata\n";
      #JKF 20040322 } elsif ($rectype eq 'O') {
      } elsif ($rectype eq 'R') {
        # Original recipients are handled by MS as normal recipients,
        # but are put back into the 'O' originalrcpts list in the
        # replacement message.
        # Original recipient address
        $recdata =~ s/^\<//;
        $recdata =~ s/\<$//;
        $recdata = lc($recdata);
        push @{$message->{to}}, lc($recdata) unless $ORIGFound;
        push @{$message->{metadata}}, "$rectype$recdata";
        #JKF 20040322 $message->{originalrecips}{"$recdata"} = 1;
        $message->{postfixrecips}{lc("$recdata")} = 1;
        $TOFound = 1;
        #print STDERR "Pre O Recip $recdata\n";
```
Btw. is `$recdata = lc($recdata); ` in `'R'` part necessary?

**Comment by ghost** [comment]
@Skywalker-11 I'm not sure about $recdata = lc($recdata); .  I'm going to leave it just to be safe.

**Comment by ghost** [comment]
https://github.com/MailScanner/v5/pull/201

**Comment by dobrildobrilov** [comment]
enable_original_recipient=yes - All addresses appears correctly

Message Headers: | Received: from mail.stanga.net (unknown [195.34.122.2])     (using TLSv1 with cipher ADH-AES256-SHA (256/256 bits))     (No client certificate requested)     by mail.snowthunder.org (Postfix) with ESMTPS id A9C23626BC;     Thu, 12 Jul 2018 16:25:53 +0300 (EEST)Received: by mail.stanga.net (Postfix, from userid 0)     id 7A16D30A0AC4; Thu, 12 Jul 2018 16:25:52 +0300 (EEST)Date: Thu, 12 Jul 2018 16:25:52 +0300To: test@snowthunder.org, dobril@snowthunder.org, xxx@snowthunder.orgCc: admins@snowthunder.org, admin@snowthunder.orgSubject: TestMail J2User-Agent: Heirloom mailx 12.4 7/29/08MIME-Version: 1.0Content-Type: text/plain; charset=us-asciiContent-Transfer-Encoding: 7bitMessage-Id: <20180712132552.7A16D30A0AC4@mail.stanga.net>From: root@mail.stanga.net (root)X-Stanga-MailScanner-ID: 7A16D30A0AC4.A8B8EX-Stanga-MailScanner: Not scanned: please contact your Internet E-Mail Service Provider for detailsX-Stanga-MailScanner-SpamCheck: not spam (whitelisted),     SpamAssassin (score=-0.001, required 5, autolearn=disabled,     NO_RELAYS -0.00)X-Stanga-MailScanner-From: root@mail.stanga.netX-Spam-Status: No
-- | --
From: | root@mail.stanga.net[Add to Whitelist \| Add to Blacklist] | root@mail.stanga.net | [Add to Whitelist \| Add to Blacklist]
root@mail.stanga.net | [Add to Whitelist \| Add to Blacklist]
To: | test@snowthunder.orgxxx@snowthunder.orgadmin@snowthunder.orgdobril@snowthunder.orgadmins@snowthunder.org
Subject: | TestMail J2

after applied the path to MailScanner.
enable_original_recipient=no - Show only final addresses , after postfix stripe mail groups. This is not OK  because if need to Release from quarantine , it will show different addressees.  Looks like MailScanner or Mailwatch is not intended to work with enable_original_recipient=no , unfortunately there are no much duplicated mails without this option.


Message Headers: | Received: from mail.stanga.net (unknown [195.34.122.2])     (using TLSv1 with cipher ADH-AES256-SHA (256/256 bits))     (No client certificate requested)     by mail.snowthunder.org (Postfix) with ESMTPS id 56951626C4;     Fri, 13 Jul 2018 12:01:58 +0300 (EEST)Received: by mail.stanga.net (Postfix, from userid 0)     id 3571630A0A81; Fri, 13 Jul 2018 12:01:52 +0300 (EEST)Date: Fri, 13 Jul 2018 12:01:52 +0300To: test@snowthunder.org, dobril@snowthunder.org, xxx@snowthunder.orgCc: admins@snowthunder.org, admin@snowthunder.orgSubject: TestMail K1User-Agent: Heirloom mailx 12.4 7/29/08MIME-Version: 1.0Content-Type: text/plain; charset=us-asciiContent-Transfer-Encoding: 7bitMessage-Id: <20180713090152.3571630A0A81@mail.stanga.net>From: root@mail.stanga.net (root)X-Stanga-MailScanner-ID: 3571630A0A81.A7C60X-Stanga-MailScanner: Not scanned: please contact your Internet E-Mail Service Provider for detailsX-Stanga-MailScanner-SpamCheck: not spam (whitelisted),     SpamAssassin (score=-0.001, required 5, autolearn=disabled,     NO_RELAYS -0.00)X-Stanga-MailScanner-From: root@mail.stanga.netX-Spam-Status: No
-- | --
From: | root@mail.stanga.net[Add to Whitelist \| Add to Blacklist] | root@mail.stanga.net | [Add to Whitelist \| Add to Blacklist]
root@mail.stanga.net | [Add to Whitelist \| Add to Blacklist]
To: | dobril@snowthunder.orgtest@snowthunder.org
Subject: | TestMail K1

**Comment by dobrildobrilov** [comment]
Looks like I found some work around for my issue.
The only reason to put enable_original_recipient=no was fight duplicated email , but I found way to do via procmail.
virtual_transport = procmail
enable_original_recipient=yes

add follow line in procmailrc
```
  :0 Wh: msgid.lock
        | formail -D 8192 $MAILDIR/no_duplicates
```
