### ISSUE TITLE
Wrong printing in detail.php after install

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#1088]
### Issue summary

multi message loop in detail.php

### Steps to reproduce

Don't know. Was during the last test off install script.

### Version and method
 - MailWatch Version: 1.2.9
 - Install type: GitHub checkout
 - Updated from an older MailWatch or fresh install: Fresh install with installer

### Server configuration
 - Operation System: Debian
 - PHP version: 7.0
 - Database: MariaDB version 10.1
 - Mail Server: Postfix
 - Used web server: Apache 2.4

### Client configuration 
 - Operation System: Mac OSX
 - Browser: Safari OSX

Very nice bug after last install with MW installer.

in status.php (mail generated by missing sudo file)
messages are from www-data
![sc3](https://user-images.githubusercontent.com/12907102/42735586-f7aacf92-8856-11e8-9c11-e2fecef95595.png)

In detail.php
if I click on the first message in status.php
all messages in status.php printed in the same detail.php page
![sc4](https://user-images.githubusercontent.com/12907102/42735595-21fc86aa-8857-11e8-80b9-227cc83e90ed.png)

**Comment by ghost** [comment]
@stefaweb This is probably a side effect of clamav not running.

**Comment by stefaweb** [comment]
@shawniverson For the mails ok but for the detail.php page?

**Comment by Skywalker-11** [comment]
https://github.com/mailwatch/MailWatch/blob/1.2/mailscanner/detail.php#L126-L128
```
echo '<table class="maildetail" border="0" cellspacing="1" cellpadding="1" width="100%">' . "\n";
while ($row = $result->fetch_array()) {
    $listurl = 'lists.php?token=' . $_SESSION['token'] .'&amp;host=' . $row[__('receivedfrom04')] . '&amp;from=' . $row[__('from04')] . '&amp;to=' . $row[__('to04')];
```
If all mails have the same QueueID it would explain why all are shown. The sql query fetches all with the id and while loop does all the stuff for all mail entries

EDIT: Was there a reason that the while loop is there? Its in the code since the initial commit

**Comment by stefaweb** [comment]
You're true. The Queue ID is the same (768F5BC0F30.AF122) for all the 96 mails.

Will test it again with next PR/try.

**Comment by Skywalker-11** [comment]
Were they manually send or as regular mails via postfix?

**Comment by stefaweb** [comment]
I no longer have the problem with last setup.sh code.

But the mailwatch code with the while loop should may be be changed.

**Comment by Skywalker-11** [comment]
@endelwar @asuweb @shawniverson 
Do you know any real use case in which the while loop is useful there?

**Comment by ghost** [comment]
@Skywalker-11 I can't think of one.  Emails with the same ID are/should be, the same email, so why display it over and over?  Furthermore, why does MailScanner freak out when A/V scanning fails (a separate issue) and loop the mails numerous times?

**Comment by stefaweb** [comment]
avscanner was not fine but also /etc/sudo.d/mailwatch.
And the postfix was not configured (just out of the box).

**Comment by Skywalker-11** [comment]
Sudoers.d/mailwatch is only important for the Linting and queue display. It should be independent from the logging to the DB (.pm-files).
Also postfix should work just fine with the default config as long as the header_check is enabled.

**Comment by endelwar** [comment]
> Do you know any real use case in which the while loop is useful there?

I agree with @shawniverson : same id= same email, so no loop should be necessary
