### ISSUE TITLE
Publish last code

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#1089]
Hello!

Possible to publish all last codes waiting as 1.3.0?

**Comment by endelwar** [comment]
I will do a 1.2.10 release later today

**Comment by stefaweb** [comment]
A version 1.2.10 is very good too. ;)

**Comment by Skywalker-11** [comment]
Can we also publish current docs?

**Comment by endelwar** [comment]
@Skywalker-11 already did ;)
