### ISSUE TITLE
Problem to send quarantine report with French language (1.2.10)

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#1091]
### Issue summary

Quarantine Report is not sent when we use French language in GUI.

I hope that the problem is on my side but I've verified two time my setup.

### Steps to reproduce

Click on user_manager.php and "Send now"

English -> `The quarantine report was successfully sent.`
French -> `Une erreur s'est produite lors de l'envoi du rapport de quarantaine.` (not sent)

Others languages works.

### Version and method
 - MailWatch Version: 1.2.10

### Server configuration
 - Operation System: Debian Stretch
 - PHP version:  7.0
 - Database: MariaDB 10.1
 - Mail Server: Postfix
 - Used web server: Apache 2.4

Report is not sent and I found this in /var/log/apache2/error.log:

```
[Thu Jul 19 11:49:05.852691 2018] [:error] [pid 30241] [client xx.xx.xx.xx:54207] PHP Warning:  sprintf(): Too few arguments in /opt/mailwatch/public/quarantine_report.inc.php on line 584, referer: https://antispam.domain.tld/user_manager.php?token=fddd97b169f0a6aa2527f80e016e46ea1b079df7692ff09e956583fdf374d945&action=edit&id=20
[Thu Jul 19 11:49:05.853065 2018] [:error] [pid 30241] [client xx.xx.xx.xx:54207] PHP Warning:  sprintf(): Too few arguments in /opt/mailwatch/public/quarantine_report.inc.php on line 585, referer: https://antispam.domain.tld/user_manager.php?token=fddd97b169f0a6aa2527f80e016e46ea1b079df7692ff09e956583fdf374d945&action=edit&id=20
```

**Comment by stefaweb** [comment]
May be a problem of "parsing" with French language (éàçè).

**Comment by Skywalker-11** [comment]
I also get this when sending the report...
`count(): Parameter must be an array or an object that implements Countable in /opt/1.2-dev/mailscanner/lib/pear/Mail/mimePart.php on line 314, referer: https://mailtest/dev/user_manager.php?token=15fef2fa3b8047d893b84a7a56f0c915973a9913e5e9f4d21df83b779d2769d8&action=edit&id=16`

**Comment by Skywalker-11** [comment]
Mine error is due to PHP 7.2: http://php.net/manual/en/function.count.php
> count() will now yield a warning on invalid countable types passed to the array_or_countable parameter.

**Comment by stefaweb** [comment]
I'm still with standard 7.0 version from Debian Stretch.

**Comment by endelwar** [comment]
@stefaweb `text613` in french translation contains an extra `%s` and make sprintf function complain about missing arguments

**Comment by endelwar** [comment]
@Skywalker-11 Mime_mimePart (and other pear libraries) needs to be tested on php7.2, I don't think that it is fully complaint

**Comment by stefaweb** [comment]
Works.

Thanks @endelwar 

I'll post the new file.

```
    'text613' => 'Au cours du ou des %s dernier(s) jours, vous n\'avez reçu aucun message mis en quarantaine.',
```
```
    'text613' => 'In the last %s day(s) you have received no e-mails that have been quarantined.',
```

**Comment by stefaweb** [comment]
PR #1092

**Comment by stefaweb** [comment]
Done.

**Comment by endelwar** [comment]
@Skywalker-11 pear/Mail_Mime 1.10.2 is declared to be compatible with php 7.2, just updated it

**Comment by Skywalker-11** [comment]
> @Skywalker-11 pear/Mail_Mime 1.10.2 is declared to be compatible with php 7.2, just updated it

Error is gone with updated version
