### ISSUE TITLE
Small cosmetic bug in rep_total_mail_by_date.php

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#1093]
With 1.2.10.

![sc](https://user-images.githubusercontent.com/12907102/42997605-a01391a0-8c17-11e8-9d8c-3e7f4f08b229.png)

**Comment by Skywalker-11** [comment]
Which page is that?

**Comment by stefaweb** [comment]
With `rep_total_mail_by_date.php`

![capture d ecran 2018-07-20 a 14 13 50](https://user-images.githubusercontent.com/12907102/43002037-ab884958-8c27-11e8-838e-02c309b39081.png)

**Comment by Skywalker-11** [comment]
Found it https://github.com/mailwatch/MailWatch/blob/1.2/mailscanner/rep_total_mail_by_date.php#L308
` echo ' <TD class="white"><BR></TD>' . "\n";`
Preparing PR
