### ISSUE TITLE
I'm still alive...

### ISSUE THREAD

**Issue by ghost** [mailwatch/1.2.0#1097]
### Steps to reproduce
1.  Hire me
2.  Give me lots of work
3.  All work and no play makes me a dull boy

### Expected result
I should have weekends to work on MailWatch with my buddies!

### Actual result
I work all the time and don't have any left over time.

### Version and method
 - MailWatch Version: [ develop ]
 - Install type: [ GitHub checkout ]
 - Updated from an older MailWatch or fresh install: [ Fresh install  ]

### Server configuration
 - Operation System: [ Debian | Ubuntu | CentOS | Other ] 
 - PHP version: [ 5.3 | 5.4 | 5.5 | 5.6 | 7.0 | 7.1 ]
 - Database: [ MySQL | MariaDB ]
 - Mail Server: [ Postfix | Exim | Sendmail ]
 - Used web server: [ Apache | Nginx ] 

### Client configuration 
 - Operation System: [ any ] version [any supported ]
 - Browser: [ any browser supported ]

**Comment by ghost** [comment]
@Skywalker-11 lol

**Comment by stefaweb** [comment]
In Paris, there are plenty of developer position to fill. Around 40K € / year for a junior.   ;)
