### ISSUE TITLE
Malformed From Address 

### ISSUE THREAD

**Issue by ghost** [mailwatch/1.2.0#1101]
### Issue summary
https://forum.efa-project.org/viewtopic.php?f=13&p=12609

### Steps to reproduce
1.  construct an invalid from "fubar" <>example.org   (address outside the brackets)

### Expected result
Should we handle this malformed address or tell folks to adhere to the RFCs?

### Actual result
Nothing is logged in from field (rightfully so)

**Comment by stefaweb** [comment]
It's better to handle that. You do not have to rely on people to correct this. ;)

**Comment by Skywalker-11** [comment]
Currently we get the value from MS (https://github.com/mailwatch/MailWatch/blob/1.2/MailScanner_perl_scripts/MailWatch.pm#L358) which then is queried https://github.com/mailwatch/MailWatch/blob/1.2/mailscanner/detail.php#L76 and then printed https://github.com/mailwatch/MailWatch/blob/1.2/mailscanner/detail.php#L211.

So this may is also a MS problem. 

One more thing to consider is that it could be abused eg. by injecting html inside that address and so it would need to be sanitized.

**Comment by ghost** [comment]
I'm going to run some tests and see what I can do about this.

**Comment by ghost** [comment]
My milter code correctly addresses this problem, but the other mail processors do not in MailScanner, so I am going to continue working on this.

**Comment by ghost** [comment]
Unable to reproduce on the postfix processor with latest MailScanner code.

![image](https://user-images.githubusercontent.com/6255179/46446013-de3dd600-c747-11e8-8dce-d8c81a4151c1.png)
