### ISSUE TITLE
The return of the infamous dietoken99

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#1107]
As the title said. ;)

Just got it after a session timeout.

dietoken99
Error: unable to validate security token

![capture d ecran 2018-09-27 a 15 40 36](https://user-images.githubusercontent.com/12907102/46150113-1fc41200-c26c-11e8-9441-c976f47c5925.png)

EDIT:

I was on rep_message_listing.php.

**Comment by Skywalker-11** [comment]
Is it reproducable? Where did you try to go from rep_message_listing.php?

If I go to rep_message_listing.php and have a session_timeout of 10 I always go to the login page after the timeout.

**Comment by ghost** [comment]
@stefaweb are you trying to hack your MailWatch again?

**Comment by stefaweb** [comment]
Hi!

Seems reproductible.

Login.
Go to rep_message_listing.php page
Wait for timeout.
Click on the "reload page" of the browser
MW go to login page
login again
MW return to rep_message_listing.php page
And we got the infamous message.

**Comment by ghost** [comment]
That is odd, I followed these steps, no dice.  Can anyone else reproduce?  I'm going to try a few more times...

**Comment by stepgr** [comment]
Yes , I can confirm , it happens to me on a fresh install on  a Debian 9  machine 
on status page  MailWatch Version: 1.2.10

**Comment by ghost** [comment]
I can't reproduce this on CentOS7 using Chrome 67 hmm.....

When I log back in, it redirects back to Recent Messages instead.

**Comment by stepgr** [comment]
Actually  I don't have the exact problem as the screenshot from stefaweb. Mine logs out  and you get the login page that reports the session expired but you can't  login  unless you clear the url. I'm waiting to expire to send a screenshot.

**Comment by ghost** [comment]
Not sure if it matters, but I am on post 1.2.10 at latest commit of the 1.2 branch

**Comment by stepgr** [comment]
the url is:  domain.name/login.php?error=timeout
you cannot login after that unless you clear the url .

![screenshot at 2018-09-30 17 06 18](https://user-images.githubusercontent.com/24478970/46258447-957de700-c4d3-11e8-941b-e31ced15c0ad.png)

**Comment by stefaweb** [comment]
> Actually I don't have the exact problem as the screenshot from stefaweb. Mine logs out and you get the login page that reports the session expired but you can't login unless you clear the url. I'm waiting to expire to send a screenshot.

I also have this problem some time.

**Comment by ghost** [comment]
Is that firefox?  I can switch over to it and give it a try.

**Comment by stepgr** [comment]
> Is that firefox? I can switch over to it and give it a try.

mine is chromium but I run it now on Firefox to see, I will let you know

**Comment by stefaweb** [comment]
Tried on Safari Mac v12 and Chrome W10.

**Comment by stepgr** [comment]
Firefox works OK, mine are both on linux mint  17.3

**Comment by ghost** [comment]
Still can't reproduce, I may need to build another one as a test.  Need server specs to match up with someone and the MailWatch commit point you are using.

**Comment by stepgr** [comment]
Another thing not related to this is that in all browsers tested the page is always wider (Chromium, Chrome, Firefox )  : 
![screenshot at 2018-09-30 17 19 51](https://user-images.githubusercontent.com/24478970/46258543-610b2a80-c4d5-11e8-92e1-f512b51fde25.png)

**Comment by stefaweb** [comment]
@shawniverson 

Debian Stretch
apache 2.4
php 7.0
mariadb 10.1
postfix 3.1.8
mailscanner 5.1.1-1
mw 1.2.10

**Comment by stepgr** [comment]
It happens with firefox also it's just a different message : 
![screenshot at 2018-10-01 16 23 39](https://user-images.githubusercontent.com/24478970/46291337-d985f000-c596-11e8-836c-709c59c42464.png)

**Comment by stepgr** [comment]
> Another thing not related to this is that in all browsers tested the page is always wider (Chromium, Chrome, Firefox ) :
> ![screenshot at 2018-09-30 17 19 51](https://user-images.githubusercontent.com/24478970/46258543-610b2a80-c4d5-11e8-92e1-f512b51fde25.png)

And this is related to Virus Scanners = auto 
when I specific state Virus Scanners = clamav  then the page has a normal width.
(of course I mean  in /etc/MailScanner.conf eh?)

**Comment by stefaweb** [comment]
@stepgr 

Hi! It ill be better do open a specific issue on this.

The screen copy is all pixelated and illegible on my side.

**Comment by ghost** [comment]
@stepgr Yeah, open a new issue on that.  I think you'll find it is probably the length of the description of "Top Virus" near the top causing that, which is a separate issue.

**Comment by ghost** [comment]
@stefaweb I am building a Debian instance now.  Are you at the 1.2.10 tag or the latest commit?

**Comment by Skywalker-11** [comment]
I think the problem is that we also have a token on the login page which itself times out after some time. When you then try to login (now with timed out token) it gives the error message. Probably from:
https://github.com/mailwatch/MailWatch/blob/1.2/mailscanner/checklogin.php#L33
https://github.com/mailwatch/MailWatch/blob/1.2/mailscanner/functions.php#L4653

**Comment by ghost** [comment]
@Skywalker-11 We problably need to alter the behavior a little bit here.  A token is needed to protect the login form, but it needs to say something along the lines "Login token expired, please log in again" and redirect back to login page.

**Comment by ghost** [comment]
Just a little background why this is a necessary evil..
https://support.detectify.com/customer/portal/articles/1969819-login-csrf

**Comment by xpufx** [comment]
Error: unable to validate security token

I am having this also on 1.2.11 . Mine shows this on a blank page with this message alone usually. Few reloads usually fix it.

**Comment by Skywalker-11** [comment]
@oktayaa on which page was that?

**Comment by xpufx** [comment]
I think it times out and send me to the log in page but when I log in I get that error. I do log into a few different accounts. It might be related to that. I will pay more attention and provide more details if/when it happens again.

**Comment by Skywalker-11** [comment]
If you see it again please post the page you were on and what you tried to do so we can take a look

**Comment by stepgr** [comment]
See attached screenshots

1 is when the session times out

2 this comes up after you type ( correct ) credentials  and the third 
time  works OK

This only happens  in Firefox (linux) for me at least

**Comment by ghost** [comment]
@stepgr, does this happen right away after the session times out, or has a period of time passed between 1 and 2?

**Comment by stepgr** [comment]
I cant really tell you for sure,  usually some times passes before I 
notice that

the session ended but  how much time  I dont know , I would guess more than

30 min  anyway

**Comment by Skywalker-11** [comment]
@oktayaa the linked PR should prevent that error while on the login page. And instead gives the user a notice to reload the page before he can login
