### ISSUE TITLE
1.2.10 "Search and Reports" error sorting output by "Client IP" > Error: unable to validate input

### ISSUE THREAD

**Issue by tgreggs** [mailwatch/1.2.0#1108]
MW 1.2.10 throws Error: unable to validate input when trying to sort reports output by client ip.  Other fields sort without error.

**Comment by ghost** [comment]
Which report and filter criteria, specifically?

**Comment by tgreggs** [comment]
Shawn if I go to reports then message listings with or without any filters applied and then sort the output by the “client ip” column, it produces the error every time.  I can sort by any other column no problems.

 

Tracy

**Comment by ghost** [comment]
@tgreggs I don't have a client ip column. do you have a redacted screenshot?  Is this something new, I wonder (I may not be on the latest codebase)...

**Comment by tgreggs** [comment]
You can turn it on or off and include PTR or not in the conf.php

 

 

okla2

 <mailto:tgreggs@okla.com> Tracy Greggs

Greggs Enterprises, LLP

DBA Oklahoma Network Consulting

(405) 550-6636

**Comment by Skywalker-11** [comment]
It is working correctly for me. Can you fill out the formular here: https://github.com/mailwatch/MailWatch/blob/1.2/.github/ISSUE_TEMPLATE.md

And also check if there are any errors logged in your webserver log eg. /var/log/apache2/error.log

**Comment by tgreggs** [comment]
This is the fix for the issue I described.  Still incorrect in current functions.php:


        case 'orderby':       
                //Added |clientip| to string 11-28-2018 
           // if (preg_match('/^(datetime|from_address|to_address|subject|size|sascore)$/', $input)) {
            if (preg_match('/^(datetime|from_address|clientip|to_address|subject|size|sascore)$/', $input)) {
                return true;
            }
            break;
