### ISSUE TITLE
Truncate TOP virus

### ISSUE THREAD

**Issue by ghost** [mailwatch/1.2.0#1110]
### Steps to reproduce
1. Login to Mailwatch and try to send mail with virus with ESETS deamon installed, ESETS reports 3 actions and all this is displayed in TOP virus section in GUI, see screenshot

### Expected result
Text should be truncated

### Actual result
Text is not truncated and whole thing is displayed which makes looking through mails very difficult

### Version and method
 - MailWatch Version: [ stable 1.2.x ]
 
![mailwatch_truncate](https://user-images.githubusercontent.com/17081737/46333953-94a79b00-c622-11e8-9317-171f6e16dd09.PNG)

**Comment by endelwar** [comment]
Looks like Esets regex need to be fixed to extract the virus name from the antivirus output.
Can you please post some examples of virus description like the one in the picture?

**Comment by ghost** [comment]
Sure:

As seen form message detail under REPORT:

1. 
Report:	Esets: found in winmail.dat » TNEF » attachment.bin Esets Actions: Esets Additional Info: none
Esets: found in winmail.dat Esets Actions: Esets Additional Info: none 

2. 
Report:	Esets: found a variant of Win32/GenKryptik.CMUE trojan in RFQ_350608317BD.iso » ISO » RFQ_350608317BD.exe Esets Actions: deleted Esets Additional Info: none
Esets: found a variant of Win32/GenKryptik.CMUE trojan in RFQ_350608317BD.iso Esets Actions: deleted Esets Additional Info: none 

3. 
Report:	Esets: found a variant of MSIL/GenKryptik.CHAV trojan in request_ttpdf.gz.rar » RAR5 » request_ttpdf.gz.exe Esets Actions: deleted Esets Additional Info: none
Esets: found a variant of MSIL/GenKryptik.CHAV trojan in request_ttpdf.gz.rar Esets Actions: deleted Esets Additional Info: none Esets: found a variant of MSIL/GenKryptik.CHAV trojan in request_ttpdf.gz.exe Esets Actions: cleaned by deleting Esets Additional Info: none MailScanner: Executable DOS/Windows programs are dangerous in email (request_ttpdf.gz.exe) No programs allowed (request_ttpdf.gz.exe)
Esets: found a variant of MSIL/GenKryptik.CHAV trojan in request_ttpdf.gz.exe Esets Actions: cleaned by deleting Esets Additional Info: none MailScanner: Executable DOS/Windows programs are dangerous in email (request_ttpdf.gz.exe) No programs allowed (request_ttpdf.gz.exe) 

4.
Report:	Esets: found a variant of MSIL/Kryptik.PRG trojan in SBSP01127.iso » ISO » SBSP01127.exe Esets Actions: deleted Esets Additional Info: none Esets: found a variant of Win32/Injector.EASG trojan in SBSP01128.iso » ISO » SBSP01128.exe Esets Actions: deleted Esets Additional Info: none
Esets: found a variant of MSIL/Kryptik.PRG trojan in SBSP01127.iso Esets Actions: deleted Esets Additional Info: none
Esets: found a variant of Win32/Injector.EASG trojan in SBSP01128.iso Esets Actions: deleted Esets Additional Info: none 

5. 
Report:	Esets: found a variant of Win32/Injector.EARS trojan in BL %26 Commercia.doc » RTF » mondi.exe Esets Actions: cleaned by deleting Esets Additional Info: none Esets: found a variant of Win32/Injector.EARS trojan in BL %26 Commercia.doc » RTF » mondi.exe » NSIS » judoist.dll Esets Actions: cleaned by deleting Esets Additional Info: none Esets: found BAT/Agent.OOJ trojan in CI %26Packing Li.doc » RTF » hondi.cmd Esets Actions: cleaned by deleting Esets Additional Info: none Esets: found XML/Agent.D trojan in BL %26 Commercia.doc » RTF » trbatehtqevyay.ScT Esets Actions: cleaned by deleting Esets Additional Info: none Esets: found a variant of Win32/Injector.EARS trojan in CI %26Packing Li.doc » RTF » mondi.exe » NSIS » judoist.dll Esets Actions: cleaned by deleting Esets Additional Info: none Esets: found a variant of Win32/Injector.EARS trojan in CI %26Packing Li.doc » RTF » mondi.exe Esets Actions: cleaned by deleting Esets Additional Info: none Esets: found BAT/Agent.OOJ trojan in BL %26 Commercia.doc » RTF » hondi.cmd Esets Actions: cleaned by deleting Esets Additional Info: none Esets: found BAT/Agent.OOI trojan in CI %26Packing Li.doc » RTF » dqfm.cmd Esets Actions: cleaned by deleting Esets Additional Info: none Esets: found XML/Agent.D trojan in CI %26Packing Li.doc » RTF » trbatehtqevyay.ScT Esets Actions: cleaned by deleting Esets Additional Info: none Esets: found BAT/Agent.OOI trojan in BL %26 Commercia.doc » RTF » dqfm.cmd Esets Actions: cleaned by deleting Esets Additional Info: none
Esets: found multiple threats in BL %26 Commercia.doc Esets Actions: cleaned by deleting Esets Additional Info: none
Esets: found multiple threats in CI %26Packing Li.doc Esets Actions: cleaned by deleting Esets Additional Info: none

**Comment by ghost** [comment]
@gregecslo Please give https://github.com/mailwatch/MailWatch/pull/1112 a try and let me know if I have truncated the top virus output sufficiently.  

Note this does not address the root issue with the ESETS antivirus wrapper in MailScanner, it just limits the output in MailWatch.  That will need addressed separately.

**Comment by ghost** [comment]
Hi!

Patched the code and it looks good.
Will experiment with lenght but 30-40 looks OK.

Another thing, under virus report esets is not included at all...
See image
![efa_virus](https://user-images.githubusercontent.com/17081737/46467828-0d4b5a80-c7cf-11e8-9e35-6352c94222b9.PNG)
