### ISSUE TITLE
Return of the Emoticons!

### ISSUE THREAD

**Issue by ghost** [mailwatch/1.2.0#1113]
### Issue summary

While goofing around with utf-8 and MailScanner on a cool Friday evening, I came across a little bugaroo...I'm checking to see whether this is a MailScanner bug or a MailWatch bug...haven't determined that quite yet...might be insightful to see if anyone else gets different results.

### Steps to reproduce
1.   Construct an email with the following subject line (just random utf-8 emoticons in quoted printable)

```
=?utf-8?Q?=F0=9F=98=8E=F0=9F=A4=B7=E2=80=8D=E2=99=82=EF=B8=8F=E2=9C=8C=F0=9F=A4=9E=F0=9F=98=89=F0=9F=A4=A6=E2=80=8D=E2=99=80=EF=B8=8F=F0=9F=91=8C=F0=9F=91=8D?=
```

2.  Send to a MailWatch server

### Expected result
Emoticons should display consistently 

### Actual result
Subject on Recent Messages list does not display properly.

![image](https://user-images.githubusercontent.com/6255179/47592628-09c87080-d942-11e8-9690-f5c9803d6361.png)

However, it displays properly on the Details and Viewmail panes.

![image](https://user-images.githubusercontent.com/6255179/47592648-1fd63100-d942-11e8-9404-b4922e7fc557.png)

![image](https://user-images.githubusercontent.com/6255179/47592708-6af04400-d942-11e8-9918-6606131d2fc3.png)

### Version and method
 - MailWatch Version: [ 1.2.10 develop ]
 - Install type: [ GitHub checkout ]
 - Updated from an older MailWatch or fresh install: [ Fresh install ]

### Server configuration
 - Operation System: [  CentOS ] version 7
 - PHP version: [ 7.2 ]
 - Database: [  MariaDB ] version 10.1.35
 - Mail Server: [ Postfix ]
 - Used web server: [ Apache ] version 2.4.6
 - MailScanner: master branch (unreleased 5.1.2-2)

### Client configuration 
 - Operation System: Windows 10 Version 1809
 - Browser: Chrome version 69

**Comment by ghost** [comment]
Okay, this seems to be a bug introduced to MailScanner for MailWatch 2.0.

Can someone explain to me this in the MTA processors?

```
# Decode ISO subject lines into UTF8
# Needed for UTF8 support in MailWatch 2.0
    eval {
    $message->{utf8subject} = Encode::decode('MIME-Header',
                                              $message->{subject});
    };
    if ($@) {
     # Eval failed - store a copy of the subject before MIME::WordDecoder
     # is run, as this appears to destroy the characters of some subjects
     $message->{utf8subject} = $message->{subject};
    }
```

The problem is this line
```
$message->{utf8subject} = Encode::decode('MIME-Header',
                                              $message->{subject});
```

Unfortunately Encode::decode is mangling the quoted printable utf-8 subject line.  Is this needed for MailWatch 2.0?

I would much rather just do this and store the raw subject in all cases:

```
$message->{utf8subject} = $message->{subject};
```

**Comment by Skywalker-11** [comment]
Interesting @jcbenton already knew 3 years before there was any code that for MW 2.0 that we would need that...
[https://github.com/MailScanner/v5/blame/master/common/usr/share/MailScanner/perl/MailScanner/Postfix.pm#L933](https://github.com/MailScanner/v5/blame/master/common/usr/share/MailScanner/perl/MailScanner/Postfix.pm#L933)

I guess the intention was to convert headers from non utf8 (eg. iso-8859-1) to utf8 so that it can be stored in the DB and the encoding is consistent.

**Comment by jcbenton** [comment]
I have found that if you set the database column to utf8, mysql/maria will preserve it correctly without converting it beforehand. You also need to be sure that PHP doesn't screw it up when pulling it from the DB and displaying it.

**Comment by ghost** [comment]
@jcbenton That's odd, because my column is utf8, and it is not preserving it for some reason...

**Comment by jcbenton** [comment]
Try utf8mb4_unicode_ci

**Comment by Skywalker-11** [comment]
> Try utf8mb4_unicode_ci

The subject column should already have ``  `subject` longtext COLLATE utf8mb4_unicode_ci,``.

**Comment by jcbenton** [comment]
@shawniverson is it in the DB correctly when you do a select?  Not from PHP, but direct DB select.

**Comment by ghost** [comment]
@jcbenton negative, it just had ? marks when I directly queried the database, I'm resetting my instance...should have more info shortly...

**Comment by ghost** [comment]
@Skywalker-11 

@jcbenton is correct, my character set was "utf8_unicode_ci."  I had to run upgrade.php, even though it was a fresh install of the latest develop to convert it to utf8mb4_unicode_ci.

Marking as invalid.

**Comment by ghost** [comment]
@Skywalker-11 Should the default character set be extended on a fresh install from 1.2 develop from the start?

**Comment by ghost** [comment]
btw, @jcbenton must be a time traveler or something...that's spooky....

**Comment by Skywalker-11** [comment]
The create.sql still doesn't include all adjustments to the database because it still supported older systems eg. Centos 6 where MySQL didn't support utf8mb4 and some other features. These will only be used after running the upgrade.php:

https://github.com/mailwatch/MailWatch/blob/1.2/upgrade.php#L375

Maybe the doc should be clearer that it is necessary to run the upgrade.php

**Comment by ghost** [comment]
@Skywalker-11 Makes sense, yeah, I missed that.  However, now that we have support problems for PHP < 5.4 (I think CentOS 6 uses 5.3.x) and Maxmind requiring new GeoIP, is this really an issue anymore?

**Comment by jcbenton** [comment]
I'm not supporting CentOS for Mailborder v5 until they release a distribution that includes PHP 7.x native. I am not going to frankenstein a CentOS PHP 7.x solution I have to support for hundreds or thousands of customers. Many issues like the one you are experiencing are non-issues in 7.x.

**Comment by ghost** [comment]
@jcbenton Wise decision.  I'll create a diversion for people who want to use your product but don't want to pay for it and use the IUS repo for PHP 7.x support.  Should be lots of fun and free you up for real paying customers! 😆🤣😆😂
