### ISSUE TITLE
How to increase mailwatch database update time?

### ISSUE THREAD

**Issue by surjitiit** [mailwatch/1.2.0#1115]
I want to increase mailwatch database refresh time. How it is possible by cron?? 
Means i want to update maillog table in database on every 50 sec interval.

**Comment by Skywalker-11** [comment]
The database is updated as soon as MailScanner has finished analyzing the mail. So if you want the mails to be shown faster you have to improve the speed of MailScanner. Depending on your system usage you may have to add more computing resources (faster cpu/storage) to acchive this.

**Comment by surjitiit** [comment]
Are there any cron who is updating maillog database table??

**Comment by Skywalker-11** [comment]
No. As soon as your server received the mail MailScanner is going to start the dcan and once finished the result is written to the maillog table in the database. 

Only changes to the black/whitelist can have a delay until they are applied

**Comment by Skywalker-11** [comment]
Can this be closed?
