### ISSUE TITLE
Mailwatch is revealing postfix ALWAYS_BCC email address

### ISSUE THREAD

**Issue by xpufx** [mailwatch/1.2.0#1116]
### Issue summary

When a user logs into mailwatch, the TO: field also displays the email address specified in postfix for ALWAYS_BCC . This is used to send a a copy of each incoming/outgoing message to an archival mailbox.

**Comment by Skywalker-11** [comment]
Can you give an example of the headers that are shown and what you would expect instead?

**Comment by xpufx** [comment]
The ALWAYS_BCC setting sends a copy of each email to the email address listed there. Let's call this archive@domain.com .

Below is a portion of the log with domain names changed. When the recipients receive these messages they do not see the BCC recipient name. But on the interface it is displayed with the original recipient name and if I release etc, it would probably be sent as To:, not BCC:

It probably has something to do with them being in the same envelope and it's a pain to separate those in postfix. It might also have something to do with the delivery mechanism being dovecot instead of postfix's own. However I doubt that.

```
Dec 11 17:31:02 virt01 postfix/smtpd[14612]: 874984A0026: client=mail.seyirmobil.com[213.14.26.62]
Dec 11 17:31:02 virt01 postfix/cleanup[14614]: 874984A0026: hold: header Received: from mail.seyirmobil.com (mail.seyirmobil.com [213.14.26.62])??by mail.domain.com (Postfix) with ESMTPS id 874984A0026??for <username@domain.com>; Tue, 11 Dec 2018 17:31:02 +0100 (CET) from mail.seyirmobil.com[213.14.26.62]; from=<web@seyirmobil.com> to=<username@domain.com> proto=ESMTP helo=<mail.seyirmobil.com>
Dec 11 17:31:02 virt01 postfix/cleanup[14614]: 874984A0026: message-id=<3867480468-1724@mail.seyirmobil.com>
Dec 11 17:31:06 virt01 MailScanner[12270]: Requeue: 874984A0026.A10D5 to 4ED9B4A0028
Dec 11 17:31:06 virt01 MailScanner[12270]: MailWatch: Logging message 874984A0026.A10D5 to SQL
Dec 11 17:31:07 virt01 MailScanner[13560]: MailWatch: 874984A0026.A10D5: Logged to MailWatch SQL
Dec 11 17:31:06 virt01 MailScanner[12270]: Requeue: 874984A0026.A10D5 to 4ED9B4A0028
Dec 11 17:31:06 virt01 postfix/qmgr[26551]: 4ED9B4A0028: from=<web@seyirmobil.com>, size=51453, nrcpt=2 (queue active)
Dec 11 17:31:07 virt01 postfix/pipe[14632]: 4ED9B4A0028: to=<username@domain.com>, orig_to=<username@domain.com>, relay=dovecot, delay=4.8, delays=4.4/0/0/0.46, dsn=2.0.0, status=sent (delivered via dovecot service)
Dec 11 17:31:07 virt01 postfix/pipe[14631]: 4ED9B4A0028: to=<archive@domain.com>, relay=dovecot, delay=5.3, delays=4.4/0/0/0.96, dsn=2.0.0, status=sent (delivered via dovecot service)
Dec 11 17:31:07 virt01 postfix/qmgr[26551]: 4ED9B4A0028: removed

```

You can see in the logs that this user is not in the original To:.

How is this handled with mailing lists which contain multiple recipients per a single address ?

**Comment by xpufx** [comment]
I should also add that there's no mention of  archive@domain.com in any of the headers received by the username@domain.com user.

**Comment by Skywalker-11** [comment]
I guess that postfix adds the recipient defined by ALWAYS_BCC before it is scanned by mailscanner.
If you take a look at http://www.postfix.org/OVERVIEW.html section "How Postfix receives mail" you can see that the mail first enters the cleanup server and after that go to the incoming queue. The cleanup server does add missing headers and address rewriting and in this case the ALWAYS_BCC recipient as "To:" recipient to keep track where the server has to send the mail to:

> The cleanup(8) server implements the final processing stage before mail is queued. It adds missing From: and other message headers, and transforms addresses as described in the ADDRESS_REWRITING_README document. Optionally, the cleanup(8) server can be configured to do light-weight content inspection with regular expressions as described in the BUILTIN_FILTER_README document. The cleanup(8) server places the result as a single file into the incoming queue, and notifies the queue manager (see next section) of the arrival of new mail.

MailScanner uses the mail in the state of the incoming queue and as such already gets the meta information postfix added. As such the "To:" recipient information also contains the ALWAYS_BCC recipient.

Like with normal BCC in a mail the message headers (which are relayed to all recipients) do not contain the "BCC:" recipients but only the "To:", "Reply-To:" and similar. The BCC is handled internally by Postfix. It works the same way as ALWAYS_BCC.

**Comment by Skywalker-11** [comment]
@shawniverson do you know if the ALWAYS_BCC and BCC recipient can be differenciated by MailScanner?

**Comment by ghost** [comment]
@Skywalker-11 I'm not sure, but let me find out for certain.  I'll set an ALWAYS_BCC and run some tests.

**Comment by xpufx** [comment]
@Skywalker-11 Thank you for the explanation. 

>  Like with normal BCC in a mail the message headers (which are relayed to all recipients) do not contain the "BCC:" recipients but only the "To:", "Reply-To:" and similar. The BCC is handled internally by Postfix. It works the same way as ALWAYS_BCC.


Does this mean BCC emails would behave the same way? i.e reveal them to the recipients? (I will test that now).

**Comment by xpufx** [comment]
> Dec 12 08:59:08 virt01 MailScanner[1915]: MailWatch: Logging message 8AD294A0009.AA6BB to SQL
> Dec 12 08:59:08 virt01 MailScanner[1915]: MailWatch: Logging message D54884A000C.AA30F to SQL

A regular BCC has distinct message IDs as opposed to ALWAY_BCC that has the same message id. BCC works fine with mailwatch.

It looks like the issue might be the envelope being the same for ALWAYS_BCC.

**Comment by xpufx** [comment]
Now that I think about this a little bit more. I think even if we fixed this issue, we'd end up with the archive@domain.com emails cluttering the database/view. Since these are essentially duplicates and are subject to the same rules as the To: recipient(s), it would be more useful (and applicable to other scenarios) if one could define a list of email addresses to ignore and not log into the database.

This would probably go in MailWatch.pm sub MailWatchLogging .

**Comment by asuweb** [comment]
Another potential option for this (use case specific of course) is to use mailscanner's built in Mail Archiving functions - which may solve your issue as it moves the processing to mailscanner and not postfix.

**Comment by Skywalker-11** [comment]
> A regular BCC has distinct message IDs as opposed to ALWAY_BCC that has the same message id. BCC works fine with mailwatch.

It depends if your postfix is the first mail server that directly receives the mail from the client or it is some server in the middle/end. If it is the first server there is only a single mail id and a single entry in mailwatch and the to header "To:" field contains only the normal "To:" recipients (or non at all if all recipients are BCC) while the To: field displayed by mailwatch contains all recipients including the BCC ones:

Here from a mail with all BCC recipients (`verborgene empfaenger` means hidden recipients):
![grafik](https://user-images.githubusercontent.com/11180862/49884591-80a7c300-fe35-11e8-9cb2-5c6248beb69f.png)

The first mail server would then send separate mails to each recipient (To: or BCC or CC) as displayed by mailwatch. So if you send a mail eg. from a gmail account to multiple BCC recipients on your own server you would see seperate mails with separate ids for each recipient.

On the other hand if the MUA (eg. Thunderbird/Outlook) sends the mail to your own server (because it is defined as server for outbound mails) you would only see a single mail entry.

**Comment by xpufx** [comment]
> while the To: field displayed by mailwatch contains all recipients including the BCC ones:

Just to confirm, if the server is the final destination when the BCC arrives mailwatch will reveal the BCC users to the user in the To: field?

If yes, wouldn't this be considered an issue since we can allow users to log into the interface with their own username and password?

**Comment by xpufx** [comment]
> Another potential option for this (use case specific of course) is to use mailscanner's built in Mail Archiving functions - which may solve your issue as it moves the processing to mailscanner and not postfix.

@asuweb Thanks for this comment. I wasn't aware of MailScanner's archiving functionality. I already don't like ALWAYS_BCC so I am looking into this as we speak.

**Comment by Skywalker-11** [comment]
> Just to confirm, if the server is the final destination when the BCC arrives mailwatch will reveal the BCC users to the user in the To: field?
> 
> If yes, wouldn't this be considered an issue since we can allow users to log into the interface with their own username and password?

Yes and no. It depends if it is also the first receiving server. 

Lets assume this mail delivery: MUA->first.server->(someother.servers)->final.server
- first.server receives all BCCs and shows them in the To: field in MailWatch; removes BCC addresses from mail headers and replaces with some message like in the screenshot; send one mail each per recipient (no difference between BCC and To recipients)
- someother.servers/final.server receives one mail per recipient (BCC or To); mail headers contains regular To: recipients but no BCC recipients only the message from first.server

So if you have only a single mail server (first.server=final.server) and one of your own users send a mail then other users of your organization (if they are To: or BCC: recipient of that mail) can see the BCC recipients of that mail.

If the mail was send from outside your organization or you have an additional server in between the users won't be able to see the BCC.

If: MUA->first.server(only postfix relay)->second.server(with MW)->(someother.servers)->final.server
So you have a two server setup: one for your own users to send mails to (first.server) and an other server (second.server) which has mailscanner+mailwatch installed and all mails from first.server are relayed to second.server. The users would also not be able to see any BCC of any mails (not even their own) as there would be a single mail for each recipient as first.server would generate a different mail for each recipient (BCC or To)

**Comment by Skywalker-11** [comment]
@oktayaa if this explains is sufficient can we close this issue?

**Comment by xpufx** [comment]
Yes thank you.
