### ISSUE TITLE
rep_viruses.php

### ISSUE THREAD

**Issue by tgreggs** [mailwatch/1.2.0#1117]
MailWatch 1.2.10 rep_viruses.php does not include the code for Avast. Same with 1.2.11. Any chance that could be included?

**Comment by endelwar** [comment]
Can you provide a working regex or some meaningful output string from avast client?

**Comment by tgreggs** [comment]
Here is the output from a command line scan with the same scan options used by MailScanner wrapper for Avast:

scan -b -f -a message 

/var/spool/MailScanner/quarantine/20181207/A951D21208AF.A7C41/message   Other:Malware-gen [Trj]

**Comment by Skywalker-11** [comment]
Can you try adding the following at https://github.com/mailwatch/MailWatch/blob/1.2/mailscanner/rep_viruses.php#L108 

```
        case('avast'):
            $scanner[$vscanner]['name'] = 'Avast';
            $scanner[$vscanner]['regexp'] = "/(\S+) (\S+)/";
            break;
```
And at https://github.com/mailwatch/MailWatch/blob/1.2/mailscanner/functions.php#L236 add
```
            case 'avast':
                $regex = '/(\S+) (\S+)/';
                break;
```

Then check if it works correct?

**Comment by tgreggs** [comment]
Here is what the virus report now looks like.

[MailWatch Filter Report_ Virus Report.pdf](https://github.com/mailwatch/MailWatch/files/2663819/MailWatch.Filter.Report_.Virus.Report.pdf)

**Comment by Skywalker-11** [comment]
Can you check if the output for all malware that is found by avast match the pattern `<path> <type> [xxx]` especially the square brackets to distinct them from other messages.

**Comment by tgreggs** [comment]
It kind of seems like the way sophos and avast are logged by MailScanner could be part of the issue.  Am running both.

MailScanner 5.1.1 Postfix/Dovecot
MailWatch 1.2.10

MailScanner uses Sophos and Avast.  Notice in the logging the 1st two lines are Sophos results.  

Maillog:
Dec  4 18:54:23 mail MailScanner[6973]: >>> Virus 'Mal/Fareit-Q' found in file /var/pool/MailScanner/incoming/6973/CA20221208AC.A40F1/z1INVOICES.exe
Dec  4 18:54:23 mail MailScanner[6973]: >>> Virus 'Mal/Fareit-Q' found in file /var/pool/MailScanner/incoming/6973/CA20221208AC.A40F1/nINVOICES.zip/INVOICES.exe
Dec  4 18:54:23 mail MailScanner[6973]: Virus Scanning: Sophos found 2 infections
Dec  4 18:54:23 mail MailScanner[6973]: Avast::INFECTED::Win32:Trojan-gen
Dec  4 18:54:23 mail MailScanner[6973]: Avast::INFECTED::Win32:Trojan-gen
Dec  4 18:54:23 mail MailScanner[6973]: Virus Scanning: Avast found 2 infections
Dec  4 18:54:23 mail MailScanner[6973]: Infected message var came from
Dec  4 18:54:23 mail MailScanner[6973]: Infected message CA20221208AC.A40F1 came from 209.222.102.95
Dec  4 18:54:23 mail MailScanner[6973]: Virus Scanning: Found 4 viruses
Dec  4 18:54:23 mail MailScanner[6973]: Virus Scanning completed at 273477 bytes per second
Dec  4 18:54:23 mail MailScanner[6973]: Viruses marked as silent: Avast: found Win32:Trojan-gen in 1INVOICES.exe, Avast: found Win32:Trojan-gen in INVOICES.zip
Dec  4 18:54:23 mail MailScanner[6973]: Saved entire message to /var/spool/MailScanner/quarantine/20181204/CA20221208AC.A40F1
Dec  4 18:54:23 mail MailScanner[6973]: Saved infected "1INVOICES.exe" to /var/spool/MailScanner/quarantine/20181204/CA20221208AC.A40F1
Dec  4 18:54:23 mail MailScanner[6973]: Saved infected "INVOICES.zip" to /var/spool/MailScanner/quarantine/20181204/CA20221208AC.A40F1

The MailWatch message detail shows:
Report:	Avast: found Win32:Trojan-gen in 1INVOICES.exe MailScanner: Executable DOS/Windows programs are dangerous in email (1INVOICES.exe) No programs allowed (1INVOICES.exe)
Avast: found Win32:Trojan-gen in INVOICES.zip

Notice no mention of Sophos results in the message detail view in MW.

**Comment by ghost** [comment]
@tgreggs Those lines reveal that the text output from Sophos is not being parsed properly by MailScanner, probably because the output from sophos has changed over yesterday's versions.  We will need to update the sophos-wrapper and SweepViruses.pm code to parse Sophos properly.   If possible, I will need a sample raw output from a commandline sophos scan, unaltered and unfiltered, using the same command that the wrapper uses, to make the necessary changes.  I will also need to know your version of Sophos.

**Comment by ghost** [comment]
@tgreggs While we are at it, let's tackle Avast too and do the same thing.

**Comment by tgreggs** [comment]
OK this is for Sophos, Using SweepViruses.pm command options.  Will post Avast results next.
```
SAVScan virus detection utility
Copyright (c) 1989-2018 Sophos Limited. All rights reserved.

System time 01:55:49 PM, System date 10 December 2018

Product version           : 5.53.0
Engine version            : 3.74.2
Virus data version        : 5.57
User interface version    : 2.03.074
Platform                  : Linux/AMD64
Released                  : 13 November 2018
Total viruses (with IDEs) : 27178325

[root@mail CA20221208AC.A40F1]# savscan -sc -f -all -rec -ss -archive -cab -loopback --no-follow-symlinks --no-reset-atime -TNEF -di *
>>> Virus 'Mal/Fareit-Q' found in file /var/spool/MailScanner/quarantine/20181204/CA20221208AC.A40F1/1INVOICES.exe
>>> Virus 'Mal/Fareit-Q' found in file /var/spool/MailScanner/quarantine/20181204/CA20221208AC.A40F1/INVOICES.zip/INVOICES.exe
```

**Comment by tgreggs** [comment]
Avast 2.2.0
```
[root@mail CA20221208AC.A40F1]# scan -b -f -a *
/var/spool/MailScanner/quarantine/20181204/CA20221208AC.A40F1/1INVOICES.exe     Win32:Trojan-gen
/var/spool/MailScanner/quarantine/20181204/CA20221208AC.A40F1/INVOICES.zip      Win32:Trojan-gen
/var/spool/MailScanner/quarantine/20181204/CA20221208AC.A40F1/message   Win32:Trojan-gen
```

**Comment by ghost** [comment]
@tgreggs Thank you for the outputs.  I stand corrected.  They are being parsed properly by MailScanner.  The way they are being output to the mail log threw me. There seems to be a lack of consistency in the MailScanner code.

In ProcessSophosOutput
```
MailScanner::Log::InfoLog($logout);
```

In ProcessAvastOutput
```
MailScanner::Log::InfoLog("Avast::INFECTED::$threat");
```

**Comment by tgreggs** [comment]
So is the fix something you can facilitate with MailScanner dev team?  While on the topic, a wrapper and correct reporting for the current cloud controlled BitDefender linux command line scanner would be super nice.  It seems to have a better detection rate than sophos or avast.  It catches things on workstations regularly that the others miss.

We are willing to buy the dev team a 1 yr license for BitDefender if that would get the ball rolling.

**Comment by ghost** [comment]
@tgreggs Happy to help. I'll stand by on this specific issue in case I'm needed. (I apologize for jumping in...)  Right now I think getting MailWatch to display the Avast stuff is the topic.  Hopefully @Skywalker-11 has some insight based on your additional outputs.

Please open a new issue for BitDefender over at MailScanner and we can discuss.

**Comment by Skywalker-11** [comment]
@shawniverson does MS use a relative or absolute path as parameter for the scans?

**Comment by ghost** [comment]
@Skywalker-11 To get to the scan binary and the files to scan, it uses an absolute path.

**Comment by Skywalker-11** [comment]
This may work: https://github.com/mailwatch/MailWatch/blob/1.2/mailscanner/rep_viruses.php#L108
```
        case('avast'):
            $scanner[$vscanner]['name'] = 'Avast';
            $scanner[$vscanner]['regexp'] = "/^(\/\S+)\s+(\S+)/";
            break;
```
And at https://github.com/mailwatch/MailWatch/blob/1.2/mailscanner/functions.php#L236 
```
            case 'avast':
                $regex = '/^(\/\S+)\s+(\S+)/';
                break;
```

**Comment by tgreggs** [comment]
> @tgreggs Happy to help. I'll stand by on this specific issue in case I'm needed. (I apologize for jumping in...) Right now I think getting MailWatch to display the Avast stuff is the topic. Hopefully @Skywalker-11 has some insight based on your additional outputs.
> 
> Please open a new issue for BitDefender over at MailScanner and we can discuss.

Will do Shawn, sorry been a little hammered today with things that are paying the bills :)

**Comment by tgreggs** [comment]
> case 'avast': $regex = '/^(\/\S+)\s+(\S+)/'; break;

That does not fix the virus report.  No avast matches at all with that.  I posted a PDF above that shows the virus report output with the prior recommendation which did have output but incorrectly populated.

**Comment by tgreggs** [comment]
Just to reiterate, message detail shows what avast found not what sophos has found.  Virus report shows what sophos found but not avast.  The bitdefender subject will get opened as a new case with the MS group.

**Comment by Skywalker-11** [comment]
> That does not fix the virus report. No avast matches at all with that. I posted a PDF above that shows the virus report output with the prior recommendation which did have output but incorrectly populated.

Thats what I would have expected if there are no entries from avast at all the database. The previous once from "avast" were probably false positive matches because the check could find a matching pattern in the sophos reports. 

Can you try adding the following before the foreach https://github.com/mailwatch/MailWatch/blob/1.2/mailscanner/rep_viruses.php#L134:

```
echo $row->report . "____";
```

This will print the raw data for the virus reports from the database on the website (each entry devided by `____`). Try to send a mail with a virus eg. EICAR and check if the output contains an entry with two detections. The entry for the newest mail should be at the end. If there is no such entry it could be an issue with MailScanner

**Comment by Skywalker-11** [comment]
@tgreggs Can you post the output from my comment above?

**Comment by tgreggs** [comment]
Jan 14 08:16:37 mail MailScanner[4896]: >>> Virus 'EICAR-AV-Test' found in file /var/pool/MailScanner/incoming/4896/B045521208A8.A857A/neicar.com
Jan 14 08:16:37 mail MailScanner[4896]: Virus Scanning: Sophos found 1 infections
Jan 14 08:16:37 mail MailScanner[4896]: Avast::INFECTED::EICAR Test-NOT virus!!!
Jan 14 08:16:37 mail MailScanner[4896]: Virus Scanning: Avast found 1 infections
Jan 14 08:16:37 mail MailScanner[4896]: Infected message B045521208A8.A857A came from 76.229.242.250
Jan 14 08:16:37 mail MailScanner[4896]: Infected message var came from
Jan 14 08:16:37 mail MailScanner[4896]: Virus Scanning: Found 2 viruses
Jan 14 08:16:37 mail MailScanner[4896]: Virus Scanning completed at 479 bytes per second
Jan 14 08:16:37 mail MailScanner[4896]: Viruses marked as silent: Avast: found EICAR Test-NOT virus!!! in eicar.com
Jan 14 08:16:37 mail MailScanner[4896]: Saved entire message to /var/spool/MailScanner/quarantine/20190114/B045521208A8.A857A
Jan 14 08:16:37 mail MailScanner[4896]: Saved infected "eicar.com" to /var/spool/MailScanner/quarantine/20190114/B045521208A8.A857A

**Comment by Skywalker-11** [comment]
@tgreggs I was referring to https://github.com/mailwatch/MailWatch/issues/1117#issuecomment-446424760. So not the log output but the debug output on the MailWatch rep_viruses page

**Comment by tgreggs** [comment]
____Avast: found EICAR Test-NOT virus!!! in eicar.com MailScanner: Executable DOS/Windows programs are dangerous in email (eicar.com) ____Avast: found EICAR Test-NOT virus!!! in eicar.com MailScanner: Executable DOS/Windows programs are dangerous in email (eicar.com) ____

**Comment by Skywalker-11** [comment]
@tgreggs Can you check #1133?

**Comment by tgreggs** [comment]
I implemented the changes, rep_viruses page was showing the sophos matches correctly previously, now it isn't.  Avast was not showing matches in rep_viruses previous, now it does but they are garbled up.  Sophos is free for you to implement on your end, Avast is not.

**Comment by Skywalker-11** [comment]
what do you mean by `now it does but they are garbled up`? can you give a screenshot?

**Comment by Skywalker-11** [comment]
As for the sophos results not showing up does changing `/>>> Virus \'(?P<virus>\S+)\' found in (?P<file>.*)/` to `/>>> Virus \'(?P<virus>\S+)\' found/` help?

**Comment by tgreggs** [comment]
Business is closing for the day in a few minutes.  Let me get everyone out and I will go back to altered functions.php and re_viruses and get some screen shots for you both ways.

**Comment by tgreggs** [comment]
So here is a before alterations screen shot.  I am running Sophos and Avast but not Clam on this server.

![screenshot 2019-01-14 17 54 18](https://user-images.githubusercontent.com/43651880/51149037-fda7cd00-1825-11e9-95b7-ac92f111053e.png)

**Comment by tgreggs** [comment]
Didn't mean to close the issue.

**Comment by tgreggs** [comment]
Skywalker-11: Can you provide your modified functions.php and rep_viruses.php so I can temp replace the existing scripts and provide you with the results?

**Comment by tgreggs** [comment]
Michael: I sent you an email off list.  It explains why, confidentiality issues etc.

**Comment by ghost** [comment]
This PR may be of interest concerning Sophos:

https://github.com/MailScanner/v5/pull/351

**Comment by tgreggs** [comment]
> This PR may be of interest concerning Sophos:
> 
> [MailScanner/v5#351](https://github.com/MailScanner/v5/pull/351)

Thanks Shawn.

**Comment by ghost** [comment]
@tgreggs Refactored that PR...https://github.com/MailScanner/v5/pull/353

**Comment by ghost** [comment]
Hi!

ESET is also not included here.

**Comment by tgreggs** [comment]
This on the last real virus detected today.

 ____Sophos: >>> Virus 'Troj/DocDl-RJO' found in file /var/spool/MailScanner/incoming/10849/D27CF21200E0.A46CD/DOC-651252.doc Avast: found Other:Malware-gen [Trj] in DOC-651252.doc ____

**Comment by Skywalker-11** [comment]
@shawniverson is the name of the virus scanner always in front of the report for all virus scanners?

**Comment by ghost** [comment]
@Skywalker-11 I believe that is true.

**Comment by ghost** [comment]
@Skywalker-11 Is the absolute path in the virus report a potential problem for Sophos?

**Comment by Skywalker-11** [comment]
@shawniverson Absolute path makes no defference there. But it could help if the reports of different scanners could be seperated somehow. Especially if I look at the regex for the other scanners that can take anything with `.*` including the output of the previous or following scan output. And currently the only ways to somehow seperate these would be to match for `ScannerName: ` as the start of a report and also prevent this as the end of the report. Something like `Avast: ((?! (MailScanner|Avast|Sophos|....):).)*`. Hoping none of the scanners have their own name followed by `:` inside their reports...

**Comment by ghost** [comment]
@Skywalker-11 https://github.com/MailScanner/v5/issues/355
