### ISSUE TITLE
Recipient notifications

### ISSUE THREAD

**Issue by funtomko** [mailwatch/1.2.0#1121]
MailWatch Version: 1.2.8, Operating System Version: CentOS Linux 7 (Core), Postfix Version: 2.10.1,PHP Version: 5.4.16, MySQL Version: 5.5.56-MariaDB

Hello,

we have configured some blocked extensions in filename.rules.conf. If recipient gets email with such unallowed attachment it's blocked and replaced with warning message from report stored.filename.message.txt.
I would like to configure same thing for messages containing viruses. For now when somebody gets message containing virus the whole message is blocked not just the infected attachment and there is no notification about blocked message to the recipient. I found in reports also stored.virus.message.txt which is exactly what I need to be used but I don't know how to fire up this trigger.
I looked for the option how to turn on these notifications but was not successful. Could you please advice?

in MailScanner.conf we have set
Quarantine Infections = yes
Quarantine Silent Viruses = yes
Quarantine Modified Body = yes
Quarantine Whole Message = yes
Quarantine Whole Messages As Queue Files = no
Stored Virus Message Report = %report-dir%/stored.virus.message.txt
Virus Subject Text = {Virus?}

Thank you

**Comment by Skywalker-11** [comment]
@funtomko This sounds like its a configuration problem with MailScanner. Please create an issue on https://github.com/MailScanner/v5
Or maybe @shawniverson can give an advise?

**Comment by ghost** [comment]
@funtomko Is this set to yes?  By default all viruses are treated as "Silent Viruses."

```
# Still deliver (after cleaning) messages that contained viruses listed
# in the above option ("Silent Viruses") to the recipient?
# Setting this to "yes" is good when you are testing everything, and
# because it shows management that MailScanner is protecting them,
# but it is bad because they have to filter/delete all the incoming virus
# warnings.
#
# Note: Once you have deployed this into "production" use, you should set
# Note: this option to "no" so you don't bombard thousands of people with
# Note: useless messages they don't want!
#
# This can also be the filename of a ruleset.
Still Deliver Silent Viruses = yes
```

**Comment by funtomko** [comment]
Thanks for the reply @Skywalker-11 and @shawniverson . I have set this option "Still Deliver Silent Viruses = yes" before it was "no" and the result is almost OK. I got the email with {Virus?} in subject and infected attachment is replaced by "Malware Alert Text.txt" which conatins a text`Malware was detected in one or more attachments included with this email message.
Action: All attachments have been deleted.
201811rechnung_6402634317.docx	O97M/Obfuse.CB`
This is not exactly the message from the report "stored.virus.message.txt" and I can't find this report/template.
In mailwatch I can see this info `Report: Clamd: 201811rechnung_6402634317.docx was infected: Doc.Malware.Generic-6782748-0`
If the file is blocked due to filename (extension) then in Mailwatch I can see `Report: MailScanner: We are blocking .doc files which may contain macro viruses (ACC_362648.doc)`.
Do you have any ide hwo to make use report "stored.virus.message.txt" or where to find template for "Malware Alert Text.txt"
Thank you

**Comment by ghost** [comment]
@funtomko Okay, I jumped into the code...

```
my $storeme = 0;
  $storeme = 1
    if MailScanner::Config::Value('quarantineinfections', $this) =~ /1/;
  #print STDERR "StoreMe = $storeme\n";
  # Cancel the storage if it is silent and no-one wants it quarantined
  $storeme = 0 if $this->{silent} && !$this->{noisy} &&
                  MailScanner::Config::Value('quarantinesilent', $this) !~ /1/;
```

Which means if ...

```
Quarantine Infections = yes
Quarantine Silent Viruses = yes
```

$storeme should be 1, which should select stored.virus.message.txt not the deleted message.

What do you get when you run these?

```
/usr/sbin/ms-peek quarantineinfections /etc/MailScanner/MailScanner.conf
/usr/sbin/ms-peek quarantinesilent /etc/MailScanner/MailScanner.conf
```

**Comment by funtomko** [comment]
@shawniverson 

I have set exactly same
Quarantine Infections = yes
Quarantine Silent Viruses = yes

I got "yes" when I ran `/usr/sbin/ms-peek quarantineinfections /etc/MailScanner/MailScanner.conf`
and got nothing when ran `/usr/sbin/ms-peek quarantinesilent /etc/MailScanner/MailScanner.conf`
So this is the problem?

The message which I get when I receive virus is not from deleted.virus.message.txt report but maybe some Clamav template? Just guessing.

Thank you

**Comment by ghost** [comment]
@funtomko Yes without this setting you are not getting the desired effect.  What version of MailScanner are you using?

Also, what do you get when you run this?

```
grep QuarantineSilent /usr/share/MailScanner/perl/MailScanner/ConfigDefs.pl
grep quarantinesilent /usr/share/MailScanner/perl/MailScanner/ConfigDefs.pl
```

**Comment by funtomko** [comment]
@shawniverson, version 5.0.7-2 
hi, here is the output from first
`QuarantineSilent        0       no      0       yes     1`
and second command
`quarantinesilent                = quarantinesilentviruses`

**Comment by ghost** [comment]
@funtomko I'm stratching my head.  If...

```
/usr/sbin/ms-peek quarantinesilent /etc/MailScanner/MailScanner.conf
```
Is not returning anything, and based on the info you have shared with me, something may be wrong somewhere in your config file, but I have no idea where...

**Comment by Skywalker-11** [comment]
Maybe just try `grep -r -i "Quarantine Silent" /etc/MailScanner/` to find all occurences and see if this returns something different?

**Comment by funtomko** [comment]
@Skywalker-11 
Hi guys, the above command from Skywalker-11 returned only this  `/etc/MailScanner/MailScanner.conf:Quarantine Silent Viruses = yes`

@shawniverson - yes, there is nothing in output
[root@ MailScanner]# /usr/sbin/ms-peek quarantinesilent /etc/MailScanner/MailScanner.conf

[root@ MailScanner]# grep QuarantineSilent /usr/share/MailScanner/perl/MailScanner/ConfigDefs.pl
QuarantineSilent        0       no      0       yes     1

[root@ MailScanner]# /usr/sbin/ms-peek quarantineinfections /etc/MailScanner/MailScanner.conf
yes

**Comment by ghost** [comment]
@funtomko If you do this (with curl installed)

```
curl https://raw.githubusercontent.com/MailScanner/v5/master/common/etc/MailScanner/MailScanner.conf > ~/MailScanner.conf
/usr/sbin/ms-peek quarantinesilent ~/MailScanner.conf
```

What do you get?

**Comment by funtomko** [comment]
Hi @shawniverson, I got the same

[root@]# curl https://raw.githubusercontent.com/MailScanner/v5/master/common/etc/MailScanner/MailScanner.conf > ~/MailScanner.conf
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  145k  100  145k    0     0   312k      0 --:--:-- --:--:-- --:--:--  314k
[root@]# /usr/sbin/ms-peek quarantinesilent ~/MailScanner.conf

[root@]#

**Comment by Skywalker-11** [comment]
@shawniverson I get the same with MS 5.1.1 ms-peek for `quarantinesilent` returns empty result while `quarantinesilentviruses` returns the actual config that is set in .conf files (MailScanner.conf or in conf.d/*). Also when adding an entry like `Quarantine Silent = bla` in the conf files it is found by ms-peek

**Comment by ghost** [comment]
@Skywalker-11 @funtomko I see that.  It appears that ConfigDefs.pl isn't loading, at least for ms-peek.  I am going to see if that is also true with the config call internally.  This could potentially be part of a much bigger problem...

**Comment by funtomko** [comment]
@Skywalker-11 @shawniverson 
I have another issue. I wanted to block macros so I set this:
`OLE2BlockMacros yes`
After this setting I can see in mailwatch message "Virus (Clamd: Subor s makrom.doc was infected: Heuristics.OLE2.ContainsMacros" but it is normally delivered to mailbox with attachment, only in Subject is addedd "{Virus?}" Is this normal behaviour? I tried the same with other infected file (Doc.Malware.Generic-6782748-0) and the attachment was blocked and replaced with warning mesage. So what is the difference. Both messages are clasified as Viruses, but attachment with Heuristics.OLE2.ContainsMacros is delivered to inbox. Thank you for your help.

**Comment by funtomko** [comment]
@shawniverson 

Hi, I red the new topic "ConfigDefs.pl not being parsed when using ms-peek" and seems that is not a bug. So do you have any why mailscanner is not using "stored.virus.message.txt" ?

What about my other issue with delivering Virus attachments (Heuristics.OLE2.ContainsMacros), should I open new thread? Thanks is andvance.

**Comment by ghost** [comment]
@funtomko Still trying to figure out what is going on here...haven't had much time due to my day job to go deep with this yet...

**Comment by ghost** [comment]
Ok, revisited this.  Just a note about the above conversation, ms-peek does not use the internal names in ConfigDefs.pl, just the full length regular config entry names.  That was my mistake.

It is impossible, despite the MailScanner.conf comments implying message cleaning to get the virus warning message on a attachment/message marked as a Silent Virus.

Here's my relevant config that is working.  Notice that I removed "All-Viruses" from the Silent Viruses section and turned off silent virus settings.

```
Mark Infected Messages = yes
Deliver Disinfected Files = no
Silent Viruses = HTML-IFrame
Still Deliver Silent Viruses = no
Quarantine Infections = yes
Quarantine Silent Viruses = no
Quarantine Denial Of Service = yes
Quarantine Modified Body = no
Quarantine Whole Message = yes
Quarantine Whole Messages As Queue Files = no
Stored Virus Message Report        = %report-dir%/stored.virus.message.txt
Virus Subject Text = {Virus?}
```
