### ISSUE TITLE
Blank report Total Messages by Date if not entered single day

### ISSUE THREAD

**Issue by e-fik123** [mailwatch/1.2.0#1126]
### Issue summary
In report Total Messages by Date i must enter filter "date is equal to " yyyy-mm-dd, if no filter entered of filter with date and condition any other then "is equal to" report screen is returned blank
### Steps to reproduce
1. No filter used / or / filter date higher then yyyy-mm-dd (in the past)
2. click Total Messages by Date
3. Empty report screen

### Expected result
Report with multidates displayed

### Actual result
Empty screen

### Version and method
 - MailWatch Version: 1.2.12
 - Install type: zip
 - Updated from an older MailWatch or fresh install: Upgrade from version [ v1.2.10 ])

### Server configuration
 - Operation System: Ubuntu 18.04.1 LTS (Bionic Beaver)
 - PHP version: 7.2.10-0ubuntu0.18.04.1
 - Database: 5.7.24-0ubuntu0.18.04.1
 - Mail Server: Postfix 
 - Used web server: Nginx 1.14.0

### Client configuration 
 - Browser: Firefox, Chrome, Safari, Internet explorer

###Error log:
Stack trace:
#0 /var/www/html/MailWatch/mailscanner/functions.php(1046): mysqli->query('\n SELECT\n  DATE...')
#1 /var/www/html/MailWatch/mailscanner/graphgenerator.inc.php(194): dbquery('\n SELECT\n  DATE...')
#2 /var/www/html/MailWatch/mailscanner/graphgenerator.inc.php(94): GraphGenerator->prepareData()
#3 /var/www/html/MailWatch/mailscanner/rep_total_mail_by_date.php(195): GraphGenerator->printLineGraph()
#4 {main}
  thrown in /var/www/html/MailWatch/mailscanner/functions.php on line 1046" while reading upstream, client: 127.0.0.1, server: mailwatch.domain.ltd, request: "GET /rep_total_mail_by_date.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.2-fpm.sock:", host: "mailwatch.domain.ltd", referrer: "https://mailwatch.domain.ltd/reports.php"
2019/01/04 10:17:18 [error] 1481#1481: *4749 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught mysqli_sql_exception: Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'mailscanner.maillog.date' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by in /var/www/html/MailWatch/mailscanner/functions.php:1046

**Comment by Skywalker-11** [comment]
@e-fik123 #1127 should fix this issue

**Comment by e-fik123** [comment]
Thank you this fixed the report. But i noticed one more issue in the graph section
Graph section does not display first colum of total emails for the first day, displays only total spam and volume for the first day (missing total emails), second day is fine, last day graph display only total emails and volume (missing total spam).
In the attached picture it can be noticed that first day should start with blue bar but starts with red (blue is missing), last day red bar is missing. In the graph there is only 6 days, but table shows 7 days.
If i use bar for volume graph shows all bars ok. See attached screenshots
<img width="940" alt="bar graph" src="https://user-images.githubusercontent.com/25080278/51076510-93622180-1699-11e9-8177-5b248f195136.png">
<img width="934" alt="wrong graph" src="https://user-images.githubusercontent.com/25080278/51076513-99f09900-1699-11e9-85dc-0ac58c721fa0.png">

**Comment by Skywalker-11** [comment]
Second part still not resolved. Working on it
