### ISSUE TITLE
PHP Notice and Warning from mailwatch_geoip_update.php

### ISSUE THREAD

**Issue by ghost** [mailwatch/1.2.0#1129]
### Issue summary
PHP Notice: Undefined variable: files in /usr/bin/mailwatch/tools/Cron_jobs/mailwatch_geoip_update.php on line 51
PHP Warning: Invalid argument supplied for foreach() in /usr/bin/mailwatch/tools/Cron_jobs/mailwatch_geoip_update.php on line 51

**Comment by endelwar** [comment]
It's a leftover from split ipv4 and ipv6 files.
I'm working on it

**Comment by endelwar** [comment]
I'm doing a small refactor of this cronjob script, I need a string translation from @Skywalker-11 , @stefaweb and  @rafaelbsd :
"**MailWatch sudoer /etc/sudoers.d/mailwatch file not found, check and set right permission on GeoLite2 files in**" /path/to/destination/files

**Comment by stefaweb** [comment]
Hi @endelwar!

Happy new year.

For French:

`Fichier MailWatch sudoer "/etc/sudoers.d/mailwatch" non trouvé. Vérifiez et définissez les autorisations appropriées sur les fichiers GeoLite2 dans /path/to/destination/files`

**Comment by Skywalker-11** [comment]
German: `MailWatch sudoer /etc/sudoers.d/mailwatch Datei nicht gefunden. Überprüfe und Setze gültige Berechtigungen für die GeoLite2-Dateien in /path/to/destination/files`

**Comment by endelwar** [comment]
Fixed in #1131
