### ISSUE TITLE
PHP Warning on logout

### ISSUE THREAD

**Issue by ghost** [mailwatch/1.2.0#1138]
### Issue summary
MailWatch --  PHP Warning: ini_set(): A session is active. You cannot change the session module's ini settings at this time in /var/www/html/mailscanner/logout.php on line 40, referer: https://xxxx/mailscanner/sf_version.php

Line 40:
```
    ini_set('session.cookie_httponly', 1);
```
Not sure if we can simply remove this line and move on or if we need to do something else here...

### Steps to reproduce
1. Log in
2. Log out

### Version and method
 - MailWatch Version: [ latest 1.2 develop ]

**Comment by asuweb** [comment]
I've commented it out, haven't found any issues with doing so yet
