### ISSUE TITLE
No environment when using php-fpm

### ISSUE THREAD

**Issue by dwhile** [mailwatch/1.2.0#1140]
### Issue summary
When running mailwatch on a system with apache and php-fpm by default php-fpm does not carry the environment through. This means that any execs (getting versions for example) don't work as the environment PATH variable is not set. so nothing is found.

This is not a bug in mailwatch but perhaps should go in the documentation somewhere as it took some time to find out what was going on.

The solution is to uncomment (remove the semi-colon) from the clear_env=no line in the www.conf of php-fpm and restart php-fpm. All works as it should then.

**Comment by ghost** [comment]
This is bad security practice, this should be done instead and the clear_env directive left alone...

```
env[PATH] = /usr/sbin;/usr/bin;/usr/local/bin;/usr/local/sbin;
```

**Comment by perplexityjeff** [comment]
Just to add to this in case of people searching for this the original error that we got in the interface for this was the following:

SA Learn Use of uninitialized value $ENV{"PATH"} in split /usr/lib/x86_64-linux-gnu/perl-base/File/Spec/Unix.pm on line 136.
