### ISSUE TITLE
MailWatch traffic grapch issuse

### ISSUE THREAD

**Issue by janarzz** [mailwatch/1.2.0#1145]
Hey,
when i upgrade my PHP to version PHP7.3.2, then MailWatch traffic graph use UTC timeformat ?
How i can fix this ?

My conf:
Ubuntu server 18.04.1
Apache 2.4.37
PHP 7.3.2
MailWatch version 1.2.10

Thnaks.

**Comment by Skywalker-11** [comment]
You can set these variables in the conf.php
```
// Set Time Zone
// See http://php.net/manual/en/timezones.php for a list of usable timezones.
define('TIME_ZONE', 'America/New_York');
// Date/Time settings
define('DATE_FORMAT', '%d/%m/%y');
define('TIME_FORMAT', '%H:%i:%s');
```

**Comment by janarzz** [comment]
Hey, its done, but still wrong timezone.
When i activate PHP7.2, then traffic graph correct.

**Comment by janarzz** [comment]
For now i get this errors:
Notice: session_start(): ps_files_cleanup_dir: opendir(/var/lib/php/sessions) failed: Permission denied (13) in /opt/mailwatch/MailWatch-1.2.10/mailscanner/functions.php on line 133

Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /opt/mailwatch/MailWatch-1.2.10/mailscanner/functions.php:133) in /opt/mailwatch/MailWatch-1.2.10/mailscanner/functions.php on line 133

Warning: Cannot modify header information - headers already sent by (output started at /opt/mailwatch/MailWatch-1.2.10/mailscanner/functions.php:133) in /opt/mailwatch/MailWatch-1.2.10/mailscanner/login.function.php on line 39

**Comment by endelwar** [comment]
It seems like a bug with php 7.3.2 packaged by Ondrej
https://bugs.php.net/bug.php?id=77582

Downgrade to 7.3.1 or latest 7.2 or wait for a PHP package rebuild by Ondrej
