### ISSUE TITLE
User should release dangerous content

### ISSUE THREAD

**Issue by ghost235** [mailwatch/1.2.0#1146]
Hi,

I know it is stupid!!!! But "customer is king..."

It is possible to make a "user" (not admin or domain admin) to be able to release dangerous content e.g. blocked attachments?

**Comment by ghost** [comment]
@ghost235 Customers may be kings, but developers are gods :rofl: 

It is possible, but I am against codifying such a thing in the official MailWatch codebase.

**Comment by ghost235** [comment]
@shawniverson I am of your opinion! But can you nonetheless tell me how?

**Comment by asuweb** [comment]
If you look at `detail.php` lines `559-563` you'll see how it is done for Domain Admins, and then you can modify to suit your requirements.

**Comment by ghost235** [comment]
all right.

A = Admin
D = Domain Admin
User = U ?
when it is so I've made a mistake :)

**Comment by ghost235** [comment]
Oh I think I've to edit line 507 - 511 also. Right ?

**Comment by asuweb** [comment]
Yes, correct
