### ISSUE TITLE
Uninitialized string offset: 0 in /opt/mailwatch/public/lib/pear/Mail/mimeDecode.php on line 483

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#1148]
### Version and method
 - MailWatch Version: 1.2.13

### Server configuration
 - Operation System: Debian Stretch
 - PHP version: 7.0
 - Database: MariaDB 10.1
 - Mail Server: Postfix
 - Used web server: Apache

Hi!

Found this when a message is blocked with  "MailScanner: Too many attachments in message" and when I click on viewmail.php (detail).

![sc1](https://user-images.githubusercontent.com/12907102/54997731-a9ab2880-4fcc-11e9-836d-e8ecc74488a2.png)

![sc2](https://user-images.githubusercontent.com/12907102/54997669-88e2d300-4fcc-11e9-912f-30e439081ab0.png)

**Comment by Skywalker-11** [comment]
How large is that mail including the attachments and how many of them are attached?

**Comment by stefaweb** [comment]
Hi @Skywalker-11 

I don't now for the moment exactly but many. The message is 15Mo large. The message seems to contains other messages in attachement with inside theses messages pdf and images files. I've the source of the message but I can't give it (confidential lawyer message).

I can't liberate the message right now. When I try to liberate it, I got this:

![sc3](https://user-images.githubusercontent.com/12907102/54999387-618e0500-4fd0-11e9-8267-488c897b5ae6.png)

The "attachment files" seems to be in the body as many ..png, .gif and .jpg images (the logo and footer of the message).

![sc4](https://user-images.githubusercontent.com/12907102/54999611-e4af5b00-4fd0-11e9-91dc-37d65d4cf77c.png)

The message is not well displayed in the MW GUI due to the php errors.

**Comment by stefaweb** [comment]
A screen shot off the message downloaded from quarantine folder and loaded in Outlook.

Very special this include of many message in the message. Each message contains tens of footer and header images (multiple reply inside the messages). hundreds of images finally.

People can do things that can not be imagined. ;-)

![Unknown](https://user-images.githubusercontent.com/12907102/55002070-3c03fa00-4fd6-11e9-9546-37878d61fec0.jpg)
