### ISSUE TITLE
Cannot open MailScanner configuration file

### ISSUE THREAD

**Issue by fgerrits** [mailwatch/1.2.0#1161]
### Issue summary
When login to the frontend, ill get the error presented 'Cannot open MailScanner configuration file'.
The Server is running with this configuration over a year, just 3 days ago when i want to login ill get this error.

In the maillog no errors also, i have checked all permissions on the folders and on the files.
All the files are in place where they belong.
No errors in the database mailscanner, all clean.

### Version and method
 - MailWatch Version: [ stable 1.2.x | RC-x | master | develop ]
 - Install type: [ GitHub checkout | Zip/tarball install  ]
 - Updated from an older MailWatch or fresh install: [ Fresh install ] (from version [ version ])

### Server configuration
 - Operation System: [ Ubuntur ] version [ 18.04.3 LTS‬ ]
 - PHP version: [ 7.1.33 ]
 - Database: [ MariaDB ] version [ 10.1.41 ]
 - Mail Server: [ Postfix  ]
 - Used web server: [ Apache  ] version [ 2.4.29 ]

### Client configuration 
 - Operation System: [ Windows 10 ] version [ 19.03 ]
 - Browser: [ Firefox 66.0.5 - Edge 44.18362.387.0 ]

![Schermafdruk 2019-11-06 14 03 00](https://user-images.githubusercontent.com/5964212/68300774-bcc3c200-009e-11ea-8f23-42269eeb9b1e.png)

**Comment by Skywalker-11** [comment]
Which version of MailWatch are you using?

**Comment by fgerrits** [comment]
MailWatch 1.2.12

**Comment by fgerrits** [comment]
I did do an upgrade also to check for error's, there were 2 Warnings.

It also shows that is reading the Mailscanner.conf file.

`root@one:/opt/mailwatch# php upgrade.php

MailWatch for MailScanner Database Upgrade to 1.2.12

Have you done a full backup of your database? Type 'yes' to continue: yes

Testing connectivity to the database ................................. OK

Updating database schema:

 - Convert database to utf8........................................... ALREADY DONE

 - Drop `geoip_country` table......................................... ALREADY DROPPED
 - Drop `spamscores` table............................................ ALREADY DROPPED
 - Add autorelease table to `mailscanner` database.................... ALREADY EXIST
 - Add mtalog_ids table to `mailscanner` database..................... ALREADY EXIST
 - Add resetid, resetexpire and lastreset fields in `users` table..... ALREADY EXIST
 - Add login_expiry and login_timeout fields in `users` table......... ALREADY EXIST
 - Add id field in `users` table...................................... ALREADY EXIST
 - Fix schema for type field in `users` table......................... OK

 - Fix schema for username field in `audit_log` table................. ALREADY DONE
 - Fix schema for id field in `blacklist` table....................... ALREADY DONE
 - Fix schema for id field in `whitelist` table....................... ALREADY DONE
 - Fix schema for username field in `users` table..................... ALREADY DONE
 - Fix schema for username field in `user_filters` table.............. ALREADY DONE
 - Fix schema for spamscore field in `users` table.................... ALREADY DONE
 - Fix schema for highspamscore field in `users` table................ ALREADY DONE
 - Fix schema for timestamp field in `maillog` table.................. ALREADY DONE
 - Fix schema for nameinfected in `maillog` table..................... ALREADY DONE
 - Fix schema for password field in `users` table..................... ALREADY DONE
 - Fix schema for fullname field in `users` table..................... ALREADY DONE
 - Fix schema for rule_desc field in `mcp_rules` table................ ALREADY DONE

 - Cleanup orphaned user_filters...................................... OK
 - Add id field and primary key to `audit_log` table.................. ALREADY DONE
 - Add inq_id field and primary key to `inq` table.................... ALREADY DONE
 - Add maillog_id field and primary key to `maillog` table............ ALREADY DONE
 - Add rblspamreport field to `maillog` table......................... ALREADY DONE
 - Add token field to `maillog` table................................. ALREADY DONE
 - Add released field to `maillog` table.............................. ALREADY DONE
 - Add last_update field to `maillog` table........................... ALREADY EXIST
 - Add salearn field to `maillog` table............................... ALREADY DONE
 - Check for missing tokens in `maillog` table........................ DONE
   0 token generated
 - Add mtalog_id field and primary key to `mtalog` table.............. ALREADY DONE
 - Add mtalog_id field and primary key to `outq` table................ ALREADY DONE
 - Add id field and primary key to `saved_filters` table.............. ALREADY DONE
 - Add mtalog_id field and primary key to `user_filters` table........ ALREADY DONE

 - Dropping too big index `maillog_from_idx` on table `maillog`....... ALREADY DONE
 - Dropping too big index `maillog_to_idx` on table `maillog`......... ALREADY DONE

 - Convert database to utf8mb4........................................ ALREADY DONE

 - Convert table `audit_log` to utf8mb4............................... ALREADY CONVERTED
 - Convert table `autorelease` to utf8mb4............................. ALREADY CONVERTED
 - Convert table `blacklist` to utf8mb4............................... ALREADY CONVERTED
 - Convert table `inq` to utf8mb4..................................... ALREADY CONVERTED
 - Convert table `maillog` to utf8mb4................................. ALREADY CONVERTED
 - Convert table `mcp_rules` to utf8mb4............................... ALREADY CONVERTED
 - Convert table `mtalog` to utf8mb4.................................. ALREADY CONVERTED
 - Convert table `mtalog_ids` to utf8mb4.............................. ALREADY CONVERTED
 - Convert table `outq` to utf8mb4.................................... ALREADY CONVERTED
 - Convert table `saved_filters` to utf8mb4........................... ALREADY CONVERTED
 - Convert table `sa_rules` to utf8mb4................................ ALREADY CONVERTED
 - Convert table `users` to utf8mb4................................... ALREADY CONVERTED
 - Convert table `user_filters` to utf8mb4............................ ALREADY CONVERTED
 - Convert table `whitelist` to utf8mb4............................... ALREADY CONVERTED

 - Convert table `audit_log` to InnoDB................................ ALREADY CONVERTED
 - Convert table `autorelease` to InnoDB.............................. ALREADY CONVERTED
 - Convert table `blacklist` to InnoDB................................ ALREADY CONVERTED
 - Convert table `inq` to InnoDB...................................... ALREADY CONVERTED
 - Convert table `maillog` to InnoDB.................................. ALREADY CONVERTED
 - Convert table `mcp_rules` to InnoDB................................ ALREADY CONVERTED
 - Convert table `mtalog` to InnoDB................................... ALREADY CONVERTED
 - Convert table `mtalog_ids` to InnoDB............................... ALREADY CONVERTED
 - Convert table `outq` to InnoDB..................................... ALREADY CONVERTED
 - Convert table `saved_filters` to InnoDB............................ ALREADY CONVERTED
 - Convert table `sa_rules` to InnoDB................................. ALREADY CONVERTED
 - Convert table `users` to InnoDB.................................... ALREADY CONVERTED
 - Convert table `user_filters` to InnoDB............................. ALREADY CONVERTED
 - Convert table `whitelist` to InnoDB................................ ALREADY CONVERTED

 - Search for missing indexes on table `maillog`...................... DONE

Checking for obsolete files:

 - Cache dir already removed.......................................... OK

Checking MailScanner.conf settings:

 - QuarantineWholeMessage ............................................ OK
 - QuarantineWholeMessagesAsQueueFiles ............................... OK
 - DetailedSpamReport ................................................ OK
 - IncludeScoresInSpamAssassinReport ................................. OK
 - SpamActions ....................................................... WARNING
 - HighScoringSpamActions ............................................ WARNING
 - AlwaysLookedUpLast ................................................ OK

Checking conf.php configuration entry:

 - All mandatory entries are present.................................. OK
 - All obsolete entries are already removed........................... OK
 - optional RPC_PORT ................................................. INFO
 - optional RPC_SSL .................................................. INFO
 - optional RPC_REMOTE_SERVER ........................................ INFO
 - optional VIRUS_REGEX .............................................. INFO
 - optional LDAP_BIND_PREFIX ......................................... INFO
 - optional LDAP_BIND_SUFFIX ......................................... INFO
 - optional EXIM_QUEUE_IN ............................................ INFO
 - optional EXIM_QUEUE_OUT ........................................... INFO
 - optional PWD_RESET_FROM_NAME ...................................... INFO
 - optional PWD_RESET_FROM_ADDRESS ................................... INFO
 - optional MAILQ .................................................... INFO
 - optional MAIL_SENDER .............................................. INFO
 - optional SENDMAIL_QUEUE_IN ........................................ INFO
 - optional SENDMAIL_QUEUE_OUT ....................................... INFO
 - optional MAILWATCH_SMTP_HOSTNAME .................................. INFO
 - optional ALLOW_NO_USER_DOMAIN ..................................... INFO
 - optional ENABLE_SUPER_DOMAIN_ADMINS ............................... INFO


 - Checking minimal PHP version >= 5.4................................ PHP version OK

*** ERROR/WARNING SUMMARY ***
MailScanner.conf: SpamActions != store (=deliver header "X-Spam-Status: Yes")
MailScanner.conf: HighScoringSpamActions != store (=delete)
conf.php: optional configuration entry "RPC_PORT" is missing, needed if RPC_ONLY mode is enabled
conf.php: optional configuration entry "RPC_SSL" is missing, needed if RPC_ONLY mode is enabled
conf.php: optional configuration entry "RPC_REMOTE_SERVER" is missing, needed to show number of mails in postfix queues on remote server (RPC)
conf.php: optional configuration entry "VIRUS_REGEX" is missing, needed in distributed setup
conf.php: optional configuration entry "LDAP_BIND_PREFIX" is missing, needed when using LDAP authentication
conf.php: optional configuration entry "LDAP_BIND_SUFFIX" is missing, needed when using LDAP authentication
conf.php: optional configuration entry "EXIM_QUEUE_IN" is missing, needed only if using Exim as MTA
conf.php: optional configuration entry "EXIM_QUEUE_OUT" is missing, needed only if using Exim as MTA
conf.php: optional configuration entry "PWD_RESET_FROM_NAME" is missing, needed if Password Reset feature is enabled
conf.php: optional configuration entry "PWD_RESET_FROM_ADDRESS" is missing, needed if Password Reset feature is enabled
conf.php: optional configuration entry "MAILQ" is missing, needed when using Exim or Sendmail to display the inbound/outbound mail queue lengths
conf.php: optional configuration entry "MAIL_SENDER" is missing, needed if you use Exim or Sendmail Queue
conf.php: optional configuration entry "SENDMAIL_QUEUE_IN" is missing, needed only if using Sendmail as MTA
conf.php: optional configuration entry "SENDMAIL_QUEUE_OUT" is missing, needed only if using Sendmail as MTA
conf.php: optional configuration entry "MAILWATCH_SMTP_HOSTNAME" is missing, needed only if you use a remote SMTP server to send MailWatch emails
conf.php: optional configuration entry "ALLOW_NO_USER_DOMAIN" is missing, allow usernames not in mail format for domain admins and regular users
conf.php: optional configuration entry "ENABLE_SUPER_DOMAIN_ADMINS" is missing, allows domain admins to change domain admins from the same domain
`

**Comment by asuweb** [comment]
Can you show the file permissions of the Mailscanner.conf file?  

`ls -l /etc/MailScanner/MailScanner.conf`

It runs from the command line as root, but not the webserver - this is most likely a file permission issue.

**Comment by fgerrits** [comment]
So this is not right ?

:~# ls -l /etc/MailScanner/MailScanner.conf
-rw-r--r-- 1 root root 149272 nov  6 01:28 /etc/MailScanner/MailScanner.conf

**Comment by Skywalker-11** [comment]
Can you also try 
`sudo -u www-data ls -l /etc/MailScanner/MailScanner.conf`
and  
`sudo -u www-data ls -l /etc/MailScanner/conf.d/*`

**Comment by fgerrits** [comment]
:~$ sudo -u www-data ls -l /etc/MailScanner/MailScanner.conf
-rw-r--r-- 1 root root 149272 nov  6 01:28 /etc/MailScanner/MailScanner.conf

~$ sudo -u www-data ls -l /etc/MailScanner/conf.d/*
-rw-r--r-- 1 root root 1126 jan 27  2019 /etc/MailScanner/conf.d/README

**Comment by Skywalker-11** [comment]
Is there anything the apache logs? 
Do you use AppArmor? If that is the case check the kernel logs if there is anything logged by it (`journalctl -k`)

**Comment by fgerrits** [comment]
Yes found it, finally the log files from apache were stored somewhere else on a plesk server.
There was an error about open_basedir (few days ago `file` was updated) and probably it was reset to standard settings.
Added `/etc/MailScanner/` to it and it works again.

Thanks guys for thinking with me.
