### ISSUE TITLE
Maxmind GeoLite2 Changes

### ISSUE THREAD

**Issue by ghost** [mailwatch/1.2.0#1165]
https://github.com/E-F-A/v4/issues/166

https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/

**Comment by ghost** [comment]
Timeline

December 23rd -- Begin refactor and test using license key
Before December 30th -- Push out refactor, notify community, and provide documentation

**Comment by Skywalker-11** [comment]
So if everything works as planned there will be <1 week to implement, test and deploy this and its holiday time....

**Comment by ghost** [comment]
@Skywalker-11 Appears that way, based on Maxmind's current plan.

**Comment by endelwar** [comment]
As of now (14:09 GMT) there is still no link to get a LicenseKey from MaxMind to start developing and testing a solution.

I think that the fix will be fair simple:
- create a new config variable MAXMIND_LICENSE_KEY
- If no MAXMIND_LICENSE_KEY, no download (maybe a warning in logs/root mail?)
- Put a warning if MAXMIND_LICENSE_KEY is missing on GeoIP update page
- Fix download link by adding MAXMIND_LICENSE_KEY [as stated here](https://dev.maxmind.com/geoip/geoipupdate/#Direct_Downloads)
- ML announcement and post on website

**Comment by ghost** [comment]
@endelwar Yes, my thoughts as well.  I will keep an eye on Maxmind.  Hopefully they will start allowing license keys so we can test this soon.

**Comment by oschwald** [comment]
The blog post has been updated with the new license and sign-up details.

**Comment by ghost** [comment]
@oschwald Sounds good.  I'll be on the road tonight, but I should have some time in the next couple of days to work on it.

**Comment by endelwar** [comment]
Tested direct download, it's working: this is the url:
https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country&license_key=XXXXXXXXXXX&suffix=tar.gz

**Comment by ghost** [comment]
Translations needed for geoipnokey15

https://github.com/mailwatch/MailWatch/pull/1166

**Comment by ghost** [comment]
PR #1166 ready for review and testing for the 1.2 branch.

**Comment by ghost** [comment]
Folks, are we still doing this?

https://support.maxmind.com/geolite-faq/general/what-do-i-need-to-do-to-meet-the-geolite2-attribution-requirement/

I recall seeing this exact message at one point, but I don't see it any longer?

**Comment by Skywalker-11** [comment]
We have a reference to MaxMind in the README.md but with other wording and without link and its missing entirely from docs.mailwatch.org

**Comment by Skywalker-11** [comment]
We are technically not distributing the GeoLite2 data itself but only providing the interface to use the data and download it. So attribution requirement in https://github.com/mailwatch/MailWatch/issues/1165#issuecomment-569418714 might not apply to MailWatch itself. 

When providing MailWatch as a service (and such using the GeoLite db) on the other hand it might be required to include such a notice.

The code we are using to download the GeoIp/GeoLite database and to interact with it is licensed under the Apache License or by the MailWatch team and as such probably wont't require the explicit wording.

**Comment by ghost** [comment]
@Skywalker-11 Good to know.

**Comment by endelwar** [comment]
> I recall seeing this exact message at one point, but I don't see it any longer?

I remember this to, but I don't remember removing it.
Adding it back doesn't harm anyone, I think
