### ISSUE TITLE
MailWatch message content access denied

### ISSUE THREAD

**Issue by janarzz** [mailwatch/1.2.0#1172]
Hey, i have problem with my MailWatch.
I cannot see my messages content.
I use MailWatch 1.2.15
Ubuntu server 18.04.4
Apacahe 2.4.41
mysql 14.14
Pic link: https://pilv.addit.ee/index.php/s/tG98qi7Zzd9JgmR

Thanks for help.

**Comment by Skywalker-11** [comment]
Is there anything in the apache log? The default path of it is `/var/log/apache2/error.log`

**Comment by janarzz** [comment]
apache log dont show nothing..

**Comment by Skywalker-11** [comment]
Does the hostname from that message match the fqdn of your MailWatch instance?

**Comment by janarzz** [comment]
Do you think pilv.addit.ee ?

**Comment by Skywalker-11** [comment]
`mail.addit.ee`

**Comment by janarzz** [comment]
> `mail.addit.ee`

Yes :)

**Comment by Skywalker-11** [comment]
Does this happen with every mail or only some of them and is that reproducible for a single mail/attachement combination?
The error message is the equivalent for `<host> refused to connect.`. So I think it might be a firewall issue or general connection problems.

**Comment by janarzz** [comment]
> Does this happen with every mail or only some of them and is that reproducible for a single mail/attachement combination?
> The error message is the equivalent for `<host> refused to connect.`. So I think it might be a firewall issue or general connection problems.

This happend every mails. Wierd..i have two servers with same conf. One works fine, but another this problem...i cannot understand..

**Comment by Skywalker-11** [comment]
Are both servers supposed to show up in the same MailWatch interface? If yes: what kind of cluster setup do you have?

**Comment by janarzz** [comment]
> Are both servers supposed to show up in the same MailWatch interface? If yes: what kind of cluster setup do you have?

Nope..i have two different servers, but same configuration and soft versions.

**Comment by janarzz** [comment]
Hey, finally i found log. I get this error:
[Fri Mar 27 12:49:36.574027 2020] [php7:notice] [pid 28482] [client 62.65.61.55:54701] PHP Notice:  Undefined index: country in /var/www/mailscanner/functions.php on line 3371

**Comment by Skywalker-11** [comment]
Make sure that you have a license key for MaxMind geoip in your conf.php `define('MAXMIND_LICENSE_KEY', 'mylicensekey');` and run mailwatch_geoip_update.php

**Comment by janarzz** [comment]
I have MaxMind license and update success.
Pic: https://pilv.addit.ee/index.php/s/Z7F6M3fAtJENeNb

**Comment by janarzz** [comment]
Maybe MailWatch 1.2.15 dont have full support PHP7.4 ?

**Comment by Skywalker-11** [comment]
Can you check the file permissions and size of the `GeoLite2-Country.mmdb` file?
It is located in the MailWatch directories subfolder `temp`. It should be owned by `www-data:www-data` , permission `rw-r--r--` and size ~3.7M

**Comment by janarzz** [comment]
> Can you check the file permissions and size of the `GeoLite2-Country.mmdb` file?
> It is located in the MailWatch directories subfolder `temp`. It should be owned by `www-data:www-data` , permission `rw-r--r--` and size ~3.7M

Geofile permission:
-rw-r--r-- 1 www-data www-data 3781378 märts 27 16:58 GeoLite2-Country.mmdb

**Comment by ghost** [comment]
@janarzz Are you using php-fpm, by chance?

**Comment by janarzz** [comment]
i dont know...how i can chechk this ?

**Comment by ghost** [comment]
@janarzz You would have specifically had to set it up, so I'm thinking it is not.  If you were, php-fpm runs under a different user context.

**Comment by janarzz** [comment]
php-fpm is required ?

**Comment by ghost** [comment]
@janarzz No, it is optional.

**Comment by janarzz** [comment]
i dont know..still this error:
 [php7:notice] [pid 21278] [client 62.653.64.55:61652] PHP Notice:  Undefined index: country in /opt/mailwatch/mailscanner/functions.php on line 3371

[php7:notice] [pid 21278] [client 62.653.64.55:61652] PHP Notice:  Trying to access array offset on value of type null in /opt/mailwatch/mailscanner/functions.php on line 3371

**Comment by ghost** [comment]
@janarzz  with those kind of errors, you need to double check your conf.php and make sure you have required settings defined properly.

**Comment by janarzz** [comment]
Hey, i think i find solution my problem.
X-frame options blocked my mailwatch message content.
I add .htaccess file this line: Header always unset X-Frame-Options
For now works fine :)
