### ISSUE TITLE
Block messages by Geo-IP

### ISSUE THREAD

**Issue by mmgomess** [mailwatch/1.2.0#1175]
I would like to suggest the option to block messages by Geo-IP using ISO 3166-1 country codes.

Thanks in advance.

Marcelo Gomes

**Comment by ghost** [comment]
This is something you can do in SpamAssassin already.  Were you thinking of something different?

**Comment by mmgomess** [comment]
Hello Shawn.

I know that SpamAssassin can do this with RelayCountryPlugin, but I would
like something that would really block messages and not just a score.

Marcelo

Em sáb., 16 de mai. de 2020 às 10:36, Shawn Iverson <
notifications@github.com> escreveu:

**Comment by endelwar** [comment]
> block messages by Geo-IP

I use csf firewall with maxmind database to block access to ports on server for countries that must not connect to them, i.e. block ssh access from outside Italy.

I don't think that this kind of feature belong to MailWatch, but to firewall config.
