### ISSUE TITLE
MailWatch web user

### ISSUE THREAD

**Issue by janarzz** [mailwatch/1.2.0#1184]
Hey, how i can create MailWatch web user ?
This command not works for me:
INSERT INTO users SET username = 'admin', password = MD5('<password>'), fullname = '<name>', type = 'A'
I use ubuntu server 20.04, mariaDB, mailwatch 1.2.15

**Comment by Skywalker-11** [comment]
Do you get any error message?

**Comment by janarzz** [comment]
I send you pic.
https://pilv.addit.ee/index.php/s/mtqy6AepZgzYdcX

**Comment by Skywalker-11** [comment]
there is an `;` missing at the end

**Comment by janarzz** [comment]
Many thnaks ;) Works ;)
