### ISSUE TITLE
Mailwatch message content

### ISSUE THREAD

**Issue by janarzz** [mailwatch/1.2.0#1185]
Hey,
i have problem with mailwatch message content.
I dont have quarantine box there..?
I send picture:
https://pilv.addit.ee/index.php/s/N3QftPb54FJBeXz

Conf: ubuntu server 20.04
         PHP 7.4
         MariaDB
         MailWatch 1.2.15
         MailScanner 5.3.3

**Comment by ghost** [comment]
@janarzz Did you get your issue resolved?

**Comment by janarzz** [comment]
Hey, yes. This problem has been rseolved.
