### ISSUE TITLE
Quarantine Report does not display quarantined spam when message sent to multiple recipients is quarantined as spam

### ISSUE THREAD

**Issue by gordoncolyn** [mailwatch/1.2.0#1188]
Hi,

The Quarantine Report that is emailed to users does not display the quarantined spam if a message is sent to multiple recipients and is quarantined as spam.  So emails are available to view in the web interface, however the email report does not show these emails as they have multiple recipients.

Server is running mailwatch v1.2.11 installed from zip on centos 7 server, php 7.3, mysql 5.7, postfix, apache

**Comment by Gatorfreak** [comment]
Still a problem in v1.2.15
