### ISSUE TITLE
Several Problems

### ISSUE THREAD

**Issue by eliwap** [mailwatch/1.2.0#1189]
From the Software Versions page

MailWatch Version: 1.2.15
Operating System Version: CentOS Linux 8 (Core)
Sendmail Version: sendmail not found
MailScanner Version: 5.3.3
ClamAV Version:
SpamAssassin Version: 3.4.4
PHP Version: 7.4.7
MySQL Version: 10.3.17-MariaDB
GeoIP Database Version: GeoLite2 Country database 2020-06-30 17:23:55

As you can see MailWatch can't see the sendmail version nor the ClamAV version.

When I try to see  Clam AV status I get a blank page.

sudo -u apache /usr/lib/MailScanner/wrapper/clamav-wrapper . /usr -V

produces:

sudo -u apache /usr/lib/MailScanner/wrapper/clamav-wrapper . /usr -V
mkdir: cannot create directory ‘/var/spool/MailScanner/incoming’: Permission denied
mktemp: failed to create directory via template ‘/var/spool/MailScanner/incoming/clamav-tmp/tmp.XXXXXXXXXX’: Permission denied
ERROR: Option --tempdir requires a non-empty string argument
ERROR: Can't parse command line options

Sorry about this old problem popping up again.

**Comment by Skywalker-11** [comment]
Can you run `ls -l /var/spool/MailScanner/` and `ls -l /var/spool/MailScanner/incoming`

**Comment by eliwap** [comment]
Thanks for your response :)

ls -l /var/spool/MailScanner/
total 0
drwxrwxr-x  2 root     mtagroup   6 May 25 23:14 archive
drwxrwx--- 11 clamscan clamscan 260 Jul  3 18:16 incoming
drwxrwxr-x  2 postfix  mtagroup   6 May 25 23:14 milterin
drwxrwxr-x  2 postfix  mtagroup   6 May 25 23:14 milterout
drwxrwxr-x  2 root     msusers    6 Jul  1 03:49 quarantine
drwxrwx---  8 clamscan clamscan 149 Feb 19 12:56 ramdisk_store

ls -l /var/spool/MailScanner/incoming
total 48
drwxrwx--- 2 clamscan clamscan    40 Jul  3 18:00 26441
drwxrwx--- 2 clamscan clamscan    40 Jul  3 18:16 26443
drwxrwx--- 2 clamscan clamscan    40 Jul  3 17:04 26935
drwxrwx--- 2 clamscan clamscan    40 Jul  3 17:25 27839
drwxrwx--- 2 clamscan clamscan    40 Jul  3 18:02 29434
drwxrwx--- 2 clamscan clamscan    40 Jul  3 17:51 30062
drwxr-xr-x 2 root     root        40 Jul  3 13:34 clamav-tmp
drwxr-xr-x 2 root     mail       200 Jul  3 12:46 Locks
-rw------- 1 root     mail     16384 Jul  3 18:16 Processing.db
-rw------- 1 root     mail     32768 Jul  3 18:16 SpamAssassin.cache.db
drwxr-xr-x 2 root     root        60 Jul  3 18:16 SpamAssassin-Temp

**Comment by ghost** [comment]
Replace all items with group "clamscan" with "mtagroup"

**Comment by eliwap** [comment]
OK.... Things are looking 1/2 way up :). Following your suggestion.... And continuing to travel the etheways.... I ran into this article.

https://github.com/MailScanner/v5/issues/308

It described what the permissions should be on that folder. I added apache to the mtagroup as well. Running

sudo -u apache /usr/lib/MailScanner/wrapper/clamav-wrapper . /usr -V
ClamAV 0.102.3/25858/Mon Jun 29 16:30:49 2020

Howeer, the clamav-status page is still blank

**Comment by ghost** [comment]
(removed tmpfiles.d suggestion not applicable)

**Comment by eliwap** [comment]
I'm not a programmer. So apologies in advance for my "smart ass" workaround and please forgive me if I'm presenting this in the wrong format but this worked.

I changed clamav_status.php from

    exec("which clamscan", $clamscan);
    if (isset($clamscan[0])) {
        passthru("$clamscan[0] -V | awk -f " . __DIR__ . '/clamav.awk');
    }

to

    $clamscan="/usr/bin/clamscan";
//    exec("which clamscan", $clamscan);
    if (isset($clamscan)) {
        passthru("$clamscan -V | awk -f " . __DIR__ . '/clamav.awk');
    }

**Comment by ghost** [comment]
That workaround will work, but your root issue is still permissions-related.  Either apache can't execute which or the which command can't return the path in the apache context.

**Comment by eliwap** [comment]
when I run: runuser -s /bin/bash apache

and then run: which clamscan

I get: /usr/bin/clamscan

which is correct. From here, I'm at a total loss

**Comment by ghost** [comment]
Check your php settings for exec restrictions.

**Comment by eliwap** [comment]
You are reading my mind.... lol.

I'm looking for it, but I can't seem to find where it is being disabled. Its not in php.ini nor php-fpm.conf files

**Comment by Skywalker-11** [comment]
You could also check if the apache server actually has the correct clamscan in the PATH variable when running php scripts:
Create a file eg. test.php in your MailWatch web directory with this content and open it with your browser:
```
<?php
var_dump($_SERVER['PATH']);

exec("which clamscan", $clamscan);
var_dump($clamscan);
```
The result should be something like `string(60) "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" array(1) { [0]=> string(17) "/usr/bin/clamscan" } `

Might also be apparmor or SELinux interfering

**Comment by eliwap** [comment]
Turns out to have been a different security feature.

I had to uncomment:
  clear_env = no
from
  /etc/php-fpm.d/www.conf
restart php-fpm and all was well.


Thank you so very very much for your assistance.

**Comment by ghost** [comment]
Just for post-mortem here.  Removing clear_env is not good practice.  It should be cleared then explicity set.
