### ISSUE TITLE
Mailwatch - Recent Messages page blank?  Nothing in quarantine list either

### ISSUE THREAD

**Issue by hepkat63** [mailwatch/1.2.0#1197]
Hi,
I've only just now installed MailScanner and Mailwatch onto my Centos 7 server.  It was a fresh install using all the latest version.
Mailscanner works perfectly.
Mailwatch loads in the GUI interface just fine once I log on - however, RECENT MESSAGES pages is blank - i.e loads no messages from log.
The quarantine list shows the dates on the folders , but NO messages within.
I've checked all the relevant paths in conf.php , and all seem ok.  Where else can I look please?  I followed the install guide from the Mailwatch website.

**Comment by ghost** [comment]
@hepkat63 Did you add and configure the Custom Functions for MailWatch in MailScanner?  Those would need copied to the CustomFunctions directory in MailScanner (typically /usr/share/MailScanner/perl/custom) and the file MailWatchConf.pm also configured with your database connection to log messages.

**Comment by hepkat63** [comment]
thanks Shawn for the reply.  yes, sure did.  I actually have gone through the whole procedure three times this weekend and i end up with the same result - 'recent messages' is not showing any messages, no logging to the mailscanner sql table and although I can see the quarantine dates, there is nothing in them (although there actually is).  I've tripled checked the install guide and everything is configured as per the mailscanner website - MTA (postfix) doc and the install doc on the Mailwatch site - along with extras to do for postfix.
I thought perhaps it could be permissions with mail log (/var/log/maillog) - but that's not it.  I thought maybe an issue with Perl - DBI::SQL (i think that's the name of it - but all the modules are loaded and working.
I also ran 'upgrade.php' several times in the mailwatch directory and it finds no faults either.   When I run MailScanner --lint - there are no issues listed and it says connects to database.
I am running Centos 7.3 and Php 7.4 if that helps?  I've been right through the maillog and messages log and can't see any problems jumping off the pages at me.
I 've googled all weekend and there are others have have had this issue, but no real solutions.
Just re-reading your question, I put a symlink to those files from my www directory - perhaps I should physically copy them over?  Not sure if it would make a difference though as --lint showed it reading them , so they must be working??
Really stuck :(

**Comment by ghost** [comment]
@hepkat63 Does your /var/log/maillog actually say that it is logging the messages to mysql when messages pass through MailScanner?

**Comment by hepkat63** [comment]
not that I can see - no.

**Comment by hepkat63** [comment]
Hey all,
so if this happens to anyone else - the problem was Encoding::FixLatin.  The /var/log/messages showed that MailWatch.pm could not be compiled due to this perl module.  The module was installed, working and loading fine.  I removed the module, reinstalled it, restarted services and now it's all good.
