### ISSUE TITLE
Logging of failed login attempts

### ISSUE THREAD

**Issue by tofuSCHNITZEL** [mailwatch/1.2.0#1201]
### Feature request summary
I would like to watch and ban failed login attempts to the mailwatch gui with fail2ban. 
To be able to do this Mailwatch should log failed attempts to a readable logfile (e.g. /var/log/mailwatch.log)
Is this already the case? Can it be configured? is there any other place failed login attempts are logged?

## Installation
MailWatch used by eFa

### Server configuration
 - Operation System: CentOS 8
 - PHP version:  7.1 
 - Database:  MySQL
 - Mail Server:  Postfix
 - Used web server:  Apache

**Comment by Skywalker-11** [comment]
At the moment failed logins aren't logged. You can patch your MailWatch instance for now by modifying
https://github.com/mailwatch/MailWatch/blob/a2c9c9d80266c2da48874ea62b0fc67f28b01754/mailscanner/checklogin.php#L81-L83
to
```
    } else {
        header('Location: login.php?error=emptypassword');
        error_log('MailWatch login failed for user: ' +$myusername);
        die();
```

This will write a message to the web servers error log on failed logins

**Comment by tofuSCHNITZEL** [comment]
Hi,
I refined the whole thing and created a pull request for it: https://github.com/mailwatch/MailWatch/pull/1202

**Comment by endelwar** [comment]
I've merged your patch @tofuSCHNITZEL, would you like to document fail2ban integration in a new PR?

**Comment by tofuSCHNITZEL** [comment]
@endelwar thanks for merging. I will implement a fail2ban filter for eFa and then I can try to document it in general. the big problem I see is that the place where php logs the error can be very different (fpm/cgi nginx/apache rpm/deb) so there might not be a "turnkey" way, (like there is for eFa because the os and parameters are mostly fixed)
