### ISSUE TITLE
PHP Fatal error:  Call to undefined function get_email() in /usr/local/bin/mailwatch_sendmail_relay.php on line 78

### ISSUE THREAD

**Issue by brettco** [mailwatch/1.2.0#1204]
### Issue summary
mailwatch sendmail relay stopped functioning.  This was working for a short time and stopped.  Nothing had been added to the system.
I find nothing regarding this in google searches, nor in closed issues here.  Any assistance is greatly appreciated.

### Steps to reproduce
1. Start mailwatch_sendmail_relay.php
2. 
3. 

### Expected result
No error and logging showing relay information in mailwatch
### Actual result
Throws error as listed and no logging and no relay information listing.  The email is logged and can be displayed but nothing for relay information.

### Version and method
 - MailWatch Version: v1.2.16
 - Install type: Zip/tarball install
 - fresh install

### Server configuration
 - Operation System: CentOS Linux release 7.9.2009 (Core)
 - PHP version: php-5.4.16-48.el7.x86_64
 - Database: mariadb-server-5.5.68-1.el7.x86_64
 - Mail Server: sendmail-8.14.7-6.el7.x86_64
 - Used web server: Apache httpd-2.4.6-97.el7.centos.x86_64

### Client configuration 
 - Operation System: windows
 - Browser: firefox, chrome, edge

Thank you

**Comment by ghost** [comment]
Can you change "get_email" on line 78 to "getEmail" instead and give it a try?

**Comment by brettco** [comment]
Similar result I'm afraid
PHP Fatal error:  Call to undefined function getEmail() in /usr/local/bin/mailwatch_sendmail_relay.php on line 78
Thank you

**Comment by shawniverson** [comment]
Is your mailwatch path properly defined at the top of the file if it isn't in the default path?

**Comment by ghost** [comment]
Ok, the getEmail function defined in mtalogprocessor.inc.php doesn't take an argument, and the get_email function as used here doesn't exist anywhere else, so I'm trying to find it in the git history.  You said this was originally working?

**Comment by ghost** [comment]
Okay I tracked it down, this code is wrong.  The line should read as follows:

```'status' => safe_value($this->entries['reject'])```

**Comment by brettco** [comment]
Thank you relay logging has returned  :)
Small issue now, more of an annoyance I guess.
This appears when I check the service status via systemctl 
PHP Notice:  Undefined index: reject in /usr/local/bin/mailwatch_sendmail_relay.php on line 71
Thank you

**Comment by ghost** [comment]
Ok, this needed more work.  Take a look at https://github.com/mailwatch/MailWatch/pull/1206/files

**Comment by brettco** [comment]
Fantastic
Thank you
