### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by alchemist18** [mailwatch/1.2.0#1205]
After following carefully the install guide (https://docs.mailwatch.org/install/installing.html) when I point my browser to http://my-mailwatch-virtualhost-address/ I am prompted for a download (it downloads the index,php file) instead of being prompt for the user name and password. 

### Version and method
 - MailWatch Version: stable 1.2.16
 - Install type: Zip/tarball install 
 - Fresh install

### Server configuration
 - Operation System: Ubuntu 18.04
 - PHP version: 7.2.24
 - Database: MySQL version 14.14
 - Mail Server:  Postfix 
 - Used web server: Apache 2.4.29 (Ubuntu)

### Client configuration 
 - Operation System: Ubuntu 18.04
 - Browser: chromium  86.0.4240.198 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)

**Comment by ghost** [comment]
Did you install and enable the php apache module?

**Comment by alchemist18** [comment]
No I didn't. I installed it and now it works!
Thanks!
