### ISSUE TITLE
Port Number for MySQL Database

### ISSUE THREAD

**Issue by markrochester** [mailwatch/1.2.0#1212]
I had a quick question around using a remote database for the logging of the mail coming through.

I have setup a remote server but it doesn't use port 3306 for security reasons.

In the configuration there is no designated port entry, and you cannot append it to the hostname for the connection.

So my question is, is there a way to use a remote server with a different port number in the current configuration.

Thanks,

Mark

**Comment by endelwar** [comment]
Hi Mark,

actually is not possible to define a non-standard port for MySQL, I'll add this functionality, it's trivial.

**Comment by endelwar** [comment]
@markrochester do you mind testing the PR?

**Comment by markrochester** [comment]
Excellent. Thank you very much. I will test it today.

**Comment by endelwar** [comment]
@markrochester how did the tests go?
