### ISSUE TITLE
Fix for making it work with PHP 8

### ISSUE THREAD

**Issue by deependhulla** [mailwatch/1.2.0#1218]
For making MailWatch work with Debian 11 and  PHP 8,  I had  Fixed few code-file to avoid error : 
PHP Fatal error:  Array and string offset access syntax.

Sharing below changes for users using with PHP8., Hopeful to update in new version or users trying to use MailWatch with PHP8.
-Deepen.

Changed in MailWatch-1.2.17/mailscanner/lib/ForceUTF8/Encoding.php
-----------------------------------------
196c196
<         $c1 = $text{$i};
---
>         $c1 = $text[$i];
198,200c198,200
<           $c2 = $i+1 >= $max? "\x00" : $text{$i+1};
<           $c3 = $i+2 >= $max? "\x00" : $text{$i+2};
<           $c4 = $i+3 >= $max? "\x00" : $text{$i+3};
---
>           $c2 = $i+1 >= $max? "\x00" : $text[$i+1];
>           $c3 = $i+2 >= $max? "\x00" : $text[$i+2];
>           $c4 = $i+3 >= $max? "\x00" : $text[$i+3];

-------------------------------------------------------
changed in MailWatch-1.2.17/mailscanner/filter.inc.php
-------------------------------------------------------
222c222
<         } elseif ($val[2]!=='' && $val[2]{0} === '!') {
---
>         } elseif ($val[2]!=='' && $val[2][0] === '!') {
-------------------------------------------------------

**Comment by deependhulla** [comment]
Thanks for Update of ForceUTF8 , suggested to update  MailWatch-1.2.17/mailscanner/filter.inc.php. (change of {} to [] )
 to support php 8 , else Error like : array and string offset access syntax with curly braces is no longer supported.

line : 222 
OLD : } elseif ($val[2]!=='' && $val[2]{0} === '!') {
NEW:  } elseif ($val[2]!=='' && $val[2][0] === '!') {

**Comment by endelwar** [comment]
In PR #1220 I've updated PEAR package to 1.10.13 which has better compatibility with PHP 7.4/8
