### ISSUE TITLE
How to configure Path message

### ISSUE THREAD

**Issue by ualace86** [mailwatch/1.2.0#1222]
I have installed Mailwatch 1.2.10 with CentOS 7
Everything working fine. In recent messages in column # I can open in Path Message only the emails that are classified as Spam. I would like to know how to configure to be able to read emails that are not being classified as spam as well.
How can I configure it?

Thanks!

**Comment by Skywalker-11** [comment]
The mails have to be store by mailscanner `Non Spam Actions = store deliver [....]`

**Comment by ualace86** [comment]
To explain better, when the message is spam I can open the email inside MailWatch as in this image: https://mega.nz/file/RF8BVCwD#qt0HU3aXtTfoaJQk90Gcc3nELLvUeazTcesMMaNpciE

But when the email is not spam I can't, as in this image: https://mega.nz/file/YQkDAYSQ#kYS1JSXuGqLwqEpo_DG-s1Yqade5wPr3d7mI4vlN_J8

I wish I could open the email too which is not spam

**Comment by Skywalker-11** [comment]
Yeah you have to have the `store` directive for the `Non Spam Actions` in your MailScanner config (/etc/MailScanner/MailScanner.conf or /etc/MailScanner/conf.d/* ). Otherwise MailScanner is not storing the mail and MailWatch can't display it

**Comment by ualace86** [comment]
Works fine!
Thanks!
