### ISSUE TITLE
Column length too big for column 'rule_desc' (max = 255); use BLOB or TEXT instead

### ISSUE THREAD

**Issue by rizkypratama01** [mailwatch/1.2.0#1223]
### Issue summary
Hi, i have new issue with mailwatch v1.2.17, when import create.sql to mysql, error like this

```
root@smtp1:/opt/mailwatch# mysql < create.sql 
ERROR 1074 (42000) at line 153: Column length too big for column 'rule_desc' (max = 255); use BLOB or TEXT instead
```

but when use mailwatch v1.2.16 no error found

is this still a possible bug in the latest version of mailwatch?

### Version and method
 - MailWatch Version: stable 1.2.17
 - Install type: Zip/tarball install
 - Updated from an older MailWatch or fresh install: Fresh install

### Server configuration
 - Operation System: Ubuntu 20.04.3
 - PHP version: 7.4
 - Database: MySQL 8.0.26-0 and MariaDB 10.3.31
 - Mail Server: Postfix
 - Used web server: Nginx 1.20.1

Any suggest for this issue? please help, thank you

**Comment by endelwar** [comment]
Both MySQL 5.7+ and MariaDB 10.3 supports VARCHAR size up to 65,535 bytes (max value per row is approximately half the size of innodb_page_size).
On MySQL 5.7.35 I have no error when importing create.sql

**Comment by bungee-** [comment]
Can confirm error on freshly installed Ubuntu 20.04.  - mysql 8.0.26-0ubuntu0.20.04.3 (Ubuntu)

My workaround is to change type from char to varchar. I don't find the reference right now, but historically char field is limited to 255 bytes and varchar 65535 bytes.

`sed -i 's/ char(512)/ varchar(512)/g' /opt/mailwatch/create.sql` is my temp fix for now.

Problematic part of create.sql:

```
CREATE TABLE IF NOT EXISTS 'mcp_rules' (
  'rule' char(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  'rule_desc' char(512) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  PRIMARY KEY ('rule')
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

```

Field is defined as char(512)

**Comment by endelwar** [comment]
You are both right! I used the development [create.sql](https://github.com/mailwatch/MailWatch/blob/1.2/create.sql) in my previous test, and not the one contained in the 1.2.17 release: I fixed this error some months ago, it's time for a new release I suppose.

**Comment by rizkypratama01** [comment]
Ahh you are right, looks like thats the problem, meanwhile, i'll follow your steps to temp fix, instead wait for the update from mailwatch developer, thank you

**Comment by endelwar** [comment]
Release 1.2.18 is ready: https://github.com/mailwatch/MailWatch/releases/tag/v1.2.18
