### ISSUE TITLE
Update failed

### ISSUE THREAD

**Issue by ghost235** [mailwatch/1.2.0#1225]
Hi,
I got an issue on updating 1.2.4 to 1.2.17 
### Issue summary
upgrade.php fail with 

PHP Warning:  Constants may only evaluate to scalar values in /opt/mailwatch/mailscanner/conf.php on line 116

MailWatch for MailScanner Database Upgrade to 1.2.17

Have you done a full backup of your database? Type 'yes' to continue: yes

Testing connectivity to the database ................................. OK

Updating database schema:

 - Convert database to UTF-8.......................................... ALREADY DONE

 - Fix security issues in database.................................... No known security issues

 - Drop `geoip_country` table......................................... ALREADY DROPPED
 - Drop `spamscores` table............................................ ALREADY DROPPED
 - Add autorelease table to `mailscanner` database.................... ALREADY EXIST
 - Add mtalog_ids table to `mailscanner` database..................... ALREADY EXIST
 - Add resetid, resetexpire and lastreset fields in `users` table..... ALREADY EXIST
 - Add login_expiry and login_timeout fields in `users` table......... ALREADY EXIST
 - Add id field in `users` table...................................... ALREADY EXIST
 - Fix schema for type field in `users` table......................... OK

 - Fix schema for username field in `audit_log` table................. ALREADY DONE
 - Fix schema for ipv6 support in `audit_log` table................... ALREADY DONE
 - Fix schema for id field in `blacklist` table....................... ALREADY DONE
 - Fix schema for id field in `whitelist` table....................... ALREADY DONE
 - Fix schema for username field in `users` table..................... ALREADY DONE
 - Fix schema for username field in `user_filters` table.............. ALREADY DONE
 - Fix schema for spamscore field in `users` table.................... ALREADY DONE
 - Fix schema for highspamscore field in `users` table................ ALREADY DONE
 - Fix schema for timestamp field in `maillog` table.................. ALREADY DONE
 - Fix schema for nameinfected in `maillog` table..................... ALREADY DONE
 - Fix schema for password field in `users` table..................... ALREADY DONE
 - Fix schema for fullname field in `users` table..................... ALREADY DONE
 - Fix schema for rule and rule_desc field in `mcp_rules` table....... ERROR
Database error: Specified key was too long; max key length is 767 bytes - SQL = 'ALTER TABLE `mcp_rules` CHANGE `rule` `rule` VARCHAR(255) NOT NULL DEFAULT '', CHANGE `rule_desc` `rule_desc` VARCHAR(512) NOT NULL DEFAULT '';'

### Version and method
 - MailWatch Version: 1.2.4
 - Install type:  Zip/tarball install
 - Updated from an older MailWatch or fresh install: Upgrade (from version 1.2.4)

### Server configuration
 - Operation System: Debian version 9
 - PHP version: 5.6.40-0+deb8u12
 - Database: MySQL version 5.6.48
 - Mail Server: Postfix
 - Used web server: Apache version  2.4.25

**Comment by Skywalker-11** [comment]
MariaDB >=10.2 or MySQL >= 5.7 should work. 
@endelwar due to https://github.com/mailwatch/MailWatch/commit/d4ccb5e497b5f39fd5d5bc801418ced6b548c84c#diff-dea6e5c43f67267b15b05bd95702fd29f4a146561e47dc7ca424832b6ee0ab20 the primary key would be 4x255=1020 bytes when using utf8mb4. Older MySQL/MariaDB versions only support primary key with < 767 Bytes. Either the minimum required sql server has to be changed (release notes/docs) or the varchar size has to be reduced to 191 (4x191=764)

**Comment by endelwar** [comment]
At this point, it is better to convert the `varchar(512)` into a `text` for maximum compatibility: rule descriptions don't need to be fully indexed.

Also, I see that on PHP 5.6 array const can't be arrays, so `TRUSTED_PROXIES` needs to be refactored.

**Comment by Skywalker-11** [comment]
Issue is the rule name (`rule` column). The `rule_desc` is not a primary key so the 191 byte restriction doesn't apply and size doesn't matter there.

Debian 9 LTS reaches EOL in juni 2022 (~8 month), but newer versions are available via sury packages. Debian 10 has PHP 7.3 support. 
Ubuntu 18.04 LTS (currently oldest still supported) has PHP 7.2. 
But RHEL 7 (EOL 2024) only has 5.4 in default repositories but at least 7.2 can be installed via RHSCL. RHEL 8 comes with at least PHP 7.3.

So maybe its time to require PHP >7 or use the following in `getHTTPClientIP` to disable the feature for PHP 5.x and add a notice in the conf to comment the TRUSTED_PROXIES out if PHP <7 is used
```
if (preg_match('/^5\./', phpversion())) {
  return $remote_addr;
}
```

**Comment by stefaweb** [comment]
Hi!

I've the same problem with upgrade.php and v18.

I also tried manually with phpmyadmin. Same problem.

` - Fix schema for rule and rule_desc field in `sa_rules` table........ ERROR
Database error: Index column size too large. The maximum column size is 767 bytes - SQL = 'ALTER TABLE `sa_rules` CHANGE `rule` `rule` VARCHAR(255) NOT NULL DEFAULT '', CHANGE `rule_desc` `rule_desc` VARCHAR(512) NOT NULL DEFAULT '''
`

Debian 10 Buster with MariaDB 10.4 et PHP 7.4.

**Comment by Fonant** [comment]
I've managed to get this to work on my servers by adding this to the MySQL/MariaDB config:

```
innodb_default_row_format = dynamic
```

Along with:

```
innodb_large_prefix = true
innodb_file_format = barracuda
innodb_file_per_table = true
```

which may or may not be needed too.

**Comment by stefaweb** [comment]
Hi!

One more related.

When we go to: https://localhost/sa_rules_update.php

We got on screen:

`Fatal error: Uncaught mysqli_sql_exception: Data too long for column 'rule_desc' at row 1 in /opt/mailwatch/public/functions.php:1048 Stack trace: #0 /opt/mailwatch/public/functions.php(1048): mysqli->query() #1 /opt/mailwatch/public/sa_rules_update.php(75): dbquery() #2 {main} thrown in /opt/mailwatch/public/functions.php on line 1048`

And at the end of the page:

![sc](https://user-images.githubusercontent.com/12907102/138452213-fd6b70cf-ad3c-4a7d-8f3c-0b18a64faef9.png)
