### ISSUE TITLE
Missing parts in HTMLPurifier with 1.2.18 source

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#1227]
Hi Folks,

After install of the v18 release the complete directory "DefinitionCache" for HTMLPurifier is missing.

With v17 release:

```
drwxrwxr-x 5 root root 4096 Feb 26  2021 ConfigSchema
drwxrwxr-x 3 root root 4096 Feb 26  2021 DefinitionCache
drwxrwxr-x 2 root root 4096 Feb 26  2021 EntityLookup
drwxrwxr-x 2 root root 4096 Feb 26  2021 Filter
drwxrwxr-x 4 root root 4096 Feb 26  2021 Language
drwxrwxr-x 2 root root 4096 Feb 26  2021 Lexer
drwxrwxr-x 2 root root 4096 Feb 26  2021 Printer
-rw-rw-r-- 1 root root 5897 Feb 26  2021 Printer.php
```

With v18 release:

```
drwxrwxr-x 5 root root 4096 Oct 19 10:45 ConfigSchema
drwxrwxr-x 2 root root 4096 Oct 19 10:45 EntityLookup
drwxrwxr-x 2 root root 4096 Oct 19 10:45 Filter
drwxrwxr-x 3 root root 4096 Oct 19 10:45 Language
drwxrwxr-x 2 root root 4096 Oct 19 10:45 Lexer
drwxrwxr-x 2 root root 4096 Oct 19 10:45 Printer
-rw-rw-r-- 1 root root 5860 Oct 19 10:45 Printer.php
```

We got this when accessing the GUI:

`Warning: Base directory /opt/mailwatch/public/lib/htmlpurifier/standalone/HTMLPurifier/DefinitionCache/Serializer does not exist, please create or change using %Cache.SerializerPath in /opt/mailwatch/public/lib/htmlpurifier/HTMLPurifier.standalone.php on line 15754`

**Comment by ghost** [comment]
Looks like the directory may have fell off when this file was removed in this commit? https://github.com/mailwatch/MailWatch/commit/6f8dadb90efcfe76db15afacff7da4b9451411af

mailscanner/lib/htmlpurifier/standalone/HTMLPurifier/DefinitionCache/Serializer/HTML/4.12.0,42d2529d2d2aa4f137a4d6d6292a92e3ee82eb86,1.ser
