### ISSUE TITLE
MailWatch Logger fails to log anything on first start

### ISSUE THREAD

**Issue by ghost** [mailwatch/1.2.0#1230]
### Steps to reproduce
1. Start mailscanner

### Expected result
MailWatch Logger should be sending info, warnings, etc. to syslog

### Actual result
Nothing is sent to syslog until after the Logger dies (3600 seconds later after idle) and is respawned

### Version and method
 - MailWatch Version: [ stable 1.2.17 ]
 - Install type: [ GitHub checkout ]
 - Updated from an older MailWatch or fresh install: [ Fresh install ])

### Server configuration
 - Operation System: [ AlmaLinux ] version [ 8 ]
 - PHP version: [ 7.2 ]
 - Database: [  MariaDB ] version [ 10.3.28 ]
 - Mail Server: [ Postfix ]
 - Used web server: [ Apache ] version [ 2.4.37 ]

**Comment by mbotebm** [comment]
I have run the php upgrade and it runs all through producing one warning and a few informational messages.  However despite this I am still unable to get the mailscanner to log the emails. Hope the below highlighted is not serious.

*** ERROR/WARNING SUMMARY ***
_**Table Index: MySQL version unsupported for index `subject_idx` on table `maillog`, upgrade to version >= 50604 (you have version 50568)**_
conf.php: optional configuration entry "RPC_PORT" is missing, needed if RPC_ONLY mode is enabled
conf.php: optional configuration entry "RPC_SSL" is missing, needed if RPC_ONLY mode is enabled
conf.php: optional configuration entry "RPC_REMOTE_SERVER" is missing, needed to show number of mails in postfix queues on remote server (RPC)
conf.php: optional configuration entry "VIRUS_REGEX" is missing, needed in distributed setup
conf.php: optional configuration entry "LDAP_BIND_PREFIX" is missing, needed when using LDAP authentication
conf.php: optional configuration entry "LDAP_BIND_SUFFIX" is missing, needed when using LDAP authentication
conf.php: optional configuration entry "PWD_RESET_FROM_NAME" is missing, needed if Password Reset feature is enabled
conf.php: optional configuration entry "PWD_RESET_FROM_ADDRESS" is missing, needed if Password Reset feature is enabled
conf.php: optional configuration entry "SESSION_NAME" is missing, needed if experiencing session conflicts
conf.php: optional configuration entry "MAILWATCH_SMTP_HOSTNAME" is missing, needed only if you use a remote SMTP server to send MailWatch emails
conf.php: optional configuration entry "ALLOW_NO_USER_DOMAIN" is missing, allow usernames not in mail format for domain admins and regular users
conf.php: optional configuration entry "ENABLE_SUPER_DOMAIN_ADMINS" is missing, allows domain admins to change domain admins from the same domain
