### ISSUE TITLE
Call to undefined routine when viewing message

### ISSUE THREAD

**Issue by dwhile** [mailwatch/1.2.0#1233]
### Issue summary
When attempting to open a message the message windows remain blank. This doesn't happen on every message so I suggest that it is to do with the encoding of the message. 

The following error details are in the log file.

[18-Nov-2021 17:52:50 Europe/London] PHP Fatal error:  Uncaught Error: Call to undefined function create_function() in /opt/mailwatch/mailscanner/lib/pear/Mail/mimeDecode.php:829
Stack trace:
#0 /opt/mailwatch/mailscanner/lib/pear/Mail/mimeDecode.php(802): Mail_mimeDecode->_quotedPrintableDecode()
#1 /opt/mailwatch/mailscanner/lib/pear/Mail/mimeDecode.php(316): Mail_mimeDecode->_decodeBody()
#2 /opt/mailwatch/mailscanner/lib/pear/Mail/mimeDecode.php(344): Mail_mimeDecode->_decode()
#3 /opt/mailwatch/mailscanner/lib/pear/Mail/mimeDecode.php(237): Mail_mimeDecode->_decode()
#4 /opt/mailwatch/mailscanner/viewpart.php(106): Mail_mimeDecode->decode()
#5 {main}
  thrown in /opt/mailwatch/mailscanner/lib/pear/Mail/mimeDecode.php on line 829
[18-Nov-2021 17:52:50 Europe/London] PHP Fatal error:  Uncaught Error: Call to undefined function create_function() in /opt/mailwatch/mailscanner/lib/pear/Mail/mimeDecode.php:829
Stack trace:
#0 /opt/mailwatch/mailscanner/lib/pear/Mail/mimeDecode.php(802): Mail_mimeDecode->_quotedPrintableDecode()
#1 /opt/mailwatch/mailscanner/lib/pear/Mail/mimeDecode.php(316): Mail_mimeDecode->_decodeBody()
#2 /opt/mailwatch/mailscanner/lib/pear/Mail/mimeDecode.php(344): Mail_mimeDecode->_decode()
#3 /opt/mailwatch/mailscanner/lib/pear/Mail/mimeDecode.php(237): Mail_mimeDecode->_decode()
#4 /opt/mailwatch/mailscanner/viewpart.php(106): Mail_mimeDecode->decode()
#5 {main}
  thrown in /opt/mailwatch/mailscanner/lib/pear/Mail/mimeDecode.php on line 829

### Steps to reproduce
1. Attempt to open a message
2. 
3. 

### Expected result
Content of the message displayed

### Actual result
Blank windows

### Version and method
 - MailWatch Version: stable 1.2.18
 - Install type:  GitHub checkout
 - Fresh install

### Server configuration
 - Operation System: Fedora 35
 - PHP version: 8.0.12
 - Database: MariaDB
 - Mail Server: Sendmail
 - Used web server: Apache 2.4.51

### Client configuration 
 - Operation System: Windows 11
 - Browser: Chrome Version 95.0.4638.69 (Official Build) (64-bit)

**Comment by endelwar** [comment]
I've updated and fixed some PEAR libs, to get better PHP8 compatibility. Could you test the 1.2 branch?

**Comment by dwhile** [comment]
I have updated by doing a git pull and initial tests seems to be positive. I will continue checking the functionality.

**Comment by endelwar** [comment]
Fixed by #1234
