### ISSUE TITLE
mailwatch shows no f-secure status

### ISSUE THREAD

**Issue by ez-w** [mailwatch/1.2.0#1239]
### Issue summary
mailwatch not show the status for last f-secure linux security edition

### Steps to reproduce
1. install last f-secure linux security edition
2. install mailscanner 5.4.3-1 rhel
3. install mailwatch 1.2.18

### Expected result
show status of F-Secure antivirus

### Actual result
no information displayed 

### Version and method
 - MailWatch Version: [ stable 1.2.18 ]
 - Install type: [ tarball install  ]
 - Updated from an older MailWatch 1.2.12

### Server configuration
 - Operation System: [ CentOS 7 ]
 - PHP version: [ 7.4 ]
 - Database: [ MariaDB version 10.1.48 ]
 - Mail Server: [ Sendmail ]
 - Used web server: [ Apache  ]

mailwatch 1.2.18 indicate support to f-secure 12 but new f-secure edition use fsanalyze and not fsav, you can see in MailScanner in the new wrapper file

https://github.com/MailScanner/v5/blob/master/common/usr/lib/MailScanner/wrapper/f-secure-12-wrapper

old f-secure version wrapper

https://github.com/MailScanner/v5/blob/master/common/usr/lib/MailScanner/wrapper/f-secure-wrapper

**Comment by endelwar** [comment]
To support new f-secure binary info we need an example output from fsanalyze (or equivalent binary) that can output desired information, like `/opt/f-secure/fsav/bin/fsav --version` does.
Can you run the command and put the output in a txt file, and attach it to this issue?

**Comment by ez-w** [comment]
I'm a new user of F-Secure linux Edition, I don't have old version.

I have 2 fsanalyze binaries and it displays little information :-(

> /opt/f-secure/linuxsecurity/bin/fsanalyze --version
fsanalyze 1.0.18

> /opt/f-secure/baseguard/bin/fsanalyze --version
fsanalyze 2.0.40

**Comment by ghost** [comment]
Create an eicar test file and scan it please
```/opt/f-secure-baseguard/bin/fsanalyze --quiet eicar.txt```

**Comment by ghost** [comment]
Also try it without --quiet, in case this is suppressing all output

**Comment by ghost** [comment]
Also the output from "MailScanner --lint" would be helpful

**Comment by ez-w** [comment]
**_/opt/f-secure/linuxsecurity/bin/fsanalyze --quiet eicar.com_** 
eicar.com: result=infected infection=EICAR_Test_File
eicar.com: action=renamed

**_/opt/f-secure/linuxsecurity/bin/fsanalyze eicar.com_**
eicar.com.malware: result=infected infection=EICAR_Test_File

Engine versions: F-Secure Corporation Aquarius/18.0.790/2021-12-12_10 F-Secure Corporation Hydra/6.0.425/2021-12-10_01 F-Secure Corporation FMLib/17.11.62.513  (8a526f1)/2021-12-02_01  fsicapd/2.0.211

1 files scanned
1 files infected


_**MailScanner --lint** (I use too Sophos antivirus in the same server)_

Trying to setlogsock(unix)
Reading configuration file /etc/MailScanner/MailScanner.conf
Reading configuration file /etc/MailScanner/conf.d/README
Read 1500 hostnames from the phishing whitelist
Read 5056 hostnames from the phishing blacklists
Config: calling custom init function MailWatchLogging
MailWatch: Started MailWatch SQL Logging child
Checking version numbers...
Version number in MailScanner.conf (5.4.3) is correct.
Your envelope_sender_header in spamassassin.conf is correct.
Checking for SpamAssassin errors (if you use it)...
SpamAssassin reported no errors.
Connected to Processing Attempts Database
Created Processing Attempts Database successfully
There are 0 messages in the Processing Attempts Database
Using locktype = posix
MailScanner.conf says "Virus Scanners = f-secure-12 sophos"
Found these virus scanners installed: f-secure-12, sophos

Virus and Content Scanning: Starting
Virus Scanning: F-Secure found virus EICAR_Test_File
./1/eicar.com: result=infected infection=EICAR_Test_File
Virus Scanning:  found 1 infections
Virus 'EICAR-AV-Test' found in file /var/spool/MailScanner/incoming/31831/1/eicar.com.malware
Virus Scanning: Sophos found 1 infections
Infected message 1 came from 10.1.1.1
Virus Scanning: Found 2 viruses

Virus Scanner test reports:
./1/eicar.com said "result=infected infection=EICAR_Test_File"

If any of your virus scanners (f-secure-12,sophos)
are not listed there, you should check that they are installed correctly
and that MailScanner is finding them correctly via its virus.scanners.conf.
Config: calling custom end function MailWatchLogging

**Comment by ghost** [comment]
Thanks, it looks like the information we need is displayed without the --version parameter.  I wonder if we can get that output to display without carrying out an actual scan.

**Comment by ez-w** [comment]
**/opt/f-secure/linuxsecurity/bin/fsanalyze** without parameter => nothing is displayed maybe it's scan all files and it takes hours 

If I specify a folder like /tmp

 **/opt/f-secure/linuxsecurity/bin/fsanalyze /tmp**

Engine versions: F-Secure Corporation Aquarius/18.0.790/2021-12-13_03 F-Secure Corporation Hydra/6.0.425/2021-12-13_01 F-Secure Corporation FMLib/17.11.62.513  (8a526f1)/2021-12-02_01  fsicapd/2.0.211

42 files scanned





**/opt/f-secure/linuxsecurity/bin/fsanalyze -h**
Usage: fsanalyze [OPTIONS] [FILE...]
Analyze each FILE for potential malicious content.
If no file is specified, analyze standard input,
in which case the only supported action is "none".

OPTIONS:
 -h, --help                   Show help.
 --malware=ACTION             Action to take when a file is detected as
                              malware: if ACTION is 'remove' the file is
                              removed; if ACTION is 'rename' the file is
                              renamed adding the detection type as extension;
                              if ACTION is 'none', the infection is only
                              reported on standard output. (Policy default:
                              rename)
 --pua=ACTION                 Action to take when a file is detected as a
                              Potentially Unwanted Application. (Policy
                              default: none)
 --suspected=ACTION           Action to take when a file is detected as
                              suspected. (Policy default: none)
 -L, --follow                 Follow symbolic links.
 -l, --list                   List all scanned files.
 --preserve-atime=VALUE       Preserve the access time of files that are
                              scanned. VALUE can be 'yes' or 'no'. (Default:
                              no)
 -q, --quiet                  Output only scan results.
 --scan-archives=VALUE        Enable archive scanning. VALUE can be 'yes' or
                              'no'. (Policy default: no)
 --max-nested=NUMBER          Set maximum allowed nesting level of scanned
                              archives. (Policy default: 5)
 --detect-max-nested=VALUE    If enabled, treat too-deeply nested archives as
                              malware. VALUE can be 'yes' or 'no'. (Policy
                              default: no)
 --detect-encrypted-archives=VALUE
                              Treat encrypted archives as malware. VALUE can
                              be 'yes' or 'no'. (Policy default: no)
 --detect-pua=VALUE           If disabled, Potentially Unwanted Applications
                              are ignored. VALUE can be 'yes' or 'no'. (Policy
                              default: yes)
 --use-orsp=VALUE             If enabled, use reputation service (ORSP) from
                              Security Cloud. VALUE can be 'yes' or 'no'.
                              (Policy default: yes)
 --quoting-style=STYLE        How to quote output: if STYLE is 'url', output
                              will be url encoded; if STYLE is 'escape', ASCII
                              control characters in the output will be escaped
                              as <NAME>. If the output is not redirected to a
                              file they will also be highlighted; if STYLE is
                              'literal', output will be printed as is.
                              (Default: url)
 --ignore-exclude-paths       Do not use exclude paths from policy.
 -v, --version                Display program version and exit.

**Comment by ghost** [comment]
This is good info, we should be able to "scan" a directory with little or nothing in it and scrape the info from the output. We should be able to get a PR going.

**Comment by endelwar** [comment]
@ez-w can you try a scan on an inexistent file, like `/opt/f-secure/linuxsecurity/bin/fsanalyze ./idontexist.txt` to see if the output is still useful or not? Also, try to perform a scan on an empty file and tell us which is faster (empty vs non-existent) by using the `time` command. I would like to implement the faster and less resource consuming solution.

**Comment by ez-w** [comment]
**time /opt/f-secure/linuxsecurity/bin/fsanalyze ./toto.txt**
fsanalyze: failed to process './toto.txt' (No such file or directory)

Engine versions: F-Secure Corporation Aquarius/18.0.790/2021-12-15_10 F-Secure Corporation Hydra/6.0.425/2021-12-14_01 F-Secure Corporation FMLib/17.11.62.513  (8a526f1)/2021-12-02_01  fsicapd/2.0.217

0 files scanned
1 files could not be scanned

real	0m0.005s
user	0m0.000s
sys	0m0.004s

**time /opt/f-secure/linuxsecurity/bin/fsanalyze ./empty.txt** 

Engine versions: F-Secure Corporation Aquarius/18.0.790/2021-12-15_10 F-Secure Corporation Hydra/6.0.425/2021-12-14_01 F-Secure Corporation FMLib/17.11.62.513  (8a526f1)/2021-12-02_01  fsicapd/2.0.217

1 files scanned

real	0m0.009s
user	0m0.002s
sys	0m0.004s

it's very speed

**Comment by endelwar** [comment]
@ez-w I've just [pushed a PR](https://github.com/mailwatch/MailWatch/pull/1241) with a fix to be tested: could you pull it and see if with the real executable this patch gives the right results (I've tested it only with a txt files containing the output reported above)?

@shawniverson I went with "f-secure-12" for `Virus Scanners` in MailScanner.conf, is it correct?

**Comment by ghost** [comment]
@endelwar that is correct

**Comment by ez-w** [comment]
@endelwar perfect it works

<img width="777" alt="mailwatch-tools-and-links" src="https://user-images.githubusercontent.com/18184902/146645578-1f82556b-7f2e-4728-aecf-be7045edaebc.png">
<img width="887" alt="mailwatch-fsecure-info" src="https://user-images.githubusercontent.com/18184902/146645580-494e3fbf-5d22-4ce1-82f7-b0e5a788a877.png">
