### ISSUE TITLE
MailWatch messages keeps with content

### ISSUE THREAD

**Issue by janarzz** [mailwatch/1.2.0#1242]
Hi,
i have problem with mailwatch messages keep with content.
For now i have this choose:
// Define how many days of emails to keep.
define('RECORD_DAYS_TO_KEEP', 840);

But messages with content only 45days
I use ubuntu server 18.04
MailWatch 1.2.10
MailScanner 5.4.1
PHP 7.3.33

**Comment by ghost** [comment]
That keeps the records, but not the content. For content, you need to look at QUARANTINE_DAYS_TO_KEEP

**Comment by janarzz** [comment]
Hi,
QUARANTINE_DAYS_TO_KEEP its the same value.

**Comment by Skywalker-11** [comment]
Also look at your MailScanner config. MailScanner itself also has a cron that can remove quarantined items (configure via /etc/MailScanner/defaults setting `q_days`)
