### ISSUE TITLE
issue with upgrade

### ISSUE THREAD

**Issue by askewdread** [mailwatch/1.2.0#1255]
Hi there,

i have been using version 1.2.1 for a long time but ive just updated Mailscanner so needed to update MailWatch,
im getting the following error when trying to run upgrade.php or access the web interface

PHP Parse error:  syntax error, unexpected ')', expecting :: (T_PAAMAYIM_NEKUDOTAYIM) in /opt/mailwatch/mailscanner/functions.php on line 4953

the server is running php 5.4.16 as recmmended in the requirements page

**Comment by ghost** [comment]
Hello @askewdread which version did you update to?

**Comment by askewdread** [comment]
i updated to the latest version,

ive upgraded to PHP7 nowe and its all working correctly, maybe the php version on the https://docs.mailwatch.org/install/getting-started.html page needs to be updated to a newer one now?

**Comment by ghost** [comment]
I thought that 5.4 and up was okay, but maybe not on the latest version, I'll double check.

**Comment by endelwar** [comment]
I've just parsed the `mailscanner` dir and everything should run smoothless on PHP 5.4: there are lots of polyfills and conditional checks to ensure backward compatibility.

This said, I suggest to run MailWatch on PHP 7.4

**Comment by askewdread** [comment]
strange, oh well its working now with php 7 anyway, but seems odd that on both servers it wouldnt work on the php 5.4.16
