### ISSUE TITLE
UI Enhancement Request: wrap words in the message details, message headers row

### ISSUE THREAD

**Issue by pdwalker** [mailwatch/1.2.0#1258]
The message headers row in https://<Server>/mailscanner/detail.php sometimes has really long words that are unbreakable.  This cause the table to become larger than the screen width and requires we scroll far to the right to see all the details.

This also causes a display issue with the quarantine table at the bottom of the detail.php page.  If the first table is extremely wide, then this table also becomes very wide and the submit button is not conveniently accessible because of the need to now scroll far to the right.

My quick fix was to modify style.css and add 'word-break: break-word' to the 'table.maildetail td.detail' style, like so:
```
table.maildetail td.detail {
    background-color: #EBEBEB;
    font-size: 8pt;
    word-break: break-word;
}
```

Would it be possible to at least apply this style to the message headers row?

**Comment by dneuhaeuser** [comment]
I saw the same problem sometimes...
Your suggestion kind of works, but not in all cases:
sometimes there is a really long line without any blankspace in it.
Then the CSS word-break doesn't help.

**Comment by endelwar** [comment]
A good compromise on header section would be using `word-break: break-all;` that breaks words when needed without requiring a space
