### ISSUE TITLE
message operations: bulk learn as spam/ham/forget or release not working

### ISSUE THREAD

**Issue by dneuhaeuser** [mailwatch/1.2.0#1264]
On the page "Message Operations" I cannot bulk learn or release any messages.
After clicking on "Learn" I just get an empty result table:
![image](https://user-images.githubusercontent.com/11788579/198853732-9af00d80-636c-4f8b-83c4-f876c7caf725.png)
There's also no hint in the apache errorlog.
Single learn or release on each message work perfectly.
How can I probably debug this?

MailWatch Version: 1.2.19
Operating System Version: Ubuntu 22.04.1 LTS (Jammy Jellyfish)
Postfix Version: 3.6.4
MailScanner Version: 5.4.5
PHP Version: 8.1.2

**Comment by dneuhaeuser** [comment]
found a bug.
turns out this has to do with milter mode.
see PR #1267

**Comment by endelwar** [comment]
Fixed by https://github.com/mailwatch/MailWatch/pull/1267
