### ISSUE TITLE
MailWatch 1.2.10 not showing MailScanner or Postfix as running

### ISSUE THREAD

**Issue by jcrower** [mailwatch/1.2.0#1274]
### Issue summary
Mailwatch reports MailScanner and Postfix not running

### Steps to reproduce
1. Log in to MailWatch interface

### Expected result
MailScanner and Postfix status should show green Ok and number of processes.

### Actual result
MailScanner and Postfix show red No

### Troubleshooting steps
I ran the command **ps ax | grep MailScanner | grep -v grep** as per another thread here and it returns the MailScanner processes.  I can also run this command as the apache user successfully.

### Version and method
 - MailWatch Version: stable 1.2.10
 - Install type: Zip/tarball install
 - Fresh install

### Server configuration
 - Operation System: Rocky 9.1
 - PHP version: 8.0.20
 - Database: MySQL 8.0.30
 - Mail Server: Postfix
 - Used web server: Apache2.4.53
### Client configuration 
 - Operation System: Win 10
 - Browser: Firefox and MS Edge

**Comment by Skywalker-11** [comment]
Can you try updating to the current version? Since 1.2.10 where some fixes regarding the postfix status.

**Comment by jcrower** [comment]
Can't believe (well I can actually) what an idiot I am.  I must have blindly copied a download link from somewhere and thought I was installing the latest version.  Dangerous thing to do!

Anyway....
![image](https://user-images.githubusercontent.com/66984454/219984416-e1c41071-2bd7-4500-b6cf-55c4f7012bab.png)

EDIT: I can run the postconf command manually, can't see any errors in any logs
![image](https://user-images.githubusercontent.com/66984454/219984555-7b869d5c-6d78-43de-888e-c17ad92718ee.png)

I had a look in the sf_version.php file and it appears this is what it tries to run (below is me running the command manually).  I can't see any errors that might suggest php can't run exec();
**which postconf**
 _/usr/sbin/postconf_
**/usr/sbin/postconf -d | grep 'mail_version =' | cut -d' ' -f3**
 _3.5.9_

**Comment by endelwar** [comment]
I think that this error is related to this issue https://github.com/mailwatch/MailWatch/issues/1026#issuecomment-357818247

**Comment by jcrower** [comment]
Yep that's it! Thanks endelwar.
