### ISSUE TITLE
MailWatch clean mail in quarantine

### ISSUE THREAD

**Issue by Doctober** [mailwatch/1.2.0#1279]
### Issue summary
All Mail is being stored in Quarantine no matter if it actually is "bad" or not.
I cannot find any point in my configuration that makes it so that "clean" mails do not get quarantined

### Expected result
Only "bad" mails should appear in quarantine (spam, bad content/infected)

### Actual result
Mails marked as "Clean" are being shown in Quarantine

### Version and method
 - MailWatch Version: [ stable 1.2.20 ]
 - Install type: [ Zip/tarball install ]
 - Updated from an older MailWatch or fresh install: [ Fresh install ]

### Server configuration
 - Operation System: [ Ubuntu ] version [ 20.04 ]
 - PHP version: [ 7.4 ]
 - Database: [ MySQL ] version [ 8.0.33 ]
 - Mail Server: [ Postfix ]
 - Used web server: [ Apache ] version [ 2.4.41 ]

**Comment by Skywalker-11** [comment]
You should have a setting in your MailScanner config like `Non Spam Actions = deliver header "X-Spam-Status: No" store`
If you remove the `store` option the non spam mails should not be stored anymore.

**Comment by Doctober** [comment]
Thank you, the changes have worked.
