### ISSUE TITLE
QUARANTINE_USE_SENDMAIL not working after update

### ISSUE THREAD

**Issue by slsguerra** [mailwatch/1.2.0#1282]
After upgrade from 1.2.10 to 1.2.20 QUARANTINE_USE_SENDMAIL not respect true flag.
Messages are sent as postmaster and broken DKIM. On status page these messages appers only one time, unlike before that appers two times.
Any suggestion?
I'm using postfix as server

**Comment by endelwar** [comment]
From 1.2.10 to 1.2.20 function `quarantine_release` (where `QUARANTINE_USE_SENDMAIL` is checked) hasn't changed functionality, the only edits are:

- convert long array syntax to short array syntax
- use Yoda style on if

Both of these changes have been done by the PHP-CS-Fixer tool

**Comment by slsguerra** [comment]
Any way to debug this? Outgoing messages are ok, incoming messages do not arrive in the email box.

**Comment by slsguerra** [comment]
After review sendmail symlink works
