### ISSUE TITLE
Problem after upgrading from ubuntu 18.04 to 20.04 and mailwatch 1.2.16 to 1.2.21

### ISSUE THREAD

**Issue by alchemist18** [mailwatch/1.2.0#1296]
### Steps to reproduce
1. update from ubuntu 18.04 to 20.04
2. update from mailwatch 1.2.16 to 1.2.21
3. THE PROBLEM APPEARED JUST WITH THE ubuntu update. The mailwatch update was an attempt to resolve the issue

### Expected result
Login to watchmail site and see the full mailwatch page with all the information about the emails etc...

### Actual result
Login to watchmail site successful BUT I only see very little information, no information about my emails... (see attachment).

### Version and method
 - MailWatch Version: stable 1.2.21
 - Install type: Zip/tarball install
 - Updated from an older MailWatch or fresh install: Upgrade from version 1.2.16

### Server configuration
 - Operation System: Ubuntu  version [ 20.04.6 ]
 - PHP version: [ 5.3 | 5.4 | 5.5 | 5.6 | 7.0 | 7.1 ]
 - Database: [ MySQL ] version [Ver 8.0.35-0ubuntu0.20.04.1 ]
 - Mail Server: [ Postfix ]
 - Used web server: [ Apache ] version [2.4.41-4ubuntu3.15  ]

### Client configuration 
 - Operation System: [ Ubuntu ] version [ 20.04.6 ]
 - Browser: [ chromium] version [Chromium 120.0.6099.224 snap] ALSO [firefox] version [121.0.1]
ERROR LOG OF apache2 in attachment
[error.log](https://github.com/mailwatch/MailWatch/files/14013878/error.log)
![Screenshot from 2024-01-21 16-33-35](https://github.com/mailwatch/MailWatch/assets/53316525/ba6c6482-e7a7-464e-ad29-5774984deaab)

**Comment by alchemist18** [comment]
forgot php information: I am using 8.3

**Comment by alchemist18** [comment]
SOLVED
1) used php 7.2 (probably not necessary...)
   a2dismod php8.3 (or what you have)
  a2enmod php7.2

2) at the end of: /etc/apache2/apache2.conf
ADD THE LINES:
 .   <FilesMatch \.php$>
 .      SetHandler application/x-httpd-php
 .   <./FilesMatch>
 .  <FilesMatch \.html>
 .       SetHandler application/x-httpd-php
 .   <./FilesMatch>

3) CHANGE /etc/apache2/mods-available/php7.2.conf, COMMENTING OUT "< ifModule mod_userdir.c:>" ... TO ..."< /ifModule>"

.....#  < ifModule mod_userdir.c> 
.....#    <Directory /home/*/public_html>
.....#        php_admin_flag engine Off
.....#    < /Directory>
.....#   < /IfModule>

(see the php7.2.conf.diff patch in attachment)

**Comment by endelwar** [comment]
Reading the log you posted there is a permission error on the filesystem that's mounted after `/boot/efi`, you can look it up with `cat /proc/mounts`.

Could it be that php 7.2 runs on different user that php 8.3?

**Comment by alchemist18** [comment]
Hello,
thank you for your answer, but the issue has been solved. See:
https://github.com/mailwatch/MailWatch/issues/1296
It was a matter of manual configurations of Mailscanner and php that
got lost after the upgrade of Ubuntu...
My best greetings,
Paolo
