### ISSUE TITLE
Cannot Update GeoIP Database

### ISSUE THREAD

**Issue by rizkypratama01** [mailwatch/1.2.0#1301]
### Issue summary
Cannot update GeoIP Database

On page geoip_update.php, show success download, but no database downloaded when I check on Software Version page

Geoip_update.php :
Downloading file, please wait...
Download complete, unpacking files...

Software Version Page :
GeoIP Database Version: No database downloaded

I check on directory, show like this, size file just 23 bytes, there are no mmdb geolite files

root@rz1:/opt/mailwatch# ls -ltrh /opt/mailwatch/mailscanner/temp/
total 4.0K
-rw-r--r-- 1 www-data www-data 23 Jul  4 22:20 GeoLite2-Country.tar.gz

I've tried changing the maxmind key, but the geolite file is not downloaded

### Version and method
 - MailWatch Version: 1.2.23
 - Install type: Zip/tarball install
 - Updated from an older MailWatch or fresh install: Upgrade from version 1.2.21

### Server configuration
 - Operation System: Ubuntu 22.04.4 LTS (Jammy Jellyfish)
 - PHP version: 8.1.29
 - Database: MariaDB 10.11.8-MariaDB-ubu2204-log
 - Mail Server: Postfix
 - Used web server: Nginx nginx/1.26.1

### Client configuration 
 - Operation System: MacOS 14.5
 - Browser: Chrome 126.0.6478.127

**Comment by endelwar** [comment]
Hi,
What's inside the GeoLite2-Country.tar.gz file?
Do you have any error logged in php or nginx error log?

**Comment by rizkypratama01** [comment]
> Hi, What's inside the GeoLite2-Country.tar.gz file? Do you have any error logged in php or nginx error log?

Hi, the file cannot be extracted

root@rz1:/opt/mailwatch/mailscanner/temp# tar -zxvf GeoLite2-Country.tar.gz 
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now


Like this error in nginx

2024/07/04 22:20:09 [error] 1753887#1753887: *43 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught UnexpectedValueException: internal corruption of phar "/opt/mailwatch/mailscanner/temp/GeoLite2-Country.tar.gz" (__HALT_COMPILER(); not found) in /opt/mailwatch/mailscanner/geoip_update.php:161
Stack trace:
#0 /opt/mailwatch/mailscanner/geoip_update.php(161): PharData->__construct()
#1 {main}
  thrown in /opt/mailwatch/mailscanner/geoip_update.php on line 161" while reading upstream, client: xx.xx.xx.xx, server: xx.domain.com, request: "POST /geoip_update.php HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php8.1-fpm.sock:", host: "xx.domain.com", referrer: "https://xx.domain.com/geoip_update.php"

**Comment by ghost** [comment]
What do you see when you `cat GeoLite2-Country.tar.gz` ?

**Comment by rizkypratama01** [comment]
> What do you see when you `cat GeoLite2-Country.tar.gz` ?

Hi, Like this

root@rz1:/opt/mailwatch/mailscanner/temp# cat GeoLite2-Country.tar.gz 
An account ID and license key are required to use this service.

Need account ID and license key, I have entered a valid license key in MAXMIND_LICENSE_KEY in the conf.php file, and for account ID, where should I insert it?

**Comment by endelwar** [comment]
Ah, great they changed download method again, without notification...
