### ISSUE TITLE
Segfault in Mailwatch.pm when using MySql 8.4.2

### ISSUE THREAD

**Issue by adri-k** [mailwatch/1.2.0#1304]
### Issue summary
When starting MailScanner, multiple errors occur in the syslog (/var/log/messages) about a perl segfault.
Running the same MailWatch installation with MySql 8.0.35 produces no errors.
### Steps to reproduce
1. Install MySql 8.4.2 and create the MailWatch tables.
2. Configure MailScanner to use the MailWatch Custom function.
3. Start MailScanner.

### Expected result
MailScanner should start without any errors.

### Actual result
MailScanner starts, produces multiple errors but continues to function and messages are logged by MailWatch.

Jul 31 12:06:25 mail kernel: pid 17685 (perl), jid 0, uid 0: exited on signal 11 (core dumped)
Jul 31 12:06:25 mail kernel: pid 17690 (perl), jid 0, uid 0: exited on signal 11 (no core dump - bad address)
Jul 31 12:06:30 mail kernel: pid 17700 (perl), jid 0, uid 0: exited on signal 11 (no core dump - bad address)
Jul 31 12:06:35 mail kernel: pid 17709 (perl), jid 0, uid 0: exited on signal 11 (no core dump - bad address)
Jul 31 12:06:40 mail kernel: pid 17718 (perl), jid 0, uid 0: exited on signal 11 (no core dump - bad address)
Jul 31 12:08:48 mail kernel: pid 17762 (perl), jid 0, uid 0: exited on signal 11 (no core dump - bad address)
Jul 31 12:08:53 mail kernel: pid 17764 (perl), jid 0, uid 0: exited on signal 11 (no core dump - bad address)
Jul 31 12:08:58 mail kernel: pid 17766 (perl), jid 0, uid 0: exited on signal 11 (no core dump - bad address)
Jul 31 12:09:03 mail kernel: pid 17768 (perl), jid 0, uid 0: exited on signal 11 (no core dump - bad address)
Jul 31 12:09:09 mail kernel: pid 17770 (perl), jid 0, uid 0: exited on signal 11 (no core dump - bad address)
Jul 31 12:09:14 mail kernel: pid 17772 (perl), jid 0, uid 0: exited on signal 11 (no core dump - bad address)

The problem seems to be inside the CheckSQLVersion() function.
If I change this function to just 'return 80402', the error message and segfaults disappear.
### Version and method
 - MailWatch Version: [1.2.21]
 - Install type: [Zip/tarball install]
 - Updated from an older MailWatch or fresh install: [Upgrade ] (from version [ 1.2.20])

### Server configuration
 - Operation System: [ FreeBSD ] version [ 14.1 ]
 - PHP version: [ 8.2.21 ]
 - Database: [ MySQL ] version [ 8.4.2 ]
 - Mail Server: [ Sendmail ]
 - Used web server: [ Apache version [ 2.4.62 ]

**Comment by endelwar** [comment]
Could you try the latest 1.2 branch? I've just merged a PR that modifies CheckMysqlVersion(). You need to install DBI:MariaDB to make the new code work.

**Comment by adri-k** [comment]
I just had a quick look at the CheckSQLVersion() in MailScanner_perl_scripts/MailWatch.pm and it seems to eb simplfied a lot, without any charset options etc.
Will DBD:MariaDB work with an MySql database?
I won't be able to easily migrate from MySql to MariaDB for the database server.

**Comment by endelwar** [comment]
> Will DBD:MariaDB work with an MySql database?

Yes, we migrated to `DBD:MariaDB` because it supports both MySQL 5.7/8.x and MariaDB

**Comment by adri-k** [comment]
Thank you for the extra information.
I will try the new MailWatch.pm first using DBI:MariaDB and let you know if I encounter any problems.
If the current 1.2 branch stable enough to upgrade the whole of MailWatch?

**Comment by adri-k** [comment]
Mailwatch.PM version 1.7 using DBD:MariaDB works with MySql version 8,2,4.
