### ISSUE TITLE
quarantine_report.php not showing for domain admins

### ISSUE THREAD

**Issue by mealerzrich** [mailwatch/1.2.0#132]
Hi,
When I run this the the to_address and the to_domain is both my email address - 
SELECT DISTINCT
    -> a.id AS id,
    -> DATE_FORMAT(timestamp,'%d/%m/%y <br/>%H:%i:%s') AS datetime,
    -> a.from_address AS from_address,
    -> a.subject AS subject,
    -> CASE
    ->  WHEN a.virusinfected>0 THEN 'Virus'
    ->  WHEN a.nameinfected>0 THEN 'Bad Content'
    ->  WHEN a.otherinfected>0 THEN 'Infected'
    ->  WHEN a.ishighspam>0 THEN 'Spam'
    ->  WHEN a.issaspam>0 THEN 'Spam'
    ->  WHEN a.isrblspam>0 THEN 'Spam'
    ->  WHEN a.spamblacklisted>0 THEN 'Blacklisted'
    ->  WHEN a.isspam THEN 'Spam'
    ->  WHEN a.ismcp>0 THEN 'Policy'
    ->  WHEN a.ishighmcp>0 THEN 'Policy'
    ->  WHEN a.issamcp>0 THEN 'Policy'
    ->  WHEN a.mcpblacklisted>0 THEN 'Policy'
    ->  WHEN a.isspam>0 THEN 'Spam'
    ->  ELSE 'UNKNOWN'
    -> END AS reason
    -> FROM
    ->  maillog a
    -> WHERE
    ->  a.quarantined = 1
    -> AND
    ->  ((to_address='richard@mydomain.co.uk') OR (to_domain='richard@mydomain.co.uk'))
    -> AND
    ->  a.date >= DATE_SUB(CURRENT_DATE(), INTERVAL 7 DAY)
    -> ORDER BY a.date DESC, a.time DESC;
Empty set (1.05 sec)

I get a list of emails for my email address but not for the domain itself.

**Comment by endelwar** [comment]
Hi,
you should change the name of your domain admin user to the domain that you want to receive report (in your example above it should be `mydomain.co.uk`) as per this doc page http://docs.mailwatch.org/using/per-domainper-user-filtering.html

**Comment by endelwar** [comment]
@mealerzrich: did the above suggestion work?

**Comment by mealerzrich** [comment]
No I didn't follow your advice, as everyone on the mailwatch list told me you should use an email address for domain administrators. Also when you create a user, it also tells you to use an email address, so I ended up splitting the to_domain with a regex on the lists.php page. 

I think I did this - 

// Split user/domain if necessary (from detail.php)
$touser = '';
$to_domain = '';
if (preg_match('/(\S+)@(\S+)/', $url_to, $split)) {
    $touser = $split[1];
    $to_domain = $split[2];
} else {
    $to_domain = $url_to;
}

I've really modified my mailwatch with jquery and things for the lists page, as I have drop downs for each domain, so my lists.php is probably very different from everyone elses now.
