### ISSUE TITLE
MailScanner v.85.2.0-beta path change

### ISSUE THREAD

**Issue by shawniverson** [mailwatch/1.2.0#136]
Just a heads up...

Path is changing from 
/usr/lib/MailScanner 

to 
/usr/share/MailScanner

Just in case this affects MailWatch down the road...

**Comment by endelwar** [comment]
This shouldn't be a problem: it's a variable that needs to be modified anyway.
I'll change it to the new default as soon as the new MailScanner version is released

Good catch @shawniverson ;)
