### ISSUE TITLE
Suggestion development

### ISSUE THREAD

**Issue by MisterM74** [mailwatch/1.2.0#137]
Good Morning
Just a suggestion for the future application which is for me cooler than baruwa.
What's missing 3 things:
Given the opportunity to modify the MailScanner configuration file.
Giving the possibility that, when an email is not spam, but that is recognized, re-send the message.
Manage a DNS service, with the addition of:
dkim
Relay MX
Sends SMTP
SPF ...
Voila
Mz

**Comment by endelwar** [comment]
> Given the opportunity to modify the MailScanner configuration file.

This will be implemented in the next major release (no, no ETA yet)

> Giving the possibility that, when an email is not spam, but that is recognized, re-send the message.

this is already possible: just put a tick on "release" on detail page and hit "submit", or you can do it on multiple email from the "message operations" report page

> Manage a DNS service
This goes far beyond the MailWatch scope (i.e. A web based front-end to MailScanner )

**Comment by MisterM74** [comment]
This goes far beyond the MailWatch scope (i.e. A web based front-end to MailScanner )
a simple suggestion, clear as a dns management can be done at the source.
