### ISSUE TITLE
Password recovery option

### ISSUE THREAD

**Issue by mitgib37** [mailwatch/1.2.0#139]
Would this be possible to implement?  End users not being able to recover password adds to admin overhead
##

**Comment by asuweb** [comment]
I've implemented a password reset function, which works as follows:

Forgotten Password link on login screen
Requests email address, then checks that it is a registered user (doesn't allow domain or admin users), and if so sends an email with a confirmation link.

User clicks the link, if it's still valid, takes them to a password reset page, where they enter their new password.  

Emails user to confirm their password has been reset - user can now login.

Can be enabled or disabled through the config file.

I'll submit a pull request if you like?

**Comment by FraGManiA** [comment]
Hi @asuweb, I would like to see your code for the password reset! Thanks in advance!

**Comment by asuweb** [comment]
@FraGManiA - I'll tidy up the code then submit a pull request

**Comment by asuweb** [comment]
@FraGManiA - I haven't forgotten about this - just waiting to find out when RC4 will be released, as there is a large code base change / tidy up, and it would be better to incorporate it into the new release.  

Either way, I'll get it to you soon :)

**Comment by endelwar** [comment]
Password editing should be enabled only if LDAP auth is not enabled.

**Comment by asuweb** [comment]
Good point

**Comment by FraGManiA** [comment]
I don't have LDAP auth enabled.
Is there already a releasedate planned for RC4?
I need the password reset possibilty asap for my users, thanks in advance!

**Comment by asuweb** [comment]
@FraGManiA - RC4 is released, although further feature enhancements won't be incorporated into the core (see #341).  I'll get you a patch for this by the end of the week, I haven't tested it on RC4 yet

**Comment by FraGManiA** [comment]
@asuweb awesome man! :-)

**Comment by asuweb** [comment]
@FraGManiA - The password reset function is here, tested on RC4.  It'll only allow users to reset their passwords, not admins.  Needs enabling in conf.php, and the referenced file (in conf.php) needs to be run to alter the user table.  

hhttps://github.com/mailwatch/1.2.0/compare/develop...asuweb:password-reset

@endelwar - I'll create a pull request to the develop branch if you want to merge this with RC4 / 1.2.0

**Comment by FraGManiA** [comment]
@asuweb many thanks! Is it possible to enable this for domain admins as well?

**Comment by asuweb** [comment]
It's possible with some code changes, but it possibly opens up a security vulnerability should the domain admin's email be compromised, a potential hacker could then monitor all of the mail for that domain.  

To change it, you need to edit line 45 of password_reset.php

`if ($row['type'] == 'U' OR $row['type'] == 'D') {`

**Comment by FraGManiA** [comment]
Thanks @asuweb, I will consider this.

**Comment by stefaweb** [comment]
This one can be closed.
