### ISSUE TITLE
Issue in viewmail.php if duplicate header fields exist

### ISSUE THREAD

**Issue by jwilcock** [mailwatch/1.2.0#154]
If a message has, for example, two distinct "To:" headers, then viewmail.php issues warnings: 

Warning: mb_check_encoding() expects parameter 1 to be string, array given in /var/www/localhost/htdocs/mailscanner/viewmail.php on line 162
Warning: mb_convert_encoding() expects parameter 1 to be string, array given in /var/www/localhost/htdocs/mailscanner/viewmail.php on line 163

Adding a var_dump shows that in this case the $structure->headers['to'] is an array rather than a single string.

**Comment by endelwar** [comment]
as per RFC 5322 there can be at maximum one of the following headers:
* bcc
* cc
* from
* in-reply-to
* message-id
* orig-date
* references
* reply-to
* sender
* subject
* to

so, after thinking about it, I think that the workaround in commit a227bacf60755023f3109e32a88013aa5c24193a will suffice for this out of RFC emails

**Comment by jwilcock** [comment]
Agree entirely that your workaround will suffice. This condition should never occur for RFC-compliant e-mails, and the workaround is sufficient to ensure that non-compliant messages result in a meaningful display without throwing a warning.
