### ISSUE TITLE
Header information doesn't display if GeoIP files are zero byte

### ISSUE THREAD

**Issue by atftb** [mailwatch/1.2.0#155]
If the process to update the GeoIP process doesn't complete properly and leaves behind zero length files in the temp directory, the header information doesn't display on the detail.php page.  If the sparse files are removed, the message header is displayed properly.

The sparse files are left behind when the geoip_update.php process is run and php-curl isn't installed.  No warning is given that the download failed.  I suspect that is because the script exams the return code from curl, but since curl isn't called the rc isn't set, so appears to succeed.  But that's just a SWAG, as I'm not a php programmer.  

The simplest fix to me, seems to be to test that the  GeoIPv6.dat.gz and GeoIP.dat.gz files aren't zero length after download. If they are, they should be deleted so they don't interfere with the header display.  It may be prudent to also look a the status.php code to so it displays regardless of the existence of the zero byte files, as there may be other actions which cause a zero byte file to be created.

Also, php-curl should be noted as a requirement in the docs.

Thanks much.

**Comment by gojensen** [comment]
Seems to be related to https://github.com/mailwatch/1.2.0/issues/153
