### ISSUE TITLE
New template for the future of mailwatch

### ISSUE THREAD

**Issue by MisterM74** [mailwatch/1.2.0#156]
hello
Surely my message not going to please the dev Baruwa, which accepts the number of the year (the bond of the first version is no longer available) and version 2 and only accessible from Centos 6.
So I break you quesiton, there will be t it in the future, a new template for the management of Malwatch panel.
it's a question

Mz

**Comment by endelwar** [comment]
Absolutely yes!
The actual tempalte shows its age and on next version (>= 2.0) there will be an interface redesign.

no ETA at the moment.

**Comment by MisterM74** [comment]
ok with options?
example, manage MailScanner options?
Because for me, it would be more?
nice work
Michel

**Comment by endelwar** [comment]
If I can get it to work properly I would like to move the entire (or part of) MailScanner config in a database table, and manage this info from MailWatch

**Comment by MisterM74** [comment]
Good Good
