### ISSUE TITLE
MAILWATCH_HOME already defined

### ISSUE THREAD

**Issue by MisterM74** [mailwatch/1.2.0#161]
Hello

I have this error in the logs

php: PHP Notice:  Constant MAILWATCH_HOME already defined in /var/www/mailscanner/conf.php on line 88

Mz

**Comment by endelwar** [comment]
On which page are you getting this error? 
There is only one definition of `MAILWATCH_HOME` in all source code.

**Comment by MisterM74** [comment]
Hello
that locate the error in the file mailq.php
We will say that I is not need
In the sense that I use MailScanner / mailwatch with my Postfix Mail server.
I close the subject
thank you
Mz
