### ISSUE TITLE
patch to manage yes/no/other in function get_conf_truefalse

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#164]
Hello!

The current code is not working if « Use SpamAssassin » have other
variable than yes or no. Works now with « Use SpamAssassin =
&SQLNoScan » (

Stephane

```
@@ -1221,7 +1221,13 @@ function get_conf_truefalse($name)
                case "0":
                    return false;
                default:
                    return false;
                break;
             }
             $parameter_value = trim($parameter_value);
             if (strlen($parameter_value) > 0) {
             return (true);
             } else {
                return (false);
            }
        }
    }
```

**Comment by stefaweb** [comment]
I updated my dev server with last code (discard my previous patch).

The problem is back. Some links are now missing (spamassassin --lint, Mailscanner --lint and others).

In Mailscanner.conf
Use SpamAssassin	  &SQLNoScan

![capture d ecran 2015-06-18 a 13 28 02](https://cloud.githubusercontent.com/assets/12907102/8230178/0cf096ca-15be-11e5-9eec-262f1d02cdbc.png)

**Comment by stefaweb** [comment]
But doesn't work.

On other.php, I got:

DISTRIBUTED_SETUP = 1
get_conf_truefalse('UseSpamAssassin') = 1

And the lines are not printed on screen.

Doesn't work.
if (!DISTRIBUTED_SETUP && get_conf_truefalse('UseSpamAssassin') === true) {

**Comment by endelwar** [comment]
That's is how it is meant to work: in distributed setup mailwatch should not be installed on the machines that run mailscanner
