### ISSUE TITLE
ClamD -> Clamd

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#165]
With mailscanner 4.85.2-3 default config, the "ClamD" in rep_viruses.php doesn't work.

Works fine with "Clamd".

rep_viruses.php = $scanner[$vscanner]['name'] = "Clamd";

**Comment by endelwar** [comment]
That's strange, that variable is used only to diplay the antivirus name on the graph.
Which kind of error are you getting?

**Comment by stefaweb** [comment]
Sorry, it seems that the "bug" is gone. I tried again. Not reproductible. In fact, it was a previous problem due of the yes/no script in "Use SpamAssassin &SQLNoScan". ClamAV Status and ClamAV link to their site was not print on other.php screen.

Since, I have changed the get_conf_truefalse function, no problem in other.php and detail.php.

**Comment by stefaweb** [comment]
Hi Manuel!

More for you. A more complete init.d script for sendmail_relay or
postfix_relay.php.

Works with www-data or Debian-exim uid.

Sincerely,

Stéphane



De :  Manuel Dalla Lana <notifications@github.com>
Répondre à :  "mailwatch/1.2.0"
<reply+00c4f25e20c38aa7efb72d71de51c69a20b08c8bf466f6a492cf000000011198f7989
2a169ce0548b1ce@reply.github.com>
Date :  mercredi 17 juin 2015 10:53
À :  "mailwatch/1.2.0" <1.2.0@noreply.github.com>
Cc :  Stéphane Leclerc <sleclerc@actionweb.fr>
Objet :  Re: [1.2.0] ClamD -> Clamd (#165)

**Comment by endelwar** [comment]
you should add the init scripts as text on github as attachments by email don't work
