### ISSUE TITLE
rep_total_mail_by_date.php

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#167]
Hello!

This chart doesn't work here.

I got theses colors by default.

![total_mail_by_date](https://cloud.githubusercontent.com/assets/12907102/8211787/b6b65e66-1518-11e5-992d-338af491a626.png)

And in the code...
rep_total_mail_by_date.php:    $bar1->SetFillColor('blue');
rep_total_mail_by_date.php:    $bar2->SetFillColor('red');
rep_total_mail_by_date.php:    $bar3->SetFillColor('pink');
rep_total_mail_by_date.php:    $bar4->SetFillColor('lightblue');
rep_total_mail_by_date.php:    $line1->SetFillColor('green');

cache is ok. Changes works on SetLegend and new Graph size.

Others report scripts seems to work.

Cheers,

**Comment by stefaweb** [comment]
Problem in code. JPGraph déclarations should be in the right order.
Working on. MCP missing switch. Tomorrow.
![total_mail_by_date png 1434563828](https://cloud.githubusercontent.com/assets/12907102/8214713/54e8e290-152b-11e5-9404-5e350f7ca9a5.png)

**Comment by stefaweb** [comment]
How to upload the new rep_total_mail_by_date.php?

**Comment by endelwar** [comment]
Fork the project (top right button), then push your new file to your new fork, or edit it directly in the browser

**Comment by stefaweb** [comment]
Try with this. Sorry, I'm not a pro of Git.

New file with good color and MCP management.
https://gist.github.com/stefaweb/a276a2d357a7c8a9f0a3

**Comment by stefaweb** [comment]
Colors are not very nice but it's working.

![total_mail_by_date png 1434614102](https://cloud.githubusercontent.com/assets/12907102/8226686/284232b6-15a1-11e5-84a9-5ba4c93681a4.png)

**Comment by endelwar** [comment]
Good work Stéphane!

**Comment by stefaweb** [comment]
I've done the fork but not sure as it work.
https://github.com/stefaweb/1.2.0

Update sendmail_relay.php
Update sendmail_relay.init
Update rep_sa_score_dist.php
Update rep_total_mail_by_date.php

**Comment by endelwar** [comment]
Yes, that's the way to go! Just push the "pull request" button on https://github.com/stefaweb/1.2.0 to create a merge request of your editing.
