### ISSUE TITLE
GeoIP php library and GeoIP extension are in conflict

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#175]
Added  E_NOTICE.

// Set error level (some distro's have php.ini set to E_ALL)
if (version_compare(phpversion(), '5.3.0', '<')) {
    error_reporting(E_ALL);
} else {
    // E_DEPRECATED added in PHP 5.3
   //  E_NOTICE  added in PHP 5.4
    error_reporting(E_ALL ^ E_DEPRECATED ^ E_STRICT ^ E_NOTICE);
}

**Comment by endelwar** [comment]
Where is E_NOTICE triggered in the code?
It's better to fix the problem that hide it.

**Comment by stefaweb** [comment]
in detail.php.

Notice: Constant GEOIP_COUNTRY_EDITION already defined in /var/www/mailscanner/lib/geoip.inc on line 31

Notice: Constant GEOIP_PROXY_EDITION already defined in /var/www/mailscanner/lib/geoip.inc on line 32

Notice: Constant GEOIP_ASNUM_EDITION already defined in /var/www/mailscanner/lib/geoip.inc on line 33

Notice: Constant GEOIP_NETSPEED_EDITION already defined in /var/www/mailscanner/lib/geoip.inc on line 34

Notice: Constant GEOIP_REGION_EDITION_REV0 already defined in /var/www/mailscanner/lib/geoip.inc on line 35

Notice: Constant GEOIP_REGION_EDITION_REV1 already defined in /var/www/mailscanner/lib/geoip.inc on line 36

Notice: Constant GEOIP_CITY_EDITION_REV0 already defined in /var/www/mailscanner/lib/geoip.inc on line 37

Notice: Constant GEOIP_CITY_EDITION_REV1 already defined in /var/www/mailscanner/lib/geoip.inc on line 38

Notice: Constant GEOIP_ORG_EDITION already defined in /var/www/mailscanner/lib/geoip.inc on line 39

Notice: Constant GEOIP_ISP_EDITION already defined in /var/www/mailscanner/lib/geoip.inc on line 40

Notice: Constant GEOIP_UNKNOWN_SPEED already defined in /var/www/mailscanner/lib/geoip.inc on line 51

Notice: Constant GEOIP_DIALUP_SPEED already defined in /var/www/mailscanner/lib/geoip.inc on line 52

Notice: Constant GEOIP_CABLEDSL_SPEED already defined in /var/www/mailscanner/lib/geoip.inc on line 53

Notice: Constant GEOIP_CORPORATE_SPEED already defined in /var/www/mailscanner/lib/geoip.inc on line 54

Notice: Constant GEOIP_DOMAIN_EDITION already defined in /var/www/mailscanner/lib/geoip.inc on line 55

**Comment by endelwar** [comment]
do you have php geoip extension installed? I think that php library and extension are in conflict

**Comment by stefaweb** [comment]
Yes.

ii  php5-geoip                            1.0.7-8
