### ISSUE TITLE
on/off RCP flag

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#176]
If the hostname in server and Mailscanner.conf hostname are not ok (case in my dev server).

I got error in detail.php (and may be other pages) as RPC try to go on the original server.

XML-RPC Error: Didn't receive 200 OK from remote server. (HTTP/1.1 404 Not Found)

May be a RPC ON/OFF flag will be useful in conf.php

define('RPC_ON', false);

This in functions.php cause the problem.

function is_local($host)
{
    $host = strtolower($host);
    // Is RPC required to look-up??
    $sys_hostname = strtolower(chop(`hostname`));
    switch ($host) {
        case $sys_hostname:
        case gethostbyaddr('127.0.0.1'):
            return true;
        default:
            // Remote - RPC needed
            return false;
    }
}

**Comment by endelwar** [comment]
You got this error when you import a database on a machine that has a different name (like in dev environment, as you discovered): this is the normal behaviour needed to know if a machine is local or not.

By the way I wrote a simple application to generate email for testing a smtp server (and MailWatch), you can find it here https://github.com/endelwar/spammer

**Comment by stefaweb** [comment]
ok
