### ISSUE TITLE
LDAPS authentication error

### ISSUE THREAD

**Issue by dp4qb** [mailwatch/1.2.0#178]
Hello.
I've stumbled upon LDAPS auth error.
My conf.php looks like this:

    define('USE_LDAP',         '1');
    define('LDAP_HOST',        'dc.site.local');
    define('LDAP_PORT',        '636');
    define('LDAP_DN',          'dc=site,dc=local');
    define('LDAP_USER',        'cn=user,dc=site,dc=local');
    define('LDAP_PASS',        'pass');
    define('LDAP_SITE',        'site');
    define('LDAP_EMAIL_FIELD', 'proxyaddresses');
    define('LDAP_MS_AD_COMPATIBILITY', true);

It always throws "Could not search" with these errors in apache log:

    PHP Warning:  ldap_bind(): Unable to bind to server: Can't contact LDAP server in mailscanner/functions.php on line 2348, referer: http://ip/mailscanner/login.php
    PHP Warning:  ldap_search(): Search: Can't contact LDAP server in mailscanner/functions.php on line 2352, referer: http://ip/mailscanner/login.php

I've figured out that it tries to connect without ssl and fails. This workaround helped.

    $ds = ldap_connect('ldaps://'.LDAP_HOST, LDAP_PORT) or die ("Could not connect to " . LDAP_HOST);
    // $ds = ldap_connect(LDAP_HOST, LDAP_PORT) or die ("Could not connect to " . LDAP_HOST);

I suggest, there should be some protocol switch depends on port, because setting 

    define('LDAP_HOST',        'ldaps://dc.site.local');

doesn't solving the issue.

**Comment by endelwar** [comment]
Could you please test the new code that I pushed earlier today?

**Comment by dp4qb** [comment]
Everything works. Thanks :)
