### ISSUE TITLE
Wrong print on some Subject

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#179]
Some message do not print well on screen (crédit adapté).

![capture d ecran 2015-06-18 a 14 14 10](https://cloud.githubusercontent.com/assets/12907102/8230906/c66f338a-15c4-11e5-8f2a-7b40cc1b04a7.png)

Exim log:
/var/log/exim4/mainlog.4.gz:2015-06-13 01:21:38 1Z3YGY-0002UC-QN <= reply@bounces.shopimium.eu H=mta.52.196.smtp.fr [37.60.52.196]:59515 I=[62.210.166.11]:25 P=esmtp S=10245 id=a57ec1612ad34d5cc1af36ca69387561@localhost.localdomain T="Demandez un crédit adapté" from reply@bounces.shopimium.eu for xxx@xxx.org

In mysql:

![capture d ecran 2015-06-18 a 14 18 31](https://cloud.githubusercontent.com/assets/12907102/8230944/026a8f06-15c5-11e5-9e62-498aaad2c306.png)
##

**Comment by stefaweb** [comment]
crédit adapté
00000000  63 72 c3 a9 64 69 74 20  61 64 61 70 74 c3 a9 0a  |cr..dit adapt...|
00000010

This comes from the old mailwatch 1.x. I have to try it with the new code.

**Comment by endelwar** [comment]
Has this message been logged before converting the database to UTF-8?

**Comment by stefaweb** [comment]
I should do more test as explained.
I also found some "empty" Subject too (but present in the log and database).

**Comment by stefaweb** [comment]
Seems to work on the dev server.
Will have to check when new code will be on the production server.

![capture d ecran 2015-06-19 a 09 12 47](https://cloud.githubusercontent.com/assets/12907102/8248864/2ef0412a-1664-11e5-8230-3d009bd2c8a3.png)

**Comment by endelwar** [comment]
any feedback on this?

**Comment by stefaweb** [comment]
I should switch the code on the production server. Seems that the problem is related to special header arriving in my gateway. I can't reproduce it on the dev platform.

Let it open. I'll will try when time will be ok to push the code on my production platform.

**Comment by endelwar** [comment]
did you updated your production code? any feedback?

**Comment by endelwar** [comment]
up

**Comment by endelwar** [comment]
This should be resolved with migration to utf8mb4

**Comment by stefaweb** [comment]
Great job.
I'll will try.

**Comment by stefaweb** [comment]
Don't work.

On console, I typed:

Subject: test utf8 &éèààà
dfsfdsf èèè!!éé

And in the MS screen I got:

![capture d ecran 2016-12-05 a 13 17 46](https://cloud.githubusercontent.com/assets/12907102/20884745/763f1b76-baed-11e6-8775-356cb3eb7ae8.png)

**Comment by endelwar** [comment]
did you converted your database to utf8mb4 like described in tools/UTF8_Database/readme.md

**Comment by stefaweb** [comment]
In the database:

![capture d ecran 2016-12-05 a 13 21 50](https://cloud.githubusercontent.com/assets/12907102/20884848/e7bfdefc-baed-11e6-9718-6d57f886c574.png)

**Comment by stefaweb** [comment]
Yes, I run the script.

**Comment by stefaweb** [comment]
Table structure (export) after ran the script:

CREATE TABLE IF NOT EXISTS `maillog` (
  `timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `id` text,
  `size` bigint(20) DEFAULT '0',
  `from_address` text,
  `from_domain` text,
  `to_address` text,
  `to_domain` text,
  `subject` text,
  `clientip` text,
  `archive` text,
  `isspam` tinyint(1) DEFAULT '0',
  `ishighspam` tinyint(1) DEFAULT '0',
  `issaspam` tinyint(1) DEFAULT '0',
  `isrblspam` tinyint(1) DEFAULT '0',
  `isfp` tinyint(1) DEFAULT '0',
  `isfn` tinyint(1) DEFAULT '0',
  `spamwhitelisted` tinyint(1) DEFAULT '0',
  `spamblacklisted` tinyint(1) DEFAULT '0',
  `sascore` decimal(7,2) DEFAULT '0.00',
  `spamreport` text,
  `virusinfected` tinyint(1) DEFAULT '0',
  `nameinfected` tinyint(1) DEFAULT '0',
  `otherinfected` tinyint(1) DEFAULT '0',
  `report` text,
  `ismcp` tinyint(1) DEFAULT '0',
  `ishighmcp` tinyint(1) DEFAULT '0',
  `issamcp` tinyint(1) DEFAULT '0',
  `mcpwhitelisted` tinyint(1) DEFAULT '0',
  `mcpblacklisted` tinyint(1) DEFAULT '0',
  `mcpsascore` decimal(7,2) DEFAULT '0.00',
  `mcpreport` text,
  `hostname` text,
  `date` date DEFAULT NULL,
  `time` time DEFAULT NULL,
  `headers` text,
  `quarantined` tinyint(1) DEFAULT '0',
  KEY `maillog_datetime_idx` (`date`,`time`),
  KEY `maillog_id_idx` (`id`(20)),
  KEY `maillog_clientip_idx` (`clientip`(20)),
  KEY `maillog_from_idx` (`from_address`(200)),
  KEY `maillog_to_idx` (`to_address`(200)),
  KEY `maillog_host` (`hostname`(30)),
  KEY `from_domain_idx` (`from_domain`(50)),
  KEY `to_domain_idx` (`to_domain`(50)),
  KEY `maillog_quarantined` (`quarantined`),
  KEY `timestamp_idx` (`timestamp`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

**Comment by endelwar** [comment]
default charset should be utf8mb4, and collation of text fields utf8mb4_general_ci

**Comment by stefaweb** [comment]
This time, message sent using my Macintosh (using Outlook OSX 15):

![capture d ecran 2016-12-05 a 13 29 10](https://cloud.githubusercontent.com/assets/12907102/20885039/f91364ca-baee-11e6-8493-1a65f19a4f06.png)

Result on MS:

![capture d ecran 2016-12-05 a 13 27 44](https://cloud.githubusercontent.com/assets/12907102/20884999/c857a63e-baee-11e6-812b-442d084eeb2a.png)

**Comment by stefaweb** [comment]
After ran the script, the database is still mixed and not well setup:

![capture d ecran 2016-12-05 a 13 33 45](https://cloud.githubusercontent.com/assets/12907102/20885182/af45805c-baef-11e6-801c-e82906285527.png)

**Comment by stefaweb** [comment]
Sorry, I'm lost.

I use MySQL 5.5.53 and ran upgrade_mysql_db_to_utf8.

If I understand the readme.md, I should use upgrade_mysql_db_to_utf8mb4.sql only when using a prior version ?

**Comment by stefaweb** [comment]
More on this.

At start the database is utf8_general_ci:

![capture d ecran 2016-12-05 a 13 59 18](https://cloud.githubusercontent.com/assets/12907102/20885832/4becfc34-baf3-11e6-916d-cc57af23dd15.png)

After script upgrade_mysql_db_to_utf8.sql, the database is now utf8_unicode_ci:

![capture d ecran 2016-12-05 a 14 00 14](https://cloud.githubusercontent.com/assets/12907102/20885858/69982c9a-baf3-11e6-8762-30701e3b0dd6.png)

**Comment by stefaweb** [comment]
No change if I use upgrade_mysql_db_to_utf8mb4.sql. The database is converted to utf8mb4 but characters are not well coded.

**Comment by endelwar** [comment]
> If I understand the readme.md, I should use upgrade_mysql_db_to_utf8mb4.sql only when using a prior version ?
if your mysql is newer than 5.5.3 you have full utf8 support, and not limited like before: that is called utf8mb4 in mysql terms

**Comment by endelwar** [comment]
running `upgrade_mysql_db_to_utf8mb4.sql` should convert tables and text fields to utf8mb4_unicode_ci like img below.

![mw_utf8](https://cloud.githubusercontent.com/assets/28512/20898195/bb98646a-bb25-11e6-923b-25e8c90a08fb.png)
![mw_utf8mb4](https://cloud.githubusercontent.com/assets/28512/20898205/bee6f262-bb25-11e6-9fbe-c00cb306bfa7.png)

**Comment by stefaweb** [comment]
Hello!

Something changed somewhere. It's working now.

![capture d ecran 2016-12-05 a 20 15 51](https://cloud.githubusercontent.com/assets/12907102/20898749/c623ab4a-bb27-11e6-99f8-e770c6d68c6e.png)

I updated MailWatch.pm and tools/Sendmail_queue/mailq.php.
