### ISSUE TITLE
New link order proposal in reports.php

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#182]
Total Messages by Date
Top Mail Relays
Top Viruses
Virus Report
Top Senders by Quantity
Top Senders by Volume
Top Recipients by Quantity
Top Recipients by Volume
Top Sender Domains by Quantity
Top Sender Domains by Volume
Top Recipient Domains by Quantity
Top Recipient Domains by Volume
SpamAssassin Score Distribution
SpamAssassin Rule Hits
Message Listing
Message Operations
MailWatch Audit Log                  (added MailWatch)

Can we do something for "To set date you must use YYYY-mm-dd format" (not urgent)?

**Comment by endelwar** [comment]
Message Operations and Message Listing are the functions that I use 99% of the time I use MailWatch, I think that they should be on top.

**Comment by stefaweb** [comment]
Not a problem. I close.
