### ISSUE TITLE
Long black/whitelists have become slow 

### ISSUE THREAD

**Issue by darky83** [mailwatch/1.2.0#204]
Long black/whitelists have become slow.

Confirmed in testing myself, in previous versions (beta 2 is the last one I tested) loading a black/whitelist with 1000+ entry's is done in a second, 

Now the same list takes up toe 20 seconds to load.

See also the topic here:
https://forum.efa-project.org/viewtopic.php?f=14&t=1115

**Comment by stefaweb** [comment]
I confirm. Very fast in 1.x. Very slow in curent version.

Another small problem. System time in top left screen is only printed when page is completely loaded.

**Comment by endelwar** [comment]
And with this bugfix I'm going on vacation for a week, bye bye ;)

**Comment by darky83** [comment]
have an good vacation :) thanks for all your work.
