### ISSUE TITLE
Whishlist for rep_total_mail_by_date.php

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#206]
If column is empty don't print.

Will permit very often to fit the table in screen.

![capture d ecran 2015-06-26 a 09 00 48](https://cloud.githubusercontent.com/assets/12907102/8372267/f664773a-1be1-11e5-817d-7fb4c17d1ac0.png)

**Comment by endelwar** [comment]
This should be fixed by #250
