### ISSUE TITLE
Bug in user_manager.php

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#209]
Since last merge, the user management page is no longer working at all.

When I go the page, I got:

![capture d ecran 2015-06-26 a 18 16 43](https://cloud.githubusercontent.com/assets/12907102/8381997/e118566e-1c2f-11e5-937b-515d9f2987db.png)

**Comment by stefaweb** [comment]
Thanks you @endelwar .

@rafaelbsd have trouble to commit all theses changes (merge). He sent me a direct mail. Lost with Git too. For me, I'm starting to fill better with Git. I was an old Subversion user...

**Comment by rafaelbsd** [comment]
Hi, @endelwar and @stefaweb. Should I keep commiting the everyday changes or do you prefer that I first work a few days and then commit the changes?

About the user_manager.php problem I didn´t undertand what was wrong, because I´m modfying the code direct in my webserver, to get any problems immediatly. And I haven´t see any problem on this file....

Thanks!!

**Comment by endelwar** [comment]
I prefer that you work on your branch until you consider that code a work of art and then commit when you are confident that the code works great in every situation.

also squash all your commits into one (or more if they are significant)

I'm going on vacation for a week, good work to you ;)

**Comment by endelwar** [comment]
The problem was on an unescaped apostrophe in French translation

**Comment by rafaelbsd** [comment]
Ok... now I undertood.... About the commits, what I can do (to let other translators test it too) is to commit my changes, but not open a pull request. After I finishged, I´ll squash my commits in only one, as you suggested. 

Yeah! Vacation in Italy (or Paris, @stefaweb )... what I dream!!! ehehehe

Have a nice time @endelwar !!!

**Comment by stefaweb** [comment]
Hi @endelwar !

Have a nice vacations too.

Me, it's only for August.
