### ISSUE TITLE
Bug in login.php

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#213]
MailWatch logo not printed.

![capture d ecran 2015-06-27 a 09 08 50](https://cloud.githubusercontent.com/assets/12907102/8390926/3b706a80-1cac-11e5-941d-7e08ba4047b6.png)

**Comment by stefaweb** [comment]
@endelwar 
Back from vacations!

No new from @rafaelbsd.

**Comment by rafaelbsd** [comment]
Hey, guys...

Rough week.... Couldn´t work on this project... I hope I restart it today....

**Comment by rafaelbsd** [comment]
Hi guys. Just uploaded more translations, mostly on the report form. 
Cheers!

**Comment by stefaweb** [comment]
@rafaelbsd 
When do you think to merge with master project?

I will be absent starting tomorrow until July 15.

**Comment by rafaelbsd** [comment]
Hi @stefaweb , I agreed with @endelwar to finish all the translation and then submit one big merge request. I believe that about 70% of the work is done, so when you get back it will be merged. I visited your company´s webpage and saw that you offer solutions based on this tool (as I do too). So I am very exciting about your submits too.

Cheers!!

**Comment by stefaweb** [comment]
Hi!

I'm back. No problem to wait for merge when you will have finished. I'm here until August 4th. After, I will leave for 20 days.

Cheers.
