### ISSUE TITLE
Whishlist for translation

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#216]
When a i18 variable is missing in a specific language, print:

i18_missing message + (variable name)

Example:

Not translated yet (colorcodes03)

With this, no need to look at the code and find the variable to add something in language file.

**Comment by endelwar** [comment]
I was thinking about leaving the English text on untranslated string and adding the "not translated yet" in parenthesis if debug is enabled so that usability is better for day-to-day usage by average user

**Comment by stefaweb** [comment]
@endelwar 

ok but add the variable name.

**Comment by endelwar** [comment]
this was fixed a log time ago in 626ca53bed5b15bce3b7fb54b6d1270e550490f7
