### ISSUE TITLE
MD5 password hash is a shame!

### ISSUE THREAD

**Issue by endelwar** [mailwatch/1.2.0#217]
We are in 2015, password should be hashed in a better and secure way

**Comment by stefaweb** [comment]
Hi @endelwar!

I can see that you upgraded sql schema. May be "upgrade.php" should be upgraded too?

**Comment by endelwar** [comment]
There is an automated upgrade command in the password check code ( see [there] (https://github.com/mailwatch/1.2.0/blob/cdc2fd4b604c07669dc1dfcf857471c0f27ec9a2/mailscanner/functions.php#L3320-L3328)).
Another commit is coming that will change the sql schema a bit and the upgrade.php file will be taken care of

**Comment by stefaweb** [comment]
Really great.
