### ISSUE TITLE
Why mailscanner as base directory?

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#218]
Not important, but if you're agree and have free time...

Why the MailWatch directory is called "mailscanner" as we talk of MailWatch?

We can may be rename it "mailwatch".

And.

Currently, the default path is "/var/www/html/mailscanner". According to Debian rules, the correct path should be "/var/www/mailscanner".

**Comment by endelwar** [comment]
It's there for historical reason, Steve (the original author) made the decision.

in 2.0 release everything will be different, and some webserver config will be necessary
