### ISSUE TITLE
StyleCI Header Config

### ISSUE THREAD

**Issue by GrahamCampbell** [mailwatch/1.2.0#222]
It looks like you've got too many spaces in your header config before each line.

**Comment by GrahamCampbell** [comment]
Looks like you've corrected it. If you need anything, ping me. :)

**Comment by endelwar** [comment]
Thanks Graham, I'm working on style right now as you seen ;)
why hasn't styleci.io catched the php files in /tools dir? is it because they are script with a shebang?

**Comment by GrahamCampbell** [comment]
It seems to be fixing things in the tools directory? Do you mean the header isn't working?

**Comment by GrahamCampbell** [comment]
I think that's probably due to the comment at the start of the file.

**Comment by endelwar** [comment]
yes, the header with copyright wasn't changed
