### ISSUE TITLE
quarantine_report.php & login

### ISSUE THREAD

**Issue by mealerz** [mailwatch/1.2.0#226]
Hi,
Upon receiving this report you want to view a message, but you are not logged into mailwatch. When you click on the view icon within the email you receive, it takes you to the login page. When you log in, it just logs in and doesn't take you to the message in question. 
Can this be fixed? Something to do with url passthrough? I'm not sure. 

Thanks,
Rich
##

**Comment by mealerz** [comment]
Or cookies? http://stackoverflow.com/questions/12885538/php-curl-and-cookies

**Comment by asuweb** [comment]
This could be fixed by storing the `$_SEERVER['QUERY_STRING']` in the `$_SESSION['QUERY_STRING']` in he login.functions.php.

And appending the `$_SESSION['QUERY_STRING']` to the `$redirect_url` in checklogin.php

**Comment by asuweb** [comment]
It seems this has already been fixed.  It works on both of my versions.  RC3 & Develop

**Comment by mealerz** [comment]
Yes I agree, I think it was fixed when the login pages changed a while ago. I think this can be closed.
