### ISSUE TITLE
SQL errors possible via Reports page

### ISSUE THREAD

**Issue by kairu0** [mailwatch/1.2.0#228]
Searching for emails using "To" or "From" (others?) where the search term contains a single quote will throw a SQL error. e.g. "me'@example.com". I am using v1.2.0 RC1 DEV, in case that matters.

**Comment by atftb** [comment]
Did you try escaping the single quote, i.e. :me\’ @example.com”?  Don’t know if that will work or not but worth a shot.
You could also just create a filter statement saying from contains “me” and a 2nd saying from contains example.com.

...Kevin
--
Kevin Miller
Network/email Administrator, CBJ MIS Dept.
155 South Seward Street
Juneau, Alaska 99801
Phone: (907) 586-0242, Fax: (907) 586-4500 Registered Linux User No: 307357

**Comment by kairu0** [comment]
I actually don't need to search for an address containing a single quote. I just wanted to raise this as a possible security/stability issue. Single quotes in email addresses do seem to be permitted per RFC 5322, so maybe the reports page could automatically escape them?
