### ISSUE TITLE
PieGraph images are cropped on the right hand side

### ISSUE THREAD

**Issue by georgepatterson** [mailwatch/1.2.0#229]
With MailWatch 1.2.0 and PHP5.45 on Centos 6.7, we have found that the Piegraphs are cropped on the right hand side for the virus reports.
![top_mail_relays png 1442458117](https://cloud.githubusercontent.com/assets/123958/9923623/78e6cdb8-5d3a-11e5-84a6-e6f220edce2f.png)

We have found that changing the SetCenter from 0.73 to 0.70 move the Pie Graph to the left enough to be able to see the entire percentage.

The files to modify are as follows:-
- rep_top_mail_relays.php
- rep_top_recipient_domains_by_quantity.php
- rep_top_recipient_domains_by_volume.php
- rep_top_recipients_by_quantity.php
- rep_top_recipients_by_volume.php
- rep_top_sender_domains_by_quantity.php
- rep_top_sender_domains_by_volume.php
- rep_top_senders_by_quantity.php
- rep_top_senders_by_volume.php
- rep_top_viruses.php

Loom for the line
    $p1->SetCenter(0.73, 0.4);
and change it to
    $p1->SetCenter(0.70, 0.4);

Please let me know if you'd like this submitted as a patch (I haven't done a pull request as yet)

For completeness, I have included the version of the major software:
MailWatch Version:1.2.0 - RC1 DEV
MailScanner Version:4.85.2

SpamAssassin Version:3.4.0
PHP Version:5.4.45
MySQL Version:10.0.21-MariaDB-wsrep

**Comment by endelwar** [comment]
thanks!
