### ISSUE TITLE
en-us and en-uk report directories

### ISSUE THREAD

**Issue by atftb** [mailwatch/1.2.0#230]
Rather than a single %report-dir%/en directory, it would be nice to have it broken down into en-us and en-uk.  The current current reports contain verbiage referring to RIPA which doesn't exist in outside of Great Britain and which need to be edited out when installing MailWatch.  The US flavor would contain the same messages sans the RIPA warning.  This would save having to edit them, and/or delete .rpmnew files following an upgrade.

Thanks...

**Comment by endelwar** [comment]
this should be forwarded to @MailScanner, what do you think @jcbenton?

**Comment by jcbenton** [comment]
I plan on changing the language at some point anyway.

**Comment by atftb** [comment]
You’re quite right.
Excuse me while I go wipe the egg from my face...

...Kevin
--
Kevin Miller
Network/email Administrator, CBJ MIS Dept.
155 South Seward Street
Juneau, Alaska 99801
Phone: (907) 586-0242, Fax: (907) 586-4500 Registered Linux User No: 307357
