### ISSUE TITLE
postfix_relay.php error if bad line on log

### ISSUE THREAD

**Issue by olarriga** [mailwatch/1.2.0#235]
If there is a bad line (this can occur after an inexpected reboot) on mail.log file the postfix_relay.php generate the error:
Notice: Undefined index:  in /var/www/mailscanner/postfix_relay.php on line 77
The line causing the error:
Nov  3 14:03:53 mxa postfix/smtpd[30179]: disconnect from localhost[127.0.0.1]
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@Nov  3 14:31:14 mxa opendmarc[592]: OpenDMARC Filter v1.3.0 starting (args: -c /etc/opendmarc.conf -u opendmarc -P /var/run/opendmarc/opendmarc.pid -p local:/var/spool/postfix/opendmarc/opendmarc.sock)
Nov  3 14:31:14 mxa opendmarc[592]: trusted authentication services: (none)
##

**Comment by endelwar** [comment]
are the strange chars "^@" a the begining of the line or on a line on its own? Can you tell me with char is it (hex code would be great)?

**Comment by endelwar** [comment]
Any feedback to provide?
