### ISSUE TITLE
MailWatch.pm does not log messages with certain UTF8 subjects

### ISSUE THREAD

**Issue by spamcopper** [mailwatch/1.2.0#238]
Version: Mailwatch 1.2.0
OS: FreeBSD 10.2
perl5-5.20.3_8
p5-Encoding-FixLatin-1.04
p5-DBD-SQLite-1.48 
p5-DBD-mysql-4.033 
p5-DBI-1.634   
mysql55-server-5.5.46
 
All mysql tables are utf8/utf8_general_ci

Example subject:

Subject: =?UTF-8?B?VGlja2V0IEFsZXJ0IPCfk6MgbWV0IEJydWNlIFNwcmluZ3N0ZWVu?=
 =?UTF-8?B?LCBWYW5lc3NhIENhcmx0b24sIEJpcmR5LCBQcmltZXJhIGVuIG1lZXI=?=

Output dbitrace.log:

Incorrect string value: '\xF0\x9F\x93\xA3 m...' for column 'subject' at row 1 error 1366 recorded: Incorrect string value: '\xF0\x9F\x93\xA3 m...' for column 'subject' at row 1
                <-- do_error
IGNORING ERROR errno 0
 <- dbd_st_execute returning imp_sth->row_num 18446744073709551614
    !! ERROR: 1366 'Incorrect string value: '\xF0\x9F\x93\xA3 m...' for column 'subject' at row 1' (err#0)
    <- execute= ( undef ) [1 items] at MailWatch.pm line 134
    -- DBI::END ($@: , $!: )
    -> disconnect_all for DBD::mysql::dr (DBI::dr=HASH(0x808065ca8)~0x80807abd0) thr#801c19e00
    <- disconnect_all= ( ) [0 items] (not implemented) at DBI.pm line 762
!   -> DESTROY for DBD::mysql::st (DBI::st=HASH(0x8080655d0)~INNER) thr#801c19e00
        Freeing 34 parameters, bind 0 fbind 0
       ERROR: 1366 'Incorrect string value: '\xF0\x9F\x93\xA3 m...' for column 'subject' at row 1' (err#0)
!   <- DESTROY= ( undef ) [1 items] during global destruction
!   -> DESTROY for DBD::mysql::db (DBI::db=HASH(0x8077dba50)~INNER) thr#801c19e00
imp_dbh->pmysql: 80748d500
       ERROR: 1366 'Incorrect string value: '\xF0\x9F\x93\xA3 m...' for column 'subject' at row 1' (err#0)
!   <- DESTROY= ( undef ) [1 items] during global destruction
!   -> DESTROY in DBD::_::common for DBD::mysql::dr (DBI::dr=HASH(0x80807abd0)~INNER) thr#801c19e00
!   <- DESTROY= ( undef ) [1 items] during global destruction
    -> selectrow_array for DBD::SQLite::db (DBI::db=HASH(0x80b76d948)~0x80b8c31c8 DBI::st=HASH(0x80cf181c8) undef 'u1C9lMTZ088365') thr#801c19e00
    <- selectrow_array= ( ) [0 items] at Sendmail.pm line 1078
    -> execute for DBD::SQLite::st (DBI::st=HASH(0x80cf22c90)~0x809fdd7b0 'u1C9lMTZ088365' 1 1455270801) thr#801c19e00
    <- execute= ( 1 ) [1 items] at Sendmail.pm line 1118
    -- DBI::END ($@: , $!: )
    -> disconnect_all for DBD::SQLite::dr (DBI::dr=HASH(0x809f99240)~0x809f992d0) thr#801c19e00
    <- disconnect_all= ( '' ) [1 items] at DBI.pm line 762
!   -> DESTROY for DBD::SQLite::st (DBI::st=HASH(0x809fdd7b0)~INNER) thr#801c19e00
sqlite trace: Finalizing statement: 80b5c2a08 at dbdimp.c line 1273
sqlite trace: Removing statement from list: 80b5c2a08

**Comment by spamcopper** [comment]
Subject without CR:

Subject: =?UTF-8?B?VGlja2V0IEFsZXJ0IPCfk6MgbWV0IEJydWNlIFNwcmluZ3N0ZWVu?==?UTF-8?B?LCBWYW5lc3NhIENhcmx0b24sIEJpcmR5LCBQcmltZXJhIGVuIG1lZXI=?=

**Comment by endelwar** [comment]
Could you provide 2 example queue file with these subjects to test them in my local environment?

**Comment by spamcopper** [comment]
Mailed 2 queue files to endelwar**[at]**aregar.it

**Comment by spamcopper** [comment]
As a temp fix I changed line 284 from

`$msg{subject} = fix_latin($message->{utf8subject});`

to

`$msg{subject} = fix_latin($message->{subject});`

The 2  example queue files are logged okay now.

**Comment by spec1re** [comment]
@stefaweb 

http://www.perlmonks.org/?node_id=745506

> The point is that perl still uses a single byte internally for characters in the original the Latin-1 range (from iso-8859-1), and even when perl has flagged a latin-1 string as being utf8 data, you should "encode" it into an external (true multibyte) form before sending it to the database. 

This could be a cause for the "DBD::mysql::st execute failed: Incorrect string value" error?
