### ISSUE TITLE
Uncaught Error: Call to undefined function mysql_connect()

### ISSUE THREAD

**Issue by dbjansen** [mailwatch/1.2.0#239]
This error started happening recently.  I can identify no changes that were made that would cause it to have happened, in other words: it worked last time I used it!

[Mon Mar 21 14:27:56 2016] [error] [client xxx.xxx.xxx.xxx] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /www/mailscanner/functions.php:747\nStack trace:\n#0 /www/mailscanner/functions.php(816): dbconn()\n#1 /www/mailscanner/checklogin.php(53): safe_value('luser')\n#2 {main}\n  thrown in /www/mailscanner/functions.php on line 747, referer: https://www.domainname.com/mailscanner/login.php?error=emptypassword

I have searched the Internets looking for similar problems, checked my configuration, file permissions, and php setup.  MediaWiki, Wordpress and other interfaces that access the database have no issues.

Is there some advice that you may have for me?

**Versions:**
MailScanner version 4.85.2
    1.00     AnyDBM_File
    1.835   DB_File
    1.634   DBI
mailwatch version 1.2.0
Mysql Version 14.14 Distrib 5.7.10, for Linux

**Comment by endelwar** [comment]
Did you update your php version or disabled the (deprecated) mysql extension? MailWatch won't work without the old mysql extension until all code is migrated to a different mysql extension (mysqli or pdo)

**Comment by dbjansen** [comment]
I updated the php version, it is:

 

PHP 7.0.4 (cli) (built: Mar  5 2016 01:46:27) ( NTS )

Copyright (c) 1997-2016 The PHP Group

Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies

    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

    with Xdebug v2.4.0RC3, Copyright (c) 2002-2015, by Derick Rethans

 

… and it was working, it also has the latest CentOS repository MySQL on it.

 

Which extension would I disable and where?

 

Thank you.

**Comment by endelwar** [comment]
I'm sorry but on php7 the deprecated mysql extension (http://php.net/mysql_connect) is removed and MailWatch won't work on this php version as is. MailWatch 1.2 is compatible only with php 5.

**Comment by dbjansen** [comment]
I understand.  I do not know how it worked at all with 7 then, as it did for a week.

 

I appreciate your assistance.
