### ISSUE TITLE
HIDE_NON_SPAM option side effect

### ISSUE THREAD

**Issue by shawniverson** [mailwatch/1.2.0#240]
One of our more astute members of the community pointed out that hiding non-spam from quarantine reports may have the unintended effect of also hiding the other categories (such as Bad Content) because it is technically also non-spam.  This may be fine for some but not for others.

Suggest either

1) Changing this to "HIDE_UNKNOWN" to hide any content not flagged in some fashion and adjusting the SQL query.

or

2) Leaving this setting, since some may only want spam in reports, and just adding "HIDE_UNKNOWN" as another option.

Let me know your thoughts.  I have some code I am testing.

**Comment by asuweb** [comment]
I'd recommend having it as an option in the config, that way you cover both camps.

**Comment by endelwar** [comment]
I prefer the second option, it's better, for 1.2 release, to not modify historical options behaviour, but rather add a second option (documented in conf.php and in docs) that modify the first option's actions
