### ISSUE TITLE
Any password works when LDAP is enabled

### ISSUE THREAD

**Issue by shawniverson** [mailwatch/1.2.0#246]
When USE_LDAP is set to true, a fault in the new logic of checklogin.php allows anyone to log in with any password.

Problem is on line 77 in which the password checking routine is enclosed within  if (USE_LDAP === false). 

Therefore, it doesn't matter if LDAP auth above succeeds or fails, user is given a login success regardless

**Comment by endelwar** [comment]
Thanks, fixed in master and development branches
