### ISSUE TITLE
Not being allowed to release Virus quarantined messages

### ISSUE THREAD

**Issue by techeez** [mailwatch/1.2.0#253]
No one is able to release Virus quarantined messages unless it is done manually from the command line. At least the Admins should be able to do it.
##

**Comment by endelwar** [comment]
What's the value of MailScanner.conf `Quarantine Silent Viruses`? If set to `no` all virus type defined in `Silent Viruses` won't be quarantined, and consequently can't be released

**Comment by asuweb** [comment]
Can't find any issues with this.  It works on my mailscanners
