### ISSUE TITLE
Garbage content in detail.php Spam report

### ISSUE THREAD

**Issue by Kharag** [mailwatch/1.2.0#257]
Hi,

since the last update to Mailwatch 1.2.0 RC2 we have an issue with the spam report in the detail.php
I attached a picture to better describe it.
It looks like the content of the spam report is split incorrect...

![spam_report](https://cloud.githubusercontent.com/assets/2721885/16612290/749cf5bc-4366-11e6-8377-e913d6583ca1.png)

The relevant database entry (spamreport) looks like this:

 spam, SpamAssassin (zwischen gespeichert, Wertung=14.223, benoetigt 5, DCC_CHECK 2.00, DKIM_ADSP_CUSTOM_MED 0.00, FORGED_YAHOO_RCVD 1.02, FREEMAIL_FROM 2.00, NML_ADSP_CUSTOM_MED 1.20, RDNS_NONE 1.00, URIBL_BLACK 7.00)

I'm not sure why the report is in german to begin with (we are located in Austria) - we are specifically using english locales on our servers to avoid such issues.

It does not seem to cause any malfunctions but it's confusing at a first glance :)
Please let me know if you need any information.

**Comment by endelwar** [comment]
I think that spamassassin on your server uses german locale for its output.
Some english strings are already filtered out (see https://github.com/mailwatch/1.2.0/blob/master/mailscanner/functions.php#L946).

**Comment by Kharag** [comment]
Mhm that is indeed the problem.
Funny thing is that everything is set to english locales yet spamassassin chose to ignore this.

As a temporary fix for us until i can track down the issue I've amended the filtering function.
Thanks!

**Comment by endelwar** [comment]
@Kharag do you have a comprehensive list of German words that you can find in spam details?

**Comment by endelwar** [comment]
@stefaweb any French in words in spam details?

**Comment by stefaweb** [comment]
I've to look.

**Comment by stefaweb** [comment]
Found "requis"  (required).
