### ISSUE TITLE
Documentation for integrating with MailScanner v5

### ISSUE THREAD

**Issue by asuweb** [mailwatch/1.2.0#258]
The documentation needs updating to reflect the new path for the custom perl modules when using the later versions of MailWatch v4 and all version of v5.  Mailscanner fails to run when upgraded if paths aren't changed.  

The new path is: /usr/share/MailScanner/perl/custom

**Comment by endelwar** [comment]
Fixed on online documentation with commit e60539116129b92a94cc10d214379344a2778150
