### ISSUE TITLE
LDAP binding

### ISSUE THREAD

**Issue by pathiaki** [mailwatch/1.2.0#267]
Hi,

I am trying to bind user authorization to LDAP.  In conf.php, I found the LDAP entries right after the MySQL entries....

I'm getting these errors:

[client 192.168.0.29:22037] PHP Warning:  ldap_bind(): Unable to bind to server: Invalid DN syntax in /usr/local/www/mailwatch/functions.php on line 2272, referer: http://mailwatch.example.com/login.php
[Wed Aug 17 01:59:44.313264 2016] [:error] [pid 38981] [client 192.168.0.29:22037] PHP Notice:  Undefined offset: 0 in /usr/local/www/mailwatch/functions.php on line 2280, referer: http://mailwatch.example.com/login.php

// LDAP settings
define('USE_LDAP',         '1');
define('LDAP_HOST',        '192.168.0.8');
define('LDAP_PORT',        '389');
//define('LDAP_DN',          'ou=people,dc=example,dc=com');
define('LDAP_DN',          'dc=example,dc=com');
define('LDAP_USER',        'mailwatch@example.com');
define('LDAP_PASS',        'password');
define('LDAP_SITE',        'default');

My LDAP works.  EVERYTHING is authenticating against it.  The new mailwatch user is there and I can even login with the password from the machine I'm on.  I can pull up the information using:

ldapsearch -W -b 'dc=example,dc=com' -h 192.168.0.8 -D 'cn=mailwatch,ou=people,dc=example,dc=com'
Enter LDAP Password:  password
.
.
.
# search result

search: 2
result: 0 Success
# numResponses: 121
# numEntries: 120

So, why is it refusing to bind?

I have the php-session and php-ldap modules loaded.

Any help is appreciated....

P.
##

**Comment by endelwar** [comment]
which kind of ldap server are you authenticating against? I've tested MailWatch with openLdap and has been reported successful login with Active Direcotry

**Comment by pathiaki** [comment]
I'm authenticating against OpenLDAP 2.4.x . Again, my OpenLDAP works with every other application.  Why not mailwatch?

**Comment by Skywalker-11** [comment]
have you tried to use "cn=mailwatch,ou=people,dc=example,dc=com" as LDAP_USER?
