### ISSUE TITLE
SpamAssassin Rule Hits report - descriptions interpreted as html

### ISSUE THREAD

**Issue by pdwalker** [mailwatch/1.2.0#269]
Apologies if this has been reported/fixed before

I've found some of the rule descriptions have html tags or "<>" characters.  When displaying the report, the browsers try to parse these tags and this breaks the rendering of the report.

Fix:
rep_sa_rule_hits.php, line 134:
change
`<TD>" . return_sa_rule_desc(strtoupper($key)) . "</TD>`
to
`<TD>" . htmlentities(return_sa_rule_desc(strtoupper($key))) . "</TD>`
and that corrects the problem.

**Comment by endelwar** [comment]
Thank you for reporting this bug!

**Comment by stefaweb** [comment]
Done in #274

**Comment by endelwar** [comment]
@stefaweb this was fixed in https://github.com/mailwatch/1.2.0/commit/a70141c26b6a7db24e50826fadce6a5cfca62d70 on the development branch
