### ISSUE TITLE
Deprecated HTTP_RAW_POST_DATA xmlrpc

### ISSUE THREAD

**Issue by mealerz** [mailwatch/1.2.0#277]
I'm receiving this error on a remote call - PHP Deprecated:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0

I am using the new php56-5.6.24_1 version, which shows HTTP_RAW_POST_DATA as deprecated.

**Comment by endelwar** [comment]
Do you debug enabled or set $client->setDebug(1) in mailscanner/lib/xmlrpc/xmlrpc_wrappers.inc?

**Comment by mealerz** [comment]
I had problems releasing quarantine from a remote host, but since I changed the php.ini file to always_populate_raw_post_data = -1 the error has gone away from the debug output and now the page in viewmail.php loads fine. The error was getting in the way. 
I'm not sure this is needed since all I find is this in ./lib/xmlrpc/xmlrpcs.inc - 

* A debugging routine: just echoes back the input packet as a string value
                * DEPRECATED!
                */
                function echoInput()
                {
                        $r=new xmlrpcresp(new xmlrpcval( "'Aha said I: '" . $GLOBALS['HTTP_RAW_POST_DATA'], 'string'));
                        print $r->serialize();
                }
                
I commented this out and it made no difference.

**Comment by mealerz** [comment]
Also I found error by changing - var $debug=0;
to - var $debug=1;

Inside lib/xmlrpc/xmlrpc.inc

**Comment by endelwar** [comment]
The only place in MailWatch where the deprecated `GLOBALS['HTTP_RAW_POST_DATA']` is used in xmlrpc library. I've added a small fix in develop branch, but an upgrade to xml-rpc version 4 has to be done before releasing MW1.2

**Comment by endelwar** [comment]
quick fix in 8eb84f436faf20ac2285ef6fe5ef350db4d3118d
