### ISSUE TITLE
Translation in mysqlquery for user_manager.php

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#278]
Hello Manuel!

I don't know how to manage the translation of "Yes" and "No" in the mysql query. 

An idea?

                $sql = "SELECT filter, CASE WHEN active='Y' THEN 'Yes' ELSE 'No' END AS active, CONCAT('<a href=\"javascript:delete_filter\(\'" . mysql_real_escape_string($id) . "\',\'',filter,'\'\)\">" . __('delete12') . "</a>&nbsp;&nbsp;<a href=\"javascript:change_state(\'" . mysql_real_escape_string($id) . "\',\'',filter,'\')\">" . __('toggle12') . "</a>') AS actions FROM user_filters WHERE username='" . mysql_real_escape_string($id) . "'";

![capture d ecran 2016-08-23 a 15 43 37](https://cloud.githubusercontent.com/assets/12907102/17894593/2e951298-694a-11e6-8ae6-d304616fa872.png)

I've the same case in others parts of the codes (Yes, YES, Y, No, NO, N). Not easy to translate without checking all the code and how it works.

**Comment by endelwar** [comment]
this should work:
`$sql = "SELECT filter, CASE WHEN active='Y' THEN '" . __('Yes') . "' ELSE '" . __('No') . "' END AS active, CONCAT('<a href=\"javascript:delete_filter\(\'" . mysql_real_escape_string($id) . "\',\'',filter,'\'\)\">" . __('delete12') . "</a>&nbsp;&nbsp;<a href=\"javascript:change_state(\'" . mysql_real_escape_string($id) . "\',\'',filter,'\')\">" . __('toggle12') . "</a>') AS actions FROM user_filters WHERE username='" . mysql_real_escape_string($id) . "'";`

On other places, when Yes, YES, Y, No, NO, N are used as simple string printed on screen it should be safe to replace them with `__('something')`, if there is a comparison with database data then they must be left as is

**Comment by stefaweb** [comment]
Done
