### ISSUE TITLE
Question mark in detail.php

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#281]
At the bottom of detail.php, we can see Dangerous with a question mark.

Do we really need the question mark ?

![pict](https://cloud.githubusercontent.com/assets/12907102/18027688/ecd74758-6c6a-11e6-81d9-fe1aedb29bf0.png)

**Comment by endelwar** [comment]
Yes, it must be there, the column values are an answer to that question (Y/N)

**Comment by stefaweb** [comment]
ok
