### ISSUE TITLE
Bug in reports.php

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#282]
rep_top_sender_domains_by_quantity.php do not print on screen !

![pict2](https://cloud.githubusercontent.com/assets/12907102/18034775/38f2409e-6d46-11e6-86f5-f1737d70bf56.png)

**Comment by endelwar** [comment]
look at line 104 in your PR
https://github.com/mailwatch/1.2.0/pull/280/files#diff-3bc1ca1484c437220cca1d46468242afR104

**Comment by stefaweb** [comment]
ok, thanks.
