### ISSUE TITLE
Bug in rep_top_viruses.php

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#283]
Legends not well printed.

![pict3](https://cloud.githubusercontent.com/assets/12907102/18034833/2f031814-6d47-11e6-9fac-48afd8409c77.png)
##

**Comment by endelwar** [comment]
We should change graph library for this

**Comment by stefaweb** [comment]
The FREE version of the jpgraph library doesn't handle this.

**Comment by stefaweb** [comment]
Found this library.
May be a good replacement.
https://www.amcharts.com/javascript-charts/

**Comment by stefaweb** [comment]
Solved in #531.
