### ISSUE TITLE
.awk files

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#285]
Can I translate all these?

And how as not php code?

-rw-r--r-- 1 root root 1309 août 25 17:32 clamav.awk
-rw-r--r-- 1 root root 1630 août 25 17:32 f-prot.awk
-rw-r--r-- 1 root root 2406 août 25 17:32 f-secure.awk
-rw-r--r-- 1 root root 1206 août 25 17:32 mcafee.awk
-rw-r--r-- 1 root root 1857 août 25 17:32 sophos.awk

**Comment by endelwar** [comment]
Technically it's possible (see https://www.gnu.org/software/gawk/manual/html_node/Internationalization.html#Internationalization), but it's not worth the effort

**Comment by stefaweb** [comment]
You're right. ;-)
