### ISSUE TITLE
Problem with table definition in auto-release.php

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#291]
In auto-release.php, we have a table definition.

```
CREATE TABLE `autorelease` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `msg_id` varchar(255) NOT_NULL,
  `uid` varchar(255) NOT_NULL,
  PRIMARY_KEY (`id`)
);
```

When we insert the table in MysQL (5.5 in this case), we got a syntax error.

> #1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'NOT_NULL, `uid` varchar(255) NOT_NULL, PRIMARY_KEY (`id`) )' at line 3

This following definition will work better:

```
CREATE TABLE IF NOT EXISTS `autorelease` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `msg_id` varchar(255) COLLATE utf8_general_ci NOT NULL,
  `uid` varchar(255) COLLATE utf8_general_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci AUTO_INCREMENT=1 ;
```

**Comment by asuweb** [comment]
Fixed with pull request #293
