### ISSUE TITLE
Domain admin user problem viewing quarantine messages - all messages displayed on the same page.

### ISSUE THREAD

**Issue by webtel** [mailwatch/1.2.0#306]
Hello

I have noticed a problem with Domain Admins.

I create a domain admin user, for eg user@domain.com - so that when they log in with user@domain.com they can see all messages for domain.com

The problem is when they log in and go to the Quarantine section and click on any message - the page just loads all messages jointly on a single page and there is no way to release a single message from quarantine.
The problem is on this page for eg : http://domainname/detail.php?id=7C50E15D0.A525C

**Comment by webtel** [comment]
Hi there.

Do you know when this bug can be resolved - or if there is a temporary workaround available for this?

Thanx
Tony

**Comment by webtel** [comment]
Hello

Would there be a patch for this sometime, or is there a way I can resolve this on my installation?

**Comment by endelwar** [comment]
Can you confirm this behavior with last develop branch? I can't replicate this on RC2, RC3 and develop...

**Comment by webtel** [comment]
Hi Manuel

I havent downloaded any updates since original install. Let me try quick 
and test

To upgrade do I just download the files and copy over existing 
installation?

Regards
Tony Da Silva
tony@web-telecoms.co.za



------ Original Message ------

**Comment by endelwar** [comment]
Yes, replace the content of old directory and copy over new files. beware that *pm files need to be edited again with username and password for database

**Comment by endelwar** [comment]
@webtel any news?

**Comment by Skywalker-11** [comment]
I think we can close this as it is not reproducible with current develop.
