### ISSUE TITLE
LDAP authentication fails on passwords with special characters &, >, etc.

### ISSUE THREAD

**Issue by danbrunt** [mailwatch/1.2.0#309]
LDAP authentication fails on passwords with special characters like &, >, etc.

In the ldap_authenticate function in /var/www/html/mailscanner/functions .php change
  if (ldap_bind($ds, $user, "$password")) {
to
  if (ldap_bind($ds, $user, html_entity_decode($password))) {
##

**Comment by endelwar** [comment]
@danbrunt could you test login with last commit in develop branch?
