### ISSUE TITLE
%var% expansion broken in case of multiple variables

### ISSUE THREAD

**Issue by LucianoCavalheiro** [mailwatch/1.2.0#311]
MailScanner directives allow for multiple files to specified for a single parameter, in a space-separated list. However %var% expansion in /var/www/html/mailscanner/functions.php fails in case of multiple variable occurrences in the assigned value. 

For instance, in the case bellow: 
`Phishing Safe Sites File = %etc-dir%/phishing.safe.sites.conf %etc-dir%/phishing.safe.sites-local.conf`

current implementation will lookup a variable called `%etc-dir%/phishing.safe.sites.conf %etc-dir%`, instead of `%etc-dir%`.

**Comment by endelwar** [comment]
fixed in 1.2.0-rc3
