### ISSUE TITLE
"Call to undefined function" when trying to login

### ISSUE THREAD

**Issue by wioxjk** [mailwatch/1.2.0#314]
`[Wed Nov 02 08:33:08.369344 2016] [proxy_fcgi:error] [pid 30624:tid 140714067293952] [client 192.168.30.97:50527] AH01071: Got error 'PHP message: PHP Fatal error:  Call to undefined function mysql_connect() in /srv/www.mail.scan/htdocs/functions.php on line 770\n', referer: http://www.mail.scan/login.php
`

Any known solution? I do not have any knowledge in PHP currently :)

**Comment by endelwar** [comment]
MailWatch is not yet compatible with php7.
If you're receiving this error on php 5 the install/enable mysql extension

**Comment by wioxjk** [comment]
@endelwar 
Thank you for your response.
I am using PHP-fpm (5.6) but the module php-mysql was not installed as you said.

Is it possible to have a short "requirements" included in the installation guide? Would be appreciated!

**Comment by wioxjk** [comment]
Thank you @endelwar 
The php-mysql module was missing.
I currently use php-fpm (5.6)
