### ISSUE TITLE
move conf.php for security

### ISSUE THREAD

**Issue by thctlo** [mailwatch/1.2.0#32]
It would be nice to move the conf.php out of the webserver folder. 

like most webservers, for security, put conf.php for example in /etc/mailwatch

**Comment by stefaweb** [comment]
If MailWatch have access to /etc/mailwatch file, Apache will have access too. This will not change security.

**Comment by thctlo** [comment]
Correct, but if the config is set outside the webroot, it is not accessable for the public and path traversal should never be not allowed.  

A good configured webserver does not allow  http://site.name.tld/../../../etc/mailwatch/conf.php  
and therefore not accessable. 
Keeping it outsite the webroot also has the advantage the robots are not able to index the config files. 
bad robots DO index your files.
