### ISSUE TITLE
mailwatch 1.2.0 - create_relay_postfix.sql error 

### ISSUE THREAD

**Issue by oniled** [mailwatch/1.2.0#320]
Hello,

I just installed mailwatch 1.2.0 and all is working well.

OS: Centos 7
Mailscanner version: 5.0.3.7

Since I am using a postfix relay i tried to run create_relay_postfix.sql and got this error:

> [root@server Postfix_relay]# mysql -p mailscanner < create_relay_postfix.sql
> Enter password:
> ERROR 1061 (42000) at line 15: Duplicate key name 'mtalog_ids_idx'

Please let me know if you need any additional info.

**Comment by stefaweb** [comment]
Works here wth MariaDB 10.0. No error. What do you use as database?

```
CREATE TABLE IF NOT EXISTS `mtalog_ids` (
  `smtpd_id` VARCHAR(20)
             CHARACTER SET ascii
             COLLATE ascii_general_ci NULL DEFAULT NULL,
  `smtp_id`  VARCHAR(20)
             CHARACTER SET ascii
             COLLATE ascii_general_ci NULL DEFAULT NULL
)
  ENGINE = MYISAM;

ALTER TABLE `mtalog_ids` ADD UNIQUE `mtalog_ids_idx` (`smtpd_id`, `smtp_id`);
ALTER TABLE `mtalog_ids` ADD INDEX (`smtpd_id`);
ALTER TABLE `mtalog` ADD INDEX (`msg_id`);
```
But is "ascii_general_ci" the right collation?

**Comment by oniled** [comment]
Using mariadb from the CENTOS repo.

I used the create.sql to create the database.  I can confirm that is the right collation.

Reviewing the create.sql, it does most of those steps already.

```
--
-- Table structure for table `mtalog_ids`
--

CREATE TABLE IF NOT EXISTS `mtalog_ids` (
  `smtpd_id` varchar(20) CHARACTER SET ascii DEFAULT NULL,
  `smtp_id` varchar(20) CHARACTER SET ascii DEFAULT NULL,
  UNIQUE KEY `mtalog_ids_idx` (`smtpd_id`,`smtp_id`),
  KEY `smtpd_id` (`smtpd_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

```

Should I try editing something out of the create_relay_postfix.sql?

**Comment by stefaweb** [comment]
I tried with MariaDB 10.x.
Seems that the line:
ALTER TABLE `mtalog_ids` ADD UNIQUE `mtalog_ids_idx` (`smtpd_id`, `smtp_id`);
is not useful with MariaDB.

**Comment by endelwar** [comment]
create_relay_postfix.sql is not needed anymore, the same table definition is present in create.sql

I should remove that sql file and update INSTALL content

**Comment by oniled** [comment]
Thank you both for all your help =)
