### ISSUE TITLE
Move to mysqli_* function

### ISSUE THREAD

**Issue by endelwar** [mailwatch/1.2.0#322]
Update all code to use supported php mysql extension instead of deprecated one, making 1.2.0 more compatible with PHP7

**Comment by stefaweb** [comment]
Hello!

With new tools/Sendmail_queue/mailq.php:

antispam-test:/var/www/html/mailscanner# /usr/local/bin/mailq.php

Fatal error: Call to a member function query() on a non-object in /var/www/html/mailscanner/functions.php on line 823

**Comment by endelwar** [comment]
This should be fixed in commit https://github.com/mailwatch/1.2.0/commit/6579d36e3dc0f8ed683a726fe069d6f3e284dcdb

**Comment by Skywalker-11** [comment]
Do you want to stick with mysqli or move to pdo later? If not you can also close #20

**Comment by endelwar** [comment]
A move to mysqli_* was necessary to support new php versions. Next version will work with PDO
