### ISSUE TITLE
Mailwatch and MailScanner v5

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#330]
The new version of MailScanner v5 need changes in Mailwatch documentation.

- clean.quarantine no longer exist
- new configuration file: /etc/MailScanner/defaults
- new symlink in /etc/MailScanner/: custom -> /usr/share/MailScanner/perl/custom

Will add more if found.

**Comment by stefaweb** [comment]
New name for "clean.quarantine" :  /usr/sbin/ms-clean-quarantine

In /etc/MailScanner/defaults, variable for Quarantine Retention would be "q_days=0"

**Comment by stefaweb** [comment]
More changes.

In mailscanner v4: /var/run/MailScanner/MailScanner.pid
In mailscanner v5: /var/run/MailScanner.pid

No longer exist in mailscanner v5:
/etc/MailScanner/wrapper -> /usr/share/MailScanner/MailScanner/wrapper/
/etc/MailScanner/autoupdate -> /usr/share/MailScanner/MailScanner/autoupdate/

**Comment by stefaweb** [comment]
More changes:

In conf.php:

For mailscanner v4:
define('SA_PREFS', MS_CONFIG_DIR . 'spam.assassin.prefs.conf');

mailscanner v5:
define('SA_PREFS', MS_CONFIG_DIR . 'spamassassin.conf');

**Comment by stefaweb** [comment]
Debian Jessie need more setup in Mailcanner.conf do works well with clamav, spamassassin and mailscanner.

Example for Exim + Apache.

Run As User = Debian-exim
Run As Group = Debian-exim
Incoming Work User = Debian-exim
Incoming Work Group = mtagroup
Incoming Work Permissions = 0660
Quarantine User = Debian-exim
Quarantine Group = mtagroup
Quarantine Permissions = 0644

In /etc/group:
mtagroup:x:1001:clamav,Debian-exim,mail,www-data

**Comment by Skywalker-11** [comment]
Also the files `/etc/MailScanner/bayes/bayes_*` should be owned by root:mtagroup when using postfix.
Else `MailScanner --lint` will print errors that it can't access these files

**Comment by endelwar** [comment]
This issue was moved to mailwatch/mailwatch-docs#18
