### ISSUE TITLE
MailWatch needs the (deprecated) MySQL extension to work: PHP7 has removed this extension and this software will not work on it.

### ISSUE THREAD

**Issue by ajos1** [mailwatch/1.2.0#335]
-

Any news on when this will be fixed?

MailWatch needs the (deprecated) MySQL extension to work: PHP7 has removed this extension and this software will not work on it.

**Comment by endelwar** [comment]
try the devel branch, I've migrated to mysqli, but it needs some more test before making a release

**Comment by endelwar** [comment]
`$this->$link->connect_errno` cannot be used because these lines aren't in a PHP class, commit https://github.com/mailwatch/1.2.0/commit/788b1fef6ddead4cf3d0de2281ecb74adc3e3bf2 should fix this
