### ISSUE TITLE
How do email aliases work?

### ISSUE THREAD

**Issue by ovizii** [mailwatch/1.2.0#338]
I found this documentation: http://docs.mailwatch.org/using/per-domainper-user-filtering.html 

saying:
>If you need to have ‘aliases’ for your users - e.g. ‘smf@example.com’ also has an e-mail alias >‘steve.freegard@example.org’, then no problem - use the ‘Filters’ screen to add >‘steve.freegard@example.org’ and the ‘smf@example.com’ user will be able to see both.

I'm not sure how that is supposed to work. How do I add this via filters? What's to stop someone to add a filter for someone else's email address and gain access?

**Comment by endelwar** [comment]
Only administrators (not even domain admin) can add aliases for users, so there is no risk that someone "steals" an email.
Filters can be added when logged in as Administrator, using the link `filters` in user row inside Tools -> User Management

**Comment by ovizii** [comment]
Thanks for the reply, but this still doesn't make any sense:

> If you need to have ‘aliases’ for your users - e.g. ‘smf@example.com’ also has an e-mail alias ‘steve.freegard@example.org’, then no problem - use the ‘Filters’ screen to add ‘steve.freegard@example.org’ and the ‘smf@example.com’ user will be able to see both.

How does one use filters to create an alias?
