### ISSUE TITLE
Release date for RC4

### ISSUE THREAD

**Issue by asuweb** [mailwatch/1.2.0#341]
@endelwar 

Hi,

Is there a release date for RC4?  I note a large code base change / tidy up which is excellent - good work from the Mailwatch team!

I've a number of features I'm planning to work on in the next couple of months, and don't see any point in writing them twice, so if RC4 is to be released in the next month or 2 I'll develop them with the RC4 codebase, otherwise I'll work off RC3 and adapt them when RC4 is released

Thanks,

Just for info, these are the features I'm planning (I'll release them to the community for possible inclusion)

- User password reset (this is already written and working for RC3)

- Domain admins to be able to add users for their domain - potentially with csv upload

- One click Ham training from quarantine release email (possibly also one click whitelisting)

- Re-develop quarantine_report to allow users to specify individual time of report / timezone / and possibly frequency of reports

**Comment by endelwar** [comment]
Hi @asuweb, RC4 was released yesterday!
I'm planning to release 1.2.0 soon (these are the remaining issues https://github.com/mailwatch/1.2.0/milestone/1).

After 1.2.0 release, the 1.2 branch will keep updated with blocking bugs and security issues (no new features), and the so long waited 2.0 branch will be opened launching the **necessary** modernizing of this legacy php application and so there will be space for new features, like yours (which are very welcome!) and other already proposed (see https://github.com/mailwatch/1.2.0/milestone/2).

**Comment by stefaweb** [comment]
Hello!
Localisation of i18 files can may be added to 1.2 milestone.

**Comment by asuweb** [comment]
@endelwar - Excellent.  Very pleased to hear progress is being made.  

Is there a proposed launch date for 2.0? I know there is a lot of work to be done prior to then.  I may still work on some of the proposals above as I need them for my users possibly prior the release of 2.0, in which case I'll happily adapt them for 2.0 down the line if wished.

**Comment by endelwar** [comment]
No ETA yet for 2.0.

After 1.2.0 is released, seen the amount of new features already developed (or almost done), there will be space for their inclusion in 1.2.x branch, which will live on it's own.

**Comment by asuweb** [comment]
Great news :)  Thanks for all your hard work
