### ISSUE TITLE
Feature request - Domain admins should be able to release quarantined items and not just administrators.

### ISSUE THREAD

**Issue by mealerz** [mailwatch/1.2.0#343]
Domain admins should be able to release quarantined items and not just administrators.

As the subject explains, do you think this should be allowed?

**Comment by asuweb** [comment]
@mealerz - Domain admins can release spam on my system without issue.  Not sure why they can't on yours?

**Comment by mealerz** [comment]
It's dangerous viruses. They do get sent inside an attachment on my system, but I imagine it's better to create a false positive to the AV team rather than allow it for domain admins. However, I have modified my code to allow it. I'm using sendmail here and when I see the option to release, I also see an option to release the attachment, but that is not needed since when you release the email it also sends the attachment.

**Comment by mealerz** [comment]
//foreach ($quarantined as $item) {
        $item = $quarantined[0];
            echo " <tr>\n";
            // Don't allow message to be released if it is marked as 'dangerous'
            // Currently this only applies to messages that contain viruses.
            if ($item['dangerous'] !== "Y" || $_SESSION['user_type'] == 'A' || $_SESSION['user_type'] == 'D') {
                echo '  <td align="center"><input type="checkbox" name="release[]" value="' . $item['id'] . '"></td>' . "\n";
            } else {
                echo '<td>&nbsp;&nbsp;</td>' . "\n";
            }
            echo '  <td align="center"><input type="checkbox" name="delete[]" value="' . $item['id'] . '"></td>' . "\n";
            // If the file is an rfc822 message then allow the file to be learnt
            // by SpamAssassin Bayesian learner as either spam or ham (sa-learn).
            if (preg_match('/message\/rfc822/', $item['type']) || $item['file'] == "message" && (strtoupper(
                        get_conf_var("UseSpamAssassin")
                    ) == "YES")
            ) {
                echo '   <td align="center"><input type="checkbox" name="learn[]" value="' . $item['id'] . '"><select name="learn_type"><option value="ham">As Ham</
option><option value="spam">As Spam</option><option value="forget">Forget</option><option value="report">As Spam+Report</option><option value="revoke">As Ham+Revoke
</option></select></td>' . "\n";
            } else {
                echo '   <td>&nbsp;&nbsp;</td>' . "\n";
            }
            echo '  <td>' . $item['file'] . '</td>' . "\n";
            echo '  <td>' . $item['type'] . '</td>' . "\n";
            // If the file is in message/rfc822 format and isn't dangerous - create a link to allow it to be viewed
            if (($item['dangerous'] == "N" || $_SESSION['user_type'] == 'A' || $_SESSION['user_type'] == 'D') &&
                preg_match('!message/rfc822!', $item['type'])
            ) {
                echo '  <td><a href="viewmail.php?id=' . $item['msgid'] . '">' .
                    //substr($item['path'], strlen($quarantinedir) + 1) .
                    'View Message</a></td>' . "\n";
            } else {
                echo "  <td>" . substr($item['path'], strlen($quarantinedir) + 1) . "</td>\n";
            }
            if ($item['dangerous'] == "Y" && $_SESSION['user_type'] != 'A' || $_SESSION['user_type'] != 'D') {
                $dangerous = $yes;
                $is_dangerous++;
            } else {
                $dangerous = $no;
            }
            echo '  <td align="center">' . $dangerous . '</td>' . "\n";
            echo ' </tr>' . "\n";
        //}

**Comment by mealerz** [comment]
This fixes the attachment issue, so now you just see the message.

**Comment by Skywalker-11** [comment]
can we close this as it is merge already?

**Comment by mealerz** [comment]
Fine by me.
