### ISSUE TITLE
upgrade RC4 issue

### ISSUE THREAD

**Issue by renarios** [mailwatch/1.2.0#344]
While upgrading from 1.2.0. to 1.2.0-rc.4 I discovered some issues in running the upgrade.php. On Fedora 25 (mariadb-10.1.20-1) mysql_connect is not supported anymore. Could you please change them to mysqli functions?

With regards,
Rene

**Comment by asuweb** [comment]
Fixed in #344

**Comment by renarios** [comment]
Thanks a lot. It works like a charm!
