### ISSUE TITLE
Bug with whitelist/blacklist

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#346]
With last DEV version (RC4+).

When I delete an entry in the whitelist, the entry is still used by mailscanner until I restart it with "service mailscanner restart".

Same when I add an entry in whitelist.

Same with blacklist.

**Comment by stefaweb** [comment]
Sorry, seems refresh is 15 minutes.
In SQLBlackWhiteList.pm:
my ($refresh_time) = 15;        # Time in minutes before lists are refreshed

**Comment by stefaweb** [comment]
Bug still here.

The whitelist entry is deleted. I waited 15 minutes and:

Jan  4 11:37:51 antispam-test MailScanner[12557]: MailWatch: Whitelist refresh time reached
Jan  4 11:37:51 antispam-test MailScanner[12557]: MailWatch: Starting up MailWatch SQL Whitelist
Jan  4 11:37:51 antispam-test MailScanner[12557]: MailWatch: Read 1241 whitelist entries
Jan  4 11:37:51 antispam-test MailScanner[12557]: MailWatch: Blacklist refresh time reached
Jan  4 11:37:51 antispam-test MailScanner[12557]: MailWatch: Starting up MailWatch SQL Blacklist
Jan  4 11:37:51 antispam-test MailScanner[12557]: MailWatch: Read 7919 blacklist entries

I sent a new mail. Mailscanner still say that the entry is here (message still filtered).

With mailscanner 5.0.3.

**Comment by stefaweb** [comment]
Changed my ($refresh_time) = 5;
Restarted mailscanner.
NO refresh time at all.

**Comment by stefaweb** [comment]
Still with the problem.
In fact, refresh time not working at all.

Do we have a solution to debug this?

**Comment by stefaweb** [comment]
Found.
The Whitelist/Blacklist are only refresh when a new mail is received and if the database changed.

**Comment by stefaweb** [comment]
Still there.

```
Jan  5 18:40:44 antispam-test MailScanner[18309]: MailWatch: Read 1242 whitelist entries
Jan  5 18:41:45 antispam-test MailScanner[18265]: Message 1cPC2q-0004mU-Pk from 192.168.0.50 (xxx@xxxx.fr) is whitelisted
Jan  5 18:43:22 antispam-test MailScanner[18309]: Message 1cPC4P-0004mU-I4 from 192.168.0.50 (xxx@xxxx.fr) is whitelisted
Jan  5 18:49:36 antispam-test MailScanner[18296]: MailWatch: Read 1241 whitelist entries
Jan  5 18:49:36 antispam-test MailScanner[18296]: Message 1cPCAR-0004u7-SQ from 192.168.0.50 (postmaster@actionweb.fr) is whitelisted
```

**Comment by endelwar** [comment]
Just for confirmation: there isn't other whitelist that make that email pass?

Logs clearly states that the white list has been updated.

**Comment by stefaweb** [comment]
No. The only one white/black list used is the one in mailwatch.

I don't understand. It's working but depend of the value of $refresh_time and some time not working.

I changed my ($refresh_time) = 5; and restarted mailscanner.
I tried with white and black list entry and **sending a message few second after have created the entry**.
works

But not all message was ok. One message goes in green unless 1241 entries. The other goes in white after.

```
Jan  6 11:28:21 antispam-test MailScanner[1408]: Message 1cPRkz-0000O3-3C from 192.168.0.50 (xxx@xxxx.fr) is whitelisted
Jan  6 11:29:26 antispam-test MailScanner[1456]: MailWatch: Read 1242 whitelist entries
Jan  6 11:29:26 antispam-test MailScanner[1456]: Message 1cPRm1-0000O3-5g from 192.168.0.50 (xxx@xxxx.fr) is whitelisted
Jan  6 11:30:43 antispam-test MailScanner[1424]: MailWatch: Read 1241 whitelist entries
Jan  6 11:31:10 antispam-test MailScanner[1399]: MailWatch: Read 1241 whitelist entries
Jan  6 11:33:14 antispam-test MailScanner[1456]: Message 1cPRph-0000O3-45 from 192.168.0.50 (xxx@xxxx.fr) is whitelisted
```

I changed my ($refresh_time) = 15; and restarted mailscanner.
Not working. No refresh.

I made different tests. It's not reliable. Sometime works, sometime not. I can't find a "rule" to find the bug.

**Comment by stefaweb** [comment]
Hello! 
The bug is still there with the fresh new dev server.

```
Jan  8 18:40:16 antispam-dev MailScanner[21609]: MailWatch: Read 7920 blacklist entries

Entry remove: 7920 -> 7919

Jan  8:43:26 antispam-dev MailScanner[13292]: New Batch: Scanning 1 messages, 31588 bytes
Jan  8 18:43:26 antispam-dev MailScanner[13292]: Virus and Content Scanning: Starting
Jan  8 18:43:26 antispam-dev MailScanner[13292]: Virus Scanning completed at 283728 bytes per second
Jan  8 18:43:26 antispam-dev MailScanner[13292]: Spam Checks: Starting
Jan  8 18:43:26 antispam-dev MailScanner[13292]: MailWatch: Whitelist refresh time reached
Jan  8 18:43:26 antispam-dev MailScanner[13292]: MailWatch: Starting up MailWatch SQL Whitelist
Jan  8 18:43:26 antispam-dev MailScanner[13292]: MailWatch: Read 1241 whitelist entries
Jan  8 18:43:26 antispam-dev MailScanner[13292]: MailWatch: Blacklist refresh time reached
Jan  8 18:43:26 antispam-dev MailScanner[13292]: MailWatch: Starting up MailWatch SQL Blacklist
Jan  8 18:43:26 antispam-dev MailScanner[13292]: MailWatch: Read 7919 blacklist entries
Jan  8 18:43:26 antispam-dev MailScanner[13292]: Message 1cQHV7-0005go-3m from 192.168.0.100 (xxx@yyy.tld) to cyberkata.org is spam (blacklisted)
Jan  8 18:43:26 antispam-dev MailScanner[13292]: Spam Checks: Found 1 spam messages
Jan  8 18:43:26 antispam-dev MailScanner[13292]: Spam Actions: message 1cQHV7-0005go-3m actions are store
Jan  8 18:43:26 antispam-dev MailScanner[13292]: Spam Checks completed at 368209 bytes per second
Jan  8 18:43:26 antispam-dev MailScanner[13292]: Deleted 1 messages from processing-database
Jan  8 18:43:26 antispam-dev MailScanner[13292]: Batch completed at 158338 bytes per second (31588 / 0)
Jan  8 18:43:26 antispam-dev MailScanner[13292]: Batch (1 message) processed in 0.20 seconds
Jan  8 18:43:26 antispam-dev MailScanner[13292]: MailWatch: Logging message 1cQHV7-0005go-3m to SQL
Jan  8 18:43:26 antispam-dev MailScanner[13292]: "Always Looked Up Last" took 0.00 seconds
Jan  8 18:43:26 antispam-dev MailScanner[13292]: Config: calling custom end function SQLSpamScores
Jan  8 18:43:26 antispam-dev MailScanner[13292]: MailWatch: Closing down MailWatch SQL Spam Scores
Jan  8 18:43:26 antispam-dev MailScanner[13292]: Config: calling custom end function SQLWhitelist
Jan  8 18:43:26 antispam-dev MailScanner[13292]: MailWatch: Closing down MailWatch SQL Whitelist
Jan  8 18:43:26 antispam-dev MailScanner[13292]: Config: calling custom end function SQLBlacklist
Jan  8 18:43:26 antispam-dev MailScanner[13292]: MailWatch: Closing down MailWatch SQL Blacklist
Jan  8 18:43:26 antispam-dev MailScanner[13292]: Config: calling custom end function SQLNoScan
Jan  8 18:43:26 antispam-dev MailScanner[13292]: MailWatch: Closing down MailWatch SQL No Scan
Jan  8 18:43:26 antispam-dev MailScanner[13292]: Config: calling custom end function SQLHighSpamScores
Jan  8 18:43:26 antispam-dev MailScanner[13292]: MailWatch: Closing down MailWatch SQL High Spam Scores
Jan  8 18:43:26 antispam-dev MailScanner[13292]: Config: calling custom end function MailWatchLogging
Jan  8 18:43:26 antispam-dev MailScanner[13292]: MailScanner child dying of old age

MailScanner restarted:

Jan  8 18:50:03 antispam-dev MailScanner[22709]: New Batch: Scanning 1 messages, 31967 bytes
Jan  8 18:50:03 antispam-dev MailScanner[22709]: Virus and Content Scanning: Starting
Jan  8 18:50:03 antispam-dev MailScanner[22709]: Virus Scanning completed at 277522 bytes per second
Jan  8 18:50:03 antispam-dev MailScanner[22709]: Spam Checks: Starting
Jan  8 18:50:05 antispam-dev MailScanner[22709]: Spam Checks completed at 16313 bytes per second
Jan  8 18:50:05 antispam-dev MailScanner[22709]: Uninfected: Delivered 1 messages
Jan  8 18:50:05 antispam-dev MailScanner[22709]: Deleted 1 messages from processing-database
Jan  8 18:50:05 antispam-dev MailScanner[22709]: Batch completed at 15269 bytes per second (31967 / 2)
Jan  8 18:50:05 antispam-dev MailScanner[22709]: Batch (1 message) processed in 2.09 seconds
Jan  8 18:50:05 antispam-dev MailScanner[22709]: MailWatch: Logging message 1cQHbW-0005jt-RX to SQL
Jan  8 18:50:05 antispam-dev MailScanner[22709]: "Always Looked Up Last" took 0.00 seconds
```

**Comment by stefaweb** [comment]
Hello Manuel!
Have you find time to look at this?

**Comment by endelwar** [comment]
not yet

**Comment by stefaweb** [comment]
Hello Manuel!
Do you know if a "cache" of the white/black list is stored somewhere by MailScanner (as in a .db) or if MailScanner ask the mysql database each time a message is received?

**Comment by asuweb** [comment]
Assuming you are using the 
`Is Definitely Not Spam = &SQLWhitelist`
`Is Definitely Spam = &SQLBlacklist`

then on every mail mailscanner will call the custom function in `SQLBlackWhiteList.pm`, and that will in turn do the lookup.  

The default refresh time is 15 minutes.

**Comment by stefaweb** [comment]
Some time it work, some time not.
Yesterday, I created/deleted 10 times a black entry and send a mail between each action. It worked.
I restarted mailscanner. It no longer worked after the restart.
I waited 2 hours after added a black entry. Doesn't works.
Not stable.
A very annoying bug.

**Comment by stefaweb** [comment]
I have run dbitrace if can help?
I can send you the file.

**Comment by Skywalker-11** [comment]
If I understand it correctly we pass the current black/whitelist to CreateList as parameter. (Line 53/60)
`my $entries = CreateList('whitelist', \%Whitelist);`
Then we store the old list in $BlackWhite:
`my ($type, $BlackWhite) = @_;`
Then we only add the entries that we get from sql:
`$BlackWhite->{lc($to_address)}{lc($from_address)} = 1;  # Store entry`
`$BlackWhite->{lc($filter)}{lc($from_address)} = 1; # Store entry`

The old entries aren't removed or am I  wrong? I'm just beginning to learn perl...

**Comment by stefaweb** [comment]
Good luck with Perl!

I've still not understood why the script have a refresh_time when sometime the refresh is immediate after have added an entry. Seems, this script had been built when servers was slow and have many connection to the database was not an easy job.

**Comment by asuweb** [comment]
I might be wrong, but doesn't every mailscanner child (process) read the black/white list separately, and there for each process will refresh at a different time, which might explain why sometimes it's immediate and sometimes not. 

I might be wrong though

**Comment by stefaweb** [comment]
I'll try it.

**Comment by stefaweb** [comment]
A question: 
Now you have studied the code, do you know if we can have something in "real time" when we add/delete white/black entry?
This story of refresh time is back to seventies.

**Comment by Skywalker-11** [comment]
Not sure but you can set the resettime to 0 which would query the db everytime

**Comment by stefaweb** [comment]
My tests.

Still problems if we change refresh time to 5 minutes. If we stay with 15 minutes no problem.


refresh time = 15 minutes (seems to work)

sending mail and add/delete blacklist entry is done as fast I can.

delete black entry:

```
MailWatch: Read 7758 blacklist entries
send mail
black listed
delete blacklist entry
MailWatch: Read 7758 blacklist entries
send mail
black listed
restart mailscanner
MailWatch: Read 7758 blacklist entries
send mail
black listed
delete blacklist entry
MailWatch: Read 7757 blacklist entries
send mail
still black listed
restart mailscanner
MailWatch: Read 7757 blacklist entries
no longer blacklisted
```

add black entry:

```
MailWatch: Read 7757 blacklist entries
send mail
no black listed
add blacklist entry
MailWatch: Read 7757 blacklist entries
send mail
no black listed
restart mailscanner
MailWatch: Read 7758 blacklist entries
send mail
black listed
delete blacklist entry
MailWatch: Read 7758 blacklist entries
send mail
black listed
restart mailscanner
MailWatch: Read 7757 blacklist entries
no blacklisted
```

refresh time = 15 minutes

I wait 30 minutes

```
restart mailscanner
MailWatch: Read 7758 blacklist entries
send mail
black listed
delete blacklist entry
MailWatch: Read 7758 blacklist entries
I wait 30 minutes
MailWatch: Read 7757 blacklist entries
send mail
no black listed
```

refresh time = 5 minutes (doesn't work)

sending mail and add/delete blacklist entry is done as fast I can.

remove black entry:

```
Read 7757 blacklist entries
send mail
no black listed
add blacklist entry
MailWatch: Read 7758 blacklist entrie
send mail
no black listed
send mail
no black listed
restart mailscanner
MailWatch: Read 7758 blacklist entrie
black listed
```

**Comment by Skywalker-11** [comment]
If you use the debug output I mentioned in the pr does it show the blacklisted entry when the blacklisting doesn't work?

**Comment by stefaweb** [comment]
I starting to become crazy with this story.

A session with 5 minutes refresh time. I start the mailscanner just before the test and wait 1 minute.

- Refresh time of 5 minutes not respect 5 minutes setup.
- Sometime it works, sometime not.
- In database the black list entry was "xxxx@domain.tld  ->  yyyy@domain.org" but the system print or check only "domain.org".

```
Feb  9 14:11:00 antispam-dev MailScanner[18993]: MailWatch: Blacklist refresh time reached
Feb  9 14:11:00 antispam-dev MailScanner[18993]: MailWatch: Starting up MailWatch SQL Blacklist
Feb  9 14:11:00 antispam-dev MailScanner[18993]: DEBUG: $VAR1 = {};
Feb  9 14:11:00 antispam-dev MailScanner[18993]: MailWatch: Read 7758 blacklist entries
Feb  9 14:11:00 antispam-dev MailScanner[18993]: Message 1cboV1-0004wP-OR from 82.67.159.142 (xxxx@domain.tld) to domain.org is spam (blacklisted)
Feb  9 14:11:00 antispam-dev MailScanner[18993]: Spam Checks: Found 1 spam messages
Feb  9 14:11:00 antispam-dev MailScanner[18993]: Spam Actions: message 1cboV1-0004wP-OR actions are store
Feb  9 14:11:00 antispam-dev MailScanner[18993]: Deleted 1 messages from processing-database
Feb  9 14:11:00 antispam-dev MailScanner[18993]: Batch completed at 388443 bytes per second (95371 / 0)
Feb  9 14:11:00 antispam-dev MailScanner[18993]: Batch (1 message) processed in 0.25 seconds
Feb  9 14:11:00 antispam-dev MailScanner[18993]: MailWatch: Logging message 1cboV1-0004wP-OR to SQL
Feb  9 14:11:00 antispam-dev MailScanner[18993]: "Always Looked Up Last" took 0.00 seconds
Feb  9 14:11:01 antispam-dev CRON[19573]: (root) CMD (/usr/local/bin/mailq.php)
Feb  9 14:12:01 antispam-dev CRON[19631]: (root) CMD (/usr/local/bin/mailq.php)
Feb  9 14:12:08 antispam-dev MailScanner[18985]: New Batch: Scanning 1 messages, 95531 bytes
Feb  9 14:12:08 antispam-dev MailScanner[18985]: Virus and Content Scanning: Starting
Feb  9 14:12:08 antispam-dev MailScanner[18985]: Virus Scanning completed at 609312 bytes per second
Feb  9 14:12:08 antispam-dev MailScanner[18985]: Spam Checks: Starting
Feb  9 14:12:08 antispam-dev MailScanner[18985]: MailWatch: Whitelist refresh time reached
Feb  9 14:12:08 antispam-dev MailScanner[18985]: MailWatch: Starting up MailWatch SQL Whitelist
Feb  9 14:12:08 antispam-dev MailScanner[18985]: DEBUG: $VAR1 = {};
Feb  9 14:12:08 antispam-dev MailScanner[18985]: MailWatch: Read 1144 whitelist entries
Feb  9 14:12:08 antispam-dev MailScanner[18985]: MailWatch: Blacklist refresh time reached
Feb  9 14:12:08 antispam-dev MailScanner[18985]: MailWatch: Starting up MailWatch SQL Blacklist
Feb  9 14:12:08 antispam-dev MailScanner[18985]: DEBUG: $VAR1 = {};
Feb  9 14:12:08 antispam-dev MailScanner[18985]: MailWatch: Read 7757 blacklist entries
Feb  9 14:12:10 antispam-dev MailScanner[18985]: Spam Checks completed at 59531 bytes per second
Feb  9 14:12:10 antispam-dev MailScanner[18985]: Uninfected: Delivered 1 messages
Feb  9 14:12:10 antispam-dev MailScanner[18985]: Deleted 1 messages from processing-database
Feb  9 14:12:10 antispam-dev MailScanner[18985]: Batch completed at 52112 bytes per second (95531 / 1)
Feb  9 14:12:10 antispam-dev MailScanner[18985]: Batch (1 message) processed in 1.83 seconds
Feb  9 14:12:10 antispam-dev MailScanner[18985]: MailWatch: Logging message 1cboW7-0004wP-Jj to SQL
Feb  9 14:12:10 antispam-dev MailScanner[18985]: "Always Looked Up Last" took 0.00 seconds
```

**Comment by stefaweb** [comment]
@asuweb 

> I might be wrong, but doesn't every mailscanner child (process) read the black/white list separately, and there for each process will refresh at a different time, which might explain why sometimes it's immediate and sometimes not.

When we start mailscanner...

```
Feb  9 14:49:56 antispam-dev MailScanner[23949]: MailWatch: Read 7757 blacklist entries
Feb  9 14:50:01 antispam-dev MailScanner[23963]: MailWatch: Read 7758 blacklist entries
```

**Comment by stefaweb** [comment]
@Skywalker-11 

> Not sure but you can set the resettime to 0 which would query the db everytime

If I understood this page, it is possible to write a white/black list real time check calling the database for each message.

http://jpmens.net/2007/03/29/mailscanner-custom-functions-a-small-tutorial/

See also:

/etc/MailScanner/custom/MyExample.pm.
/usr/share/MailScanner/perl/MailScanner/CustomConfig.pm

**Comment by Skywalker-11** [comment]
@asuweb yes every mailscanner childs should contain individual blacklist, whitelist and timer of last reset. But if the reset time is set to 15 minutes the childs should reload the lists if it was inactive for 15 minutes or longer. So the lists that are used should have a max age of 15 minutes when used.

@stefaweb real time check shouldn't be introduced in 1.2. But maybe in 2.0

**Comment by Skywalker-11** [comment]
@stefaweb it seems like you only did the debug before the sql queries. The current version in pr contains the debug output on the correct positions.

**Comment by stefaweb** [comment]
You're right. 
The debug message was inserted between the delete and the select. Not before the delete.
Will redo some test later.

**Comment by asuweb** [comment]
@Skywalker-11 - thanks, that's was my understanding

**Comment by stefaweb** [comment]
Good news.

Seems to works now with 5 minutes for delete and add black list.

For good testing we MUST wait for all MailScanner first to be mounted.

The problem: 

With thousands of black/white entry, MailScanner forks take 2 or 3 minutes to mount (10). 

**For this reason, we can't use a very small refresh value or we risk to have some forks with not the same database content.** (to write in doc)

May be more testing to do but It can be considered that the problem is solved.

@Skywalker-11   👍
