### ISSUE TITLE
Message details page

### ISSUE THREAD

**Issue by mmgomess** [mailwatch/1.2.0#348]
Hi everyone.

In message details page the columns "Score" and "Matching Rules" are showing same values and "Description" is empty

I´m using Mailwatch RC4, Mailscanner 5.3.0.7 and Ubuntu 12.04.5 LTS.

P.S. I did upgrade from RC2.

![screen](https://cloud.githubusercontent.com/assets/9742227/21655216/3ea52bb8-d2a0-11e6-8cb6-081ecbcbd9e6.png)

**Comment by asuweb** [comment]
Bug is `get_sa_rule_desc($rule)` function.  `$rule_score` is returning the rule, not the score.  Suspect regex issue.

**Comment by asuweb** [comment]
Fixed in PR #351

**Comment by endelwar** [comment]
Closed in ebafe548dc855d06f7d7216a08922e5496c5db42
