### ISSUE TITLE
quarantine_report.php problems

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#349]
The new quarantine_report.php from DEV is not working.

antispam-test:/etc/cron.daily# ./quarantine_report.php

 === Generating report for xxxx type=D
 ==== Recipient e-mail address is xxxx
 ==== Building list for xxxx
 ==== Found 9 quarantined e-mails
PHP Strict Standards:  Non-static method Mail::factory() should not be called statically in /etc/cron.daily/quarantine_report.php on line 490

Strict Standards: Non-static method Mail::factory() should not be called statically in /etc/cron.daily/quarantine_report.php on line 490
PHP Deprecated:  Non-static method Mail_RFC822::parseAddressList() should not be called statically, assuming $this from incompatible context in /usr/share/php/Mail.php on line 253

Deprecated: Non-static method Mail_RFC822::parseAddressList() should not be called statically, assuming $this from incompatible context in /usr/share/php/Mail.php on line 253
 ==== Sent e-mail to xxxx

 === Generating report for sleclerc type=A
 ==== Recipient e-mail address is xxxx
 ==== Building list for xxxx
 ==== Found 0 quarantined e-mails

Many problems in the received mail.

- top message with wrong coding
- message subject with wrong coding (should be "test utf8 &éèààà  èèèèèèè ççççççç")
- link not good, double // (https://server.domain.tld//viewmail.php?id=1cOj19-0003WU-3v)
- link doesn't work if not logged in mailwatch (we got https://viewmail.php/?id=1cOix4-0003SK-4J after the logging)

![2d34850a-d32b-11e6-95b8-6440db503100](https://cloud.githubusercontent.com/assets/12907102/21680605/0b5b7806-d34b-11e6-87b5-2a2bf73ed489.png)

**Comment by asuweb** [comment]
@stefaweb 

> link not good, double // (https://server.domain.tld//viewmail.php?id=1cOj19-0003WU-3v)

What is `QUARANTINE_REPORT_HOSTURL` set to?

> link doesn't work if not logged in mailwatch (we got https://viewmail.php/?id=1cOix4-0003SK-4J after the logging)

Do you mean it took you to the wrong mail after logging in?  If so, is the mail ID `1cOix4-0003SK-4J` one of the other emails in the report?

**Comment by stefaweb** [comment]
QUARANTINE_REPORT_HOSTURL : I have removed the / at the end. Fine now.

If logged: we go directly to the right message.

If not logged: mail scanner present the login page and after go to the message but the hostname is lost. We got server do not exist and the url is https://viewmail.php/?id=1cOix4-0003SK-4J

**Comment by stefaweb** [comment]
Work now when not logged. The problem was the double "/".

**Comment by asuweb** [comment]
The coding issue appear related to your other issue #350, quarantine reports are working normally on my dev server

**Comment by stefaweb** [comment]
Don't think.
Encoding is ok in the exim log, database and on the GUI screens.

**Comment by stefaweb** [comment]
In received mail: 

Content-Transfer-Encoding: quoted-printable
Content-Type: text/plain; charset=**ISO-8859-1**

Content-Transfer-Encoding: quoted-printable
Content-Type: text/html; charset=**ISO-8859-1**

**Comment by stefaweb** [comment]
OK, fix to the code.

Added:

$mime_params = array(
  'text_encoding' => '7bit',
  'text_charset'  => 'UTF-8',
  'html_charset'  => 'UTF-8',
  'head_charset'  => 'UTF-8'
);

And $body = $mime->get($mime_params);

**Comment by stefaweb** [comment]
Done in #342.

**Comment by endelwar** [comment]
Also quarantine_report is using system PEAR Mail package, this need to be addressed

**Comment by asuweb** [comment]
> Also quarantine_report is using system PEAR Mail package, this need to be addressed

Have you a preference as to what it's replaced with?  PhpMailer / Swiftmailer or some other?

**Comment by stefaweb** [comment]
I've done this in f30fccb.

How to localise the string in SQL query?

**Comment by asuweb** [comment]
> How to localise the string in SQL query?

Possibly something like this (I haven't tested it though):

`CASE
 WHEN a.virusinfected>0 THEN '" . __('string01') . "'`

**Comment by stefaweb** [comment]
Fixed in PR #342 (a7f12b4).

**Comment by stefaweb** [comment]
I've a conflict in quarantine_action.php

<td align="center"><b><a href="javascript:window.close()"><?php echo __('closewindow57') ?></a></td>

Don't know to solve it.

**Comment by asuweb** [comment]
That bug was merged in PR #352.  your branch is out of date I assume

**Comment by stefaweb** [comment]
Seems ok now.

I've found another window.close without javascript.
