### ISSUE TITLE
quarantine_action.php and window.close()

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#352]
In quarantine_action.php the window.close doesn't work.

<td align="center"><b><a href="window.close()"><?php echo __('closewindow57') ?></a></td>

We got:

Not Found
The requested URL /window.close() was not found on this server.

![capture d ecran 2017-01-05 a 13 10 25](https://cloud.githubusercontent.com/assets/12907102/21680646/549da93a-d34b-11e6-943f-0a11f1930e27.png)

**Comment by asuweb** [comment]
Fixed in #352
