### ISSUE TITLE
Use SpamAssassin = &SQLNoScan no longer working

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#354]
Seems &SQLNoScan not working (was).

If Use SpamAssassin = yes, we got the SA option in details.php

![capture d ecran 2017-01-05 a 23 05 36](https://cloud.githubusercontent.com/assets/12907102/21699350/902546de-d39b-11e6-863a-be94dc485ef4.png)

If Use SpamAssassin = &SQLNoScan, the case is blank.

![capture d ecran 2017-01-05 a 23 04 48](https://cloud.githubusercontent.com/assets/12907102/21699353/93e9c4fc-d39b-11e6-9087-6cd04a9b8a0c.png)

**Comment by endelwar** [comment]
As long as I remember, this only worked if set to `Yes`

Look at this line from 1.2.0-beta4-patch4 (21 Aug 2013) : https://github.com/mailwatch/1.2.0/blob/1.2.0-beta4-patch4/mailscanner/detail.php#L391

**Comment by stefaweb** [comment]
But this will not work?

![capture d ecran 2017-01-06 a 10 26 05](https://cloud.githubusercontent.com/assets/12907102/21713541/c43c1a7e-d3fa-11e6-9a36-b5840f802ffc.png)

In the 1.x patched version, it was working.

**Comment by endelwar** [comment]
mmm... it's better to check for `Use SpamAssassin = no`, so that detail.php shows SA Learn select if there is a rule for that MailScanner value.

**Comment by stefaweb** [comment]
Tested. Ok.
