### ISSUE TITLE
Score error in web UI

### ISSUE THREAD

**Issue by yogurtnaturalny** [mailwatch/1.2.0#355]
Hi guys 

Could you inform me if I did something wrong or this is a bug please ? 

We have MailWatch on Debian 8 with RC2 version and all work fine 

however wen we create Centos 7 ( php 5,4 and Mariadb 10.1 ) with RC4 we have a issue with incorrect information about score in web UI 

![image](https://cloud.githubusercontent.com/assets/17578657/21711121/eec572c4-d3e4-11e6-9c2d-24222aab6998.png)

Can You help me please ?

**Comment by yogurtnaturalny** [comment]
Hi Guys 

I just install RC2 version and all works fine so this is code bug 4sure

**Comment by endelwar** [comment]
I confirm, it was fixed in development branch (commit https://github.com/mailwatch/1.2.0/commit/ebafe548dc855d06f7d7216a08922e5496c5db42)
