### ISSUE TITLE
Documentation for Quarantine Maintenance

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#357]
In wiki, we have:

Quarantine Maintenance
Remove the clean.quarantine cronjob configured with MailScanner.
Edit and copy quarantine_maint.sh to /etc/cron.daily/
You will then to edit conf.php the QUARANTINE_DAYS_TO_KEEP definition.
You will need to edit the quarantine_maint.php to reflect the location of the functions.php file

In tools/Cron_jobs/INSTALL, we have:

Quarantine Maintenance
Remove the clean.quarantine
quarantine_maint.php
add to /etc/cron.daily/
You need to edit conf.php the QUARANTINE_DAYS_TO_KEEP definition.
You need to edit the quarantine_maint.php to reflect the location of the functions.php file

We have two versions of the install documentation.

No clear if we still need to use quarantine_maint.sh?
No clear where  should go quarantine_maint.php in wiki?

**Comment by stefaweb** [comment]
See #370

**Comment by stefaweb** [comment]
Done basic INTALL rewrite in #380

**Comment by endelwar** [comment]
I'm leaving this open as docs.mailwatch.org need to be updated: it will be the main (only?) source for updated documentation

**Comment by stefaweb** [comment]
Too fast?

**Comment by stefaweb** [comment]
ok

**Comment by stefaweb** [comment]
I've started to update docs.

**Comment by endelwar** [comment]
This issue was moved to mailwatch/mailwatch-docs#19
