### ISSUE TITLE
New quarantine_report.php error

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#358]
With last DEV upload.

```
antispam-test:/home/sleclerc/mailwatch-1.2.0-dev# /etc/cron.daily/quarantine_report.php
PHP Fatal error:  Class 'Mail' not found in /var/www/html/mailscanner/lib/pear/Mail/mail.php on line 51

Fatal error: Class 'Mail' not found in /var/www/html/mailscanner/lib/pear/Mail/mail.php on line 51
```

**Comment by asuweb** [comment]
Have you checked the path actually exists?

**Comment by stefaweb** [comment]
Yes.

`-rw-r--r-- 1 root root 6167 janv.  6 09:10 /var/www/html/mailscanner/lib/pear/Mail/mail.p`

**Comment by asuweb** [comment]
sorry, I mis-read it, I can see it found the file

**Comment by asuweb** [comment]
Looks like Mail.php hasn't been included.  

Try addding 

`require_once '../Mail.php'` to the first line in the mail.php file

**Comment by stefaweb** [comment]
in /var/www/html/mailscanner/lib/pear/Mail/mail.php

line 51

class Mail_mail extends Mail {

**Comment by endelwar** [comment]
there is a missing include, will fix this

**Comment by stefaweb** [comment]
Ok.
I tested. All seems fine.
