### ISSUE TITLE
upgrade.php error

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#360]
Last commit from you. Updated files on the dev server and run upgrade.php.

antispam-test:/home/xxxxx/mailwatch-1.2.0-dev# ./upgrade.php
PHP Notice: Use of undefined constant DEBUG - assumed 'DEBUG' in /home/sleclerc/mailwatch-1.2.0-dev/mailscanner/functions.php on line 865

Notice: Use of undefined constant DEBUG - assumed 'DEBUG' in /home/sleclerc/mailwatch-1.2.0-dev/mailscanner/functions.php on line 865
Cannot read conf.php - please create it by copying conf.php.example and modifying the parameters to suit.

**Comment by endelwar** [comment]
**Cannot read conf.php - please create it by copying conf.php.example and modifying the parameters to suit.**

upgrade.php is intended to be used in a running (and configured) system

**Comment by stefaweb** [comment]
But the system is configured.

I placed the file in /var/www/html/mailscanner/


antispam-test:/var/www/html/mailscanner# ./upgrade.php
PHP Warning:  require(/var/www/html/mailscanner/mailscanner/functions.php): failed to open stream: No such file or directory in /var/www/html/mailscanner/upgrade.php on line 35

Warning: require(/var/www/html/mailscanner/mailscanner/functions.php): failed to open stream: No such file or directory in /var/www/html/mailscanner/upgrade.php on line 35
PHP Fatal error:  require(): Failed opening required '/var/www/html/mailscanner/mailscanner/functions.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/mailscanner/upgrade.php on line 35

Fatal error: require(): Failed opening required '/var/www/html/mailscanner/mailscanner/functions.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/mailscanner/upgrade.php on line 35

**Comment by stefaweb** [comment]
Need to change:

require __DIR__ . '/mailscanner/functions.php';

with 

require __DIR__ . '/functions.php';

**Comment by endelwar** [comment]
You don't need to move upgrade.php, just to adjust path to functions.php

**Comment by asuweb** [comment]
`__DIR__` only works if the upgrade script is placed in the web root (/var/www/html). 

Personally, I think it's better to explicitly set the path to function for the upgrade script, as I don't run mine from the web root.

**Comment by stefaweb** [comment]
Ok. I reverted to  
require '/var/www/html/mailscanner/functions.php';
As this, it will work "out of the box".
