### ISSUE TITLE
Illegal mix of collations (utf8_unicode_ci,IMPLICIT) and (utf8_general_ci,IMPLICIT) 

### ISSUE THREAD

**Issue by renarios** [mailwatch/1.2.0#365]
After upgrading to 1.2 RC4, I get the following issue:

Could not use Custom Function code MailScanner::CustomConfig::InitSQLWhitelist, it could not be "eval"ed. Make sure the module is correct with perl -wc (Error: DBD::mysql::st execute failed: Illegal mix of collations (utf8_unicode_ci,IMPLICIT) and (utf8_general_ci,IMPLICIT) for operation '=' at /usr/share/MailScanner/MailScanner/CustomFunctions/SQLBlackWhiteList.pm line 132.: 2 Time(s)

I checked the characterset in the database:
 SELECT @@character_set_database, @@collation_database;
+------------------------------+----------------------+
| @@character_set_database | @@collation_database |
+------------------------------+----------------------+
| utf8                                       | utf8_unicode_ci      |
+------------------------------+----------------------+

Cheers,
Rene

**Comment by endelwar** [comment]
This is a known issue of RC4, fixed in commit https://github.com/mailwatch/1.2.0/commit/0e9cb66f18b7724b616306c039a05e71383284bd

Did you run the upgrade.php script after upgrading to RC4?

**Comment by endelwar** [comment]
Well, don't run RC4 version of upgrade.php, there is where the error is, sorry.

just get latest develop branch upgrade.php script and run it: it should fix this problem (and upgrade your db to utf8mb4 if MySQL version >= 5.5.3)

**Comment by renarios** [comment]
I ran the upgrade.php after upgrading to RC4.
I just cloned the git and ran "source upgrade_mysql_db_to_utf8mb4.sql; Now it works like a pro!
Thanks a lot!
