### ISSUE TITLE
clamd, systemd and GUI : clamd not detected

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#367]
I migrated my dev server on a fresh Debian 8 install (I was using Wheezy).

With Debian 8.6 jessie, clamd work with systemd (clamav-freshclam too).

/lib/systemd/system/clamav-daemon.service
/lib/systemd/system/clamav-daemon.socket

As result, /var/run/clamav/clamd.pid no longer exist.

And clamd is no longer detected in GUI (clamav_status.php, sf_version.php, etc.).

```
ii  clamav                                0.99.2+dfsg-0+deb8u2          amd64        anti-virus utility for Unix - command-line interface
ii  clamav-base                           0.99.2+dfsg-0+deb8u2          all          anti-virus utility for Unix - base package
ii  clamav-daemon                         0.99.2+dfsg-0+deb8u2          amd64        anti-virus utility for Unix - scanner daemon
ii  clamav-freshclam                      0.99.2+dfsg-0+deb8u2          amd64        anti-virus utility for Unix - virus database update utility
ii  libclamav-client-perl                 0.11-2                        all          Perl client for the ClamAV virus scanner daemon
ii  libclamav7                            0.99.2+dfsg-0+deb8u2          amd64        anti-virus utility for Unix - library
```

**Comment by asuweb** [comment]
Are there any errors in the apache log when you try to display the status?

**Comment by stefaweb** [comment]
Status on Wheezy:

```
antispam-test:/home# service clamav-daemon status
clamd is running.
Status on Jessie:

```
antispam-dev:/etc/MailScanner# service clamav-daemon status
● clamav-daemon.service - Clam AntiVirus userspace daemon
   Loaded: loaded (/lib/systemd/system/clamav-daemon.service; enabled)
   Active: active (running) since dim. 2017-01-08 10:13:15 CET; 39min ago
     Docs: man:clamd(8)
           man:clamd.conf(5)
           http://www.clamav.net/lang/en/doc/
 Main PID: 26553 (clamd)
   CGroup: /system.slice/clamav-daemon.service
           └─26553 /usr/sbin/clamd --foreground=true

janv. 08 10:13:50 antispam-dev clamd[26553]: Portable Executable support enabled.
janv. 08 10:13:50 antispam-dev clamd[26553]: ELF support enabled.
janv. 08 10:13:50 antispam-dev clamd[26553]: Mail files support enabled.
janv. 08 10:13:50 antispam-dev clamd[26553]: OLE2 support enabled.
janv. 08 10:13:50 antispam-dev clamd[26553]: PDF support enabled.
janv. 08 10:13:50 antispam-dev clamd[26553]: SWF support enabled.
janv. 08 10:13:50 antispam-dev clamd[26553]: HTML support enabled.
janv. 08 10:13:50 antispam-dev clamd[26553]: XMLDOCS support enabled.
janv. 08 10:13:50 antispam-dev clamd[26553]: HWP3 support enabled.
janv. 08 10:13:50 antispam-dev clamd[26553]: Self checking every 3600 seconds.

**Comment by stefaweb** [comment]
"Are there any errors in the apache log when you try to display the status?"

NO

**Comment by stefaweb** [comment]
Debian Jessie need more setup in Mailcanner.conf:

Run As User = Debian-exim
Run As Group = Debian-exim
Incoming Work User = Debian-exim
Incoming Work Group = clamav
Incoming Work Permissions = 0660
Quarantine User = Debian-exim
Quarantine Group = mtagroup
Quarantine Permissions = 0644

**Comment by stefaweb** [comment]
I've found this after apache restart and again ran clamav_status.php.

```
mkdir: cannot create directory '/var/spool/MailScanner/incoming': Permission denied
mktemp: failed to create directory via template '/var/spool/MailScanner/incoming/clamav-tmp/tmp.XXXXXXXXXX': Permission denied
ERROR: Option --tempdir requires a non-empty string argument
ERROR: Can't parse command line options
```

```
antispam-dev:/etc/MailScanner# ll /var/spool/MailScanner/
total 8
drwxrwxr-x  2 Debian-exim mtagroup 4096 janv.  7 23:29 archive
drwxrwx--- 15 Debian-exim clamav    340 janv.  8 09:56 incoming
drwxrwxr-x  2 Debian-exim mtagroup 4096 janv.  7 09:51 quarantine
```

```
antispam-dev:/etc/MailScanner# ll /var/spool/MailScanner/incoming/
total 12
drwxrwx--- 2 Debian-exim clamav        40 janv.  8 09:55 23330
drwxrwx--- 2 Debian-exim clamav        40 janv.  8 09:56 23382
drwxrwx--- 2 Debian-exim clamav        40 janv.  8 09:56 23393
drwxrwx--- 2 Debian-exim clamav        40 janv.  8 09:56 23405
drwxrwx--- 2 Debian-exim clamav        40 janv.  8 09:56 23411
drwxrwx--- 2 Debian-exim clamav        40 janv.  8 09:56 23415
drwxrwx--- 2 Debian-exim clamav        40 janv.  8 09:56 23419
drwxrwx--- 2 Debian-exim clamav        40 janv.  8 09:56 23430
drwxrwx--- 2 Debian-exim clamav        40 janv.  8 09:56 23435
drwxrwx--- 2 Debian-exim clamav        40 janv.  8 09:56 23439
drwx------ 2 Debian-exim Debian-exim   40 janv.  7 23:45 clamav-tmp
drwxr-xr-x 2 root        Debian-exim  200 janv.  8 09:55 Locks
-rw-rw---- 1 Debian-exim Debian-exim 4096 janv.  8 08:28 Processing.db
-rw-rw---- 1 Debian-exim Debian-exim 5120 janv.  7 17:05 SpamAssassin.cache.db
drwxr-xr-x 2 Debian-exim root          60 janv.  8 09:56 SpamAssassin-Temp
```

**Comment by asuweb** [comment]
Assuming the apache user is in you mtagroup, then the following will fix it:

`chown Debian-exim:mtagroup /var/spool/MailScanner/incoming/clamav-tmp
chmod g+wrx /var/spool/MailScanner/incoming/clamav-tmp`

**Comment by stefaweb** [comment]
No change. I also tried with chmod 777 clamav-tmp. No change.

Do you know, which program try to create "clamav-tmp"?

**Comment by stefaweb** [comment]
Found: "incoming" should be mtagroup group owner.

drwxrwx--- 15 Debian-exim mtagroup  340 janv.  8 11:23 incoming

Need to change: Incoming Work Group = mtagroup

Works.

**Comment by asuweb** [comment]
That would do it

**Comment by stefaweb** [comment]
I also try to "optimize" the SpamAssassin-Temp directory group owner to be mtagroup.

drwxr-xr-x 2 Debian-exim root          60 janv.  8 09:56 SpamAssassin-Temp

No found how to change group from "root" to "mtagroup". If I delete SpamAssassin-Temp, it is re created with group root.

**Comment by asuweb** [comment]
> I also try to "optimize" the SpamAssassin-Temp directory group owner to be mtagroup.

Probably best to direct this to the mailscanner lists, as this is not a mailwatch issue (afaik)

**Comment by stefaweb** [comment]
Done.
Updated issue #330.
