### ISSUE TITLE
Mailscanner report in v5

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#375]
Hello!

Each morning, I receive this message from Mailscanner.

It's sent by cron.daily/mailscanner

# daily actions
/usr/sbin/ms-cron DAILY

But I can't comment out this as ms-cron DAILY run other things too.

Does someone know how to stop sending it?

```
/etc/cron.daily/mailscanner:
 % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                Dload  Upload   Total   Spent    Left  Speed

 0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  8643  100  8643    0     0  39926      0 --:--:-- --:--:-- --:--:-- 40013
 % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                Dload  Upload   Total   Spent    Left  Speed

 0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  107k    0  107k    0     0   206k      0 --:--:-- --:--:-- --:--:--  206k
```

**Comment by shawniverson** [comment]
I modified mailscanner and appended >/dev/null 2>&1 to the offending line.

**Comment by stefaweb** [comment]
Thanks.
Will try.
The only problem is if one of the script run by "ms-cron DAILY" crash, we will not be notified.
The best will be to have a "report" flag in /etc/Mailscanner/default.
