### ISSUE TITLE
PEAR : Pager.php

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#376]
We have version 2.4.7 currently.

Version 2.4.9 is available here.
http://pear.php.net/package/Pager/

**Comment by endelwar** [comment]
Actually from RC4 is in use a fork of official Pear Pager modified for php5/7 support: https://github.com/gartner/pear-pager
Official Pear Pager has still (deprecated) php4 class construct support

**Comment by stefaweb** [comment]
Sorry but great.
Next try !  ;)
