### ISSUE TITLE
Graph no longer works: imageantialias() is not available

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#386]
All graph scripts no longer works on my new dev server.

I got:

`JpGraph Error: 25128 The function imageantialias() is not available in your PHP installation. Use the GD version that comes with PHP and not the standalone version.`

Debian Jessie
php5-gd 5.6.29+dfsg-0+deb8u1

/etc/php5/cli/conf.d/20-gd.ini,
GD Support => enabled
GD headers Version => 2.1.1-dev
gd.jpeg_ignore_warning => 0 => 0

**Comment by stefaweb** [comment]
See lib/jpgraph/src/gd_image.inc.php

            JpGraphError::RaiseL(25128);//('The function imageantialias() is not available in your PHP installation. Use the GD version that comes with PHP and not the standalone version.')

**Comment by stefaweb** [comment]
In case of need, found this fork of JpGraph.

https://github.com/umanit/jpgraph

**Comment by stefaweb** [comment]
They also have a new 4.0.2 version.
http://jpgraph.net/download/

**Comment by stefaweb** [comment]
Works if we comment out line 110 of gd_image.inc.php.

**Comment by stefaweb** [comment]
Better solve.

In lib/jpgraph/src/jpg-config.inc.php at line 137 (at the end), add:

```
if(!ANTIALIASING){
    function imageantialias($image, $enabled){
        return true;
    }
}
```

**Comment by endelwar** [comment]
you should report this also to JpGraph.

**Comment by stefaweb** [comment]
I can do it if you want?

- update to 4.0.2
- patch for jpg-config.inc.php

**Comment by endelwar** [comment]
I've looked better at this issues and seems related to Debian/Ubuntu decision to not include this function for their policy (see https://lists.debian.org/debian-user/2015/03/msg00283.html)

**Comment by stefaweb** [comment]
Another resolution is to place this at the ned of  jpg-config.inc.php if Debian PHP.

`define('ANTIALIASING', false);`

No more.

**Comment by stefaweb** [comment]
Updated PR.

```
// Patch for Debian PHP
define('ANTIALIASING', false);

if(!ANTIALIASING){
    function imageantialias($image, $enabled){
        return true;
    }
}
// End
```

Just for information. PHP 5.6 Dotdeb is not available for Debian Jessie. 
Only PHP version 7.

**Comment by stefaweb** [comment]
Fixed in #389.

**Comment by Skywalker-11** [comment]
The patch also works if it is put in the top part of functions.php so we don't have to mess with the JpGraph library eg [https://github.com/Skywalker-11/1.2.0/commit/0b03f4cb4a4af76a7bfa4dc9a954af4d7d214052](https://github.com/Skywalker-11/1.2.0/commit/0b03f4cb4a4af76a7bfa4dc9a954af4d7d214052)

**Comment by stefaweb** [comment]
Great!

Remove lib/jpgraph/UPDATE no longer needed.
