### ISSUE TITLE
No release button in Quarantine

### ISSUE THREAD

**Issue by branko77** [mailwatch/1.2.0#392]
Hi! I managed to set up my MailWatch yesterday with a lot of help from other members for what I am more than grateful.
But I have an minor issue that I just noticed. 
When I open any of quarantined messages and scroll down to the end I can not find "Release button" and thus can not release email from quarantine... Did a bit of googling today but couldn't find any clue to resolve this...  Any ideas about this?

**Comment by asuweb** [comment]
I presume you have in mailscanner.conf, `Spam Action = store`?

**Comment by branko77** [comment]
No, I don't have that in my mailscanner.conf? Should it I manually put it in conf file?

**Comment by stefaweb** [comment]
You should have this at the bottom page of detail.php BUT ONLY if the quarantined message is "stored".

![capture d ecran 2017-01-13 a 15 53 00](https://cloud.githubusercontent.com/assets/12907102/21934169/b9c9b066-d9a8-11e6-92ec-307332305189.png)

**Comment by stefaweb** [comment]
This:

![capture d ecran 2017-01-13 a 15 57 07](https://cloud.githubusercontent.com/assets/12907102/21934250/09ee06aa-d9a9-11e6-9e21-7059196f0823.png)

**Comment by branko77** [comment]
No Stef I cant find that what you just posted at the end of detail.php... Last thing I can see is Spam Report

**Comment by branko77** [comment]
This is what I see

![mw](https://cloud.githubusercontent.com/assets/24565680/21934355/60aae7ec-d9a9-11e6-8cee-357b6d840f99.png)

**Comment by asuweb** [comment]
> No, I don't have that in my mailscanner.conf? Should it I manually put it in conf file?

What is the value of `Spam Actions =` in mailscanner.conf

**Comment by endelwar** [comment]
@branko77 did you follow the installation guide, and more specifically this paragraph: http://docs.mailwatch.org/doc/installing.html#set-up-mailscanner

**Comment by stefaweb** [comment]
Don't modify "shipped' /etc/MailScanner/MailScanner.conf. 
Use a file name as myconf.conf in /etc/MailScanner/conf.d/.
Read /etc/MailScanner/conf.d/README

**Comment by branko77** [comment]
Sorry asuweb I didn't saw it first time... In matter of fact i do have Spam Actions = store in my conf file

**Comment by branko77** [comment]
Thanks for help I will try with your suggestions and will let you know

**Comment by stefaweb** [comment]
Verify write access in OS. 
If no stored, no file in /var/spool/MailScanner/quarantine/

**Comment by branko77** [comment]
Well I am back from weekend brake... Checked all you guys suggested and this is what I found: 
In /var/spool/MailScanner/quarantine/ I can see
drwxrwx---   5 postfix mtagroup    59 Jan 10 09:30 20170110
drwxrwx---   3 postfix mtagroup    17 Jan 11 00:05 20170111
drwxrwx---   7 postfix mtagroup   105 Jan 12 17:39 20170112
drwxrwx---   3 postfix mtagroup    17 Jan 13 00:11 20170113
drwxrwx---   3 postfix mtagroup    17 Jan 14 00:23 20170114
drwxrwx---   3 postfix mtagroup    17 Jan 15 00:10 20170115
drwxrwx---   3 postfix mtagroup    17 Jan 16 00:15 20170116

in /var/spool/MailScanner/quarantine/20170116 I can see 
drwxrwx--- 2 postfix mtagroup 4096 Jan 16 09:50 spam

in /var/spool/MailScanner/quarantine/20170116/spam I can see 
-rw-rw---- 1 postfix mtagroup   2509 Jan 16 05:55 045FE601.AF985
-rw-rw---- 1 postfix mtagroup   2659 Jan 16 03:19 0A3C660A.A3F58
-rw-rw---- 1 postfix mtagroup  20014 Jan 16 01:47 0B88B601.AD591
-rw-rw---- 1 postfix mtagroup   2564 Jan 16 00:19 1AD17601.AF681
-rw-rw---- 1 postfix mtagroup 795691 Jan 16 09:41 218CDA6.A6BC1
-rw-rw---- 1 postfix mtagroup  35367 Jan 16 08:28 2507A601.AB6DC
-rw-rw---- 1 postfix mtagroup   2157 Jan 16 01:49 26C51601.AD701
-rw-rw---- 1 postfix mtagroup 795707 Jan 16 09:32 2963E7A1.A2C6F
-rw-rw---- 1 postfix mtagroup  21404 Jan 16 06:29 2CEB5608.A4B45
-rw-rw---- 1 postfix mtagroup   2650 Jan 16 02:29 34119601.A7E22
-rw-rw---- 1 postfix mtagroup   2318 Jan 16 00:16 38BF6601.A68EE
-rw-rw---- 1 postfix mtagroup   2275 Jan 16 01:14 38C74601.A14D4
-rw-rw---- 1 postfix mtagroup  35367 Jan 16 00:32 3C56460A.ACD58
 So I think that write access in OS are fine...

In my MailScanner.conf I have Spam Actions = store entry...

I checked step by step http://docs.mailwatch.org/doc/installing.html#set-up-mailscanner and everything is fine... I am not using bayes so I skipped this part "Move the Bayesian Databases and set-up permissions (skip this if you don’t use bayes)."

I still can't see release option in my quarantined emails... Any thoughts?

**Comment by endelwar** [comment]
which users are in mtagroup? is your webserver user in there?

**Comment by branko77** [comment]
mtagroup:x:5002:postfix,mail
No it's not in the mtagroup... should I put it in?

**Comment by asuweb** [comment]
Yes, add apache to this group

**Comment by branko77** [comment]
I just did it 
usermod -a -G mtagroup apache
Now vigr show mtagroup:x:5002:postfix,mail,apache
And I restarted service mailscanner

**Comment by branko77** [comment]
There is now changes in the previously quarantined messages... still no release button...

**Comment by branko77** [comment]
and newly quarantined emails still has no release option in the detail view

**Comment by branko77** [comment]
But after restart of httpd service there it is... :)
Thanks again guys... You are the best!

**Comment by branko77** [comment]
I thanked you little bit ahead... when I try to release I got an error:
Fatal error: Cannot redeclare _PEAR_call_destructors() (previously declared in /var/www/html/mailscanner/lib/pear/PEAR.php:773) in /usr/share/pear/PEAR.php on line 777

**Comment by endelwar** [comment]
This is a separate issue: I bet you have PEAR installed through yum.

I'm closing this support ticket and opening a new one.
