### ISSUE TITLE
Wishlist: limit text length in  columns in mysql_status.php

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#393]
Can we truncate the line to ovoid this?

We can may be define fix columns width.

We get a very very large screen.

![mysql](https://cloud.githubusercontent.com/assets/12907102/21935080/4a085440-d9ac-11e6-8c7a-f57b4ced12dc.jpg)

**Comment by endelwar** [comment]
well, this is a debug page, if we truncate this output information that can be useful for debugging and support can't be shown

**Comment by stefaweb** [comment]
Sorry, "Truncate" is not the right word.
I was thinking to limit the line to XXX characters and create a new line with the rest of characters. 
Or limit the size of the column.
Any solution to have a screen not too large.

**Comment by Skywalker-11** [comment]
if we savely can add spaces in that string we could use this [http://stackoverflow.com/a/5852740](http://stackoverflow.com/a/5852740)

**Comment by stefaweb** [comment]
This? 

```
code { 
  white-space: pre-wrap; 
}
```

**Comment by Skywalker-11** [comment]
and word-wrap: break-word;

**Comment by stefaweb** [comment]
I tried but doesn't work.

Line 2366 of functions.php

echo '  <td style="background-color: ' . $bgcolor . '; white-space: pre-wrap; word-wrap: break-word; ">' . $row[$f] . '</td>' . "\n";


```
  <td style="style="background-color: #D8D8D8; white-space: pre-wrap; word-wrap: break-word; ">index_merge=on,index_merge_union=on,index_merge_sort_union=on,index_merge_intersection=on,index_merge_sort_intersection=off,engine_condition_pushdown=off,index_condition_pushdown=on,derived_merge=on,derived_with_keys=on,firstmatch=on,loosescan=on,materialization=on,in_to_exists=on,semijoin=on,partial_match_rowid_merge=on,partial_match_table_scan=on,subquery_cache=on,mrr=off,mrr_cost_based=off,mrr_sort_keys=off,outer_join_with_cache=on,semijoin_with_cache=on,join_cache_incremental=on,join_cache_hashed=on,join_cache_bka=on,optimize_join_buffer_size=off,table_elimination=on,extended_keys=on,exists_to_in=on</td>

```

**Comment by Skywalker-11** [comment]
It can't work. We must have spaces in the line. There the browsers would make a line break

**Comment by stefaweb** [comment]
Work a little better with:

```
               echo '  <td style="word-wrap: break-word;
                                  word-break: break-all;
                                  width: 200px;
                                  background-color: ' . $bgcolor . '; ">' . $row[$f] . '</td>
               ' . "\n";
```

But its more difficult than I thank.

dbtable() is also used in user_manager.php.
The mod impact all tables in the pages of user_manager and mysql_status.

**Comment by stefaweb** [comment]
Another way to do very less intrusive. 
I vote for!

`echo '  <td style="background-color: ' . $bgcolor . '; ">' . str_replace(",", ", ", $row[$f]) . '</td>' . "\n";`

**Comment by Skywalker-11** [comment]
That should work but when we already trying to put all css in one file the style part should be replaced by a css class and defined in style.css

**Comment by endelwar** [comment]
Maybe a combination of `table-layout:fixed;` on table and `word-wrap:break-word;` on td should have some benefit

**Comment by stefaweb** [comment]
I tried but side effect on others tables in user_manager and mysql_status.

**Comment by Skywalker-11** [comment]
How about wrapping that mysql table with a div of class tablewrap and then using
.tablewrap>table
to only apply that css rules for that tables

**Comment by stefaweb** [comment]
Have a look at the dbtable() function. 
If you want to try. ;)

My solution is not the best as we replace "x,x" with "x, x" and if somewhere we have a useful comma, boom!

**Comment by endelwar** [comment]
I'm with @Skywalker-11 , let's wrap the table and create a specific css rule for it

**Comment by stefaweb** [comment]
Found an acceptable solution without preg_replace()

9dc189b

**Comment by Skywalker-11** [comment]
you still have preg_replace there

**Comment by stefaweb** [comment]
Done in #420.
