### ISSUE TITLE
Bug in reports.php (Add when empty)

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#394]
If we click on Add without have done anything. We got an error.

Stay with the error until we click on "Remove".

![capture d ecran 2017-01-14 a 16 26 20](https://cloud.githubusercontent.com/assets/12907102/21955994/8b7f113c-da76-11e6-9022-de9f42061a5d.png)

**Comment by asuweb** [comment]
Fixed in #403

**Comment by asuweb** [comment]
I suspect the bug has been there for a while, but gone unnoticed.  E_NOTICE is usually off in production environments

**Comment by stefaweb** [comment]
Great! It works.

**Comment by stefaweb** [comment]
Done.

**Comment by stefaweb** [comment]
Done.
