### ISSUE TITLE
Conflict with system PEAR packages

### ISSUE THREAD

**Issue by endelwar** [mailwatch/1.2.0#395]
Having PEAR installed via yum or apt create conflict on local MailWatch PEAR packages.

`Fatal error: Cannot redeclare _PEAR_call_destructors() (previously declared in /var/www/html/mailscanner/lib/pear/PEAR.php:773) in /usr/share/pear/PEAR.php on line 777`

reported on #392 and in mailing list

**Comment by branko77** [comment]
I checked and found "Package 1:php-pear-1.9.4-21.el7.noarch already installed and latest version"
Should I remove it?

**Comment by endelwar** [comment]
It depends: do you use PEAR packages for php code on this server (apart MailWatch)? If, as it should be, this server manages only MailScanner and MTA you don't need pear installed via yum.

**Comment by branko77** [comment]
I am using only nagios and webmin apart from MailWatch

**Comment by branko77** [comment]
Maybe to try remove and see if anything goes wrong with another services?

**Comment by endelwar** [comment]
nagios and webmin don't use PEAR, so it should be safe to remove php-pear-1.9.4-21.el7.noarch

**Comment by branko77** [comment]
Ok, thanks I will try and let you know

**Comment by stefaweb** [comment]
I have pear installed on Debian. No problem.

php-pear                              1:1.10.1+submodules+notgz-8.1 all          PEAR Base System

May be a conflict with the php.ini used on system (include_path).

**Comment by branko77** [comment]
Just tried remove and after removing php-pear-1.9.4-21.el7.noarch and restart of httpd everything working like a charm... I just successfully released message from quarantine...
Thank you guys so much!
One additional question... where I can edit email subject and body of the email with released message attached?

**Comment by endelwar** [comment]
Just look in `conf.php` for `QUARANTINE_SUBJECT` and `QUARANTINE_MSG_BODY`

**Comment by branko77** [comment]
Thanks!

**Comment by asuweb** [comment]
This could be solved one of 2 ways for V1.2.

Either a USE_SYSTEM_PEAR in conf.php

Or

A function which checks if required PEAR package is available, and if not loads it.  

Since it seems to only have been raised as an issue recently, I'm assuming it's not that common an issue, so perhaps the simple approach of conf.php would be sufficient?

**Comment by stefaweb** [comment]
The best!
USE_SYSTEM_PEAR

**Comment by asuweb** [comment]
I can't replicate this issue in order to fix it.

**Comment by stefaweb** [comment]
For me this is a bad php.ini in its system.

**Comment by elray** [comment]
I also have this issue. Is there a manual way to sort it ?

**Comment by asuweb** [comment]
@elray - what version of Mailwatch are you running?

**Comment by elray** [comment]
MailWatch Version: 1.2.0 - RC4

MailScanner Version: 4.84.6

ClamAV Version: 0.98.5 

SpamAssassin Version: 3.3.1 

PHP Version: 5.6.30

MySQL Version: 5.1.73

**Comment by stefaweb** [comment]
What do you get, when you type:

`php -i | grep path`

**Comment by asuweb** [comment]
@elray - I did make a patch to fix this bug, but as I couldn't replicate the issue, I couldn't test it.  

If you'd be willing to test it, then I can rebase it on the master branch for you to test. It's based on the develop branch at the moment, which isn't production ready yet.

**Comment by elray** [comment]
@stefaweb. Sorry no Internet access at moment. 

@asuweb. Happy to test on my installation, let me know what to do.

**Comment by asuweb** [comment]
@elray - great.  I'll rebase it tomorrow and let you know when it's ready

**Comment by elray** [comment]
@stefaweb 

include_path => .:/usr/share/pear:/usr/share/php => .:/usr/share/pear:/usr/share/php

**Comment by asuweb** [comment]
@elray - I've ported the changes to the master branch of RC4 if you wish to test.  No guarantee that it will resolve the conflict as I can't replicate the issue to test it, but I'd be interested in feedback.

https://github.com/asuweb/Mailwatch-1.2.0-asuantispam/commit/24edf3af0dbe6000cdfa2c8dbd46ef0680937961

**Comment by elray** [comment]
@asuweb apologies for getting back so late, been on holiday. I've just tested this however it results in blank pages for quarantine now, with this error in apache error log:

PHP Fatal error:  require_once(): Failed opening required 'Pager.php' (include_path='/var/www/html/mailscanner/lib/htmlpurifier/standalone:.:/usr/share/pear:/usr/share/php') in /var/www/html/mailscanner/functions.php on line 1651, referer: quarantine.php

**Comment by asuweb** [comment]
@elray - no problem.

Can you confirm that your system installed pear contains the Pager package?

From the shell

`pear list | grep Pager`

If it isn't, can you install it?

**Comment by Skywalker-11** [comment]
Pager should be packed with mailwatch. 
Have you set MAILWATCH_HOME to the correct path?

**Comment by elray** [comment]
@asuweb Just installed Pager, looks OK viewing quarantine.php. 

When I tried to release an email I got another error in apache error log:

PHP Fatal error:  require_once(): Failed opening required 'Mail.php' (include_path='/var/www/html/mailscanner/lib/htmlpurifier/standalone:.:/usr/share/pear:/usr/share/php') in /var/www/html/mailscanner/functions.php on line 3187, referer: detail.php?id=B59D9E8B6E.AD131

I installed Mail package for Pear then this error went away.

I can now release emails through the MailWatch UI.

Thanks for your help @asuweb

**Comment by elray** [comment]
@Skywalker-11 yep, MAILWATCH_HOME is the correct path

`define('MAILWATCH_HOME', '/var/www/html/mailscanner');`

**Comment by asuweb** [comment]
@Skywalker-11 - we're testing this with a possible patch to allow system pear for those who have pear conflicts - so in this case we're attempting to bypass mailwatch pear.  

@elray - Excellent, so the patch works without issue assuming the required pear packages are installed?

**Comment by elray** [comment]
@asuweb All working now I installed patch + Mail and Pager Pear packages

**Comment by asuweb** [comment]
Excellent, thanks.  I'll push the patch to MailWatch :)

**Comment by stefaweb** [comment]
Great!
