### ISSUE TITLE
Bug in Audit Log

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#398]
I have a small problem in Log Audit.

The system print "Ran report SpamAssassin Lint" but should be "Ran SpamAssassin Lint". 

![capture d ecran 2017-01-17 a 13 23 33](https://cloud.githubusercontent.com/assets/12907102/22020390/48653680-dcb8-11e6-90ac-f1e09d573605.png)

The problem is not in language files.

Not found where to look.

**Comment by stefaweb** [comment]
In fact, the problem is different.

We have 2 lines printed in Log Audit for only one run of "SpamAssassin Lint (Test)".

![capture d ecran 2017-01-17 a 13 46 28](https://cloud.githubusercontent.com/assets/12907102/22021082/99e79b3a-dcbb-11e6-8b36-33a08f9f4ff3.png)

![capture d ecran 2017-01-17 a 13 44 55](https://cloud.githubusercontent.com/assets/12907102/22021088/9fee945c-dcbb-11e6-83fd-020a1104a750.png)

**Comment by asuweb** [comment]
I don't see any issue with the 2 entities in audit log - after all the only purpose is to track user activity.  The first entry is denoting a page has been accessed, the second is when the lint is actually run.

**Comment by stefaweb** [comment]
With MailScanner Lint, we have only one line in Audit Log (the one without "report").

**Comment by stefaweb** [comment]
Found a difference:

ms_lint.php:
html_start(__('mailscannerlint28'), 0, false, false);

sa_lint.php:
html_start(__('salint51'), 0, false, true);

**Comment by stefaweb** [comment]
If we change "true" to "false" in sa_lint.php we got only "Ran SpamAssassin Lint".

**Comment by asuweb** [comment]
Yes, indeed.

The second bool (true/false) defines if it is a report or not.

**Comment by stefaweb** [comment]
Found the same problem in mysql_status.php.
Done in #405

**Comment by stefaweb** [comment]
Done.
