### ISSUE TITLE
verifyperm03 is missing in all language files 

### ISSUE THREAD

**Issue by Skywalker-11** [mailwatch/1.2.0#406]
it is used for the status of the queues ([functions.php#L385](https://github.com/mailwatch/1.2.0/blob/develop/mailscanner/functions.php#L385)):
![image](https://cloud.githubusercontent.com/assets/11180862/22074294/2db3f36c-dda8-11e6-9956-1caa772231b9.png)

**Comment by stefaweb** [comment]
You can add it to the languages files (at the and of 03-functions.php). Update version.

Sorry, but not sure to understand the problem. Here, seems working.

![capture d ecran 2017-01-18 a 18 10 50](https://cloud.githubusercontent.com/assets/12907102/22074828/01ebe92c-ddaa-11e6-9998-c3a038a77e3e.png)

![capture d ecran 2017-01-18 a 18 11 11](https://cloud.githubusercontent.com/assets/12907102/22074840/0e0df36c-ddaa-11e6-965c-c6730c5f806e.png)

**Comment by Skywalker-11** [comment]
verifyperm03 is only displayed if the permissions of the queue folders are incorrect

**Comment by stefaweb** [comment]
Original line:

`echo '    <tr><td colspan="3">Please verify read permissions on ' . $incomingdir . ' and ' . $outgoingdir . '</td></tr>' . "\n";`

**Comment by stefaweb** [comment]
'verifyperm03' => 'Please verify read permissions on',

French:
'verifyperm03' => 'Veuillez vérifier les autorisations de lecture de',

**Comment by endelwar** [comment]
merged #406
