### ISSUE TITLE
Bug in Black / White List page

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#413]
Seems many bugs in Black / White List page in  lists.php.

When we arrive on the page, the form is empty.

![capture d ecran 2017-01-20 a 13 11 44](https://cloud.githubusercontent.com/assets/12907102/22149086/1e6fa46c-df12-11e6-9663-84d6ef218fa0.png)

If we **create** an entry, after the refresh the form is not well emptied.

![capture d ecran 2017-01-20 a 13 15 43](https://cloud.githubusercontent.com/assets/12907102/22149173/aca8ce98-df12-11e6-86df-f48941737961.png)

If we **delete** an entry, after the refresh the form is filled with some of the variable from the deleted entry.

![21066080-df08-11e6-9951-fc74675f5200](https://cloud.githubusercontent.com/assets/12907102/22149114/57d2849a-df12-11e6-89b6-99802af8e073.png)

**Comment by stefaweb** [comment]
More on this.

If we click on "Reset" nothing append.

**Comment by Skywalker-11** [comment]
The reset button is to reset the formular to the state at which it was when the page is loaded. It does not clear the input fields in case we delete an entry because we set the values when we create the page on the server. My PullRequest fixes this

**Comment by endelwar** [comment]
I think that this is related to autocompleting feature of browser, like seen in #383

**Comment by stefaweb** [comment]
Solved in #410 

This was missing to clear variables:

```
$to_domain = '';
$touser = '';
$from = '';
$url_list = '';
```

**Comment by stefaweb** [comment]
I close it as solved in #410
