### ISSUE TITLE
Problem in user_manager.php (New)

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#416]
The system currently accept to create a duplicate user in user_manager.php?action=new

We can validate the form without error message but the duplicate is not created in the database (or the existing user is updated and crush the original values as password).

**Comment by stefaweb** [comment]
Done

**Comment by endelwar** [comment]
this is not yet merged!

**Comment by Skywalker-11** [comment]
it is now.  can be closed
