### ISSUE TITLE
Combine all CSS into style.css for easier maintenance

### ISSUE THREAD

**Issue by asuweb** [mailwatch/1.2.0#417]
Ref #412 

Having all CSS combined into style.css will ease ongoing maintenance.

I'll work on this

**Comment by Skywalker-11** [comment]
Shouldn't it be style.css?

**Comment by stefaweb** [comment]
Same question. ;)

**Comment by asuweb** [comment]
Yes, typo :)

**Comment by Skywalker-11** [comment]
are you working on this or need help? If yes at what branch are working on this

**Comment by asuweb** [comment]
Yes, I'm working on this.  It will be done tomorrow or Tuesday

**Comment by asuweb** [comment]
How far do we want to go with this?  

Just move style blocks 

`<style></style>`

Or move all most inline styles as well?

**Comment by Skywalker-11** [comment]
I think for 1.2.0 its ok to just move <style>. The inline then can be moved for 2.0

**Comment by stefaweb** [comment]
Could you put this in #496 in your wishlist ?
Not urgent.
