### ISSUE TITLE
Bug if we type two different password in user_manager.php

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#422]
If we type two different password and click on update or create, we go there:

![capture d ecran 2017-01-22 a 14 13 17](https://cloud.githubusercontent.com/assets/12907102/22182738/2fc3fa0a-e0ad-11e6-8b5a-ae1ed4429871.png)

**Comment by stefaweb** [comment]
The system should stay on the same page (edit ou new) not to go on user list.

I suggest to place the error message here:

![capture d ecran 2017-01-22 a 14 44 52](https://cloud.githubusercontent.com/assets/12907102/22182941/1e265ec8-e0b2-11e6-9497-0428e0323774.png)

**Comment by Skywalker-11** [comment]
Ok i will work on it

**Comment by stefaweb** [comment]
Message can be shorter if we use: "Password mismatch"

**Comment by stefaweb** [comment]
In French:  "Mot de passe erroné"

**Comment by Skywalker-11** [comment]
should be fixed with [https://github.com/Skywalker-11/1.2.0/commit/c5706dd27c080d2736aed409aacc7a818fd1224c](https://github.com/Skywalker-11/1.2.0/commit/c5706dd27c080d2736aed409aacc7a818fd1224c)

**Comment by stefaweb** [comment]
Done.
