### ISSUE TITLE
Proposal: Add a version number in conf.php.example

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#423]
Easy method to know if something new in conf.php...

**Comment by endelwar** [comment]
Too many version number (MailWatch, conf.php, languages files) will lead to greater confusion.

I was thinking about a routine that checks if every old and new config constant exists on conf.php, so that only an array of string (the config constant name) has to be maintained

**Comment by stefaweb** [comment]
Better idea than mine. ;)

Or a system as in mailscanner with conf.d/myconfig.conf where we place only things changed.

**Comment by asuweb** [comment]
Yes, this is a well needed feature.

Perhaps something like the following:

text file containing required constant per line

php script (checkconf.php) which reads this file, and checks if it exists in conf.php (if not, it appends it to conf.php).

checkconf.php can be called from the upgrade script as well as on demand (useful for development).

**Comment by asuweb** [comment]
Actually, it could just be part of upgrade.php, doesn't need to be separate at all. :)

**Comment by shawniverson** [comment]
The conf.php changes are admittedly difficult to maintain on upgrades.
Lots of diffing for changes :P

My vote is a conf.d.  Very common approach.  Leave conf.php alone, put
changes in conf.d that override anything present in conf.php.

**Comment by stefaweb** [comment]
No longer a question.
