### ISSUE TITLE
Bug in lists.php (Go to message)

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#424]
If we delete a black or white entry, we got this:

![capture d ecran 2017-01-22 a 17 53 26](https://cloud.githubusercontent.com/assets/12907102/22184121/093f4c4e-e0cc-11e6-802f-f14c0fbc21ca.png)

The number is the entry number ($id) of the deleted entry.

**Comment by stefaweb** [comment]
Not found how to correct this.

**Comment by Skywalker-11** [comment]
The problem is that the field for the jump to message uses $_GET['id'] and the same for the black/whitelist,
So we have to rename one of them.
