### ISSUE TITLE
AD LDAP search failure when LDAP_DN is root of domain

### ISSUE THREAD

**Issue by shawniverson** [mailwatch/1.2.0#43]
The following lines would be needed in functions.php for this situation after line 2240

ldap_set_option($ds, LDAP_OPT_REFERRALS, 0);
ldap_set_option($ds, LDAP_OPT_PROTOCOL_VERSION, 3);

It may be useful to have an LDAP_AD flag in conf.php that when on could set these two options for Active Directory if it is in use.

**Comment by endelwar** [comment]
closed by merge of #158
