### ISSUE TITLE
Wishlist: Show RBL List in Details Page

### ISSUE THREAD

**Issue by mmgomess** [mailwatch/1.2.0#431]
I would like that when MailScanner encounters a message listed in one or more RBL lists, these lists would be shown on the details page on the line "Listed in RBL" like below:

Listed in RBL: Y SPAMHAUS, BARRACUDA

![screen](https://cloud.githubusercontent.com/assets/9742227/22211768/528ed88e-e175-11e6-9bc2-69b63f2d230f.png)

**Comment by asuweb** [comment]
Yes, I have this written on a list of things to improve upon.  

I agree it would be very useful

**Comment by asuweb** [comment]
We could do this by extending the _relay.php scripts that are already tailing the logs for relay information.

It might be possible to do it in perl, but I think it would require a change to the mailscanner code in order to get the `$rblspamheader` as this is not currently returned.

The info is printed to the maillog so I think _relay.php (or perhaps a separate script) to pull the details from the log.

Any thoughts?

**Comment by asuweb** [comment]
I'm working on this at the moment, hopefully be a PR coming soon

The caveat is it will require a minor modification to mailscanner message.pm

**Comment by mmgomess** [comment]
Thank you. I'm waiting.

**Comment by mmgomess** [comment]
Thank you. I'm waiting.


On Feb 3, 2017 14:39, "asuweb" <notifications@github.com> wrote:

I'm working on this at the moment, hopefully be a PR coming soon

The caveat is it will require a minor modification to mailscanner message.pm

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mailwatch/1.2.0/issues/431#issuecomment-277296749>, or mute
the thread

**Comment by endelwar** [comment]
> The caveat is it will require a minor modification to mailscanner message.pm

Propone this change to MailScanner with a PR!

**Comment by asuweb** [comment]
Yes, that's what I'm going to do :)

**Comment by asuweb** [comment]
@mmgomess - finally got round to doing it! #649

**Comment by mmgomess** [comment]
Thanks a lot.

**Comment by mmgomess** [comment]
Hi asuweb.

This change is already in RC5

Thank you.

2017-03-18 17:04 GMT-03:00 asuweb <notifications@github.com>:

**Comment by asuweb** [comment]
Hi @mmgomess,

It hasn't been merged with the development branch yet, and also you'll need to patch or update you mailscanner installation from the master branch in the mailscanner git.

**Comment by asuweb** [comment]
Or use the code that I reference here #649

**Comment by mmgomess** [comment]
OK, understood.

Thank you again.

2017-03-20 10:02 GMT-03:00 asuweb <notifications@github.com>:

**Comment by stefaweb** [comment]
What is happening if we use this code with an older version of MailScanner?

**Comment by asuweb** [comment]
You can backport the changes, there's only 3 lines of code required for Message.pm (1 of which is a comment).  But if the changes aren't made to Message.pm, then nothing will change.  Mailwatch will continue to function as it does now.

**Comment by asuweb** [comment]
The modification to Message.pm has been pulled into Mailscanner, so it'll be available in the next release (it's in the master branch now)

**Comment by stefaweb** [comment]
ok, thanks.

**Comment by mmgomess** [comment]
What is the modification in Message.pm?

2017-03-20 11:39 GMT-03:00 Stéphane <notifications@github.com>:

**Comment by asuweb** [comment]
https://github.com/asuweb/v5/commit/b9069a9f9124930c9cf2594824019c60fe56495a

**Comment by asuweb** [comment]
It's basically just 3 lines of code, you should be able to back port it to any version.  If you're unsure, if you send me a copy of you current Message.pm file, I'll make the changes and send you a new version

**Comment by stefaweb** [comment]
This can be closed.
