### ISSUE TITLE
TODO: remove colon99

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#432]
We should remove colon99. Old. Use some times in code only. Replace with sprinf() to put : directly in loc variable.

```
detail.php:            echo '  <td colspan="6"><input type="checkbox" name="alt_recpt_yn" value="y">&nbsp;' . __('altrecip04') . __('colon99') . '&nbsp;<input type="TEXT" name="alt_recpt" size="100"></td>' . "\n";
functions.php:                ) . __('colon99') . '</td><td align="center">' . $running . '</td><td align="right">' . $procs . '</td></tr>' . "\n";
lists.php:  <td class="heading">' . __('from07') . __('colon99') . '</td>
lists.php:  <td class="heading">' . __('to07') . __('colon99') . '</td>';
lists.php:  <td class="heading">' . __('list07') . __('colon99') . '</td>
lists.php:  <td class="heading">' . __('action07') . __('colon99') . '</td>
rpcserver.php:            return new xmlrpcresp(0, $xmlrpcerruser+1, "$quarantinedir/$file" . __('colon99') . ' ' . __('permdenied60'));
```

**Comment by Skywalker-11** [comment]
Why not directly add the colon to the end of  that variables?

**Comment by stefaweb** [comment]
Yes, for the ones in lists.php and detail.php.

For rpcserver.php, the colon need a space before in French typo.

English:
word: word

French:
word : word

'permdenied60' => ': permission denied.',
'permdenied60' => ' : permission refusée.',

For functions.php, we can create 

English:
'colon03' => ':',

French:
'colon03' => ' :',

**Comment by stefaweb** [comment]
Will do this when incoming big PR will be published.

**Comment by stefaweb** [comment]
TODO: remove colon99 in tools/Cron_jobs/quarantine_report.php

**Comment by stefaweb** [comment]
Some wrong colon stay but are in /lib.

**Comment by stefaweb** [comment]
Done.
