### ISSUE TITLE
Change Mysql Engine from MyISAM to InnoDB

### ISSUE THREAD

**Issue by Skywalker-11** [mailwatch/1.2.0#433]

**Comment by asuweb** [comment]
Is there any reason to define the storage engine?  Without defining it explicitly, it will default to whatever the default storage engine is set to in my.cnf or the default for the mysql / mariadb version.

**Comment by Skywalker-11** [comment]
Like @stefaweb mentioned in #332 there are issues depending on the storage engine that is used. When using InnoDB there are less chances that mailscanner get a timeout due to a locked table because it can do a row-level lock instead of the table-level lock used by MyISAM. See [https://dev.mysql.com/doc/refman/5.7/en/internal-locking.html](https://dev.mysql.com/doc/refman/5.7/en/internal-locking.html)

**Comment by stefaweb** [comment]
At minimum, we can remove MyISAM from the database creation script.
The default engine will be used instead (InnoDB is enabled by default in /etc/mysql/my.cnf).

**Comment by Skywalker-11** [comment]
Switching to InnoDB also would enable the use of larger usernames (currently limited to 191 chars due to primary key limiations of MyISAM with utf8mb4). When we use sysvar_innodb_large_prefix (default since MySql 5.7.7) up to 768 chars can be used as primary key. 

It was introduced in MySql 5.5 but before 5.7.6 it has to be manually enabled. 

[https://dev.mysql.com/doc/refman/5.7/en/innodb-parameters.html#sysvar_innodb_large_prefix](https://dev.mysql.com/doc/refman/5.7/en/innodb-parameters.html#sysvar_innodb_large_prefix)

**Comment by endelwar** [comment]
Upgrade to InnoDB has to make it into 1.2.0 release. Documentation needs to be clear about limit in username length depending on MySQL version in use.

**Comment by stefaweb** [comment]
For reference.

Converting Tables from MyISAM to InnoDB
https://mariadb.com/kb/en/mariadb/converting-tables-from-myisam-to-innodb/

**Comment by stefaweb** [comment]
Hello!

We need to work on this. How we do it?

I've read this on the MariadB doc:

```
INDEX issues

(Most of these Recommendations and some of these Facts have exceptions.)

Fact. Every InnoDB table has a PRIMARY KEY. If you do not provide one, then the first non-NULL UNIQUE key is used. If that can't be done, then a 6-byte, hidden, integer is provided.

Recommendation. Look for tables without a PRIMARY KEY. Explicitly specify a PRIMARY KEY, even if it's an artificial AUTO_INCREMENT. This is not an absolute requirement, but it is a stronger admonishment for InnoDB than for MyISAM. Some day you may need to walk through the table; without an explicit PK, you can't do it.
```

What do you think of this?

**Comment by endelwar** [comment]
I've just committed an updated create.sql schema in 15827c6dd3b7eb6242edbd8a2567b6c3721a3237

I'm open to comments (and PR on upgrade.php 😉 )

**Comment by stefaweb** [comment]
Why this is not in the maillog table definition ?

`ALTER TABLE `maillog` ADD FULLTEXT KEY `subject_idx` (`subject`);`

A lot to stuff to add in upgrade.php.

Do you have the command to move from myISAM to innoDB?

**Comment by stefaweb** [comment]
>Do you have the command to move from myISAM to innoDB?

for upgrade.php as well.

**Comment by endelwar** [comment]
> Do you have the command to move from myISAM to innoDB?

```sql
ALTER TABLE `tablename` ENGINE = INNODB;
```

**Comment by endelwar** [comment]
> Why this is not in the maillog table definition ?
> 
> ALTER TABLEmaillogADD FULLTEXT KEYsubject_idx(subject);

this one? https://github.com/mailwatch/1.2.0/blob/15827c6dd3b7eb6242edbd8a2567b6c3721a3237/create.sql#L308-L311

**Comment by stefaweb** [comment]
Yes

**Comment by stefaweb** [comment]
Changes in #471.

**Comment by stefaweb** [comment]
Done. We can close.
