### ISSUE TITLE
Wishlist: ask for a minimum PHP version when running MailWatch

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#434]
Minimum PHP 5.5.

**Comment by Skywalker-11** [comment]
I suggest PHP 5.4 so that debian wheezy which has lts till 2018 is still supported

**Comment by stefaweb** [comment]
Right PHP 5.4 is still supported for security update (backport of DSAs from PHP 5.6). But not patch to correct bugs.
https://wiki.debian.org/LTS

**Comment by Skywalker-11** [comment]
PHP 5.5 is also EOL. PHP 5.6 just gets actively developed till 19th january 2017 and gets security updates till end 2018. [http://php.net/supported-versions.php](http://php.net/supported-versions.php)

So we have to decide if we need the features of PHP5.5 or higher so we have to use that versions or support more systems

**Comment by endelwar** [comment]
MailWatch 1.2 must run on php 5.3 for retrocompatibility with lasts beta version. 2.0 will need 5.6 or even 7.0

**Comment by stefaweb** [comment]
Can we close?

**Comment by Skywalker-11** [comment]
It should at least be mentioned in the docs

**Comment by stefaweb** [comment]
Added to documentation.
I cloud it.
