### ISSUE TITLE
TODO: missing /n

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#437]
There:

`    <tr><td>Load Average:</td><td align="right" colspan="2"><table width="100%" class="mail" cellpadding="0" cellspacing="0"><tr><td align="center">0.06</td><td align="center">0.10</td><td align="center">0.08</td></tr></table></td>
`

**Comment by stefaweb** [comment]
Another one in report.php:

`</td><td style="white-space: nowrap; text-align:right;"><button type="submit" name="action" value="load">Load</button>&nbsp;<button type="submit" name="action" value="save">Save</button>&nbsp;<button type="submit" name="action" value="delete">Delete</button></td></tr>`

**Comment by stefaweb** [comment]
Another one in rep_message_listing.php:

`<span><b>1</b></span>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;<a href="/rep_message_listing.php?pageID=2" title="page 2">2</a>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;<a href="/rep_message_listing.php?pageID=3" title="page 3">3</a>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;<a href="/rep_message_listing.php?pageID=4" title="page 4">4</a>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;<a href="/rep_message_listing.php?pageID=5" title="page 5">5</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="/rep_message_listing.php?pageID=2" title="next page">&raquo;</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>`

**Comment by stefaweb** [comment]
And many in rep_message_ops.php.

**Comment by stefaweb** [comment]
An again one in rep_audit_log.php: 

```
<span><b>1</b></span>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;<a href="/rep_audit_log.php?pageID=2" title="page 2">2</a>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;<a href="/rep_audit_log.php?pageID=3" title="page 3">3</a>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;<a href="/rep_audit_log.php?pageID=4" title="page 4">4</a>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;<a href="/rep_audit_log.php?pageID=5" title="page 5">5</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="/rep_audit_log.php?pageID=2" title="next page">&raquo;</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="/rep_audit_log.php?pageID=34" title="last page">[34]</a></td>
                </tr>
          </table>
```

**Comment by Skywalker-11** [comment]
That comes from pear library pager
