### ISSUE TITLE
Upgrade of mysql tables fails

### ISSUE THREAD

**Issue by Skywalker-11** [mailwatch/1.2.0#439]
When the sql tables are upgrade in the upgrade.php first everything is converted to utf8mb4 and after that the table structure is changed. This results in a failure of the upgrade script ( see #428) because the primary keys are limited to 1000 bytes which results in a max length of combined primary fields of 191 when using utf8mb4.

So we should split the conversion to utf8 and utf8mb4 like this:

1. convert every table to utf8 (this should not fail cause the number of used bytes is not changed)
2. update the length of the columns in the tables so that the utf8mb4 values fit in 
3. convert the tables to utf8mb4

**Comment by stefaweb** [comment]
List of tables and fields with VARCHAR > 191.


```
ALTER TABLE `users` CHANGE `password` `password` VARCHAR( 191 ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `users` CHANGE `username` `username` VARCHAR( 191 ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `users` CHANGE `fullname` `fullname` VARCHAR( 191 ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE spamscores CHANGE user user VARCHAR( 191 ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE audit_log CHANGE user user VARCHAR( 191 ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE autorelease CHANGE msg_id msg_id VARCHAR( 191 ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE autorelease CHANGE uid uid VARCHAR( 191 ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE mcp_rules CHANGE rule_desc rule_desc VARCHAR( 191 ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE user_filters CHANGE username username VARCHAR( 191 ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
```

**Comment by stefaweb** [comment]
PR here: #440

**Comment by stefaweb** [comment]
Proposal PR in #441

**Comment by stefaweb** [comment]
Done
