### ISSUE TITLE
Unused code in SQLBlackWhiteList

### ISSUE THREAD

**Issue by Skywalker-11** [mailwatch/1.2.0#443]
I'm not sure but I think the following code from line 89-98 in [SQLBlackWhieList.pm](https://github.com/mailwatch/1.2.0/blob/master/MailScanner_perl_scripts/SQLBlackWhiteList.pm#L89) can savely be deleted. At least I couldn't find any reference to it. 

```
#
# Close down the SQL whitelist and blacklist
#
sub EndSQLWhitelist {
    MailScanner::Log::InfoLog("MailWatch: Closing down MailWatch SQL Whitelist");
}

sub EndSQLBlacklist {
    MailScanner::Log::InfoLog("MailWatch: Closing down MailWatch SQL Blacklist");
}
```

**Comment by stefaweb** [comment]
We can see this in /var/log/syslog when we stop MailScanner.

Seems to be just information messages.

**Comment by asuweb** [comment]
Interestingly, this doesn't appear in the logs on centos based servers

**Comment by Skywalker-11** [comment]
but where is it called from?

**Comment by asuweb** [comment]
I can't find any reference to it being called

**Comment by shawniverson** [comment]
Mailscanner calls that function.

**Comment by stefaweb** [comment]
May be there in usr/sbin/MailScanner

```
  # Close down all the user's custom functions
  MailScanner::Config::EndCustomFunctions();

```
