### ISSUE TITLE
Wrong refresh in geoip_update.php

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#444]
When we click on "Run now", the geoip script is run but the yellow menu disappear for one second just before the messages "Downloading file, please wait..." is printed.

![capture d ecran 2017-01-26 a 12 03 22](https://cloud.githubusercontent.com/assets/12907102/22329117/0eb252a6-e3c0-11e6-9d27-485d00f08c69.png)

**Comment by Skywalker-11** [comment]
It is expected because it reloads the page. If you click the button a POST form is send which triggers the update.

Not a bug

**Comment by stefaweb** [comment]
Can we load the files before?

**Comment by Skywalker-11** [comment]
We could use ajax to trigger the call and not reload the page but I don't see a reason why we should do that

**Comment by asuweb** [comment]
Can't see any need to mess with ajax - we don't use it anywhere else in this version.

**Comment by stefaweb** [comment]
In fact, these stuff will be better in a cron.

**Comment by asuweb** [comment]
Yes it would make more sense for it to be run via cron.  I can't see why anyone wouldn't want the functionality.

**Comment by stefaweb** [comment]
Michael built a new cron system in v2.
#370

**Comment by asuweb** [comment]
Good, then can can this be put in the V2.0 pile?

**Comment by stefaweb** [comment]
Stay like this.
