### ISSUE TITLE
PR stacking ;)

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#445]
![sc](https://cloud.githubusercontent.com/assets/12907102/22423260/12f17ae8-e6f1-11e6-824a-e7ac23316fae.png)

**Comment by Skywalker-11** [comment]
maybe some of us should start merging all the prs in his upstream so that in the end we only need to merge that single branch

**Comment by asuweb** [comment]
Might make it harder to decipher if we do that.

**Comment by Skywalker-11** [comment]
True but if we have many PRs there will be many merge problems.

**Comment by asuweb** [comment]
That's also true. 

Either way there are going to be plenty of conflicts - language files have been modified in at least 2 PR's, upgrade.conf in at 3.

We could possibly come up with an order for them to be merged in, and once created the pr can re sync and fix the conflicts.  

Don't know what would be the easiest way to do it whilst still keeping some logical sense to all the changed.

**Comment by stefaweb** [comment]
I don't want to be the one who will merge style.css. ;-)

**Comment by Skywalker-11** [comment]
Or the one who has to merge the changes from unifying the styles which would effect nearly all files that were modified. ;--)

**Comment by asuweb** [comment]
Yes, you'll note I haven't pushed that PR yet ;-)

I was planning to hang back on the style.css changes until the pending PR's have been merged, otherwise we'll end up in a never ending cycle of iterations.

**Comment by endelwar** [comment]
I'm back ;) going to work on free time on all issues opened last week, if my newborn will leave me some time :)

**Comment by stefaweb** [comment]
Hard work!

As I said.

With baby 1 + 1 not equal to 2
;-)
