### ISSUE TITLE
Release to alternate recipient missing 

### ISSUE THREAD

**Issue by shawniverson** [mailwatch/1.2.0#446]
https://github.com/E-F-A/v3/issues/351

Appears to be missing in devel branch.

**Comment by shawniverson** [comment]
Looks like a bug....preparing PR

**Comment by asuweb** [comment]
It's a bug - induced by the change to the logic with this `defined('DOMAINADMIN_CAN_RELEASE_DANGEROUS_CONTENTS')` line 470 details.php
