### ISSUE TITLE
Wishlist: geoIP and private address

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#449]
The curent mailwatch  code do not handle private address subnet.

We got as message in message detail: GeoIP lookup failed

May be, it will be better to print in case of private IP subnet: "Private IP address"

![capture d ecran 2017-01-28 a 10 20 30](https://cloud.githubusercontent.com/assets/12907102/22395611/86255b4c-e543-11e6-8602-b117420a198c.png)

**Comment by asuweb** [comment]
Fixed in #451

**Comment by stefaweb** [comment]
Tanks.

One more thing.

Why double(()) ?

`((GeoIP lookup failed))`

**Comment by asuweb** [comment]
> Why double(()) ?

I've fixed that as well

**Comment by stefaweb** [comment]
So fast!
I already had the code in stock?
;)

**Comment by stefaweb** [comment]
And for fd00::/8 ?
;-)

**Comment by asuweb** [comment]
> And for fd00::/8 ?

I was waiting for someone to ask that! I hate IPv6.  I'll switch to the Pear package and do it from there.

**Comment by stefaweb** [comment]
IPv6, me too !!!

**Comment by spec1re** [comment]
127.0.0.1/localhost ? ;)

![grafik](https://cloud.githubusercontent.com/assets/11883076/22405692/4d2988bc-e63e-11e6-9c89-3ce2454bc246.png)

**Comment by asuweb** [comment]
Yes, that as well.  Hopefully tomorrow :)

**Comment by endelwar** [comment]
I would suggest to use a library like [wikimedia/IPSet](https://github.com/wikimedia/IPSet) instead of (dying) pear packages and define arrays of private/local addresses:

```php
$privateAddresses = new IPSet( array(
    '10.0.0.0/8',
    '172.16.0.0/12',
    '192.168.0.0/16',
    'fd00::/8', // or fc00::/7
    //'fec0::/10' // what about rfc 1884 lovers?
) );

$localhostAddresses = new IPSet( array(
    '127.0.0.1',
    '::1'
) );
```

**Comment by Skywalker-11** [comment]
I go with @endelwar. That way we also have control over what version of the library we are using to minimize test risk of compatibility issues.

**Comment by asuweb** [comment]
I agree

**Comment by stefaweb** [comment]
Done
