### ISSUE TITLE
MailWatch.pm and utf8mb4 charset

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#455]
Found this.

`$dbh->do('SET NAMES utf8mb4');`

MailWatch.pm doesn't have this.

http://stackoverflow.com/questions/30290384/getting-length-of-utf8mb4-string-with-perl-from-mysql

```
use utf8;
use strict;
use warnings;

use DBI;
use open qw/ :std :encoding(utf-8) /;

STDOUT->autoflush;

my $VAR1 = "\327\251\327\234\327\225\327\235 \327\242\327\225\327\234\327\235";

my $dbh = DBI->connect(
    qw/ DBI:mysql:database=temp admin admin /, {
        RaiseError => 1,
        PrintError => 0,
        mysql_enable_utf8 => 1,
    }
) or die DBI::errstr;

$dbh->do('SET NAMES utf8mb4');

$dbh->do('DROP TABLE IF EXISTS temp');
$dbh->do('CREATE TABLE temp (value VARCHAR(64) CHARACTER SET utf8mb4)');

my $insert = $dbh->prepare('INSERT INTO temp (value) VALUES (?)');
$insert->execute('שלום עולם');
$insert->execute($VAR1);

my $values = $dbh->selectcol_arrayref('SELECT value FROM temp');
printf "string: %s  foo: %d\n", $_, foo($_) for @$values;

sub foo2 {
  $_[0] =~ tr/ //c;
}

sub foo {
  length join '', split / /, $_[0];
}
```

**Comment by stefaweb** [comment]
In fact, we need to do in all *.pm files of MailWatch.

Check MySQL version -> $dbh->{mysql_serverversion}

if >= 5.3.3 select utf8mb4 during connect()

mysql_enable_utf8mb4 => 1

else

mysql_enable_utf8 => 1

No need to use SET BAME utf8 or utf8mb4 if we follow the doc.

```
If used as a part of the call to connect() then it issues the command SET NAMES utf8.

Additionally if used as a part of the call to connect() then it issues the command SET NAMES utf8mb4 instead of utf8.
```

**Comment by stefaweb** [comment]
Look in #425.

**Comment by stefaweb** [comment]
I've modified the *.pm files in #425 but problem with data stored in database.

![capture d ecran 2017-01-30 a 11 25 56](https://cloud.githubusercontent.com/assets/12907102/22419699/030f4ff4-e6df-11e6-8bc1-ba7ae6cb2f7e.png)

If someone understand where is my error?

**Comment by stefaweb** [comment]
Solved. Added SET NAME.

**Comment by Skywalker-11** [comment]
do you want to close this if it is solved?

**Comment by stefaweb** [comment]
Done.
