### ISSUE TITLE
Undefined index in mailq.php on line 266

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#459]
Hello!

If we have a wrong  char coded record in the maillog table, mailq.php complaint with a notice. As mailq.php run every minute, I receive a mail each minute.

`Jan 29 11:03:01 xxxx php: PHP Notice: Undefined index: subject in /usr/local/bin/mailq.php on line 266
`
![adb9b448-e794-11e6-93c9-b5e7583f4a34](https://cloud.githubusercontent.com/assets/12907102/22458368/7cd1ec08-e79c-11e6-8c1f-aefe4ac0568e.png)

If we can manage this case?

**Comment by Skywalker-11** [comment]
do you know where exactly in the code the notice is produced? What is at line 266?

**Comment by stefaweb** [comment]
in mails.php

`                    safe_value($msginfo['subject']) . "','" .`

```
    ('" . safe_value($msgid) . "','" .
                    safe_value($msginfo['cdate']) . "','" .
                    safe_value($msginfo['ctime']) . "','" .
                    safe_value($msginfo['sender']) . "','" .
                    safe_value(@implode(',', $msginfo['rcpts'])) . "','" .
                    safe_value($msginfo['subject']) . "','" .
                    safe_value($msginfo['message']) . "','" .
                    safe_value($msginfo['size']) . "','" .
                    safe_value($msginfo['priority']) . "','" .
                    safe_value($msginfo['attempts']) . "','" .
                    safe_value($msginfo['lastattempttime']) . "','" .
                    safe_value($sys_hostname) . "')";
                dbquery($sql);
            }
        }
    }
```

**Comment by stefaweb** [comment]
Can someone look at this?
Very boring if something goes wrong with data storage.

**Comment by asuweb** [comment]
Which version of mailq.php?

**Comment by stefaweb** [comment]
The version in develop.

tools/Sendmail_queue/mailq.php

**Comment by asuweb** [comment]
Ahh, I was confused, as there are 2 files called mailq.php

One in mailscanner/mailq.php
The other in tools/Sendmail_queue/mailq.php

I'm assuming you use sendmail in your setup?  I'll have to configure one of the dev servers to use sendmail before I can look at that

**Comment by stefaweb** [comment]
I'm confused me too now.

The one, I use is the one which read MTA log and store then in maillog table. For me, this is the one in tools/Sendmail_queue/mailq.php.

What is the use of the one in mailscanner/mailq.php?

I'll ask @endelwar to rename the file.
tools/MailWatch_queue/mailwatch_mailq.php.

**Comment by asuweb** [comment]
The mailq.php in the mailscanner directory displays what's in the inq / outq in the database if you use sendmail - I use postfix so I get the posftixmailq.php instead.

**Comment by Skywalker-11** [comment]
can you provide mails that produces that error?

**Comment by stefaweb** [comment]
If I remember.

Write an email with this in the Subject:

`=?utf-8?Q?=F0=9F=92=98=C2=A0Single=20or=20Taken=2C=20we=27re=20got=20you=20covered=20this=20V=2DDAY?=`

What you want in the body.

Pass subject column in maillog table to utf8.

Switch MailWatch.pm to utf8mb4 only.

Sent the mail.

You will store "garbage" data utf8mb4 coded in the subject utf8 coded column.

When mailq.php, read it. Boom!

**Comment by Skywalker-11** [comment]
Is it correctly shown in the message listing at status.php? If not: does the problem still exists when using #425 and sql form #471?

When using postfix its working when #425 is used for pm files and database format is from #471

**Comment by stefaweb** [comment]
Was not correctly show in my remember. But not sure at 100%. I encounter this when we was talking and testing the problem of charset in the long #430 post.

Works fine with #425 and #471 as well.

I'd look on Google. It seems that php get a notice undefined index comes when we have a problem of charset somewhere. If I'm right, with the 2 PRs, this problem should not arrive in the "real life".

**Comment by stefaweb** [comment]
Closing this one as this error should not show in "real life".
