### ISSUE TITLE
maillog table

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#460]
Can we modify mailing table?

phpMyAdmin complaint if we want to edit a record.

`Current selection does not contain a unique column. Grid edit, checkbox, Edit, Copy and Delete features are not available.`

**Comment by Skywalker-11** [comment]
If it is save to assume that the ids are unique than we can use that. Else we could use a combination of id and timestamp as primary/unique key

**Comment by endelwar** [comment]
MTA id are not unique (postfix implemented the long id to bypass this problem): a combination of

- id
- hostname
- date
- time

should be enough to sure of uniqueness

**Comment by Skywalker-11** [comment]
I think we can't use hostname because of the restriction of key lengths

**Comment by endelwar** [comment]
yeah @Skywalker-11 you're right: the only solution is to add a new id column (`maillog_id`?):
```sql
ALTER TABLE `maillog` ADD `maillog_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT FIRST, ADD PRIMARY KEY (`maillog_id`);
```

**Comment by endelwar** [comment]
18446744073709551615 rows should be enough (ahahah! Bill Gates docet)

also `SERIAL` column type should be considerate (backward compatibility with old MySQL versions)

**Comment by stefaweb** [comment]
`ALTER TABLE `maillog` ADD `maillog_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT FIRST, ADD PRIMARY KEY (`maillog_id`);`

Can I add this to upgrade.php ?

**Comment by stefaweb** [comment]
Sorry, could you check this:

```
    // Add new field to maillog table
    echo pad(' - Add maillog_id field to `maillog` table');
    $sql = "IF NOT EXISTS( (SELECT * FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE()
               AND COLUMN_NAME='maillog_id' AND TABLE_NAME='maillog') ) THEN
               ALTER TABLE `maillog` ADD `maillog_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT FIRST, ADD PRIMARY KEY (`maillog_id`);
            END IF;";
    executeQuery($sql);
```

**Comment by stefaweb** [comment]
This is may be better.

```
    // Add new field to maillog table
    $sql = "SELECT * FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND COLUMN_NAME = 'maillog_id' AND TABLE_NAME = 'maillog'"
    executeQuery($sql);
    if (false === $sql) {
        echo " ALREADY DONE\n";
    } else {    
    echo pad(' - Add maillog_id field to `maillog` table');
	    $sql = "ALTER TABLE `maillog` ADD `maillog_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT FIRST, ADD PRIMARY KEY (`maillog_id`)";
	    executeQuery($sql);
    }
```

**Comment by stefaweb** [comment]
Go back later.

**Comment by stefaweb** [comment]
Added maillog_id in #441.

**Comment by stefaweb** [comment]
Done
