### ISSUE TITLE
PHP Preg error in functions.php - MailWatch can't find the virus scanner in MailScanner configuration when set to auto

### ISSUE THREAD

**Issue by GoranLundberg** [mailwatch/1.2.0#463]
The following errors appear in /var/log/apache2/error.log every time MailWatch is loaded.

```
[Tue Jan 31 19:54:43.336264 2017] [:error] [pid 12503] [client 192.168.1.1:49302] PHP Notice:  Use of undefined constant VIRUS_REGEX - assumed 'VIRUS_REGEX' in /var/www/mailscanner/functions.php on line 1112
[Tue Jan 31 19:54:43.336554 2017] [:error] [pid 12503] [client 192.168.1.1:49302] PHP Warning:  preg_match(): Delimiter must not be alphanumeric or backslash in /var/www/mailscanner/functions.php on line 1112
```
And nothing is showing up under "Recent Messages" in the MailWatch interface.

**Edit:** Had a faulty solution to the problem that i removed.

**Solution:**
The problem is that MailWatch does not parse the configuration item `Virus Scanners` correctly in the MailScanner configuration file when set to `auto`. On Debian it's located in `/etc/MailScanner/conf.d/yourlocal.conf` (Replace yourlocal with the name of your custom configuration file)

I changed `Virus Scanners = auto` to `Virus Scanners = clamd`
and now it seems to be working fine.

This problem should be fixed and handled correctly in MailWatch.
Hope someone can make a fix so that no one else has to debug it.
Took several hours searching the web trying to fix this.

Thanks @DiederikvandenB for mentioning the solution!

**Comment by Skywalker-11** [comment]
What MailWatch and anti virus module are you using?

Normally the constant VIRUS_REGEX should be defined as soon as the functions.php is loaded (line 120-178). The only case in which the constant is not set (that's what the PHP Notice says) is when you are using an unsupported anti virus.

**Comment by DiederikvandenB** [comment]
I am experiencing the exact same issue. Possibly interesting to note that I am running PHP7.0, not 100% sure whether that's an influencing factor here but I thought it was worth noting. Furthermore I am running the master version of MW and ClamAV as anti-virus.

**Comment by DiederikvandenB** [comment]
I seemed to have fixed the issue myself already. I had the `Virus Scanner` setting in MailScanner set to `auto`. This is not recognised by MailWatch, causing the error. Changing this setting to `clamd`fixed the issue, however I feel like MW should handle this setting appropriately (no offense to the developers obviously, thank you for making the software ;) )

**Comment by GoranLundberg** [comment]
Thanks @DiederikvandenB that solved it for me aswell. Disregard my previous "solution". in functions.php

**Comment by endelwar** [comment]
This is the [first entry in the FAQ section](http://docs.mailwatch.org/using/faq.html#how-to-resolve-primary-virus-scanner-auto-error) of MailWatch documentation.

@DiederikvandenB MailWatch can't automatically guess your installed antivirus like MailScanner does because MailWatch doesn't scan your system, but simple read MailScanner.conf file if available (MailWatch can reside on a separate machine from MailScanner)

**Comment by asuweb** [comment]
@endelwar - perhaps this can be included in upgrade.php in the "Check MailScanner settings"

**Comment by endelwar** [comment]
@asuweb good idea!

**Comment by asuweb** [comment]
It happens occasionally ;-)

**Comment by asuweb** [comment]
@stefaweb - can you include this in #471

**Comment by GoranLundberg** [comment]
@endelwar Didn't find the FAQ while searching the web. It should be updated to include the actual error messages in the log so that it can be easily found while searching the web. Also the error messages doesn't really say that it is actually not finding the virus scanner as in the FAQ.

Would be easy to add an error check in functions.php if Virus Scanner = auto. And then log the problem syslog and how to solve it.

**Comment by asuweb** [comment]
@GoranLundberg - we'll add it to the checks in upgrade.php

**Comment by GoranLundberg** [comment]
Great! :D

**Comment by asuweb** [comment]
@endelwar - can you re-open this.  There is in fact a bug in this somewhere (I've yet to locate it), but if you happen to use "esets" as the first virus scanner in the list, it also produces the same issue.

**Comment by DiederikvandenB** [comment]
@endelwar Wow, I feel kind of silly for not seeing that in the FAQ. In that case I haven't said anything ;).
