### ISSUE TITLE
Do we still need UTF8_Database in tools?

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#465]
With the new version of upgrade.php, do we still need UTF8_Database directory and associated files in tools?

https://github.com/mailwatch/1.2.0/tree/develop/tools/UTF8_Database

We can may be remove them.

**Comment by Skywalker-11** [comment]
it is also incorrect with the 250chars

**Comment by endelwar** [comment]
with updated upgrade.php and the yet-to-be-written install.php this files are useless

**Comment by stefaweb** [comment]
Done in #467.
