### ISSUE TITLE
Bug in user_manager.php?action=edit

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#469]
Seems the username is replicated in Go to message:

To check as I'm not using the last code in my dev server.

![capture d ecran 2017-02-03 a 10 16 41](https://cloud.githubusercontent.com/assets/12907102/22585954/a530835c-e9fa-11e6-97e9-d222be5ec646.png)

**Comment by Skywalker-11** [comment]
it is fixed in pr #418

**Comment by stefaweb** [comment]
ok, thanks.
