### ISSUE TITLE
Broken graphes with too many recipients

### ISSUE THREAD

**Issue by Skywalker-11** [mailwatch/1.2.0#476]
When mails with many recipients (4+) or very long mail addresses are in the statistic of the top recipients/senders this breaks the legend of the table. The color of the fields shown in the lengend are outside of the graphic and mail adresses overlapping large parts of the diagram

**Comment by stefaweb** [comment]
See also #283.

If you"re brave. ;)

https://www.amcharts.com/javascript-charts/

**Comment by stefaweb** [comment]
Can be closed.
