### ISSUE TITLE
What the use of files in tools/Sendmail_relay?

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#478]
We found this in tools/Sendmail_relay:

- an init.d file: sendmail_relay.init
- an php script: sendmail_relay.php

Are these files still used?

Seems to be old files needed if we use the old MTA "sendmail".

If we still need them, the init script need to be updated to be working with modern Linux OS (and systemd).

Or we can delete them.

**Comment by endelwar** [comment]
I hear some Sendmail Gods throwing lightning bolts down to Earth 😃 

Sendmail is rock solid, still developed and maintained, also supported by MailScanner (it's the default choice on install): I've never messed up with it, I'm more a Postfix guy, but need to and will be supported.

The init script needs to be maintained and, if not working right, fixed.

I'm leaving systemd implementation to the reader, I'm not going to dirty my hand with that 💩

**Comment by stefaweb** [comment]
In fact, I already updated the init script in 2015.

I close.
