### ISSUE TITLE
TODO and BUG: in rep_audit_log.php (datetime-local doesn't work with Safari and Firefox)

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#479]
- remove the mailscanner logo
- move the button "apply" below
- add colon

![capture d ecran 2017-02-05 a 09 38 51](https://cloud.githubusercontent.com/assets/12907102/22624823/50966436-eb87-11e6-8e94-840f0a703fbf.png)

**Comment by stefaweb** [comment]
And:

- date doesn't work?
- add a line after "No row retrieved!"

![capture d ecran 2017-02-05 a 09 44 43](https://cloud.githubusercontent.com/assets/12907102/22624849/0a456102-eb88-11e6-902b-b96c6426d77e.png)

**Comment by asuweb** [comment]
Does the date not need to be in the form - yyyy-mm-dd (the same as in reports?)

**Comment by stefaweb** [comment]
Also tried 20/12/16. Doesn't work.
Start date doesn't work too.

**Comment by asuweb** [comment]
Is that a new version of rep_audit_log?

**Comment by stefaweb** [comment]
version in develop

**Comment by stefaweb** [comment]
What is the use of Action" field?

User and IP fields works.

**Comment by asuweb** [comment]
@stefaweb - your version is different from mine

![image](https://cloud.githubusercontent.com/assets/13250955/22627949/70c8a8ea-ebc3-11e6-9ebd-d85a180203a8.png)
![image](https://cloud.githubusercontent.com/assets/13250955/22627952/7377a780-ebc3-11e6-89e8-151e48e6ee84.png)

**Comment by stefaweb** [comment]
???

I uploaded the last develop version!
I will try again.

**Comment by stefaweb** [comment]
Found.

Not compatible with Safari and Firefox for Macintosh.
Works with Chrome on Macintosh.
Works on Windows.

**Comment by stefaweb** [comment]
Button "apply" can be stay at the same place. Just try to center it if this look better.

**Comment by stefaweb** [comment]
Problem with "datetime-local" in some browser. These command is not compatible with Safari, Firefox and others.

`Note: <input> elements with type="datetime-local" do not show as any datetime field/calendar in Firefox or in IE12 and earlier versions.`

http://www.w3schools.com/jsref/dom_obj_datetime-local.asp

http://caniuse.com/input-datetime/embed/

Try to implement a version compatible with all browsers.

**Comment by asuweb** [comment]
Do we need fancy html5 elements in v1.20?  

We don't use them in reports which presumably are used far more often than audit reports.

**Comment by stefaweb** [comment]
Or at minimum explain how to type the date if not working.

Not found a replacement for "datetime-local" without using jscript.

**Comment by stefaweb** [comment]
colon added in #497

**Comment by asuweb** [comment]
Has this been fixed yet?

**Comment by stefaweb** [comment]
No.
I fixed only the colon in lang files.

**Comment by asuweb** [comment]
@stefaweb - no problem.  I think for compatibility, it's best if we don't use the HTML5 date elements - we can address it in V2.0 with JS

I'll sort it
