### ISSUE TITLE
BUG in reports.php (double list of reports when changing language)

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#480]
When we change of language, we got the report list in double. One set per language.

We have to quit the browser and launch it again to go back to the normal.

![capture d ecran 2017-02-05 a 09 56 07](https://cloud.githubusercontent.com/assets/12907102/22624921/879eef82-eb89-11e6-9a35-5f3e3c7dd968.png)

**Comment by Skywalker-11** [comment]
problem is with the filter->AddReport we map the translated text to the url. When we change the language the mapping of the old language to the urls still exists.

Not sure why we even use the filter here

**Comment by stefaweb** [comment]
Done.
