### ISSUE TITLE
Looking for translator!

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#488]
You are a native speakers of one of these languages, we need help translating MailWatch.

Spanish
Dutch
Italian
Portuguese

https://github.com/mailwatch/1.2.0/tree/develop/mailscanner/languages

**Comment by asuweb** [comment]
You're probably better sending this request to the mailing list - I doubt the vast majority of users will check github that often.

**Comment by remkolodder** [comment]
I'll look into the dutch translation.
