### ISSUE TITLE
Localization in postfixmailq.php and mailq.php (in mailscanner)

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#498]
I've found this in the files. I can't see the message printed somewhere in the GUI.

Where are these message used and do I need to localize them?

postfixmailq.php

`echo '<b>Combined mail queue (Inbound and Outbound)</b>' . "\n";
`

mailq.php

```
switch ($_GET['queue']) {
    case 'inq':
        $queue = 'inq';
        $display = 'Inbound Mail Queue';
        break;
    case 'outq':
        $queue = 'outq';
        $display = 'Outbound Mail Queue';
        break;
    default:
        die(__('diemq24') . "\n");
}

```

**Comment by asuweb** [comment]
postfixmailq.php is use for postfix instead of the database for queue monitoring. 

That should be localised.  

mailq.php is used for sendmail / exim and is displayed when you click the Inbound / Outbound mailqueue link.

**Comment by stefaweb** [comment]
Hello @asuweb!

I know that but I can't see "Combined mail queue (Inbound and Outbound)" or others printed somewhere in the screen in GUI.

Will do the localization.

**Comment by asuweb** [comment]
![image](https://cloud.githubusercontent.com/assets/13250955/22727780/a8500a68-edd2-11e6-8049-510e6555d679.png)

**Comment by stefaweb** [comment]
ok. 

Not see it for mail.php with Exim.

Where did you click to have the message from the screen shot?

**Comment by asuweb** [comment]
On either the "Inbound" or "Outbound" queue under "Mail Queues"

**Comment by stefaweb** [comment]
ok.

Very different with Exim.

Done in #499.

**Comment by stefaweb** [comment]
Exim version.

![capture d ecran 2017-02-08 a 09 22 21](https://cloud.githubusercontent.com/assets/12907102/22728843/58b60206-ede0-11e6-9b59-6befda6f7113.png)

**Comment by stefaweb** [comment]
Done.
