### ISSUE TITLE
Very nice bug

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#506]
If you have MailScanner personal config in `/etc/MailScanner/conf.d/myconf.conf`

If you do `vi /etc/MailScanner/conf.d/myconf.conf`

You got:

![capture d ecran 2017-02-08 a 22 29 08](https://cloud.githubusercontent.com/assets/12907102/22758264/3e8abaca-ee4e-11e6-9752-c07e7b7e16a8.png)

If you quit vi, all return to the normal.

If you vi /etc/MailScanner/MailScanner.conf, no problem...

😎

**Comment by asuweb** [comment]
I'm assuming it's not limited to just "vi" and any editor will have the same effect?

**Comment by stefaweb** [comment]
Do it with vi and vim, not nano. Not tried emacs.

It's not really important as "bug" but fun!

**Comment by stefaweb** [comment]
Close this one.
