### ISSUE TITLE
Learn as spam & report clean messages

### ISSUE THREAD

**Issue by DiederikvandenB** [mailwatch/1.2.0#515]
Hi!

My mailserver occasionally lets through some false negatives, i.e. messages that are actually spam but not marked as such. I want to be able to feed these to my bayes database and also report them as spam.

For spam messages I get the useful "actions" part at the details page, but this does not show for clean messages. As a result, I end up manually searching for the email through terminal and then calling the `sa-learn` command myself. Is there an easier way to do this?

**Comment by asuweb** [comment]
The only way to do it through mailwatch would be to also store clean messages, that way you can use sa-learn through MailWatch.

**Comment by DiederikvandenB** [comment]
That seems rather inefficient, am I right? What about this: is it possible that MailWatch tracks where the message gets stored after it's processed by MailScanner and delivered by Postfix. Because if that's possible, then one could potentially just run `sa-learn` on that path through MailWatch.

I would be happy to write the necessary code for this as I have plenty of experience with PHP. I just need some pointers to start ;).

**Comment by asuweb** [comment]
That approach would only work if mailwatch resides on the same server as the mailbox, with the additional implication that all mailboxes would have to be readable by the web-server, which would be undesirable.

One thing on my long list of todo's - although probably not until v2.0, would be to provide an upload facility where users can upload files for spam training - this is what some commercial filtering systems do, as the same limitation applies unless the clean messages are stored by the filtering gateway.

**Comment by stefaweb** [comment]
I've this working.

One server with pop/imap and spamassassin bayes using db connected to the bayes db on the mailscanner server (for me on another relay server). On the pop/imap server, Spamassassin is only used for bayes learning.

Each mail user have a "junk mail folder" called .Junk.

On the pop server a cron run each night:

```
/usr/bin/sa-learn --no-sync --spam /var/mail/*/*/.Junk/cur/
/usr/bin/find /var/mail/*/*/.Junk/cur/ -mtime +15 -type f -exec rm -f {} \;
```

This setup is for Courier but can work with other software.

Only work if people use imap and store junk email in the .Junk folder.

**Comment by asuweb** [comment]
That's a possible solution, but again it's use case specific, there's no one solution fits all.  Good way of doing it if you manage all of the end-users mailboxes.

**Comment by endelwar** [comment]
MailWatch can take sa-learn action only on MailScanner archived email.
If you don't want to store clean messages on your server you should take another route to achieve this result, like piping all email sent to a specific address (like `sendmespam@example.com`) to sa-learn command (look at this thread for postfix http://www.archivum.info/postfix-users@postfix.org/2005-07/00857/Re-Problems-with-piping-all-mail-to-sa-learn.html)

**Comment by DiederikvandenB** [comment]
Thanks for your responses. I've currently set up something very similar to what @stefaweb is proposing. Just not every client is doing this yet though, although I feel like it's more their own problem then.
