### ISSUE TITLE
Documentation for Domain Admins

### ISSUE THREAD

**Issue by asuweb** [mailwatch/1.2.0#525]
The new domain administration features where domain admins can add users needs documenting prior to release.

It introduces a security issue when existing domain admins are in the format `domain.tld`. They can then see other domain admins user details, and can change other domain admins passwords.  This is due to the change in methodology with the introduction of the new features.

The new features are very welcome, but it does alter the way some people might assign accounts and needs to be understood before upgrading.

**Comment by stefaweb** [comment]
Greueee, all my setup are like` domain.tld`.

I've not understood how to do with the new feature?

We should replace `domain.tld` by what?

**Comment by asuweb** [comment]
You should replace domain.tld by `something@domain.tld`. The `something` doesn't actually matter, but it's probably better if it's not the name on an active mailbox. 

I use `domain-admin@domain.tld` for domain admins (as of 5 minutes ago - having just discovered this issue)

**Comment by stefaweb** [comment]
It's to final release right now. We have time to solve and find a less complex solution to go around this.

**Comment by stefaweb** [comment]
Back on this.

> but it's **probably better if it's not the name on an active mailbox**.
> I use domain-admin@domain.tld for domain admins (as of 5 minutes ago - having just discovered this issue)

If the mailbox domain-admin@domain.tld doesn't exist, how works the "password reset" feature for domain admin?

**Comment by asuweb** [comment]
> If the mailbox domain-admin@domain.tld doesn't exist, how works the "password reset" feature for domain admin?

It doesn't, as I took the decision not to allow domain admins to reset their password using the reset feature for security.  

Password resets for domain admins can be enabled easily enough though - in which case you would need to use an active mailbox.

By "active" mailbox, why I actually meant was not one which is actually used to receive regular mail. For example, admin@domain may be a bad choice, as it's possible admin@ is in use actively by the admin department for example.

**Comment by endelwar** [comment]
This issue was moved to mailwatch/mailwatch-docs#20
