### ISSUE TITLE
Wishlist: better print of error message in user_manager.php

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#528]
When we have a mismatch password, the error message "Password mismatch" is printed at the top. No very visible.

It will better to have it printed (in red) at the place of the red cross in the screen shot.

![sc](https://cloud.githubusercontent.com/assets/12907102/22929654/0b30cd86-f2bd-11e6-8d79-94f7ef23e0a5.png)

**Comment by asuweb** [comment]
@stefaweb - it's not exactly displayed how you wished, but it's pretty clearly displayed now.

**Comment by stefaweb** [comment]
No problem. Do you have a screen shot?

**Comment by asuweb** [comment]
![image](https://cloud.githubusercontent.com/assets/13250955/23165046/1a757916-f832-11e6-91d8-098841ad8e8f.png)

![image](https://cloud.githubusercontent.com/assets/13250955/23165053/1d6b051e-f832-11e6-9671-881301d05b5a.png)

**Comment by stefaweb** [comment]
Fine. No need to have glasses!  😀

**Comment by stefaweb** [comment]
Done.
