### ISSUE TITLE
Wishlist: graph in reports not aligned

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#530]
Graph (or table) not aligned and Title font too small (or too light)

![sc](https://cloud.githubusercontent.com/assets/12907102/22934566/b222e4d2-f2cf-11e6-8ce5-3552e2947f62.jpg)

**Comment by Skywalker-11** [comment]
The graphic is centered but the graph inside the graphic is not centered...
It's a problem this the graphic generation can be fixed when using #477

**Comment by stefaweb** [comment]
Done in #531.
