### ISSUE TITLE
Not localized in user_manager.php

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#532]
What is this line?

`echo '<h1 style="text-align: center; color: green;">Update Completed</h1>';`

**Comment by Skywalker-11** [comment]
It shows normal users that the changed settings were saved. Probably should be `Settings saved` or so.
de would be: `Einstellungen gespeichert`

**Comment by stefaweb** [comment]
When I click on "Update", nothing printed. I go back directly to the user list.

I'm doing the localization.

**Comment by stefaweb** [comment]
Done in #522.

**Comment by Skywalker-11** [comment]
![image](https://cloud.githubusercontent.com/assets/11180862/22985462/cad14ff8-f3a8-11e6-9663-ebd4f200434e.png)

**Comment by stefaweb** [comment]
I was connected as admin... ;)

**Comment by stefaweb** [comment]
Done in #522.
