### ISSUE TITLE
BUG: we can create an "empty" user in user_manager.php

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#533]
If we leave Username empty, we can create an user.

![capture d ecran 2017-02-15 a 15 05 55](https://cloud.githubusercontent.com/assets/12907102/22977773/5ef297a0-f390-11e6-8aad-ab4f8b5d237b.png)

We need a "red" error message at the left of Username field. To do with #528.

**Comment by asuweb** [comment]
Working on this and #528

**Comment by Skywalker-11** [comment]
We shouldn't just rely on the testing in the browser but also test the fields on the server side

**Comment by stefaweb** [comment]
Done.
