### ISSUE TITLE
mailwatch_postfix_relay.php - bug

### ISSUE THREAD

**Issue by asuweb** [mailwatch/1.2.0#534]
mailwatch_postix_relay.php no longer logs to the database.

From a review of the code it appears that the function ` extractKeyValuePairs($match)` is not called - at least I can't find reference to it. 

@Skywalker-11 - I think you re-wrote this?  Any ideas?

**Comment by stefaweb** [comment]
Nothing is missing.

From RC4.

```
mailscanner/mtalogprocessor.inc.php:    abstract public function extractKeyValuePairs($match);
mailscanner/mtalogprocessor.inc.php:                $this->entries = $this->extractKeyValuePairs($match);
mailscanner/postfix_relay.php:    public function extractKeyValuePairs($match)
tools/Sendmail_relay/sendmail_relay.php:    public function extractKeyValuePairs($match)
```

From DEV:

ailscanner/mtalogprocessor.inc.php:    abstract public function extractKeyValuePairs($match);
mailscanner/mtalogprocessor.inc.php:                $this->entries = $this->extractKeyValuePairs($match);
tools/Sendmail_relay/mailwatch_sendmail_relay.php:    public function extractKeyValuePairs($match)
tools/Postfix_relay/mailwatch_postfix_relay.php:    public function extractKeyValuePairs($match)

Have you look if this something related to the move of the file from /mailscanner to /usr/local/bin.

**Comment by asuweb** [comment]
Yes, the bit I can't find is the call to the `parse()` function within mtalogprocessor.inc.php`

**Comment by asuweb** [comment]
Fixed in PR #535

**Comment by Skywalker-11** [comment]
The extractKeyValuePairs is called by the super class [mtalogprocessor.inc.php](https://github.com/mailwatch/1.2.0/blob/develop/mailscanner/mtalogprocessor.inc.php#L178)

**Comment by stefaweb** [comment]
Hello!
Just to understand. Why do we have the same function in 3 different files and not used in 2?

**Comment by asuweb** [comment]
@Skywalker-11 - thanks, I found it.  

The issue was we were not explicitly stating the fields to be updated in the SQL statement, and a possible schema change may have stopped the query running due to column mis-match.  Took a while to debug as the `dbquery()` doesn't throw an error.

**Comment by asuweb** [comment]
@stefaweb - the joy of object orientated programming.  

`public function extractKeyValuePairs($match)` these define the specific function for each of the MTA's, the

`abstract public function extractKeyValuePairs($match);` this simply says that an object of this will have an extractKeyValuePairs() function - basically.

**Comment by asuweb** [comment]
It seems that when using the tail function for `mailwatch_*_relay.php` that the db connection fails after a while.  

I've found that removing the `dbclose()` function call in `mtalogprocessor.inc.php` solves this issue.  

Anyone got any ideas as to why that would be causing issue?

**Comment by stefaweb** [comment]
What's that in mtalogprocessor.inc.php?

```
        global $fp;//@todo do we need this?
        if (!$fp = popen($input, 'r')) {
            die(__('diepipe56'));
        }

```

**Comment by Skywalker-11** [comment]
Not shure its a left over fron postfix_relax and sendmail_relay.

**Comment by stefaweb** [comment]
What is the statut of this one?

**Comment by Skywalker-11** [comment]
it tests if it can read the output of `cat` or `tail` or whatever command is used to get that logs

**Comment by Skywalker-11** [comment]
so it should stay like this and issue can be closed

**Comment by asuweb** [comment]
> I've found that removing the dbclose() function call in mtalogprocessor.inc.php solves this issue.

Anyone got any ideas as to why that would be causing issue?

**Comment by stefaweb** [comment]
A story of OS "locked file"?

**Comment by Skywalker-11** [comment]
Found the problem. The close() function in database.php closes the connection but leaves the variable untouched and so the check ` if (!self::$link) { ` in connect() function probably is still true. 
So it assumes there is still a db connection and which is not the case.

I'll create a pr

**Comment by asuweb** [comment]
Thanks @Skywalker-11

**Comment by Skywalker-11** [comment]
@asuweb can you try that?

**Comment by asuweb** [comment]
Yes, I'll try it now

**Comment by asuweb** [comment]
Notice: Undefined variable: true in /var/www/html/mailscanner/database.php on line 65

**Comment by Skywalker-11** [comment]
typo fixed in pr
