### ISSUE TITLE
What is this?   width="100%%"

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#537]
In /usr/local/bin/mailwatch_quarantine_report.php

```
<table width="100%%" border="0">
$html_table = '<table width="100%%" border="0">
```

I thought that it was a typo and removed the second %, and I got:

PHP Warning:  sprintf(): Too few arguments in /usr/local/bin/mailwatch_quarantine_report.php on line 468

**Comment by Skywalker-11** [comment]
% is reserved for formatting in sprintf. See here (http://php.net/manual/en/function.sprintf.php)[http://php.net/manual/de/function.sprintf.php]

**Comment by stefaweb** [comment]
Hard core!
Thanks. I close.
