### ISSUE TITLE
undefined index: filter in lists.php line 110 when using filters on users on the BW Lists page.

### ISSUE THREAD

**Issue by remkolodder** [mailwatch/1.2.0#542]
I have users that have multiple aliases. When linking these aliases with the main account and surfing to the BW Lists page, you'll get the notice that there is an undefined index: filter in /path/to/lists.php on line 110.

This seems to happen for every aliased user, so having 4 aliases, like I have, will show the notice 4 times below eachother. It does not matter whether or not these aliases have black and whitelist entries against them.

Please let me know what additional information you'll need to see where this goes wrong.

I am using 1.2.0-RC4 on FreeBSD with PHP7 and MySQL 5.7.

**Comment by asuweb** [comment]
Just to confirm, you add "Filters" in the User management section, and then go to the BW page, and it give the notice?

**Comment by remkolodder** [comment]
Hi Asuweb,

Yes there is where I add the filters. I can give a screenshot if you want?

**Comment by endelwar** [comment]
This should be fixed in develop branch, can you test it?

**Comment by remkolodder** [comment]
yes this fixed the issue! Thanks a lot 👍
