### ISSUE TITLE
LDAP configuration "too" tight

### ISSUE THREAD

**Issue by remkolodder** [mailwatch/1.2.0#549]
Hi,

We use a distributed setup for our mailscanner environment. Our webserver runs the MailWatch application, allowing our users to login and do their thing with the application and messages as they please.

We have a non-standard configuration, where our fields are different then the normal fields. instead of having our users defined as cn=user... we have the variable uid=user as main selector for our users.

The email field contains the email address of the user, but this is basically the same as the 'uid' field.
So for us to get this working we changed the LDAP_EMAIL_FIELD to uid and hit our first problem.

When the LDAP_EMAIL_FIELD does not match "email" the configuration forces the field to be "SMTP:$user" but this "field" is not available in our configuration at all (none of our schema's have this). Can the 

if (LDAP_EMAIL_FIELD === 'email' && strpos($user, '@')) {
            $ldap_search_results = ldap_search($ds, LDAP_DN, LDAP_EMAIL_FIELD . "=$user") or die(__('ldpaauth203'));
} elseif (strpos($user, '@')) {
            $ldap_search_results = ldap_search($ds, LDAP_DN, LDAP_EMAIL_FIELD . "=SMTP:$user") or die(__('ldpaauth203'));
        } else {

be made optional or "configurable" via conf.php so that we do not have to modify this code? We currently change the 'elseif' to match the if $ldap_search_result because that works for us. Why is the SMTP:$user being looked up btw? (e.g. where does it come from?)

In addition the 

 } else {
                    // build DN for user, when LDAP server is not an AD
                    $user = 'cn=' . $result[0]['cn'][0] . ',' . LDAP_DN;
                }

line, assumes that a user is defined as 'cn', but for us that is not the case. We can imagine that others also have different fields that markup their users. Can this also be made configurable via conf.php so that people with a different scheme can use the settings as  well without changing the functions.php (risking overwriting the changes everytime we update, note that we try to follow the develop branch as close as possible, yes at our own risk :-)).

Ofcourse, we accept the fact that we might run a non-default configuration and that we fall out of the boat for this one, if that is the case we need to be aware for every update that we revert these fields.

**Comment by Skywalker-11** [comment]
@remkolodder can you check #552 if it would be sufficient?

**Comment by stefaweb** [comment]
Is this issue solved?

**Comment by remkolodder** [comment]
Yes this issue is solved. I will close the issue when submitting this comment.

I will also try to find time for some documentation for at least OpenLDAP, can we generate a ticket or something for that and assign that to me so that I wont forget?
