### ISSUE TITLE
mailwatch_quarantine_report.php cron $mailwatch_dir does not exit, change it to MAILWATCH_HOME

### ISSUE THREAD

**Issue by remkolodder** [mailwatch/1.2.0#551]
Hi,

The variable $mailwatch_dir is not imported when sourcing the functions.php file. I believe that should be MAILWATCH_HOME instead and a small modification to the path to the required files on top so that the script actually runs;

```
--- mailwatch_quarantine_report.php.orig        2017-02-17 18:35:51.963136000 +0100
+++ mailwatch_quarantine_report.php     2017-02-17 18:34:02.856577000 +0100
@@ -60,9 +60,9 @@
     }
 }
 if ($required_constant_missing_count === 0) {
-    require_once $mailwatch_dir . 'lib/pear/Mail.php';
-    require_once $mailwatch_dir . 'lib/pear/Mail/smtp.php';
-    require_once $mailwatch_dir . 'lib/pear/Mail/mime.php';
+    require_once MAILWATCH_HOME . '/lib/pear/Mail.php';
+    require_once MAILWATCH_HOME . '/lib/pear/Mail/smtp.php';
+    require_once MAILWATCH_HOME . '/lib/pear/Mail/mime.php';
     date_default_timezone_set(TIME_ZONE);

     ini_set('html_errors', 'off');
```

Using this patch, this works without further modifications. (using functions.php this reads conf.php where MAILWATCH_HOME is defined, I think that restricts the amount of data configuration needed in this case, no need to create $mailwatch_dir as well at some place).

**Comment by asuweb** [comment]
Thanks - this will be fixed in #519 - it hasn't been merged yet due to another issue, which I forgot to fix.

I'll do it now :)

**Comment by remkolodder** [comment]
:) again thanks for that! can I just close this issue with that or should you do that after it was merged/committed?

**Comment by Skywalker-11** [comment]
Please wait till merge

**Comment by asuweb** [comment]
Can now be closed
