### ISSUE TITLE
Line break in Report:  (in detail.php)

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#554]
I don't know if we can insert a line break when we have many result in the field report.

![capture d ecran 2017-02-18 a 14 20 15](https://cloud.githubusercontent.com/assets/12907102/23093506/0700adcc-f5e6-11e6-9a73-40e7f62268fa.png)

**Comment by Skywalker-11** [comment]
we could use the same as for #393

**Comment by stefaweb** [comment]
Done in #556.

I still have a problem. See comment in the PR.

**Comment by stefaweb** [comment]
Done.
