### ISSUE TITLE
Spam scores should be float in mysql db

### ISSUE THREAD

**Issue by Skywalker-11** [mailwatch/1.2.0#555]
In users table the spam scores should be floats to enable finer definition of spam scores

```
spamscore` float DEFAULT NULL,
  `highspamscore` float DEFAULT NULL,
  `noscan` float DEFAULT NULL,
```

**Comment by stefaweb** [comment]
Hello @Skywalker-11!

I currently have create.sql in #553 and upgrade.php in #546.
Do you want that I add this to them?

**Comment by Skywalker-11** [comment]
Sure do it

**Comment by stefaweb** [comment]
Done.

**Comment by stefaweb** [comment]
Can be closed.

**Comment by Skywalker-11** [comment]
should be `default 0` instead of null
