### ISSUE TITLE
IPv6 and private network in functions.php?

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#560]
Not urgent but seems some codes in functions.php have hard IP coded routine not compatible IPv6 and not using the new IPSet.php library.

**Comment by asuweb** [comment]
Can you provide a list?

**Comment by stefaweb** [comment]
Look for 10.0.0. in function.php.

Not sure at 100% but no`require IPSet.php` in functions.php.

**Comment by asuweb** [comment]
Yes, I see them now.  They can be changed to use IPSet. 

I shall convert them to use the IPSet

**Comment by asuweb** [comment]
Merged, can be closed

**Comment by stefaweb** [comment]
Done.
