### ISSUE TITLE
Need write access for mailwatch-docs on branch "develop"

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#564]
Hello!

I started to work on documentation but I can't write on the repository. 

@endelwar, can you create a "develop" branch with write access?

(or may be, I've again forgot how to use git)

**Comment by Skywalker-11** [comment]
Why not use a pull request?

**Comment by stefaweb** [comment]
Yes, I'm again lost in GIT... I forgot to fork mailwatch-docs...

**Comment by Skywalker-11** [comment]
Ok then close the issue

**Comment by stefaweb** [comment]
Ok, forked.
