### ISSUE TITLE
New problem with mailwatch_sendmail_queue.php

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#565]
Got this message today and yesterday. Never saw it in the past.

Any idea?

```
Feb 21 20:24:02 antispam-dev php: PHP Notice:  Undefined index: subject in /usr/local/bin/mailwatch_sendmail_queue.php on line 269

Feb 20 13:16:01 antispam-dev php: PHP Notice:  Undefined index: subject in /usr/local/bin/mailwatch_sendmail_queue.php on line 269
```

**Comment by stefaweb** [comment]
The Subject message at 20:24:01 was:

`Nous avons mis à jour nos Conditions d’utilisation`

Nothing special when I look at it in detail.php.

**Comment by stefaweb** [comment]
A track can be. The subject starts with a space.

Data in the database.

![capture d ecran 2017-02-21 a 20 47 37](https://cloud.githubusercontent.com/assets/12907102/23181941/2844d56a-f877-11e6-984d-690e943021d6.png)

**Comment by stefaweb** [comment]
The one from yesterday was also a message from PayPal (the same but for another PayPal account).

Same Subject with a space...

**Comment by stefaweb** [comment]
The problem seems more complicated. I've sent a mail with a space in the Subject, no problem.

It seems that we have trouble when it's encoded as in these examples. MailWatch.pm insert LF (0a) at the wrong place. The problem occur in subject and headers fields.

```
Thread-Topic: Nous avons mis à jour nos Conditions
d’utilisation

Subject:
 =?UTF-8?Q?Nous_avons_mis_=C3=A0_jour_nos_Conditions_d=E2=80=99utilisation?=

Subject: =?UTF-8?B?8J+SmA==?= Single or taken, we're go...
 =?UTF-8?B?w6nDqcOgw6fDqMO5?= TITI

Thread-Topic: =?UTF-8?B?8J+SmA==?= Single or taken, we're go...
 =?UTF-8?B?w6nDqcOgw6fDqMO5?= TITI

Thread-Topic:  Nous avons mis =?UTF-8?B?w6A=?= jour nos Conditions
 =?UTF-8?B?ZOKAmXV0aWxpc2F0aW9u?=

Subject:  Nous avons mis =?UTF-8?B?w6A=?= jour nos Conditions
 =?UTF-8?B?ZOKAmXV0aWxpc2F0aW9u?=
```

And sometimes even when it is pure ascii.

```
Content-type: multipart/mixed;
     boundary="B_3570562210_1696148175"
```

For the moment I did not find the right combination that breaks the system.

Here is an export of the PayPal email from the database. I changed the to: address.

[crashed-email.sql.zip](https://github.com/mailwatch/1.2.0/files/791678/crashed-email.sql.zip)

**Comment by stefaweb** [comment]
Question?

In MailWatch.pm we have this:

`$msg{subject} = fix_latin($message->{utf8subject});`

What is the right syntax to apply `fix_latin()` to this line:

`$msg{headers} = join("\n", @{$message->{headers}});`

I would like to try to `apply fix_latin()` on the headers.

I wonder if it would not be better to change the `\n` separator for another character, clean the header of all special characters (LF, TAB and CR) and modify the php code to parse the separator and rebuild the printed version. At minimum, the header must be cleaned of  LF, TAB and CR before storing it in the database (and adding a `\n` during the `join()`).

For subject, il will may be better to clean the string of LF, TAB and CR before storing it in the database.

What do you think of all of this?

**Comment by stefaweb** [comment]
Hello!

Need help. I've modified the system for Subject (5097e39). Seems to work fine.

But now, I try to do this for headers:

- do a fixlatin() on the header array
- remove LF, TAB and CR in array blocks
- join the array with \n.

Using the routine for report as skeleton, I trying to it but I too complex for my poor programming knowledge.

```
    # Clean headers
    my ($file, $text, @headers_array);
    while(($file, $text) = each %{$message->{allheaders}}) {
        $file = "the entire message" if $file eq "";
        # Use the sanitised filename to avoid problems caused by people forcing
        # logging of attachment filenames which contain nasty SQL instructions.
        $file = $message->{file2safefile}{$file} or $file;
        $text =~ s/\n/ /g;  # Make sure text report only contains 1 line (LF)
        $text =~ s/\t/ /g;  # and no TAB characters
        $text =~ s/\r/ /g;  # and no CR characters

        # Uncommet the folloging line when debugging SQLBlackWhiteList.pm
        MailScanner::Log::WarnLog("MailWatch: Debug: var headers : %s", Dumper($text));

        push (@headers_array, $text);
    }

    # Sanitize headers
    my $headers = join("\n", @{$message->{headers_array}});
    # Uncommet the folloging line when debugging SQLBlackWhiteList.pm
    MailScanner::Log::WarnLog("MailWatch: Debug: var headers: %s", Dumper($headers));
```

And after:

`$msg{headers} = $headers;`

instead of 

`$msg{headers} = join("\n", @{$message->{headers}});`

**Comment by stefaweb** [comment]
The objective is to have this:

```
Received: from mta097b.pmx1.epsl1.com ([142.54.244.97]:58708)
	by antispam-dev.domain.tld with esmtps (TLS1.2:ECDHE_RSA_AES_256_GCM_SHA384:256)
	(Exim 4.84_2)
	(envelope-from <bounce-HP2v20000015a62216764cb2c4df4bbcfbb48042@mail.paypal.fr>)
	id 1cgG2Y-0004IQ-Hl
	for user@domain.tld; Tue, 21 Feb 2017 20:23:58 +0100
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=mail.paypal.fr;
	s=pp-epsilon1; t=1487705042;
	bh=Kv2yYgTlMCAo8C8QCxFTJFiUQFFJ/PQ9MrrcT1TLmfA=;
	h=MIME-Version:Subject:From:To:Date:Content-Type;
	b=Y0HNldsrqUlw6CQsShs08gPrddXCkqR5Drwu2//3WM7kOf+RcviEY58wp8jeOEkOq
	 aSsh6EJA2nmdJahLEGa9v3GnsZedzRLw8Lm4DHdo683WqsJJMh3x/DyQusTdw88xf7
	 AibWUUcCg/H0ZpDzl1FmhM9Ccs3znq6Uj2of9ZH6gstng009nUOwm6P6djyOQdMieA
	 sTXIbRIFjyuV2FxVpP5tYe4WX/zChvrFTJMz+bKm/Q4cGXFt7v7KUYJaB9BTQ1qVgq
	 GaDKOYgAnl29/4mrlu75XanNpU/BsmpNNmtbTs01vhA6NINEHmCRjOinz+Nb2s13S2
	 dfHpazv4SdFsQ==
Received: from [10.233.19.41] ([10.233.19.41:49366])
	by pc1udsmtn1n13 (envelope-from <bounce-HP2v20000015a62216764cb2c4df4bbcfbb48042@mail.paypal.fr>)
	(ecelerity 3.6.9.48312 r(Core:3.6.9.0)) with ECSTREAM
	id 58/77-45631-2D39CA85; Tue, 21 Feb 2017 19:24:02 +0000
List-Unsubscribe: <mailto:bounce-HP2v20000015a62216764cb2c4df4bbcfbb48042@mail.paypal.fr?subject=list-unsubscribe>
Message-ID: <HP2v20000015a62216764cb2c4df4bbcfbb48042@mail.paypal.fr>
MIME-Version: 1.0
Reply-To: "noreply@mail.paypal.fr" <noreply-HP2v20000015a62216764cb2c4df4bbcfbb48042@mail.paypal.fr>
Subject: =?UTF-8?Q?Nous_avons_mis_=C3=A0_jour_nos_Conditions_d=E2=80=99utilisation?=
From: "PayPal" <paypal@mail.paypal.fr>
To: user@domain.tld
Date: Tue, 21 Feb 2017 19:24:02 +0000
Content-Type: multipart/alternative;boundary="-=Part.3fc94ec.707b3f1188821426.15a62216dcc.b642417d9bd5ed62=-"
```

Instead of:

```
Received: from mta097b.pmx1.epsl1.com ([142.54.244.97]:58708)
	by antispam-dev.domain.tld with esmtps (TLS1.2:ECDHE_RSA_AES_256_GCM_SHA384:256)
	(Exim 4.84_2)
	(envelope-from <bounce-HP2v20000015a62216764cb2c4df4bbcfbb48042@mail.paypal.fr>)
	id 1cgG2Y-0004IQ-Hl
	for user@domain.tld; Tue, 21 Feb 2017 20:23:58 +0100
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=mail.paypal.fr;
	s=pp-epsilon1; t=1487705042;
	bh=Kv2yYgTlMCAo8C8QCxFTJFiUQFFJ/PQ9MrrcT1TLmfA=;
	h=MIME-Version:Subject:From:To:Date:Content-Type;
	b=Y0HNldsrqUlw6CQsShs08gPrddXCkqR5Drwu2//3WM7kOf+RcviEY58wp8jeOEkOq
	 aSsh6EJA2nmdJahLEGa9v3GnsZedzRLw8Lm4DHdo683WqsJJMh3x/DyQusTdw88xf7
	 AibWUUcCg/H0ZpDzl1FmhM9Ccs3znq6Uj2of9ZH6gstng009nUOwm6P6djyOQdMieA
	 sTXIbRIFjyuV2FxVpP5tYe4WX/zChvrFTJMz+bKm/Q4cGXFt7v7KUYJaB9BTQ1qVgq
	 GaDKOYgAnl29/4mrlu75XanNpU/BsmpNNmtbTs01vhA6NINEHmCRjOinz+Nb2s13S2
	 dfHpazv4SdFsQ==
Received: from [10.233.19.41] ([10.233.19.41:49366])
	by pc1udsmtn1n13 (envelope-from <bounce-HP2v20000015a62216764cb2c4df4bbcfbb48042@mail.paypal.fr>)
	(ecelerity 3.6.9.48312 r(Core:3.6.9.0)) with ECSTREAM
	id 58/77-45631-2D39CA85; Tue, 21 Feb 2017 19:24:02 +0000
List-Unsubscribe: <mailto:bounce-HP2v20000015a62216764cb2c4df4bbcfbb48042@mail.paypal.fr?subject=list-unsubscribe>
Message-ID: <HP2v20000015a62216764cb2c4df4bbcfbb48042@mail.paypal.fr>
MIME-Version: 1.0
Reply-To: "noreply@mail.paypal.fr"
 <noreply-HP2v20000015a62216764cb2c4df4bbcfbb48042@mail.paypal.fr>
Subject:
 =?UTF-8?Q?Nous_avons_mis_=C3=A0_jour_nos_Conditions_d=E2=80=99utilisation?=
From: "PayPal" <paypal@mail.paypal.fr>
To: user@domain.tld
Date: Tue, 21 Feb 2017 19:24:02 +0000
Content-Type: multipart/alternative;
 boundary="-=Part.3fc94ec.707b3f1188821426.15a62216dcc.b642417d9bd5ed62=-"
```

**Comment by asuweb** [comment]
I'm slightly lost here.  What has MailWatch.pm got to do with MTA queues?  As far as I can see, mailwatch_sendmail_queue.php is interested in what mail is in either the incoming or outgoing mail queue, and parses those emails in each queue and put them in the DB, and then removes them when they leave the queue? 

MailWatch.pm has no influence on the queue what so ever.  The only thing which interacts with the queue is mailscanner.

**Comment by Skywalker-11** [comment]
if you want to apply fix_latin on everything in the headers you could use map like this:
`$fixedheaders = map { fix_latin($_)}  @{$message->{headers}}`

Not tested though

**Comment by stefaweb** [comment]
@asuweb: 
Zut, you're right. I've missunderstood mailwatch_sendmail_queue.php. I was thinking that it was reading maillog table.

We have two problem in fact. Wrong formatting for headers to be stored in maillog table and sometime a message in the Queue crash mailwatch_sendmail_queue.php.

Complex.

**Comment by asuweb** [comment]
It doesn't actually crash mailwatch_sendmail_queue.php, it just produces a notice, not a fatal error.

I'm not sure I follow what exactly the issue is with how headers are currently stored in maillog.  Can you explain?

**Comment by stefaweb** [comment]
@Skywalker-11: 

`$msg{headers} = join("\n", map { fix_latin($_)} @{$message->{headers}});`

Works. No problem of encoding in the database but the wrong `\n` are still here in headers. I'll like to have a routine to clean control chars in each headers array values.

@asuweb:

Currently, MailWatch read the headers array and insert a `\n` at the end of each value.

`$msg{headers} = join("\n", @{$message->{headers}});`

The problem seems that sometime the value contains control character as `\n`.

And we got for a the array value:

```
Subject:
 =?UTF-8?Q?Nous_avons_mis_=C3=A0_jour_nos_Conditions_d=E2=80=99utilisation?=
```

Instead of:

`Subject: =?UTF-8?Q?Nous_avons_mis_=C3=A0_jour_nos_Conditions_d=E2=80=99utilisation?=
`

The problem is similar of the one I had with "report" in #556.

For mailwatch_sendmail_queue.php, it produce a notice but sent me a mail each time and may be cause a problem in the queue or in the database.

**Comment by asuweb** [comment]
@stefaweb - it sends you a message because the output from the cron hasn't been send anywhere else.  You could direct it to /dev/null or a specific log file if you desire.

Does the extra line under "Subject" in the database cause any actual issues / error with the way mailwatch works?

**Comment by stefaweb** [comment]
> Does the extra line under "Subject" in the database cause any actual issues / error with the way mailwatch works?

I don't know sure. If this is not in relation with mailwatch_sendmail_queue.php, the problem can be classified as "cosmetic" (I know, you don't like).

For the "Undefined index: subject", I don't know if this can cause a problem in the database when the value is stored in the database. But sometime it stop the refresh of the message list on the GUI screen. I've to restart services to have the refresh working again.

**Comment by asuweb** [comment]
@stefaweb - It's not that I don't like fixing or correcting cosmetic bugs, but I take a risk vs reward approach.  In this case, the only parties interest in the mail header will be sysadmins.  The majority of end user won't know what a mail header is, therefore will never look at it.  

The risk of fixing this cosmetic issue, is the introduction of more bugs which affect the operation of MailWatch.  Personally, I don't feel the risk is worth the reward with this.  If you feel it is, then by all means continue to fix it.  

With V2, I imagine there will be a lot of things changing, especially all things cosmetic, so it might be more beneficial to look at this then, rather than potentially risk making 1.2 unstable.  

I'm running the current dev version in production now, and it's performing well, so I think we (as in those that contribute to the project) have done a great job in getting it this far.  Hopefully it can be released into RC5 soon for further user feedback and then be marked as stable, and work can get underway with V2.

If the "Undefined Index" is causing an issue, then yes it needs fixed. Did see somewhere in a PR that you'd changed how exim and sendmail display queue data?  If you're now using passthrough, then presumably we don't need mailwatch_sendmail_queue.php?

**Comment by stefaweb** [comment]
@asuweb: 

When do will have a RC version for v2? In six, twelve months? We can spend some time to fix the "cosmetic bugs" especially if behind the users and us will have to live with them for many months. Especially when the PR basket is full of unpublished PRs and we need to wait.

Concerning mailwatch_sendmail_queue.php, I was not aware of the fact we no longer needed it since I have modded the calls in GUI for Exim queue. I'll modify the docs for that. The system for Sendmail is also done but not activated as we need to test it.

Concerning the header. I fixed fix_latin() only. In fact, the "original" header have the structure with wrong \n. Seems generated by wrong coded software at the source or crossed MTAs. I left it as this as the header in GUI is just to look at it, not to use it somewhere in code.

Concerning the "Undefined index: subject", I still don't know if this cause a problem. As, I'm not using Sendmail, difficult to know. 

For MailWatch.pm, it seems, we still need to identify and fix the problem described in #428.

**Comment by shawniverson** [comment]
https://media.giphy.com/media/WM3HX2cZ3zTry/giphy.gif

**Comment by Skywalker-11** [comment]
As fix for that it could help to use instead of 
```
                    safe_value($msginfo['subject']) . "','" .
````
this
```
                    safe_value( (isset($msginfo['subject']) ? $msginfo['subject'] : "") ) . "','" . 
```

It tests if the array contains subject and uses that value if it exists. Else it uses an empty string. That should prevent the Notice

**Comment by stefaweb** [comment]
@Skywalker-11 

Thanks. Works fine.

I got the subject or no nothing with var_dump(), but no NOTICE.

`string(49) "=?UTF-8?B?8J+SmA==?= Single or taken, we're go..."
`

**Comment by stefaweb** [comment]
Done in #570 and #556.

**Comment by stefaweb** [comment]
Done.
