### ISSUE TITLE
About quarantine folder

### ISSUE THREAD

**Issue by Lichengchang** [mailwatch/1.2.0#566]
Hi,

Quarantine folder only display to 21/02/2017, follows：
![mg1](https://cloud.githubusercontent.com/assets/25293877/23195900/04e2a190-f8f1-11e6-8cf2-5a37f9e6a574.png)

But on system the folder is there, follows：
![mg2](https://cloud.githubusercontent.com/assets/25293877/23195909/13404a12-f8f1-11e6-8128-7889307efb85.png)

Any idea?

**Comment by asuweb** [comment]
Could it be a timezone issue perhaps?

**Comment by Skywalker-11** [comment]
In case what @asuweb has mentioned is true what is your system timezone and timezone in mailwatch conf?

**Comment by Lichengchang** [comment]
Thanks for the suggest.
