### ISSUE TITLE
Move DB settings for perl files to separate config file

### ISSUE THREAD

**Issue by asuweb** [mailwatch/1.2.0#568]
Move the DB settings in each .pm file to a separate file to ease installation and upgrading.

**Comment by stefaweb** [comment]
What happening if the user have a another .pm script in /custom using the same variable?

If we have a "custom" script with the same connect variables but not with the same host, db, user and password.

MailWatch-DB.pm

```
+#!/usr/bin/perl
 +sub get_db_name { return 'mailscanner'};
 +sub get_db_host { return 'localhost' };
 +sub get_db_user { return 'mailwatch' };
 +sub get_db_password { return 'mailwatch' };
 +1;
```

**Comment by asuweb** [comment]
The MailWatch-DB.pm file has 4 functions in it. So it only works if the script calls these functions.  For example in MailWatch.pm

```
my ($db_name) = get_db_name();
my ($db_host) = get_db_host();
my ($db_user) = get_db_user();
my ($db_pass) = get_db_password();
```

**Comment by stefaweb** [comment]
Ok but as I'm paranoid, can you add `mailwatch_get_db_` if you do not mind?

**Comment by stefaweb** [comment]
But the fix is great...

**Comment by asuweb** [comment]
OK, I've done that :)

**Comment by stefaweb** [comment]
I've to modify the docs.
