### ISSUE TITLE
Style in New and Edit User

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#577]
Can someone look if you have this problem on your server?

(may be a false issue as my dev server is currently dev mixed)

![capture d ecran 2017-02-23 a 15 38 15](https://cloud.githubusercontent.com/assets/12907102/23263397/67ac1b4c-f9de-11e6-83d7-2997a2226206.png)

**Comment by asuweb** [comment]
What's the issue?

**Comment by stefaweb** [comment]
The style. Look at the font size. Seems a css style do not correspond.

**Comment by asuweb** [comment]
I see - I'll fix it

**Comment by stefaweb** [comment]
Done.
