### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#580]
In the doc, is this link still ok?

`![](/mailscanner/images/mailwatch-logo.png?raw=true)`

If I go to the git front page, I have:

`https://raw.githubusercontent.com/mailwatch/1.2.0/master/mailscanner/images/mailwatch-logo.png`

**Comment by endelwar** [comment]
Yes, that's the github cdn url for that file

**Comment by stefaweb** [comment]
Glup!

I love the   ` ![]`

**Comment by endelwar** [comment]
Github flavoured Markdown is very cool
