### ISSUE TITLE
Problem of Sender: with quarantine report

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#587]
Tried the new quarantine report mail engine.

Mail from quarantine report are sent with postmater@localhost.

```
    SMTP error from remote mail server after RCPT TO:<user@domain.tld>:
    host mail.domain.tld [xx.xx.xx.xx]: 550-Verification failed for <postmaster@localhost>
    550-Unrouteable address
    550 Sender verify failed
```

```
Return-path: <postmaster@localhost>
From: COMPANY hostname <postmaster>
```

**Comment by asuweb** [comment]
Define the mailwatch from address fully:

`define('MAILWATCH_FROM_ADDR', 'postmaster@domain.tld');`

It's using @localhost as presumably that is what's in your /etc/hosts or your MTA configuration

**Comment by stefaweb** [comment]
Ok, I found the problem. I correct the conf.php.example comment for

**Comment by stefaweb** [comment]
I've done this and added a comment.

Done in #588.
