### ISSUE TITLE
fix processing of postfix mta logs

### ISSUE THREAD

**Issue by remkolodder** [mailwatch/1.2.0#590]
Hi,

While trying to process my relay logs from my external mailservers running postfix+mailscanner (and mailwatch), i noticed that running the mailwatch_postfix_relay.php script does not work properly when the DELAY >= 60. Probably because that is a minute and does not feed well into SQL.

```
$ git diff mtalogprocessor.inc.php
diff --git a/mailscanner/mtalogprocessor.inc.php b/mailscanner/mtalogprocessor.inc.php
index 6bbe179..681edad 100644
--- a/mailscanner/mtalogprocessor.inc.php
+++ b/mailscanner/mtalogprocessor.inc.php
@@ -142,7 +142,7 @@ abstract class MtaLogProcessor
             }
             if (isset($_type)) {
                 dbquery(
-                    "REPLACE INTO mtalog (`timestamp`,`host`,`type`,`msg_id`,`relay`,`dsn`,`status`,`delay`) VALUES (FROM_UNIXTIME('$_timestamp'),'$_host','$_type','$_msg_id','$_relay','$_dsn','$_status','$_delay')"
+                    "REPLACE INTO mtalog (`timestamp`,`host`,`type`,`msg_id`,`relay`,`dsn`,`status`,`delay`) VALUES (FROM_UNIXTIME('$_timestamp'),'$_host','$_type','$_msg_id','$_relay','$_dsn','$_status',SEC_TO_TIME('$_delay'))"
                 );
             }
             $lines++;

```

is the patch I used to get it imported into SQL.

This does generate warnings from mysqli though:

`Warning: mysqli::real_escape_string(): Couldn't fetch mysqli in /path/to/mailscanner/functions.php on line 901`

I am not sure what they mean at this point, but I wanted to document this before I forget about it :)

**Comment by asuweb** [comment]
What version of MailWatch are you using?

**Comment by remkolodder** [comment]
I am using the devel branch Sorry I forgot to mention that :)

**Comment by asuweb** [comment]
The develop branch on all scanner servers?  It's just that line 901 in functions.php (the latest version as of a few hours ago) is a `{` which wouldn't give that warning

**Comment by asuweb** [comment]
You could also try using `gmdate('H:i:s', $your_time_in_seconds);` to convert the delay in to the time format in php, before the query

**Comment by remkolodder** [comment]
No, I updated it this morning on this machine, but did not yet sync it to my master which is actively running mailwatch :)

It's this function;

```
/**
 * @param $value
 * @return string
 */
function safe_value($value)
{
    $link = dbconn();
    if (function_exists('get_magic_quotes_gpc') && get_magic_quotes_gpc()) {
        $value = stripslashes($value);
    }
    $value = $link->real_escape_string($value);

    return $value;
}

```
and specifically the 

> $value = $link->real_escape_string($value);

 part of the function.

**Comment by remkolodder** [comment]
What would suit better? SEC_TO_TIME or a routine to do 

> $delay = gmdate('H:i:s', $delay);

prior to the REPLACE INTO query? I am not sure whether we need to apply this to everything. I can imagine that at sendmail delay line is different and might already be in the proper format.

**Comment by asuweb** [comment]
`SEC_TO_TIME` is more elegant I would think.  Can you try it with the latest `database.php` - it was changed about 3 hours ago and might fix this

**Comment by remkolodder** [comment]
I am currently merging (well rathar copying over) the checkout into my active running session on the ui-server (which receives this all syslog information as well and has the frontend for this).

it appears that the mssage and issue is gone.

I will now turn my head towards the wall and repeat a 1000 times: I will first make sure that my branch is as up to date as possible before opening an problem record ;). Apologies!

**Comment by asuweb** [comment]
No problem, one of the gotchas to using the dev branch ;)  - It'll be stable soon we hope :)
