### ISSUE TITLE
Some problems with password reset

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#592]
Screen too small.

![capture d ecran 2017-02-24 a 09 06 25](https://cloud.githubusercontent.com/assets/12907102/23295436/f1e2bc84-fa70-11e6-8371-0dde12f9c930.png)

Button too large.
Font in button a little too small.

![capture d ecran 2017-02-24 a 09 06 35](https://cloud.githubusercontent.com/assets/12907102/23295437/f206be0e-fa70-11e6-85c4-d1af3f02eb4e.png)

Where to go after this screen?
No button, no back.

![capture d ecran 2017-02-24 a 09 07 06](https://cloud.githubusercontent.com/assets/12907102/23295438/f20bad24-fa70-11e6-949a-d60aa8d3a83a.png)

**Comment by stefaweb** [comment]
Do we log the reset attempt in Audit Log?

**Comment by asuweb** [comment]
I'll adjust the styles - it works in english, but seems when translated it breaks the format. 

I'll use `min-width` and fix it that way.

Audit log was my intention, but seems I forgot to implement - I'll do that as well. 

The "where to go after this screen" - which screen?

**Comment by stefaweb** [comment]
> The "where to go after this screen" - which screen?

When the user is not found, we need to go nowhere. To the login page or go back to reset screen may be better.

Two more.

After sending the mail to user.
No button, no back to login.

![capture d ecran 2017-02-24 a 09 22 17](https://cloud.githubusercontent.com/assets/12907102/23295865/e0e42498-fa72-11e6-8486-9313cad56f25.png)

Add more space between the text and the button.
May add a button yellow as the others.

![capture d ecran 2017-02-24 a 09 24 21](https://cloud.githubusercontent.com/assets/12907102/23295926/2eb44630-fa73-11e6-9e81-bf4739a7accb.png)

**Comment by asuweb** [comment]
Working on it

**Comment by stefaweb** [comment]
The last one.

The mail.

We have "space" between the email and the dot.

![capture d ecran 2017-02-24 a 09 29 37](https://cloud.githubusercontent.com/assets/12907102/23296130/f57ec790-fa73-11e6-8f40-190d548db338.png)

**Comment by stefaweb** [comment]
Try with German too. Their wording are longer than French...

Good luke. I'm out part of the day.

**Comment by stefaweb** [comment]
If you add stuff in Audit Log, try to log the IP.

**Comment by asuweb** [comment]
audit_log logs the IP by default

**Comment by stefaweb** [comment]
Found this when I move the mouse on the button. Two vertical blue lignes appears.
OSX Firefox, Safari, Chrome.

![capture d ecran 2017-03-02 a 09 41 04](https://cloud.githubusercontent.com/assets/12907102/23499476/97c3578e-ff2c-11e6-8d22-48ee032320a6.png)

**Comment by stefaweb** [comment]
Same for this one too.

The button is till too large and the font inside the button is too small compared to the "normal" button size in login page.

![capture d ecran 2017-03-02 a 09 44 48](https://cloud.githubusercontent.com/assets/12907102/23499591/0604f8d8-ff2d-11e6-9096-90f1a4eaa97c.png)

**Comment by asuweb** [comment]
see #605

**Comment by stefaweb** [comment]
Thanks @asuweb 

I've found a little mod to apply.

In this screen, a space is missing between `Email Address:` and the field.

![capture d ecran 2017-03-02 a 13 54 07](https://cloud.githubusercontent.com/assets/12907102/23507997/f34f9856-ff4f-11e6-8bd1-316f8d0851ea.png)

As in the login screen:

![capture d ecran 2017-03-02 a 13 54 21](https://cloud.githubusercontent.com/assets/12907102/23507998/f3756ba8-ff4f-11e6-98e0-0a0b9396a057.png)
