### ISSUE TITLE
Problem with Quarantine report and user/domain

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#608]
Hello!

Something wrong with quarantine report.

USER user1@domain1.tld receive all message for domain1.tld

ADMIN DOMAIN user@domain.tld receive all domain1.tld but not message for domain.tld (domain1.tld is in filter for domain.tld)

Could you verify on your side?

**Comment by stefaweb** [comment]
@asuweb ?

**Comment by asuweb** [comment]
Strange.  The only change in the logic that I can think of would have been introduced when @Skywalker-11 implemented the domain admin bits...

**Comment by stefaweb** [comment]
Sorry, mistake. A job for @Skywalker-11

**Comment by Skywalker-11** [comment]
My changes for the domain admins only affected the user_manager.php gui. It shouldn't have changed anything with the reports

**Comment by stefaweb** [comment]
The problem was perhaps already present. Personally, as I used a very old version of MailWatch in production and only with domain admin as "domain.tld" instead of "domain-admin@domain.tld", I never saw the problem.

**Comment by asuweb** [comment]
I've never seen this issue.  I have both users and domain admins configured and no reported issues with the quarantine report system.

It's something I want to re-design at some point as I want the ability to define timezone and frequency and time of report for each user.

**Comment by stefaweb** [comment]
I've reactivated reports for 2 domain users and one user. I'll send you examples tomorrow morning.

**Comment by stefaweb** [comment]
Hello!

I've some sample of report for you. I don't want to post them here. How can I send them directly to you?

**Comment by asuweb** [comment]
@stefaweb - you can email them to me - alan [AT] asuweb.co.uk

**Comment by stefaweb** [comment]
Ok, I do it.

Look at #625. May be this problem is related. I've found tens of old/unused entries in user_filters.

**Comment by asuweb** [comment]
Did you find any old filters in the database which might have caused this issue with the wrong quarantine reports?

**Comment by stefaweb** [comment]
I've found tens of old entries in user_filters. When a changed admin domain from domain.tld to admin-domain@domain.tld, I created more again. I deleted then. I'll let you know next time report will be run.

**Comment by asuweb** [comment]
OK

**Comment by stefaweb** [comment]
Bad news. No change. The problem is still here.

**Comment by stefaweb** [comment]
Switched some personal domains to my dev server to have some flux.

To be sure, I tried with LANG = en, no change.

**Comment by stefaweb** [comment]
I have domain.tld and domain2.tld in the filter of domain.tld (active, yes).

I receive a report with domain2.tld messages but no domain.tld.

I switch to NO domain2.tld in filter: no report message.

Report for user@domain.tld receive all messages for domain.tld.

**Comment by stefaweb** [comment]
The report in console:

```
 === Generating report for domain-admin@domain.tld type=D
 ==== Recipient e-mail address is user@domain.tld
 ==== Building list for user@domain.tld
 ==== Found 1 quarantined e-mails
 ==== Sent e-mail to user@domain.tld
 ==== Building list for domain2.tld
 ==== Found 1 quarantined e-mails
 ==== Sent e-mail to user@domain.tld
```

No "Building list" for domain.tld.

**Comment by stefaweb** [comment]
I can not find the constant `FILTER_VALIDATE_EMAIL` that is used in mailwatch_quarantine_report.php somewhere?

???

**Comment by shawniverson** [comment]
FILTER_VALIDATE_EMAIL is a filter id in php.

http://php.net/manual/en/filter.filters.validate.php

**Comment by stefaweb** [comment]
May be found the problem.

Report user@domain.tld works. If no message in quarantine for him, no report message.

For domain admin.

```
 ==== Recipient e-mail address is report@domain.tld
 ==== Building list for user@domain.tld       |||| SHOULD BE domain.tld INSTEAD OF user@domain.tld
 ==== Found 1 quarantined e-mails
 ==== Sent e-mail to report@domain.tld
 ==== Building list for domain2.tld     |||| domain in filter - DO NOT WORK - 6 QUARANTINE MESSAGES FOR domain2.tld - THE MAIL REPORT CONTAINS message of domain.tld
 ==== Found 1 quarantined e-mails
 ==== Sent e-mail to report@domain.tld
```

In the report mail for domain.tld, we have user@domain.tld:

**Quarantine Report for user@domain.tld**

instead of @domain.tld.

Good luck to find where is the bug!

**Comment by Skywalker-11** [comment]
Can you share the filters you have in the db?

**Comment by stefaweb** [comment]
> Can you share the filters you have in the db?

Hello Skywalker-11! 

What do you need exactly?

I also found that. In table user_filters, there is the verify_key field. I found no reference to this field in the code.

**Comment by asuweb** [comment]
Domain admin reports work fine on mine:

```
 php mailwatch_quarantine_report.php

 === Generating report for domain-admin@asuweb.co.uk type=D
 ==== Recipient e-mail address is domain-admin@asuweb.co.uk
 ==== Building list for domain-admin@asuweb.co.uk
 ==== Found 33 quarantined e-mails
 ==== Sent e-mail to domain-admin@asuweb.co.uk
```

Resulting email contains all spam for the domain

**Comment by stefaweb** [comment]
For me `Building list for domain-admin@asuweb.co.uk` should be `Building list for asuweb.co.uk`

What do you have in the report mail for "Quarantine Report for..."?

And if you add a second domain in the filter?

**Comment by asuweb** [comment]
> Quarantine Report for...
domain-admin@

We can probably change that to just the domain, although for me it's pretty clear.

Filters don't work for domain admins, the logic just isn't written that way.  The problem is there is no way currently to tell if the filter is a domain or a user.  The logic of domain admins is only for the actual user, where we explicitly set the `$to_domain` when dealing with type "D"

For domain admins where you want the same person to receive multiple domains, it's better to just to create a separate domain admin for each domain and use the Alternative recipient field to redirect the report.

**Comment by asuweb** [comment]
I can submit a PR which changes the "quarantine report for" and "building list for" to reflect the domain in the case of domain admins.  In the same PR I'll prevent filters from running for domain admins as it's not supported at this time.

**Comment by stefaweb** [comment]
I've some domain user with 10 domains and more in user_filters. Create an admin user for each domain in not rational. Specialy when the domain user want to see all its domains in status.php and other parts of the GUI. 

Can we correct all this "illogic" system in easy way or it's a big job to do (=v2)?

**Comment by asuweb** [comment]
Yes, I can see that being an issue in those circumstances.  I can possibly adapt the logic to make it work in this way.  

Do you want a separate email per filter (as it does now) or a single email that contains the user and all users filters?

**Comment by stefaweb** [comment]
We can may be have only one mail report with all message domains for admin user.
Is it easier to do?

**Comment by stefaweb** [comment]
Your message crossing mine.

Only one mail seems better. Its crazy to receive 10 report emails each morning...

**Comment by asuweb** [comment]
The problem with a single mail for multiple domains is it will be a bigger job to then put them in chronological order as it would also require rewriting the queries and not just the logic.  

Separate emails make it easier to find a particular mail for a particular domain I think?

**Comment by asuweb** [comment]
I'll have a look at both options, and let you know which works - we might be able to do a custom array sort to put them in chronological order in a single mail

**Comment by Skywalker-11** [comment]
If you want to select multiple domains or addresses in mysql you could use instead of
` ((to_address=%s) OR (to_domain=%s))
`
this
` ((to_address IN (%s)) OR (to_domain IN (%s)))
`
and use a comma separated list as the values there

**Comment by stefaweb** [comment]
And this?

> I also found that. In table user_filters, there is the verify_key field. I found no reference to this field in the code.

**Comment by Skywalker-11** [comment]
probably obsolete

**Comment by asuweb** [comment]
Fixed in #640 

@stefaweb - please check this works in your environment

**Comment by stefaweb** [comment]
One more time. ;-)

The report use email from quarantine_rcpt field to select messages in report and others stuff.

```
 === Generating report for domain-admin@domain.tld type=D
 ==== Recipient e-mail address is report@domain-sender.tld
 ==== Building list for domain-sender.tld
 ==== Found 20 quarantined e-mails
 ==== Sent e-mail to report@domain-sender.tld
```

(I used an existing domain in quarantine_rcpt to received something)

**Comment by asuweb** [comment]
```
 === Generating report for domain-admin@domain.co.uk type=D
 ==== Recipient e-mail address is domain-admin@domain.co.uk
 ==== Building list for domain.co.uk
 ==== Found 33 quarantined e-mails
 ==== Building list for filter-domain.com
 ==== Found 5 quarantined e-mails
 ==== Sent e-mail to domain-admin@domain.co.uk
```

**Comment by asuweb** [comment]
works fine on mine

**Comment by asuweb** [comment]
Wait, I see,

**Comment by asuweb** [comment]
This must have presumably been a latent bug - it's not new....

Try it now please :)

**Comment by stefaweb** [comment]
More detail.

domain.tld: DOMAIN ADMIN domain-admin@domain.tld
domain2.tld domain in filter for DOMAIN ADMIN domain-admin@domain.tld
user@domain3.tld: email in quarantine_rcpt field (in database)

```
 === Generating report for domain-admin@domain.tld type=D
 ==== Recipient e-mail address is user@domain3.tld
 ==== Building list for domain3.tld
 ==== Found 0 quarantined e-mails (normal domain3.tld do not exist in MS/MW), I've 14 messages for domain.tld
 ==== Building list for domain2.tld (domain in filter, ok)
 ==== Found 20 quarantined e-mails
 ==== Sent e-mail to user@domain3.tld
```

If I replace `user@domain3.tld` by `user@domain.tld`, I received all messages.

**Comment by asuweb** [comment]
Try the latest commit please

**Comment by asuweb** [comment]
One more bug to fix - still need to do array sort to get them in cronological order

**Comment by stefaweb** [comment]
Others problems gone.

Just to mod.

In title of mail report, we got:

```
Quarantine Report for domain.tld
domain2.tld
```

May be better:

```
Quarantine Report for domain.tld, domain2.tld
```

Great job!

**Comment by asuweb** [comment]
Ok, once I've fixed the chronology it's good to go then

**Comment by asuweb** [comment]
Ok, that's done now

**Comment by stefaweb** [comment]
Hi @asuweb!
Could you check with languages. Here, the report is alway in English.

I'm out all the day.

```
Quarantine Report for domain.tls, tomain2.tld,

In the last 1 day(s) you have received 24 e-mails that have been quarantined and are listed below. All messages in the quarantine are automatically deleted 20 days after the date that they were received.
```

**Comment by asuweb** [comment]
Done

**Comment by stefaweb** [comment]
Works fine. #640 can be merge.

**Comment by stefaweb** [comment]
Done.
