### ISSUE TITLE
Bug in viewmail.php

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#609]
I have this error, when I view a message (a dangerous content, message part).

![capture d ecran 2017-03-07 a 08 59 23](https://cloud.githubusercontent.com/assets/12907102/23647196/d3110868-0314-11e7-8bdf-9b43066eeb00.png)

![capture d ecran 2017-03-07 a 09 01 12](https://cloud.githubusercontent.com/assets/12907102/23647203/da40efe0-0314-11e7-9065-5849289fdf9f.png)

**Comment by Skywalker-11** [comment]
The cause is probably an invalid mime message or a bug in the pear library for MIME decoding. Can you try this [https://github.com/Skywalker-11/1.2.0/commit/8dde1b8b16f55798011115af2594927aaf064414](https://github.com/Skywalker-11/1.2.0/commit/8dde1b8b16f55798011115af2594927aaf064414)

**Comment by stefaweb** [comment]
Will try thanks.

**Comment by stefaweb** [comment]
@Skywalker-11 . The patch works fine. No longer error message.
Great!

**Comment by stefaweb** [comment]
Done.
