### ISSUE TITLE
upgrade.php

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#616]
Hello @endelwar 

Yellow is difficult to read.

![capture d ecran 2017-03-08 a 12 04 05](https://cloud.githubusercontent.com/assets/12907102/23701574/9c10d0ee-03f7-11e7-8b32-62f94264dc56.png)

EDIT : removed comment on blank line.

**Comment by endelwar** [comment]
Well, yellow on yellow is surely difficult to read :)
On "normal" black background console yellow on black is very readable.
From php I can't get the terminal default background color.

**Comment by stefaweb** [comment]
Try with #FF6600.

**Comment by endelwar** [comment]
htlm color can't be used on console: there are 16 fixed colours that can be used, look at this page http://misc.flogisoft.com/bash/tip_colors_and_formatting (no 256 colour mode is not an option ;))

**Comment by stefaweb** [comment]
Light magenta will be better for WARNING.
Light red for ERROR.

Say that now we have 4K screens and we continue in 2017 to use the good old console.  😄

**Comment by stefaweb** [comment]
This WARNING still in black.

```
 - SpamActions ....................................................... OK
 - HighScoringSpamActions ............................................ WARNING
 - AlwaysLookedUpLast ................................................ OK
```

**Comment by stefaweb** [comment]
Not sure to understand. Are theses values in OPTIONAL in functions.php or not?

```
conf.php: optional configuration entry "RPC_PORT" is missing, needed if RPC_ONLY mode is enabled
conf.php: optional configuration entry "RPC_SSL" is missing, needed if RPC_ONLY mode is enabled
conf.php: optional configuration entry "PWD_RESET_FROM_NAME" is missing, needed if Password Reset feature is enabled
conf.php: optional configuration entry "PWD_RESET_FROM_ADDRESS" is missing, needed if Password Reset feature is enabled
```

**Comment by stefaweb** [comment]
Hello!
May be something wrong or not clear.

When I run upgrade.php, I got:

```
conf.php: optional configuration entry "PWD_RESET_FROM_NAME" is missing, needed if Password Reset feature is enabled
conf.php: optional configuration entry "PWD_RESET_FROM_ADDRESS" is missing, needed if Password Reset feature is enabled
```

But in conf.php, these two values seems "optional" `unless define('PWD_RESET', true);`

```
//define('PWD_RESET_FROM_NAME', 'Some other name'); // Set if you wish reset email sent from alternative name.
//define('PWD_RESET_FROM_ADDRESS', 'support@yourdomain.com'); // Set is you wish reset email sent from alternative address.
```

**Comment by asuweb** [comment]
They are indeed optional.  

Upgrade.php says "optional configuration entry"

Those 2 constants aren't actually required even when password reset is enabled - as it will default to `MAILWATCH_FROM_ADDR` & `QUARANTINE_REPORT_FROM_NAME` if not set

**Comment by stefaweb** [comment]
@endelwar 
You don't like magenta? ;-)

![capture d ecran 2017-03-10 a 15 23 17](https://cloud.githubusercontent.com/assets/12907102/23798588/a1a100b0-05a5-11e7-83cd-595e5df26bd9.png)

**Comment by endelwar** [comment]
> You don't like magenta? ;-)

NO :)
I'm keeping a standard semaphore color:
- Green -> all ok, pass
- Yellow -> be careful, watch left/right very well
- Red -> stop, disaster ahead!

also the vast majority of console screen and terminal emulator have black background (also the good old VT100 and VT220).

**Comment by endelwar** [comment]
> May be something wrong or not clear.

`needed if Password Reset feature is enabled` should be written better, specifying the customization nature of the entry

**Comment by stefaweb** [comment]
Done.
