### ISSUE TITLE
Wishlist for user_manager.php

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#617]
Move the column "actions" to the first place.

This will make it easier to select the user.

![capture d ecran 2017-03-08 a 13 21 29](https://cloud.githubusercontent.com/assets/12907102/23703928/b08ba48a-0402-11e7-8999-83fa277f45d6.png)

**Comment by asuweb** [comment]
This would be better fixed with css to highlight the row on hover.  

I'll fix it

**Comment by stefaweb** [comment]
As you want. I've look at the code and it's not a fast job to invert columns. 

I would just stop using a school rule to properly target the user. 😀

**Comment by asuweb** [comment]
It's done

**Comment by stefaweb** [comment]
Done.
