### ISSUE TITLE
Bug with IPSet.php when wrong IP in detail.php

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#622]
I got an error when one of the IP is wrong.

```
Warning: inet_pton(): Unrecognized address 1489062189 in /var/www/html/mailscanner/lib/IPSet.php on line 200

Warning: inet_pton(): Unrecognized address 1489062189 in /var/www/html/mailscanner/lib/IPSet.php on line 200

Warning: gethostbyaddr(): Address is not a valid IPv4 or IPv6 address in /var/www/html/mailscanner/detail.php on line 158
```

![capture d ecran 2017-03-09 a 13 28 05](https://cloud.githubusercontent.com/assets/12907102/23750255/56b0e6f8-04cc-11e7-8776-8b59b708d3e4.png)

Apparently the number comes from the header here:

```
X-Bluewin-Spam-Score: 0.00
X-FXIT-IP: IPv4[128.90.20.16] Epoch[1489062189]
```

**Comment by asuweb** [comment]
This is actually a bug with `get_mail_relays` in functions.php.  

That isn't an IP address, so it shouldn't be listed in the Address section.

Is that the only place in the full header of that mail where that string occurs?

**Comment by stefaweb** [comment]
Done a grep on message in Quarantine.

Only here:  `X-FXIT-IP: IPv4[128.90.20.16] Epoch[1489062189]`

**Comment by asuweb** [comment]
Nowhere do we actually check the relay is a valid IP.

I'll add a check and you can test it out

**Comment by asuweb** [comment]
@stefaweb - try this: https://github.com/asuweb/Mailwatch-1.2.0-asuantispam/compare/iss%23622

**Comment by stefaweb** [comment]
Gone.
You can do a PR.

**Comment by endelwar** [comment]
Relays should be obtained only from `Received:` headers, not from optional `x-` headers.
The bug in `get_mail_relays()` it that header type is not validated.
This headers will be catched too:
```
From: aaa[10.0.0.1] <noreply@example.org>
Reply-To: noreply@exam[10.0.0.1]ple.org
Subject: also [10.0.0.1] here
```

**Comment by stefaweb** [comment]
Good point!

**Comment by asuweb** [comment]
Yes, that is true.  - doh!

**Comment by asuweb** [comment]
that should make sense now!

**Comment by stefaweb** [comment]
With new code, in the header:

```
Received: from vimdzmsp-sfwd06.bluewin.ch ([195.186.227.133]:41410 helo=smtpauths.lb.bluewin.ch)
Received: from [192.168.1.115] ([128.90.20.16])
```

![capture d ecran 2017-03-09 a 19 22 58](https://cloud.githubusercontent.com/assets/12907102/23764463/e7c4a1bc-04fd-11e7-8d33-adb0136df419.png)

Not sure if normal to lost 192.168.1.115 in the GUI?

**Comment by asuweb** [comment]
Does that ip show up in the gui with the old code?

**Comment by stefaweb** [comment]
Yes, look screen shot at the start of the issue.

**Comment by asuweb** [comment]
There should be a "Received" line per relay host, so I would suggest that particular header is malformed.

But we can revert back to the previous regex if preferred:

 `preg_match_all('/Received.+\[(?P<ip>[\dabcdef.:]+)\]/', $header, $regs)`

**Comment by stefaweb** [comment]
No change in GUI with the last version.

May be more secure to use `if (preg_match_all('/Received:.+\[(?P<ip>.+)\]/', $header, $regs)) {` ?

**Comment by stefaweb** [comment]
I tried the last regex in PR with many messages. Seems ok.

**Comment by stefaweb** [comment]
Works fine. #631 can be merge.

**Comment by stefaweb** [comment]
Done.
