### ISSUE TITLE
PHP Notice:  Undefined offset: 1 in /var/www/mailscanner/functions.php on line 3619

### ISSUE THREAD

**Issue by rebirther** [mailwatch/1.2.0#627]
There is an error in the logs:
`PHP Notice: Undefined offset: 1 in /var/www/mailscanner/functions.php on line 3619`

I watched, but did not understand the problem.

**Comment by asuweb** [comment]
What version of Mailwatch?

**Comment by rebirther** [comment]
Version 1.2.0-rc.4

**Comment by asuweb** [comment]
Could you upgrade to 1.2.0-rc5 (master branch)?

The function which is giving that notice (`net_match()`) has been replaced in RC5

**Comment by rebirther** [comment]
Well, I'll try tomorrow.

**Comment by asuweb** [comment]
@rebirther - any update on this?

**Comment by rebirther** [comment]
Puzzled by another error, I forgot about this one.
Yes, in 1.2.0 RC5 the current error is missing.
