### ISSUE TITLE
New symbol for message listing?

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#629]
What do you think to change the symbol [#] used in message listing?

In functions.php line 2068

![capture d ecran 2017-03-10 a 14 50 29](https://cloud.githubusercontent.com/assets/12907102/23797633/1fa27890-05a1-11e7-92fc-17281b849841.png)

This one is `&#9989;`

![capture d ecran 2017-03-10 a 14 50 44](https://cloud.githubusercontent.com/assets/12907102/23797641/24eb0574-05a1-11e7-890b-fc5c5c53525a.png)

Plenty of HTML symbol here: https://www.w3schools.com/charsets/ref_utf_dingbats.asp

**Comment by asuweb** [comment]
HTML5 is not supported fully on older browsers.  Possibly better to use something like font awesome, for better compatibility.

My vote would be for: http://fontawesome.io/icon/info-circle/

**Comment by stefaweb** [comment]
Can we have color for `info-circle`?

**Comment by asuweb** [comment]
yes

**Comment by asuweb** [comment]
You can do anything with them that you can in normal css - like size, color etc

**Comment by stefaweb** [comment]
Ok for me. The "i" is easy to understand. You can do the change?

Just some lines before 2068 line, we have:

```
                case 'id2':
                    $fieldname[$f] = '#';
                    $orderable[$f] = false;
                    $align[$f] = 'center';
                    break;

```

Is this related to [#]?

**Comment by asuweb** [comment]
@stefaweb - is this ok for you now?

**Comment by stefaweb** [comment]
Yes, it works.

**Comment by stefaweb** [comment]
Works fine. #631 can be merge.

**Comment by stefaweb** [comment]
Done in #631.
