### ISSUE TITLE
Wrong character display in mailq.php

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#630]
I've found this.

When I display the Exim mailq in GUI, some Subject: are not well printed.

Look at the word `série` and `Frontière`. The `é` is replaced by a `?`.

![capture d ecran 2017-03-10 a 18 50 04](https://cloud.githubusercontent.com/assets/12907102/23806708/02476950-05c3-11e7-96e4-dd4ef113d70b.png)

But in detail.php, it's ok for the same ID.

![capture d ecran 2017-03-10 a 18 50 49](https://cloud.githubusercontent.com/assets/12907102/23807012/485d56d8-05c4-11e7-9e90-ff5ea04fd17b.png)

But not all Subject: are not well displayed in mailq.php. Some are ok.

![capture d ecran 2017-03-10 a 19 01 33](https://cloud.githubusercontent.com/assets/12907102/23806966/15a9f71e-05c4-11e7-9eb9-aa146e64d99a.png)

Crazy!

**Comment by stefaweb** [comment]
Found more.

Some Subject: are cut.

![capture d ecran 2017-03-10 a 19 09 48](https://cloud.githubusercontent.com/assets/12907102/23807212/3705a844-05c5-11e7-9bec-1d99d3c0902c.png)

`s medias dans l'école` is missing.

In detail.php, all is ok.

	TR: Programme - Lancement de la semaine de la presse et des medias dans l'école

**Comment by asuweb** [comment]
In detail.php the subject is converted to UTF8 by the function `getUTF8String` but not in mailq.php

**Comment by stefaweb** [comment]
In mailq.php, it use db_colorised_table() as in status.php, quarantine.php, rep_message_listing.php and rep_message_ops.php.

In mailq.php, the subject is cut and we have wrong characters but not in others .php files.

???

**Comment by stefaweb** [comment]
In db_colorised_table() 

```
                    case 'subject':
                        $row[$f] = htmlspecialchars(getUTF8String(decode_header($row[$f])));
                        if (SUBJECT_MAXLEN > 0) {
                            $row[$f] = trim_output($row[$f], SUBJECT_MAXLEN);
                        }
                        break;

```

Weird!

**Comment by stefaweb** [comment]
The problem is may be in mailwatch_sendmail_queue.php?

**Comment by asuweb** [comment]
Entirely possible, if the subjects being stored with the wrong / different encoding then that may well be the issue

**Comment by stefaweb** [comment]
No getUTF8String in mailwatch_sendmail_queue.php and many regex reading mailq files directly.

If you can have a look?

**Comment by stefaweb** [comment]
I've "N/A" to translate too?

**Comment by stefaweb** [comment]
Do we stay with "N/A" or can we replace this by "Not available"?

**Comment by asuweb** [comment]
Is N/A universally understood?

**Comment by stefaweb** [comment]
Not sure we can translate it.

`if ($output[$msgid]['lastattempttime'] !== 'N/A') {`

**Comment by Skywalker-11** [comment]
Couldn't we just set a default case or case for 'N/A' in switch at [https://github.com/mailwatch/1.2.0/blob/develop/mailscanner/functions.php#L1840](https://github.com/mailwatch/1.2.0/blob/develop/mailscanner/functions.php#L1840) and do the translation there?

**Comment by stefaweb** [comment]
What do you think of the fix in #634?

**Comment by stefaweb** [comment]
Fix does work for sender.

In mailq.php (From:): `=?utf-8?B?SMO2ZGwgU2FzY2hh?= <S.Hoedl@schoenher...`
In status.php (From:): `s.hoedl@schoenherr.eu`
In detail.php (header): `Hödl Sascha <S.Hoedl@schoenherr.eu>`
In detail.php (From:): s.hoedl@schoenherr.eu

I reverted back sender for the moment.

**Comment by stefaweb** [comment]
Fix don't work for subject. Some Subject become "empty".

**Comment by stefaweb** [comment]
I think that getUTF8String is not good for this job. We may be need the equivalent of fix_latin for php.

```
function getUTF8String($string)
{
    if (function_exists('mb_check_encoding')) {
        if (!mb_check_encoding($string, 'UTF-8')) {
            $string = mb_convert_encoding($string, 'UTF-8');
        }
    } else {
        if (!is_utf8($string)) {
            $string = utf8_encode($string);
        }
    }

    return $string;
}
```

**Comment by Skywalker-11** [comment]
We have to parse the part between `=?` and `?=` to get the correct charset/encoding [http://www.faqs.org/rfcs/rfc2047.html](http://www.faqs.org/rfcs/rfc2047.html) and decode that parts depending on it

**Comment by stefaweb** [comment]
I've found the problem for Subject "cut".

In header, the subject is on 2 lines.

```
Subject: 💘 Single or taken, we're go...
ééàçèù ééàçèù TITI
```

But the case, takes only the first line.

```
                                        case preg_match('/^\d{3}  Subject: (.+)$/', $line, $match):
                                            $output[$msgid]['subject'] = $match[1];
                                            break;
```

**Comment by stefaweb** [comment]
Hello!

Looking to solve this regex:

`case preg_match('/^\d{3}F .*: (.+)?<(.+)>$/', $line, $match):`

048F From: Postmaster <postmaster@domain.tld>
048F From: <postmaster@domain.tld>
048F From: postmaster@domain.tld

Doesn't work for the third case (048F From: postmaster@domain.tld)

**Comment by asuweb** [comment]
Can you post the actual data you're trying to match in a code block please?

**Comment by stefaweb** [comment]
Sorry, I forgot to quote the sample.

I want only the email (postmaster@domain.tld), without the rest. The problem is the third case.

**Comment by asuweb** [comment]
It's doens't work in the 3rd case at it's missing the `<...>`

**Comment by stefaweb** [comment]
I've also a problem with this one.

`preg_match('/^\d{3}  Subject: (.*)(\n\s+(.*))*/', $header, $match))`

It work in regex101.com but in real.

`128  Subject: =?UTF-8?B?8J+SmA==?= Single or taken, we're go...
 =?UTF-8?B?w6nDqcOgw6fDqMO5?= =?UTF-8?B?IMOpw6nDoMOnw6jDuQ==?=  TITI
`

If I remove `^\d{3}  `, it works but sometime it catch another Subject: in header. To be sure, I need to catch `128  ` too.

**Comment by stefaweb** [comment]
> It's doens't work in the 3rd case at it's missing the <...>

I know but sometime in real life, the <...> is missing.

**Comment by asuweb** [comment]
Yes, 

Try this: `^.*: <?(.*)>?$`

**Comment by asuweb** [comment]
Or this assuming you only want to match lines starting as they do in the example:

`^\d{3}. From: <?(.*@.*)>?$`

**Comment by stefaweb** [comment]
`^\d{3}. From: <?(.*@.*)>?$`

Not good.

![capture d ecran 2017-03-13 a 10 58 02](https://cloud.githubusercontent.com/assets/12907102/23849457/ff888468-07db-11e7-9737-bee812663c11.png)

**Comment by asuweb** [comment]
How about this:

`^\d{3}. From: <?(.*@.*)(>)?` then in the `$match` array, just fetch the first element?

**Comment by endelwar** [comment]
What about taking inspiration from perl `Exim-SpoolMessage`?
https://metacpan.org/source/KIRILLM/Exim-SpoolMessage-0.05/lib/Exim/SpoolMessage.pm

**Comment by stefaweb** [comment]
I solved almost all problem in last push except the problem with `From:` for this case:

`048F From: postmaster@domain.tld`

**Comment by stefaweb** [comment]
Very close.

`^\d{3}F .*: <?([\w.-]+@[\w.-]+)>?`

This time, the first one is not matched.

![capture d ecran 2017-03-13 a 13 25 07](https://cloud.githubusercontent.com/assets/12907102/23854203/a56f2328-07f0-11e7-8b73-e9c299a5f738.png)

**Comment by stefaweb** [comment]
Got it!

`^\d{3}F .*:(.+)? <?([0-9A-Za-z._-]+\@[0-9A-Za-z._-]+)>?$`

![capture d ecran 2017-03-13 a 13 39 31](https://cloud.githubusercontent.com/assets/12907102/23854640/8e3cae8a-07f2-11e7-8660-c8d49533c6d1.png)

**Comment by stefaweb** [comment]
Greeee!

I've this case too!

```
048F From: Postmaster
     <postmaster@domain.tld>
```

**Comment by stefaweb** [comment]
Not found a good regex to handle the fourth case. 
The bug with From: on 2 lines is present in dev version.

**Comment by stefaweb** [comment]
Some trouble with function decode_header().
Some Subject: are not well coded and cut.

The example come from a mailing list from a News Paper.

```

Subject cut:

121  Subject: =?Windows-1252?Q?Le_18h_actu_-_10_news_:_OGF_passe_sous_le_contr=F4le_d'O?=
 =?Windows-1252?Q?ntario_Teachers?=

Le 18h actu - 10 news : OGF passe sous le contr
 
Subject ok:

 110  Subject: =?UTF-8?Q?Le_18h_actu_-_10_news_:_OGF_passe_sous_le_contr=C3=B4le_d'Ontar?=
 =?UTF-8?Q?io_Teachers?=
 
Le 18h actu - 10 news : OGF passe sous le contrôle d'Ontario Teachers
```

**Comment by Skywalker-11** [comment]
Is it possible to identify a new header field by the index (eg. 048F) if yes we could read lines till we find the next identifier. Something like this (pseudo code).

```
$buffer ="";
while ($line = readline()) {
  if(startswith($line, $PATTERN)) {
      //do the switch case for $buffer here
      $buffer = $line;  
  } else {
      $buffer .= $line;
  }
}
```

**Comment by stefaweb** [comment]
This one is cut too.

```
In header:
Subject: DSIJ : envoi d'accusé(s) de réception logique

GUI:
Subject: DSIJ : envoi d
```

I've to find something better than decode_header() to decode the Subject:.

**Comment by stefaweb** [comment]
> The bug with `From:` on 2 lines is present in dev version.

I solved the problem with 2 cases. On for "mono" line, one for multiline.

**Comment by stefaweb** [comment]
Need help.

When I use the function: `$output[$msgid]['subject'] = mb_decode_mimeheader($output[$msgid]['subject']);`

I got: `Eternelle,_le_bouquet_inspiré_du_film_La_Belle_et_La_Bête`

Why the function, generate "_"?

Original text in header: `Eternelle, le bouquet inspiré du film La Belle et La Bête`

Also, the PHP doc is not clear if windows-1256 is supported by mb_decode_mimeheader().

Another solution is to use imap_mime_header_decode() but php5-imap module is needed.

**Comment by asuweb** [comment]
Is it worth fixing?  This only displays mail in the active mail queue, so is only of use to sys admins, and then they're likely only really interested in SMTP message / error, rather than mail subject.  

mime_header_decode was discussed in another thread somewhere (PEAR module replacement), but penciled for V2

**Comment by asuweb** [comment]
Incidentally, in the mailq for postfix, we don't even display the subject, just message ID and SMTP error if any

**Comment by stefaweb** [comment]
We have more on Exim. Useful to have all stuff and well printed. We can also go to detail.php fi needed.

I will let it run for a while but I think I finally found a solution to all the problems (without using mime_header_decode).

ingoing queue:
![capture d ecran 2017-03-15 a 11 39 46](https://cloud.githubusercontent.com/assets/12907102/23944791/62124378-0974-11e7-917d-219998b7e7b8.png)

outgoing queue:
![capture d ecran 2017-03-15 a 11 40 07](https://cloud.githubusercontent.com/assets/12907102/23944815/7d92c852-0974-11e7-839a-815ed3cb443c.png)

**Comment by stefaweb** [comment]
Found a new case completely crazy and not manageable.
```
128  Subject: 
Single 
or taken, 
we're go...
```
Another solution would be to get the Subject in the mailog table with a SQL query instead of header but I stop there because I already spent enough time over it.

The current code seems to works fine with all the other cases that I have listed.

**Comment by stefaweb** [comment]
Works fine. #634 can be merge.

**Comment by stefaweb** [comment]
The curent regex to catch all line of Subject: is `/Subject: (.*)(\n\s+(.*))*/im`

Does someone have an idea how to manage this case:

No space on secondary lines.

```
038  Date: Sun, 12 Mar 2017 17:21:39 +0100
128  Subject:  Single 
or taken, 
we're go...
048F From: User <user@domain.tld>
```

General case are like this:

With at minimum one space on each secondary line.

```
128  Subject: =?UTF-8?B?8J+SmA==?= Single or taken, we're go...
      =?UTF-8?B?w6nDqcOgw6fDqMO5?= =?UTF-8?B?IMOpw6nDoMOnw6jDuQ==?=
       more subject...
```

**Comment by Skywalker-11** [comment]
May test if the the first word on that line does not end with a colon?

**Comment by stefaweb** [comment]
I'm trying this but not works.

`/Subject: .*(?=(\d{3}([A-Z] |  )))/s`

I'm trying to define as stop the next 3 digit with one [A-Z] and a space OR 2 spaces without success.

![capture d ecran 2017-03-17 a 16 46 17](https://cloud.githubusercontent.com/assets/12907102/24051444/5f6b26e8-0b32-11e7-80f1-4f33d84afcd6.png)

If I do this to try, it work.

`/Subject: .*(?=\d{3}F)/s`

![ddd](https://cloud.githubusercontent.com/assets/12907102/24051433/5ae3afc8-0b32-11e7-924a-79b1fbc927f8.png)

**Comment by Skywalker-11** [comment]
How about `/Subject: (.*(?=\d{3}[A-Z]?[ ]+(\w|[-])+:))/sU` the U will force a stop after first match

It will search after `Subject` for a combination of 3 digits, 0-1 capital letter followed by 1-* whitespaces and a word (`(\w|[-])+` -> containing letter,number,underscore or `-`) followed by a colon

**Comment by Skywalker-11** [comment]
Problem is that it will not work if Subject is last Header. This fixes that
`Subject: (.*(?=((\d{3}[A-Z]?[ ]+(\w|[-])+:.*)|(\s*\z))))`

**Comment by stefaweb** [comment]
Tried: `/Subject: (.*(?=((\d{3}[A-Z]?[ ]+(\w|[-])+:.*)|(\s*\z))))/sUi`

No bad at all.

I added `/i` (insensitive) as sometime we have `SUBJECT:`

I'm going to test it the code.

**Comment by stefaweb** [comment]
One more.
imap_mime_header_decod() is much better than mb_decode_mimeheader(). Close to 100% of right decoding of Subject. I had 10% of wrong decoding with mb_decode_mimeheader().

**Comment by stefaweb** [comment]
Found a bug.

A space was added or not removed.

![capture d ecran 2017-03-18 a 18 37 08](https://cloud.githubusercontent.com/assets/12907102/24074493/241eb004-0c0a-11e7-9257-f2dd1e1da7f1.png)

Original header:

```
Reply-To: "easyJet" <easyjet@email.easyjet.com>
Subject: Votre réservation ERWQ8FP : Yoel, re
     cevez des informations en temps réel sur les
      vols vers Paris Charles de Gaulle
Feedback-ID: 51144:11717625:oraclersys
```

**Comment by stefaweb** [comment]
This case doesn't work with regex.

```
159  Subject:
=?UTF-8?B?MSBub3V2ZWxsZSBvZmZyZSBkJ2VtcGxvaSBHYXJkZSBww6lyaXNjb2xhaXJlIMOgIFNhbG9uLWRlLVByb3ZlbmNlIChldCAyMCBrbSBhdXRvdXIpLCA3IGRlcm5pZXJzIGpvdXJz?=MCBrbSBhdXRvdXIpLCA3IGRlcm5pZXJzIGpvdXJz?=
038  Date: Sun, 19 Mar 2017 09:58:47 +0100
```

**Comment by Skywalker-11** [comment]
Problem is that there is no space after Subject:

works with `/Subject:(.*(?=((\d{3}[A-Z]?[ ]+(\w|[-])+:.*)|(\s*\z))))/sUi`

**Comment by stefaweb** [comment]
Thanks you. In test.

I again modified the code. I think that I finally solved the problem with "iconv() detected an incomplete multibyte character in input string".

It long to test. I've to wait for the "right" message and look in all the trap I've put in the dev code...

**Comment by stefaweb** [comment]
Not good. I replaced your  last the regex for From: and Subject:.

![capture d ecran 2017-03-19 a 14 45 07](https://cloud.githubusercontent.com/assets/12907102/24081415/353713dc-0cb3-11e7-9fdc-289282e93b44.png)

The regex capture this kind of string.

`Content-Transfer-Encoding:To:Content-Type:From:Mime-Version:List-Unsubscribe:List-Id:Message-Id:Date; i=newsletter@newsletter-verychic.com; bh=jn466O+KxXYY7HgNLW6OPAmIux4=; b=XMXcaxcL7rnxF9C+SVX7N3G1KvI8fEiNz7omZoT2ab5TTVx1djBYH0KyOy+W8oxyA6jkIlKh76nj XZK8hqj8Fu44Uqg40eiaVpEQICe84RhfEOZecyWRLlkqYCyOhuf0rWHPjHgH08jGtg0TxR0Q7tcw u38B3Q+N5+k9PyTYKGo=`

Go back to: `/Subject: (.*(?=((\d{3}[A-Z]?[ ]+(\w|[-])+:.*)|(\s*\z))))/sUi`

**Comment by stefaweb** [comment]
I added code to get the From: address an print it in the GUI when we have bounce message (without evelopesender).

![capture d ecran 2017-03-19 a 15 51 23](https://cloud.githubusercontent.com/assets/12907102/24082022/10eb3984-0cbf-11e7-9a83-07c374fea231.png)

It will be nice to have this feature in status.php.

**Comment by stefaweb** [comment]
> Problem is that there is no space after Subject:

Seems to work better with space or LF. We use in group2.

`/Subject:([ ]|\n)(.*(?=((\d{3}[A-Z]?[ ]+(\w|[-])+:.*)|(\s*\z))))/sUi`

**Comment by stefaweb** [comment]
I finally got the mail which cause iconv() crash. It alway come from the same sender. A well know News paper in France...

```
Notice: iconv(): Detected an incomplete multibyte character in input string in /var/www/html/mailscanner/functions.php on line 1026
---------
Use iconv
charset: utf-8
text: [Check-list] Attaque d’Orly : l�
iconv convLine NOT decoded: [Check-list] Attaque d’Orly : l�
*********
1cprHp-00074R-BD-H
Debian-exim 104 109
<lemonde@info.lemonde.fr>
...
033  Date: 20 Mar 2017 06:59:25 +0000
350  Subject: =?utf-8?B?W0NoZWNrLWxpc3RdwqBBdHRhcXVlIGTigJlPcmx5IDogbOKA?=
=?utf-8?B?mWFzc2FpbGxhbnQgZHJvZ3XDqSBldCBzYW91bCAtwqBGYWNlIMOgIGzi?=
=?utf-8?B?gJlFdXJvcGUsIGxhIGNyb2lzYWRlIGRlIFJlY2VwIFRheXlpcCBFcmRv?=
=?utf-8?B?Z2FuIC3CoMKrIE5vdXMgZGV2b25zIGFkbWV0dHJlIHF1ZSBsYSBDb3LD?=
=?utf-8?B?qWUgZHUgTm9yZCBlc3QgdW5lIHB1aXNzYW5jZSBudWNsw6lhaXJlIMK7?=
104  Content-Type: multipart/alternative;
```

**Comment by stefaweb** [comment]
May I use safety "@" in front of iconv to ovoid the notice?

$textdecoded = @iconv(strtoupper($linePartArr[$j]->charset), 'UTF-8//TRANSLIT//IGNORE', $linePartArr[$j]->text);

**Comment by stefaweb** [comment]
ok merged
