### ISSUE TITLE
upgrade.php index warning

### ISSUE THREAD

**Issue by shawniverson** [mailwatch/1.2.0#637]
```
 - Adding missing index `subject_idx` on table `maillog`.............. WARNING
*** ERROR/WARNING SUMMARY ***
MySQL version unsupported for index `subject_idx` on table `maillog`, upgrade to version >= 50604 (you have version 50505)
```

Using MariaDB 10.1 (upgraded from mysql 5.1 via MariaDB 5.5).

Don't see any obvious issues, but not sure if this message is benign or not.  This is a server with a long-running instance of MailWatch that has been around a while on CentOS 6.8.

**Comment by endelwar** [comment]
MariaDB is lying about its MySLQ version compatibility: the backported 5.6 MySQL's innodb fulltext index in MariaDB 10.0.5 but they didn't change the `server_version` compatibility string (still 5.5.5).

If your MariaDB version is greater that 10.0.5 it's safe to add the fulltext index on `maillog`.`subject`

**Comment by shawniverson** [comment]
I suspected that, but wasn't sure 👍
