### ISSUE TITLE
Use of undefined constant VIRUS_REGEX

### ISSUE THREAD

**Issue by kingmilo** [mailwatch/1.2.0#641]
Some might come across this error in their apache error log file complaining about _undefined constant and preg_match()_ in **functions.php** (line 1112), and **rep_top_viruses.php** (line 75). This code seems to be a duplicate too just fyi.

The current line of code is as follows:
`if (preg_match(VIRUS_REGEX, $row->report, $virus_reports)) {`

and needs to be changed to include '//' as follows:
`if (preg_match('/VIRUS_REGEX/', $row->report, $virus_reports)) {`

**Comment by asuweb** [comment]
Can you update to RC5? (latest master branch).

This issue has been fixed previously.

**Comment by kingmilo** [comment]
Yes of course, I had a look around but couldn't find mention of it - thanks.
