### ISSUE TITLE
Why are messages quarantined again when I release them in MailWatch?

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#644]
Hello!

May be a problem (or a miss use from me).

When I release a message with dangerous content (in admin or admin-domain mode), the message is released but is again blocked by MS (red).

The message is blocked by a MS rule (in archives.filename.rules.conf). The only way to have the message delivered is to inactivate this rule.

**Comment by shawniverson** [comment]
Whitelist 127.0.0.1 :P  see http://docs.mailwatch.org/using/faq.html  and adapt to archives.filename.rules.conf <3

**Comment by stefaweb** [comment]
Hi @shawniverson!

I completely forgot to set up this when I rebuild my prod server from scratch.
Seems with MailScanner 5.x, the files name changed. FAQ need to be updated.

Now we have as default:

```
/etc/MailScanner/archives.filename.rules.conf
/etc/MailScanner/archives.filetype.rules.conf
/etc/MailScanner/filename.rules.conf
/etc/MailScanner/filetype.rules.conf
/etc/MailScanner/rules/bounce.rules
/etc/MailScanner/rules/max.message.size.rules
```

It's no clear what we need to do?

**Comment by stefaweb** [comment]
When we setup `/etc/MailScanner/filename.rules.allowall.conf`, we got:

Possible syntax error on line 2 of /etc/MailScanner/filename.rules.allowall.conf

When we setup `/etc/MailScanner/filetype.rules.allowall.conf`, we got:

Possible syntax error on line 2 of /etc/MailScanner/filetype.rules.allowall.conf

with `allow   .*      -       -` on line 2.

**Comment by endelwar** [comment]
specified path and actions on https://github.com/mailwatch/mailwatch-docs/commit/e280e62c30938e204d2e82b6e6d7615feb6c4f0a
