### ISSUE TITLE
Bug with 00MailWatchConf.pm

### ISSUE THREAD

**Issue by asuweb** [mailwatch/1.2.0#647]
There seems to be a bug with naming convention for this file.

On my production system using 00MailWatchConf.pm produces the errors below.

Renaming the file to MailWatchConf.pm solves this.

```
Could not use Custom Function code /usr/share/MailScanner/perl/custom/SQLBlackWhiteList.pm, it could not be "require"d. Make sure the last line is "1;" and the module is correct with perl -wc (Error: Undefined subroutine &MailScanner::CustomConfig::mailwatch_get_db_name called at /usr/share/MailScanner/perl/custom/SQLBlackWhiteList.pm line 60.
Compilation failed in require at /usr/share/MailScanner/perl/MailScanner/Config.pm line 752.
) at /usr/share/MailScanner/perl/MailScanner/Config.pm line 754
Could not use Custom Function code /usr/share/MailScanner/perl/custom/MailWatch.pm, it could not be "require"d. Make sure the last line is "1;" and the module is correct with perl -wc (Error: Undefined subroutine &MailScanner::CustomConfig::mailwatch_get_db_name called at /usr/share/MailScanner/perl/custom/MailWatch.pm line 69.
Compilation failed in require at /usr/share/MailScanner/perl/MailScanner/Config.pm line 752.
) at /usr/share/MailScanner/perl/MailScanner/Config.pm line 754
Could not use Custom Function code /usr/share/MailScanner/perl/custom/SQLSpamSettings.pm, it could not be "require"d. Make sure the last line is "1;" and the module is correct with perl -wc (Error: Undefined subroutine &MailScanner::CustomConfig::mailwatch_get_db_name called at /usr/share/MailScanner/perl/custom/SQLSpamSettings.pm line 63.
Compilation failed in require at /usr/share/MailScanner/perl/MailScanner/Config.pm line 752.
) at /usr/share/MailScanner/perl/MailScanner/Config.pm line 754
```

**Comment by stefaweb** [comment]
Are you sure?

Works fine here (with MS 5).

See this issue too: #615

We already changed MailWatch-DB.pm -> 00-MailWatch-Conf.pm -> 00MailWatchConf.pm

I'm starting to think that the problem is more complex than just the name.

**Comment by Skywalker-11** [comment]
Have you tried to use MailScanner  in version 5.0.4-4? I had the same problem and that fixed it for me. 
Here are the links to the packages [https://github.com/mailwatch/1.2.0/issues/510](https://github.com/mailwatch/1.2.0/issues/510)

**Comment by asuweb** [comment]
Yes, I've been using 5.0.4-4 since it first came out

**Comment by asuweb** [comment]
I can't remember why we went for 00Mai... in the end?

**Comment by stefaweb** [comment]
Version prior to 5.0.4 don't le "-" in the name.

**Comment by asuweb** [comment]
Yes, I get that, but why `00MailWatchConf.pm` and not `MailWatchConf.pm`?

**Comment by stefaweb** [comment]
To be sure that 00MailWatchConf.pm is read before the other files (due to the includes).

**Comment by stefaweb** [comment]
Look a the comment from @Skywalker-11 !

`Not sure what caused it but the error suddenly is gone even with the 5.0.3 version.
`

**Comment by asuweb** [comment]
Yes, but it's included by the require statement, so it will be fetched when needed.  It doesn't even need to be in the `/etc/MailScanner/custom/` directory - it can be anywhere.

**Comment by stefaweb** [comment]
I've no problem to change the name again but I'm pretty sure that the problem is somewhere else. See the comment from @Skywalker-11.

**Comment by asuweb** [comment]
It's possibly perl version related, in which case we may never find a happy medium for the naming conventions, but I'm not sure what addition of 00 solves, as it'll be parsed as needed when first called by the relevant script.

**Comment by stefaweb** [comment]
I never add the problem (Debian 8 uptodate) BUT @Skywalker-11 add the problem with the same server version, and suddenly the problem was gone.

It smells like a bug somewhere in Perl codes. May be related to internal variable crashing which stay broken or with a wrong statut somewhere.

**Comment by stefaweb** [comment]
What do we do with this?
If you prefer change again the name, go and add the PR.

**Comment by Fonant** [comment]
00MailWatchConf.pm doesn't seem to work for me, either, on CentOS 6.8 with MailScanner 4.85.2

```
This is CentOS release 6.8 (Final)
This is Perl version 5.010001 (5.10.1)

This is MailScanner version 4.85.2
Module versions are:
1.00    AnyDBM_File
1.30    Archive::Zip
0.23    bignum
1.36    Carp
2.021   Compress::Zlib
1.119   Convert::BinHex
0.18    Convert::TNEF
2.124   Data::Dumper
2.27    Date::Parse
1.03    DirHandle
1.06    Fcntl
2.77    File::Basename
2.14    File::Copy
2.02    FileHandle
2.08    File::Path
0.22    File::Temp
0.92    Filesys::Df
3.64    HTML::Entities
3.64    HTML::Parser
3.57    HTML::TokeParser
1.25    IO
1.14    IO::File
1.13    IO::Pipe
2.04    Mail::Header
1.999703        Math::BigInt
0.22    Math::BigRat
3.08    MIME::Base64
5.427   MIME::Decoder
5.427   MIME::Decoder::UU
5.427   MIME::Head
5.427   MIME::Parser
3.08    MIME::QuotedPrint
5.427   MIME::Tools
0.18    Net::CIDR
1.25    Net::IP
0.19    OLE::Storage_Lite
1.04    Pod::Escapes
3.13    Pod::Simple
1.17    POSIX
1.46    Scalar::Util
1.82    Socket
2.20    Storable
1.4     Sys::Hostname::Long
0.27    Sys::Syslog
1.40    Test::Pod
1.302059        Test::Simple
1.9721  Time::HiRes
1.02    Time::localtime

Optional module versions are:
1.58    Archive::Tar
0.23    bignum
2.09    Business::ISBN
20140910.002    Business::ISBN::Data
1.23    Data::Dump
1.82    DB_File
1.27    DBD::SQLite
1.609   DBI
1.16    Digest
1.01    Digest::HMAC
2.39    Digest::MD5
2.12    Digest::SHA1
1.01    Encode::Detect
0.17015 Error
0.280205        ExtUtils::CBuilder
2.2203  ExtUtils::ParseXS
2.38    Getopt::Long
0.80    Inline
1.08    IO::String
1.09    IO::Zlib
2.28    IP::Country
missing Mail::ClamAV
3.004001        Mail::SpamAssassin
v2.008  Mail::SPF
1.999001        Mail::SPF::Query
0.4003  Module::Build
0.21    Net::CIDR::Lite
0.65    Net::DNS
v0.003  Net::DNS::Resolver::Programmable
0.65    Net::LDAP
 4.027  NetAddr::IP
1.967012        Parse::RecDescent
missing SAVI
3.17    Test::Harness
2.02    Test::Manifest
2.0.0   Text::Balanced
1.40    URI
0.9901  version
1.13    YAML
```

I've worked around the problem by declaring the DB connection variables directly in MailWatch.pm.

**Comment by asuweb** [comment]
@Fonant - can you check if PR #653 fixes this ?

**Comment by Fonant** [comment]
I've done some more digging, and found this error:

`Mar 20 20:47:00 gus MailScanner[9410]: Could not use Custom Function code /usr/lib/MailScanner/MailScanner/CustomFunctions/MailWatch.pm, it could not be "require"d. Make sure the last line is "1;" and the module is correct with perl -wc (Error: Undefined subroutine &MailScanner::CustomConfig::mailwatch_get_db_name called at /usr/lib/MailScanner/MailScanner/CustomFunctions/MailWatch.pm line 69.`

I don't know Perl, but guessed that the 00MailWatch.pm file needed this line near the top:

`package MailScanner::CustomConfig;`

and it now works :)

**Comment by shawniverson** [comment]
I confirm the same issue, it appears immediately after commit d03090e943ad0c8ed00857b4ceb4b3234f007265 for me.  Adding the package clears the problem.

**Comment by stefaweb** [comment]
> arbitrarily loading the files in different order 

If true, we can stay with "MailWatchConf.pm". No need to add the "00".

**Comment by stefaweb** [comment]
We may be have this to add this too.

```
use strict 'vars';
use strict 'refs';
no  strict 'subs'; # Allow bare words for parameter %'s

use vars qw($VERSION);

### The package version, both in 1.23 style *and* usable by MakeMaker:
$VERSION = substr q$Revision: 1.5 $, 10;

```

**Comment by asuweb** [comment]
> I suspect that MailScanner is arbitrarily loading the files in different order and expects the package to be present in the first one.

That would possibly make sense and explain why it works for some but not others.

@stefaweb - What would the other bits do?  (I'm not a perl person)

**Comment by stefaweb** [comment]
It seems that MailScanner need to have $VERSION in custom .pm files. I don't know the reason. I discovered that when I cleaned the pm files in February.

**Comment by stefaweb** [comment]
Who do the PR?

**Comment by asuweb** [comment]
You can

**Comment by stefaweb** [comment]
#672

I removed `#!/usr/bin/perl` as no present in others .pm files.

**Comment by endelwar** [comment]
just adding `package MailScanner::CustomConfig;` fixed the issue on one of my test server (debian 7/postfix/mailscanner 4.86.1)
