### ISSUE TITLE
About db_clean.php

### ISSUE THREAD

**Issue by Lichengchang** [mailwatch/1.2.0#655]
An error occurred after execution：
Warning: mysqli::mysqli(): Headers and client library minor version mismatch. Headers:50173 Library:50312 in /var/www/html/mailscanner/database.php on line 51

mysqli version：
![mg1](https://cloud.githubusercontent.com/assets/25293877/24134196/8e35e7fc-0e3d-11e7-902b-2638c7723f08.png)

Should anyone come up with any ideas I would appreciate.
Thank you.

**Comment by asuweb** [comment]
@Lichengchang - What php extension are you using for mysql? Try changing it to php-mysqlnd, which should fix the issue

**Comment by Lichengchang** [comment]
@asuweb - Thanks for your valuable suggestion.
I try to recompile php.

**Comment by Lichengchang** [comment]
@asuweb - The question has been settled. Thank you for your kind assistance.
