### ISSUE TITLE
upgrading.php Fatal error 

### ISSUE THREAD

**Issue by branko77** [mailwatch/1.2.0#660]
I just tried upgrade to 1.2.0, followed UPGRADE instruction and after tried php upgrade.php I got following error:
Fatal error: Uncaught exception 'mysqli_sql_exception' with message 'Specified key was too long; max key length is 767 bytes' in /root/1.2.0-1.2.0/upgrade.php:82
Stack trace:
#0 /root/1.2.0-1.2.0/upgrade.php(82): mysqli->query('ALTER TABLE `ma...')

#1 /root/1.2.0-1.2.0/upgrade.php(547): executeQuery('ALTER TABLE `ma...')
#2 {main}
  thrown in /root/1.2.0-1.2.0/upgrade.php on line 82

My whole upgrade log is as follows:

Have you done a full backup of your database? Type 'yes' to continue: yes

Testing connectivity to the database ................................. OK

Updating database schema:

 - Convert database to utf8........................................... ALREADY DONE

 - Drop `geoip_country` table......................................... ALREADY DROPPED
 - Drop `spamscores` table............................................ ALREADY DROPPED
 - Add autorelease table to `mailscanner` database.................... ALREADY EXIST
 - Add resetid, resetexpire and lastreset fields in `users` table..... ALREADY EXIST

 - Fix schema for username field in `audit_log` table................. OK
 - Fix schema for id field in `blacklist` table....................... OK
 - Fix schema for username field in `users` table..................... OK
 - Fix schema for spamscore field in `users` table.................... OK
 - Fix schema for highspamscore field in `users` table................ OK
 - Fix schema for username field in `user_filters` table.............. OK
 - Fix schema for username field in `whitelist` table................. OK
 - Fix schema for username field in `audit_log` table................. OK
 - Fix schema for password field in `users` table..................... OK
 - Fix schema for fullname field in `users` table..................... OK
 - Fix schema for rule_desc field in `mcp_rules` table................ OK

 - Add id field and primary key to `audit_log` table.................. ALREADY DONE
 - Add inq_id field and primary key to `inq` table.................... ALREADY DONE
 - Add maillog_id field and primary key to `maillog` table............ ALREADY DONE
 - Add mtalog_id field and primary key to `mtalog` table.............. ALREADY DONE
 - Add mtalog_id field and primary key to `outq` table................ ALREADY DONE
 - Add id field and primary key to `saved_filters` table.............. ALREADY DONE
 - Add mtalog_id field and primary key to `user_filters` table........ ALREADY DONE

 - Convert database to utf8mb4........................................ ALREADY DONE

 - Convert table `audit_log` to utf8mb4............................... ALREADY CONVERTED
 - Convert table `autorelease` to utf8mb4............................. ALREADY CONVERTED
 - Convert table `blacklist` to utf8mb4............................... ALREADY CONVERTED
 - Convert table `inq` to utf8mb4..................................... ALREADY CONVERTED
 - Convert table `maillog` to utf8mb4................................. ALREADY CONVERTED
 - Convert table `mcp_rules` to utf8mb4............................... ALREADY CONVERTED
 - Convert table `mtalog` to utf8mb4.................................. ALREADY CONVERTED
 - Convert table `mtalog_ids` to utf8mb4.............................. ALREADY CONVERTED
 - Convert table `outq` to utf8mb4.................................... ALREADY CONVERTED
 - Convert table `saved_filters` to utf8mb4........................... ALREADY CONVERTED
 - Convert table `sa_rules` to utf8mb4................................ ALREADY CONVERTED
 - Convert table `users` to utf8mb4................................... ALREADY CONVERTED
 - Convert table `user_filters` to utf8mb4............................ ALREADY CONVERTED
 - Convert table `whitelist` to utf8mb4............................... ALREADY CONVERTED

 - Convert table `audit_log` to InnoDB................................ ALREADY CONVERTED
 - Convert table `autorelease` to InnoDB.............................. ALREADY CONVERTED
 - Convert table `blacklist` to InnoDB................................ ALREADY CONVERTED
 - Convert table `inq` to InnoDB...................................... ALREADY CONVERTED
 - Convert table `maillog` to InnoDB..................................
Fatal error: Uncaught exception 'mysqli_sql_exception' with message 'Specified key was too long; max key length is 767 bytes' in /root/1.2.0-1.2.0/upgrade.php:82
Stack trace:
#0 /root/1.2.0-1.2.0/upgrade.php(82): mysqli->query('ALTER TABLE `ma...')

#1 /root/1.2.0-1.2.0/upgrade.php(547): executeQuery('ALTER TABLE `ma...')
#2 {main}
  thrown in /root/1.2.0-1.2.0/upgrade.php on line 82

Any help with this?

**Comment by stefaweb** [comment]
Could you indicate sql engine name and version?

**Comment by branko77** [comment]
Thanks for replay 

mysql  Ver 14.14 Distrib 5.6.35, for Linux (x86_64) using  EditLine wrapper

**Comment by Skywalker-11** [comment]
can you query  `use mailscanner; show create table maillog;` in mysql?

**Comment by branko77** [comment]
this is result:

CREATE TABLE `maillog` (
 `timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 `id` mediumtext COLLATE utf8mb4_unicode_ci,
 `size` bigint(20) DEFAULT '0',
 `from_address` mediumtext COLLATE utf8mb4_unicode_ci,
 `from_domain` mediumtext COLLATE utf8mb4_unicode_ci,
 `to_address` mediumtext COLLATE utf8mb4_unicode_ci,
 `to_domain` mediumtext COLLATE utf8mb4_unicode_ci,
 `subject` mediumtext COLLATE utf8mb4_unicode_ci,
 `clientip` mediumtext COLLATE utf8mb4_unicode_ci,
 `archive` mediumtext COLLATE utf8mb4_unicode_ci,
 `isspam` tinyint(1) DEFAULT '0',
 `ishighspam` tinyint(1) DEFAULT '0',
 `issaspam` tinyint(1) DEFAULT '0',
 `isrblspam` tinyint(1) DEFAULT '0',
 `isfp` tinyint(1) DEFAULT '0',
 `isfn` tinyint(1) DEFAULT '0',
 `spamwhitelisted` tinyint(1) DEFAULT '0',
 `spamblacklisted` tinyint(1) DEFAULT '0',
 `sascore` decimal(7,2) DEFAULT '0.00',
 `spamreport` mediumtext COLLATE utf8mb4_unicode_ci,
 `virusinfected` tinyint(1) DEFAULT '0',
 `nameinfected` tinyint(1) DEFAULT '0',
 `otherinfected` tinyint(1) DEFAULT '0',
 `report` mediumtext COLLATE utf8mb4_unicode_ci,
 `ismcp` tinyint(1) DEFAULT '0',
 `ishighmcp` tinyint(1) DEFAULT '0',
 `issamcp` tinyint(1) DEFAULT '0',
 `mcpwhitelisted` tinyint(1) DEFAULT '0',
 `mcpblacklisted` tinyint(1) DEFAULT '0',
 `mcpsascore` decimal(7,2) DEFAULT '0.00',
 `mcpreport` mediumtext COLLATE utf8mb4_unicode_ci,
 `hostname` mediumtext COLLATE utf8mb4_unicode_ci,
 `date` date DEFAULT NULL,
 `time` time DEFAULT NULL,
 `headers` mediumtext COLLATE utf8mb4_unicode_ci,
 `quarantined` tinyint(1) DEFAULT '0',
 `maillog_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
 PRIMARY KEY (`maillog_id`),
 KEY `maillog_datetime_idx` (`date`,`time`),
 KEY `maillog_id_idx` (`id`(20)),
 KEY `maillog_clientip_idx` (`clientip`(20)),
 KEY `maillog_from_idx` (`from_address`(200)),
 KEY `maillog_to_idx` (`to_address`(200)),
 KEY `maillog_host` (`hostname`(30)),
 KEY `from_domain_idx` (`from_domain`(50)),
 KEY `to_domain_idx` (`to_domain`(50)),
 KEY `maillog_quarantined` (`quarantined`),
 KEY `timestamp_idx` (`timestamp`)
) ENGINE=MyISAM AUTO_INCREMENT=48863 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci

**Comment by endelwar** [comment]
@branko77 could you try upgrade.php script from develop branch? I've moved the fat indexes dropping before converting tables to innodb.

**Comment by branko77** [comment]
@endelwar where I can find develop branch?

**Comment by branko77** [comment]
Ok I found it

**Comment by branko77** [comment]
When I try upgrade.php script from develop branch I just get that script printed on the screen

**Comment by Skywalker-11** [comment]
@branko77 did you called that file from command line?

**Comment by stefaweb** [comment]
I tried it on my dev server from shell. Works.

**Comment by branko77** [comment]
I did it from cli.
made chmod 775 and after that tried with `php upgrade.php`
I tried several times but always get file printed on the screen

**Comment by stefaweb** [comment]
and just "./upgrade.php"?

**Comment by branko77** [comment]
When I try that I get:
./upgrade.php: line 7: syntax error near unexpected token `newline'
./upgrade.php: line 7: `<!DOCTYPE html>'

**Comment by stefaweb** [comment]
Line 7 ?
Its in the comment!
` * Copyright (C) 2011  Garrod Alwood (garrod.alwood@lorodoes.com)`

**Comment by branko77** [comment]
no, it is `<!DOCTYPE html>`
Are we using the same script?
I downloaded it from https://github.com/mailwatch/1.2.0/blob/develop/upgrade.php

**Comment by stefaweb** [comment]
This page in develop do not have `<!DOCTYPE html>`!

https://github.com/mailwatch/1.2.0/blob/develop/upgrade.php

**Comment by branko77** [comment]
Sorry, maybe I did some mistake during changing of the script.
I just downloaded it again and started it.
Now it does more but I got this error:

Checking conf.php configuration entry:
Fatal error: Call to undefined function checkConfVariables() in /root/1.2.0-1.2.0/upgrade.php on line 568

**Comment by branko77** [comment]
Whole log is as follows:

php upgrade.php

MailWatch for MailScanner Database Upgrade to 1.2.0 - RC4

Have you done a full backup of your database? Type 'yes' to continue: yes

Testing connectivity to the database ................................. OK

Updating database schema:

 - Convert database to utf8........................................... ALREADY DONE

 - Drop `geoip_country` table......................................... ALREADY DROPPED
 - Drop `spamscores` table............................................ ALREADY DROPPED
 - Add autorelease table to `mailscanner` database.................... ALREADY EXIST
 - Add resetid, resetexpire and lastreset fields in `users` table..... ALREADY EXIST

 - Fix schema for username field in `audit_log` table................. OK
 - Fix schema for id field in `blacklist` table....................... OK
 - Fix schema for username field in `users` table..................... OK
 - Fix schema for spamscore field in `users` table.................... OK
 - Fix schema for highspamscore field in `users` table................ OK
 - Fix schema for username field in `user_filters` table.............. OK
 - Fix schema for username field in `whitelist` table................. OK
 - Fix schema for username field in `audit_log` table................. OK
 - Fix schema for password field in `users` table..................... OK
 - Fix schema for fullname field in `users` table..................... OK
 - Fix schema for rule_desc field in `mcp_rules` table................ OK

 - Add id field and primary key to `audit_log` table.................. ALREADY DONE
 - Add inq_id field and primary key to `inq` table.................... ALREADY DONE
 - Add maillog_id field, rblspamreport and primary key to `maillog` table ALREADY DONE
 - Add rblspamreport field to `maillog` table......................... OK
 - Add mtalog_id field and primary key to `mtalog` table.............. ALREADY DONE
 - Add mtalog_id field and primary key to `outq` table................ ALREADY DONE
 - Add id field and primary key to `saved_filters` table.............. ALREADY DONE
 - Add mtalog_id field and primary key to `user_filters` table........ ALREADY DONE

 - Dropping too big index `maillog_from_idx` on table `maillog`....... OK
 - Dropping too big index `maillog_to_idx` on table `maillog`......... OK

 - Convert database to utf8mb4........................................ ALREADY DONE

 - Convert table `audit_log` to utf8mb4............................... ALREADY CONVERTED
 - Convert table `autorelease` to utf8mb4............................. ALREADY CONVERTED
 - Convert table `blacklist` to utf8mb4............................... ALREADY CONVERTED
 - Convert table `inq` to utf8mb4..................................... ALREADY CONVERTED
 - Convert table `maillog` to utf8mb4................................. ALREADY CONVERTED
 - Convert table `mcp_rules` to utf8mb4............................... ALREADY CONVERTED
 - Convert table `mtalog` to utf8mb4.................................. ALREADY CONVERTED
 - Convert table `mtalog_ids` to utf8mb4.............................. ALREADY CONVERTED
 - Convert table `outq` to utf8mb4.................................... ALREADY CONVERTED
 - Convert table `saved_filters` to utf8mb4........................... ALREADY CONVERTED
 - Convert table `sa_rules` to utf8mb4................................ ALREADY CONVERTED
 - Convert table `users` to utf8mb4................................... ALREADY CONVERTED
 - Convert table `user_filters` to utf8mb4............................ ALREADY CONVERTED
 - Convert table `whitelist` to utf8mb4............................... ALREADY CONVERTED

 - Convert table `audit_log` to InnoDB................................ ALREADY CONVERTED
 - Convert table `autorelease` to InnoDB.............................. ALREADY CONVERTED
 - Convert table `blacklist` to InnoDB................................ ALREADY CONVERTED
 - Convert table `inq` to InnoDB...................................... ALREADY CONVERTED
 - Convert table `maillog` to InnoDB.................................. OK
 - Convert table `mcp_rules` to InnoDB................................ OK
 - Convert table `mtalog` to InnoDB................................... OK
 - Convert table `mtalog_ids` to InnoDB............................... OK
 - Convert table `outq` to InnoDB..................................... OK
 - Convert table `saved_filters` to InnoDB............................ OK
 - Convert table `sa_rules` to InnoDB................................. OK
 - Convert table `users` to InnoDB.................................... OK
 - Convert table `user_filters` to InnoDB............................. OK
 - Convert table `whitelist` to InnoDB................................ OK

 - Search for missing indexes on table `maillog`...................... DONE
 - Adding missing index `maillog_from_idx` on table `maillog`......... OK
 - Adding missing index `maillog_to_idx` on table `maillog`........... OK
 - Adding missing index `subject_idx` on table `maillog`.............. OK

Checking MailScanner.conf settings:

 - QuarantineWholeMessage ............................................ OK
 - QuarantineWholeMessagesAsQueueFiles ............................... OK
 - DetailedSpamReport ................................................ OK
 - IncludeScoresInSpamAssassinReport ................................. OK
 - SpamActions ....................................................... OK
 - HighScoringSpamActions ............................................ OK
 - AlwaysLookedUpLast ................................................ OK

Checking conf.php configuration entry:


Fatal error: Call to undefined function checkConfVariables() in /root/1.2.0-1.2.0/upgrade.php on line 568

**Comment by stefaweb** [comment]
Is your mailwatch GUI in /var/www/html/mailscanner?

**Comment by branko77** [comment]
yes it is and it is working... I am looking at it as I type this

**Comment by stefaweb** [comment]
Server config?

os, php, etc.

**Comment by branko77** [comment]
CentOS Linux 7.3.1611
PHP Version: 5.4.16
MailScanner Version: 5.0.3
MySQL Version: 5.6.35
SpamAssassin Version: 3.4.0

**Comment by Skywalker-11** [comment]
What is your old MailWatch version?

**Comment by branko77** [comment]
1.2.0 - RC4

**Comment by stefaweb** [comment]
Not compatible.
GUI in /var/www/html/mailscanner should be at least 1.2.0. Upgrade need to access up to date functions.php.

**Comment by branko77** [comment]
so how I can sort it out?

**Comment by stefaweb** [comment]
Read the doc.
https://github.com/mailwatch/1.2.0/blob/master/UPGRADING

**Comment by endelwar** [comment]
@branko77 make a backup of conf.php in you actual installation, delete it, download the zip for 1.2.0 release, unpack in the same directory as before, copy in mailscanner dir your old conf.php, run upgrade.php and follow the warnings (missing entries in conf.php for example)

**Comment by branko77** [comment]
Ok I did it.
My upgrade finished with few warnings:
 - optional RPC_PORT ................................................. WARNING
 - optional RPC_SSL .................................................. WARNING
 - optional RPC_REMOTE_SERVER ........................................ WARNING
 - optional LDAP_BIND_PREFIX ......................................... WARNING
 - optional LDAP_BIND_SUFFIX ......................................... WARNING
 - optional EXIM_QUEUE_IN ............................................ WARNING
 - optional EXIM_QUEUE_OUT ........................................... WARNING
 - optional PWD_RESET_FROM_NAME ...................................... WARNING
 - optional PWD_RESET_FROM_ADDRESS ................................... WARNING

*** ERROR/WARNING SUMMARY ***
conf.php: optional configuration entry "RPC_PORT" is missing, needed if RPC_ONLY mode is enabled
conf.php: optional configuration entry "RPC_SSL" is missing, needed if RPC_ONLY mode is enabled
conf.php: optional configuration entry "RPC_REMOTE_SERVER" is missing, needed to show number of mails in postfix queues on remote server (RPC)
conf.php: optional configuration entry "LDAP_BIND_PREFIX" is missing, needed when using LDAP authentication
conf.php: optional configuration entry "LDAP_BIND_SUFFIX" is missing, needed when using LDAP authentication
conf.php: optional configuration entry "EXIM_QUEUE_IN" is missing, needed only if using Exim as MTA
conf.php: optional configuration entry "EXIM_QUEUE_OUT" is missing, needed only if using Exim as MTA
conf.php: optional configuration entry "PWD_RESET_FROM_NAME" is missing, needed if Password Reset feature is enabled
conf.php: optional configuration entry "PWD_RESET_FROM_ADDRESS" is missing, needed if Password Reset feature is enabled

Now, when I login in MailWatch GUI I can see that version is: MailWatch for MailScanner v1.2.0 - © 2006-2017

But I have bunch of notices and cannot see some features. 

On recent messages page I have one "Notice: Undefined index: token in /var/www/html/mailscanner/functions.php on line 325" and a bunch of "Notice: Undefined index: token in /var/www/html/mailscanner/functions.php on line 2120" but in the end of page I can see messages list

On B&W lists page I have: "Notice: Undefined index: token in /var/www/html/mailscanner/lists.php on line 344
No! Bad dog no treat for you!"

On Quarantine page I have bunch of "Notice: Undefined index: token in /var/www/html/mailscanner/quarantine.php on line 54" but in the end of page I can see quarantine. 

On reports page I have "Warning: Illegal string offset 'url' in /var/www/html/mailscanner/filter.inc.php on line 356

Notice: Undefined index: token in /var/www/html/mailscanner/reports.php on line 135

Notice: Undefined index: token in /var/www/html/mailscanner/filter.inc.php on line 340
No! Bad dog no treat for you!" and no report links...

**Comment by endelwar** [comment]
clean your browser cache, this is an expected behaviour

**Comment by branko77** [comment]
@endelwar 
Yes, that did it... Now it seems that everything is working as it should be and my MW is 1.2.0
Thanks a lot guys. You all helped a lot as usual 👍

**Comment by Fonant** [comment]
Just to confirm that the MailWatch 1.2.0 release's upgrade.php failed for me, with the 'Specified key was too long; max key length is 767 bytes' message. "MySQL" version 5.5.54-MariaDB.

The newer version from develop works fine: https://raw.githubusercontent.com/mailwatch/1.2.0/develop/upgrade.php

**Comment by Skywalker-11** [comment]
Can you close this as it is solved?
