### ISSUE TITLE
Bugs with user_manager.php

### ISSUE THREAD

**Issue by asuweb** [mailwatch/1.2.0#668]
There are 2 bugs currently (1 of which has been reported on the mail list)

1) Domain admins can create "Administrator" accounts, which has obvious implications

2) An admin or domain admin user can delete their own account when they are signed in

**Comment by stefaweb** [comment]
2. is fun !   😎

**Comment by asuweb** [comment]
Yes, quite!

**Comment by asuweb** [comment]
Fixed in #671

**Comment by asuweb** [comment]
Merged and closed
