### ISSUE TITLE
Link to Audit Log appears to be missing

### ISSUE THREAD

**Issue by asuweb** [mailwatch/1.2.0#669]
There no longer appears to be a link to rep_audit_log in reports

**Comment by asuweb** [comment]
Ahh good - the link to audit log is only displayed to non-admins! Makes sense...

**Comment by stefaweb** [comment]
https://github.com/mailwatch/1.2.0/commit/6f63d1d0bb4285cc505055620195a5f1d49bb235

**Comment by asuweb** [comment]
Yes, I've fixed it in #670

**Comment by asuweb** [comment]
Merged and closed
