### ISSUE TITLE
Notice: Undefined variable: n_type in user_manager.php

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#683]
Last develop.

When updating a user (activating report for a admin-domain or user + click on update button).

`Notice: Undefined variable: n_type in /var/www/html/mailscanner/user_manager.php on line 380
`

Repetitive.

**Comment by shawniverson** [comment]
hmm...looks like something from commit
e9e067cccb05a1c02a23ada79dd7c78a1bbe1795

**Comment by shawniverson** [comment]
Hmm....well maybe not, still looking....

**Comment by stefaweb** [comment]
The record seems updated.

**Comment by shawniverson** [comment]
Yep, found it.  A line needs added after that commit.

**Comment by stefaweb** [comment]
Done
