### ISSUE TITLE
View link from quarantine report bug

### ISSUE THREAD

**Issue by asuweb** [mailwatch/1.2.0#686]
The "View" link in quarantine reports is not working as designed.

If the user is already logged in, we get `Error: unable to validate security token` and if the user isn't logged in, we get the login page, and after logging in, we get status.php and not the email we want to view.

**Comment by shawniverson** [comment]
@asuweb does the View link contain a token parameter in your report?

**Comment by asuweb** [comment]
`http://domain.com/viewmail.php?token=&id=DA0BE60D00.A0F45`

It would appear the token isn't actually set

**Comment by shawniverson** [comment]
Ok, is this an email prior to the changes?

**Comment by asuweb** [comment]
Nope, this was this morning's email - I re-deployed the code at about 11pm last night.

**Comment by shawniverson** [comment]
right, but the timestamp of the particular email...was it after 11pm?

Also, was MailScanner restarted to pull in the new MailWatch.pm?

**Comment by asuweb** [comment]
No, the email was received before then.  That may explain the issue, although it's not ideal if that's the case.  

I'll check back tomorrow when it runs again - or if I get time, I'll manually do a run on the dev server.  

Yes, mailscanner was restarted.

**Comment by shawniverson** [comment]
Looks like we need to make a few modifications:

1)  Generate tokens for emails prior to upgrade
2)  Remove sanitizeInput on REDIRECT_URI (let sanitization happen after redirect)

**Comment by asuweb** [comment]
Assuming that 1 is caused by this - for my particular setup it's not going to cause ongoing issues as I only do 1 day quarantine reports, but it will no doubt be a annoyance to others.
