### ISSUE TITLE
Function to clean filter in upgrade.php

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#689]
In one of the issue I reported last week or ten days ago, we discovered that domain(s) was not deleted from filter when we delete an admin-domain or admin.

If someone can handle this and add a function in upgrade.php to clean orphan domain from the table.

**Comment by shawniverson** [comment]
@stefaweb, whew, I'm about wore out with all this coding! 😉  Let me take a short break and visit this while it is fresh in my head.

**Comment by stefaweb** [comment]
Hard job a Bug Contest!   😜

This issue is not urgent. The code in the GUI is already modified to delete domain from filter when we delete an user.

We just need to clean the past with upgrade.php.

**Comment by shawniverson** [comment]
Here you go :)  Probably not the most efficient approach in the world.  Perhaps someone with SQL magic will come along and make it better 😄

**Comment by endelwar** [comment]
a 
```sql
DELETE FROM `user_filters` WHERE username NOT IN (SELECT username FROM users);
```

should do the work in one pass

**Comment by Skywalker-11** [comment]
same idea 😄

**Comment by endelwar** [comment]
eheh, yes, just seen your comment on PR

**Comment by shawniverson** [comment]
That is sooooo much better than the monster I created hehe, updating PR (will still need tested)...

**Comment by stefaweb** [comment]
👏
