### ISSUE TITLE
No longer Mail Queue (Exim) printed in status.php with last develop

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#691]
I've to look at this.
An idea of the reason ?

(as well MAILQ = true)

**Comment by Skywalker-11** [comment]
You could check what $_GET['queue'] is and what $queue is after this call. That is the only real change since your localization
```
$queue = deepSanitizeInput($_GET['queue'], 'url');
if (!validateInput($queue, 'mailq')) { die(); }
```

**Comment by stefaweb** [comment]
The complete Queue "screen" is missing not only the values.

![capture d ecran 2017-03-23 a 20 36 10](https://cloud.githubusercontent.com/assets/12907102/24266853/8c169b2a-1008-11e7-8711-76ba49c553af.png)

**Comment by stefaweb** [comment]
$_SESSION['user_type'] = A
get_conf_var('MTA', true) = exim
MAILQ = 1
DISTRIBUTED_SETUP = 0

This no longer works.

`  } elseif (defined(MAILQ) && MAILQ === true && !DISTRIBUTED_SETUP) {`

If I replace by:

` } else {`

The queue is back.

**Comment by shawniverson** [comment]
Should MAILQ be a true/false and not a 1/0?

**Comment by stefaweb** [comment]
Sorry its true no 1.

var_dump(MAILQ);
bool(true)
var_dump(DISTRIBUTED_SETUP);
bool(false)

**Comment by shawniverson** [comment]
defined(MAILQ) should that be defined('MAILQ') ?

**Comment by stefaweb** [comment]
You win !

Works. Was so big in front of me.

Will do a PR later.

**Comment by shawniverson** [comment]
yay! 😄
