### ISSUE TITLE
Tester needed: performance branch

### ISSUE THREAD

**Issue by endelwar** [mailwatch/1.2.0#695]
I manage to cut a lot of page load time by optimizing MailScanner config file parser functions, and preliminary tests seems ok, but I need some more eyes on this.

Please checkout https://github.com/mailwatch/1.2.0/tree/feature/performance and report anything bad (or good)

**Comment by stefaweb** [comment]
I've played with this version and not found problem except $username missing in rep_audit_log.php (but I don't know where to look to find problem if exist).

I only tested on the dev server where I've only 3500 records in maillog but pages seems to load faster specially in reports. I switched back to normal version and again to performance version. Seems faster.

**Comment by endelwar** [comment]
merged
