### ISSUE TITLE
Not good with #701 (rep_audit_log.php)

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/1.2.0#703]
Boom!

![capture d ecran 2017-03-24 a 15 30 14](https://cloud.githubusercontent.com/assets/12907102/24298641/eab6975e-10a6-11e7-8ecd-e71ec2ade75b.png)

**Comment by shawniverson** [comment]
Thx let me revise :)

**Comment by shawniverson** [comment]
Can be closed now, @Skywalker-11 beat me to it
