### ISSUE TITLE
Session Handling Improvments

### ISSUE THREAD

**Issue by asuweb** [mailwatch/1.2.0#708]
As referenced in #662 - do we need additional session handling to cover scenarios like the following:

Optional configuration for fine grained control over cache expiry, auto_refresh keep alive, and admin control over which users/groups can keep sessions alive and those that can't - for example, it would be easy enough to implement a solution such as @stefaweb where a specific user can bypass session expiry (for the case where it's displays in a NOC or the likes).

Comments needed please

**Comment by shawniverson** [comment]
Perhaps we could simply set a timer variable in the current session to use to rotate session.  Each time a page refreshes, simply check the timer variable, if it is exceed, generate new session with existing values.  Then no extra controls would even be necessary?

**Comment by asuweb** [comment]
That would certainly cut down the complexity a bit

**Comment by asuweb** [comment]
Although that would also work in the case where a browser has been left open by accident, and some comes along and refreshes - better to reset session expiry on every page refresh to something like 2-5mins, and then on refresh, check session is still valid, and reset expiry to + x minutes?

**Comment by shawniverson** [comment]
I would think you would want the expiry still there for that case.  i.e. the 60 min, maybe a refresh within that interval, say 30 min, regenerate?

**Comment by stefaweb** [comment]
Made simple. We just need to have a 24/24 connection on two pages of the GUI.

What do you think to have something like this:

We add a supplementary false in `html_start(__('message'), STATUS_REFRESH, false, false, false);`

if `false`, default GUI expiry
if `true`, never expire

**Comment by shawniverson** [comment]
@stefaweb Perhaps, but it is still a good idea to rotate session, even in that case, for better session security :)

**Comment by shawniverson** [comment]
@asuweb, how about we shorten the session to a short expiration (which is much better) for regular users with no session refresh, and then set administrators and domain admins to the same value with session refresh?

That way a user can't just accidentally leave the page open and will expire if left open, and admins will have the ability to leave status and queues open as long as desired?

**Comment by shawniverson** [comment]
Or better yet, limit the users to a maximum duration (like the 60 min tops) with the technique you describe to refresh every 2-5 min if they are active in the interface?

**Comment by asuweb** [comment]
Either option is viable - I don't imagine many users sit and watch the status page (unless they're particularly bored), so I think a session expiry of 5 minutes (perhaps 10 minutes), for regular users, recalculated on user interaction (i.e, page change) should be sufficient - and then the same for admins, expect any refresh also extends the session - so status and queue autorefresh will keep them logged in. 

@endelwar  - your thoughts?

**Comment by endelwar** [comment]
> @endelwar - your thoughts?

we should follow this path:
- reduce the session duration to max 5 minutes for all
- restart session count down on user interaction (page changed or manually refreshed, not on bored playing with a select or checkbox)
- pages with autorefresh on (status, mail queue) should follow the rule above, obviously without manual interaction
- if STATUS_REFRESH > session time out we should use the latter as page refresh timeout (minus some seconds to let the browser do its job in time)

I don't think that ajax tricks to keep session refreshed is someone is sleeping in front of the monitor is needed: users must understand that security of their own privacy is important.

**Comment by asuweb** [comment]
Yes, I agree with this approach - seems the best option.  autorefresh keep alive for all users or just admins?

**Comment by Skywalker-11** [comment]
If we want to store them in the session, we have to keep in mind that people probably want to open/use multiple tabs and multiple forms at the same time. So we may want to store them in an array and put the key to that parameters in a hidden input field

**Comment by endelwar** [comment]
> autorefresh keep alive for all users or just admins?

for everyone: it's like an user interaction for me.

**Comment by shawniverson** [comment]
I can tackle this one today, unless someone else is already working on it?

**Comment by asuweb** [comment]
@shawniverson - I haven't started on this yet, so if you could do it that would be great

**Comment by shawniverson** [comment]
@asuweb Sounds good, I will get to work on this.
