### ISSUE TITLE
Bugs in user_manager.php

### ISSUE THREAD

**Issue by asuweb** [mailwatch/1.2.0#711]
The following bugs exist - I'm working on fixes:

1) Domain admins can add their own filters - this is a security issues, as they could elevate their own privileges to see other domains.  Domain admins should not be allowed to amend their own filters.

2) Domain admins should be allowed to create new users for both their own domain and domains that they have in their filters.   For example, a domain admin for `test.com` who has a filter for domain `test1.com` should be allowed to add users for `test1.com` as well as `test.com`  - This could be made optional via the config if people prefer?

**Comment by stefaweb** [comment]
> This could be made optional via the config if people prefer?

2. For me, no need to be optional. Seems logic as you propose.

**Comment by asuweb** [comment]
Fixed in #712

**Comment by endelwar** [comment]
> This could be made optional via the config if people prefer?

I agree too. If an admin give some rights to an user they can use that power.
