### ISSUE TITLE
RPC Problems. 

### ISSUE THREAD

**Issue by mealerzrich** [mailwatch/1.2.0#90]
Hi,

I've installed mailwatch on 2 mailscanner servers mx1 and mx2. Mx2 is using the mysql details for mx1 and mx1 is using it's own sql details, so all emails are logging to mx1.
When I view an email from MX1 that was processed by MX2, I get the following - 

---GOT---
HTTP/1.1 200 OK
Date: Wed, 04 Jun 2014 12:08:39 GMT
Server: Apache/2.4.6 (FreeBSD) PHP/5.4.24
X-Powered-By: PHP/5.4.24
Content-Length: 387
Connection: close
Content-Type: text/html

HEADER: date: Wed, 04 Jun 2014 12:08:39 GMT
HEADER: server: Apache/2.4.6 (FreeBSD) PHP/5.4.24
HEADER: x-powered-by: PHP/5.4.24
HEADER: content-length: 387
HEADER: connection: close
HEADER: content-type: text/html
XML error at line 1, check URL
XML-RPC Error: Invalid return payload: enable debugging to examine incoming payload (XML error at line 1, check URL)

I've tried printing all the variables from MX2's rpcserver.php file and I get this - 

---GOT---
HTTP/1.1 200 OK
Date: Wed, 04 Jun 2014 12:20:19 GMT
Server: Apache/2.4.6 (FreeBSD) PHP/5.4.24
X-Powered-By: PHP/5.4.24
Content-Length: 387
Connection: close
Content-Type: text/html

Array
(
    [HTTP_RAW_POST_DATA] => <?xml version="1.0"?>
<methodCall>
<methodName>quarantine_list_items</methodName>
<params>
<param>
<value><string>s54BSPM4052826</string></value>
</param>
</params>
</methodCall>
    [_GET] => Array
        (
        )

    [_POST] => Array
        (
        )

    [_COOKIE] => Array
        (
        )

    [_FILES] => Array
        (
        )

)

---END---
HEADER: date: Wed, 04 Jun 2014 12:20:19 GMT
HEADER: server: Apache/2.4.6 (FreeBSD) PHP/5.4.24
HEADER: x-powered-by: PHP/5.4.24
HEADER: content-length: 387
HEADER: connection: close
HEADER: content-type: text/html
XML error at line 1, check URL
XML-RPC Error: Invalid return payload: enable debugging to examine incoming payload (XML error at line 1, check URL)

I've tried using the xml-2.2.2 but that makes no difference. I'm wondering how I can debug this further or if anyone else has an idea or time to look at it? 

Thanks,
Rich

**Comment by endelwar** [comment]
@mealerzrich can we consider this bug closed?

**Comment by mealerz** [comment]
Yes from me :-)

**Comment by mealerz** [comment]
Apologies, I seem to have 2 github accounts. But yes it can be closed. It's working fine for me using 9 servers in total.

**Comment by endelwar** [comment]
Great! Thanks @mealerz!
