### ISSUE TITLE
Slow page generation after login as Domain Admin

### ISSUE THREAD

**Issue by mealerz** [mailwatch/1.2.0#97]
1) I would like to see a search page for emails, to / from address, with time / date periods to search. Possibly by subject line also, with any other searchable options you might think of. At the moment I only see a search for messageID.

2) I have a busy mail server so logging in sometimes takes a while, depending on how many days I leave in maillogs (RECORD_DAYS_TO_KEEP). If I leave 1 day then it's fine, 2 days it's quite slow, 3 days and I have about 3 or 4Gb of database and it's quite slow. Any more and it's REALLY slow. I don't see why the interface should be slow but I imagine it's trying to read all the maillogs for a given type user. Why not just incorporate a search feature for the mail logs instead of showing them all? 

Thanks,
Rich

**Comment by endelwar** [comment]
@mealerz do you have done more test on this slow login as Domain Admin? in my tests it seems that admin login is slower by 10% compared to domain admin login
